// Banco de ítems de aplicación — Asignatura VI: Machine Learning.
module.exports = {
  slug: 'bank-master-vi',
  title: 'Banco de ítems — Asignatura VI',
  scopeSlug: 'master-vi',
  questions: [
    {
      extKey: 'vi-app-01',
      skillTag: 'Introducción a Machine Learning',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un modelo de detección de una enfermedad rara (1 caso por cada 1000) reporta 99% de exactitud. ¿Por qué esa cifra puede ser un desastre?',
      options: [
        'Porque 99% es una exactitud baja.',
        'Porque un modelo que siempre dice "sano" ya acierta el 99,9%; la exactitud es engañosa con clases muy desbalanceadas y hay que mirar sensibilidad, precisión y el coste de cada tipo de error.',
        'Porque el modelo usa demasiadas variables.',
        'Porque el conjunto de prueba era pequeño.',
      ],
      correctIndex: 1,
      explanations: [
        '99% suena alto, pero el problema es que no dice nada útil aquí.',
        'Correcto: con un 0,1% de positivos, "siempre negativo" alcanza 99,9%; hay que evaluar por sensibilidad y coste de FN.',
        'El número de variables no explica esta paradoja.',
        'El tamaño del conjunto de prueba no es la causa del problema conceptual.',
      ],
    },
    {
      extKey: 'vi-app-02',
      skillTag: 'Aprendizaje Supervisado',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Vas a clasificar solicitudes en "aprobar / revisar / rechazar" con datos etiquetados históricos y necesitas poder explicar cada decisión a un auditor. Entre logística, kNN y un árbol, ¿cuál priorizas de partida y por qué?',
      options: [
        'kNN, porque no necesita entrenamiento.',
        'Un modelo interpretable por diseño (regresión logística o árbol poco profundo): la exigencia de explicar cada decisión a un auditor pesa más que un pequeño incremento de exactitud de un modelo opaco.',
        'Una red neuronal profunda siempre.',
        'kNN, porque es el más preciso en todos los casos.',
      ],
      correctIndex: 1,
      explanations: [
        'kNN es costoso en predicción y difícil de explicar caso a caso.',
        'Correcto: cuando la explicabilidad es un requisito duro, se empieza por modelos interpretables por diseño.',
        'Una red profunda agrava el problema de explicabilidad ante el auditor.',
        'kNN no es universalmente el más preciso; depende del problema.',
      ],
    },
    {
      extKey: 'vi-app-03',
      skillTag: 'Aprendizaje supervisado de regresión',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un modelo de regresión de tiempos de entrega tiene un R² de 0,85 pero se equivoca sistemáticamente por 40 minutos en los pedidos de fin de semana, que son los críticos para el negocio. ¿Qué conclusión sacas?',
      options: [
        'El modelo es bueno: R² de 0,85 es alto.',
        'Una métrica global agregada oculta un fallo en el segmento que más importa; hay que evaluar el error por segmento (fin de semana) y quizá modelar ese caso aparte.',
        'Hay que subir el R² a 0,99 sin más.',
        'El R² es la única métrica que importa.',
      ],
      correctIndex: 1,
      explanations: [
        'Un R² alto no garantiza rendimiento donde el negocio lo necesita.',
        'Correcto: el error hay que desglosarlo por segmento relevante, no solo mirar el agregado.',
        'Perseguir un R² mayor no ataca el sesgo sistemático en un segmento.',
        'El R² por sí solo no revela sesgos por segmento ni la escala del error en minutos.',
      ],
    },
    {
      extKey: 'vi-app-04',
      skillTag: 'Aprendizaje no supervisado',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Aplicas k-means para segmentar clientes con 60 variables y los grupos salen sin sentido. ¿Qué revisas primero?',
      options: [
        'El color del gráfico de dispersión.',
        'La maldición de la dimensionalidad y la escala: con 60 variables las distancias pierden significado; conviene escalar las variables y reducir dimensiones (p. ej. PCA) antes de agrupar.',
        'Aumentar k a 100.',
        'Cambiar a un lenguaje de programación distinto.',
      ],
      correctIndex: 1,
      explanations: [
        'El color no afecta al resultado del clustering.',
        'Correcto: en alta dimensión y sin escalar, las distancias se degradan; escalar y reducir dimensiones es el primer paso.',
        'Un k enorme fragmenta sin resolver el problema de fondo.',
        'El lenguaje no cambia la matemática del algoritmo.',
      ],
    },
    {
      extKey: 'vi-app-05',
      skillTag: 'Aprendizaje semi-supervisado y por Refuerzo',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'Tienes 500 ejemplos etiquetados y 50 000 sin etiquetar, y etiquetar es caro. ¿Qué familia de técnicas puede aprovechar los datos sin etiquetar?',
      options: [
        'Aprendizaje por refuerzo puro.',
        'Aprendizaje semi-supervisado (p. ej. self-training): usar el modelo entrenado con lo poco etiquetado para etiquetar lo más fiable del resto y reentrenar, con cuidado de no amplificar errores.',
        'Descartar los 50 000 sin etiquetar.',
        'Etiquetar los 50 000 a mano igualmente.',
      ],
      correctIndex: 1,
      explanations: [
        'El refuerzo requiere un entorno con recompensas, no es este caso.',
        'Correcto: el semi-supervisado explota los datos sin etiqueta cuando etiquetar es costoso.',
        'Descartarlos desaprovecha información útil.',
        'Etiquetar 50 000 a mano es justo lo que se quiere evitar por coste.',
      ],
    },
    {
      extKey: 'vi-app-06',
      skillTag: 'Interpretabilidad de Modelos',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Usas SHAP sobre un modelo de riesgo y descubres que la variable con mayor importancia es "días desde el último contacto con soporte", que en tu proceso solo se llena cuando ya hay un problema. ¿Qué implica?',
      options: [
        'Que el modelo es excelente: encontró la variable clave.',
        'Que probablemente hay fuga de datos: esa variable codifica información del propio resultado que se quiere predecir; hay que revisar cuándo se rellena respecto al momento de la predicción.',
        'Que hay que eliminar SHAP porque confunde.',
        'Que la variable debe multiplicarse por dos.',
      ],
      correctIndex: 1,
      explanations: [
        'Una importancia altísima de una variable sospechosa suele indicar fuga, no mérito.',
        'Correcto: la interpretabilidad sirve precisamente para detectar que el modelo se apoya en algo que no estará disponible al predecir.',
        'SHAP está haciendo su trabajo: revelar el problema.',
        'Escalar la variable no corrige la fuga temporal.',
      ],
    },
    {
      extKey: 'vi-app-07',
      skillTag: 'Aprendizaje Supervisado',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'En un problema de clasificación con clases 95%/5%, ¿qué métrica y qué ajuste conviene mirar antes de entrenar?',
      options: [
        'Solo la exactitud; sin ajustes.',
        'Precisión y exhaustividad (o F1) de la clase minoritaria, y decidir el umbral de decisión según el coste relativo de falsos positivos y negativos, no dejarlo en 0,5 por defecto.',
        'El tiempo de entrenamiento.',
        'El número de líneas del script.',
      ],
      correctIndex: 1,
      explanations: [
        'La exactitud es engañosa con ese desbalanceo.',
        'Correcto: se mira el rendimiento en la clase rara y se calibra el umbral según los costes del negocio.',
        'El tiempo de entrenamiento no informa sobre la calidad de las predicciones.',
        'La longitud del código es irrelevante.',
      ],
    },
    {
      extKey: 'vi-app-08',
      skillTag: 'Introducción a Machine Learning',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'El compromiso sesgo-varianza dice que, al aumentar la complejidad del modelo:',
      options: [
        'Siempre mejora tanto en entrenamiento como en datos nuevos.',
        'El error por sesgo tiende a bajar, pero el error por varianza tiende a subir; el objetivo es el punto donde el error total en datos no vistos es mínimo.',
        'Solo importa el error en entrenamiento.',
        'La varianza y el sesgo son lo mismo.',
      ],
      correctIndex: 1,
      explanations: [
        'Más complejidad mejora el entrenamiento pero puede empeorar la generalización.',
        'Correcto: es un compromiso; se busca minimizar el error de generalización, no el de entrenamiento.',
        'El error en entrenamiento por sí solo no predice el rendimiento real.',
        'Sesgo (error sistemático) y varianza (sensibilidad a los datos) son distintos.',
      ],
    },
    {
      extKey: 'vi-app-09',
      skillTag: 'Aprendizaje supervisado de regresión',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: '¿Qué efecto tiene la regularización L2 (ridge) sobre un modelo de regresión con muchas variables correlacionadas?',
      options: [
        'Elimina variables poniendo sus coeficientes exactamente a cero.',
        'Reduce la magnitud de los coeficientes de forma suave, repartiéndolos entre variables correlacionadas y reduciendo la varianza del modelo.',
        'Aumenta el sobreajuste.',
        'No tiene ningún efecto si hay correlación.',
      ],
      correctIndex: 1,
      explanations: [
        'Poner coeficientes exactamente a cero es más propio de L1 (lasso).',
        'Correcto: L2 encoge coeficientes de forma continua y estabiliza el modelo ante colinealidad.',
        'La regularización reduce, no aumenta, el sobreajuste.',
        'L2 es especialmente útil precisamente cuando hay variables correlacionadas.',
      ],
    },
    {
      extKey: 'vi-app-10',
      skillTag: 'Interpretabilidad de Modelos',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: '¿Cuál es la diferencia entre interpretabilidad "por diseño" y "post-hoc"?',
      options: [
        'No hay diferencia real.',
        'Por diseño: el modelo es inherentemente legible (regresión lineal, árbol pequeño). Post-hoc: se aplica una técnica externa (LIME, SHAP) para explicar un modelo opaco después de entrenarlo.',
        'Post-hoc significa antes de entrenar.',
        'Por diseño significa sin entrenamiento.',
      ],
      correctIndex: 1,
      explanations: [
        'Son enfoques claramente distintos.',
        'Correcto: uno es transparencia intrínseca; el otro, explicación aproximada añadida a posteriori.',
        'Post-hoc es después de entrenar, por definición.',
        'Un modelo interpretable por diseño también se entrena.',
      ],
    },
    {
      extKey: 'vi-app-11',
      skillTag: 'Aprendizaje no supervisado',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'PCA se usa principalmente para:',
      options: [
        'Etiquetar automáticamente los datos.',
        'Reducir la dimensionalidad proyectando los datos sobre las direcciones de mayor varianza, conservando la mayor parte de la información con menos variables.',
        'Aumentar el número de variables.',
        'Cifrar el conjunto de datos.',
      ],
      correctIndex: 1,
      explanations: [
        'PCA no genera etiquetas.',
        'Correcto: es una técnica de reducción de dimensionalidad basada en la varianza.',
        'PCA reduce, no aumenta, el número de dimensiones.',
        'No tiene relación con cifrado.',
      ],
    },
    {
      extKey: 'vi-app-12',
      skillTag: 'Aprendizaje semi-supervisado y por Refuerzo',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'En aprendizaje por refuerzo, el "dilema exploración-explotación" aparece cuando un agente de recomendación:',
      options: [
        'No tiene datos de ningún tipo.',
        'Debe decidir entre repetir la opción que hoy da mejor recompensa conocida (explotar) o probar opciones poco vistas que podrían ser mejores (explorar).',
        'Solo puede usar reglas fijas.',
        'Tiene demasiadas GPUs.',
      ],
      correctIndex: 1,
      explanations: [
        'El dilema aparece justamente porque hay datos y recompensas parciales.',
        'Correcto: es el equilibrio entre aprovechar lo conocido y descubrir algo potencialmente mejor.',
        'Con reglas fijas no hay aprendizaje ni dilema.',
        'El hardware no define este dilema conceptual.',
      ],
    },
  ],
};
