// Banco de ítems de aplicación — Asignatura III: Big Data dentro de la informática.
module.exports = {
  slug: 'bank-master-iii',
  title: 'Banco de ítems — Asignatura III',
  scopeSlug: 'master-iii',
  questions: [
    {
      extKey: 'iii-app-01',
      skillTag: 'Arquitecturas y Soluciones de Big Data: Análisis, Procesamiento y Escalabilidad en la Era Digital',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Una agregación sobre 30 millones de filas tarda 40 s en pandas en una máquina con 32 GB de RAM y se ejecuta una vez al día. Un equipo propone migrarla a Spark en un clúster. ¿Qué análisis corresponde?',
      options: [
        'Migrar: Spark siempre es más rápido para Big Data.',
        'Probablemente no compensa: 30 M de filas caben en memoria, el trabajo es diario (no hay presión de latencia) y Spark añade sobrecarga de coordinación; conviene medir primero Polars/DuckDB en la misma máquina.',
        'Migrar a Spark pero en modo local, sin clúster.',
        'Aumentar la RAM a 128 GB sin más análisis.',
      ],
      correctIndex: 1,
      explanations: [
        'Spark tiene sobrecarga que no compensa para datos que caben en memoria y cargas no urgentes.',
        'Correcto: el punto en que Spark compensa se justifica midiendo, no por regla; a esta escala hay opciones más simples.',
        'Spark local sigue arrastrando sobrecarga sin la ventaja del clúster.',
        'Más RAM puede ayudar, pero primero hay que medir alternativas más eficientes.',
      ],
    },
    {
      extKey: 'iii-app-02',
      skillTag: 'Arquitecturas y Soluciones de Big Data: Análisis, Procesamiento y Escalabilidad en la Era Digital',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un pipeline necesita reprocesar meses de histórico cuando se corrige un error de lógica, y a la vez servir métricas casi en tiempo real. ¿Qué arquitectura encaja?',
      options: [
        'Solo streaming, sin capa de histórico.',
        'Una arquitectura con capa batch (recálculo completo y fiable del histórico) y capa de velocidad (streaming para lo reciente), sirviendo la vista combinada.',
        'Solo batch nocturno.',
        'Guardar todo en un único CSV gigante.',
      ],
      correctIndex: 1,
      explanations: [
        'Solo streaming dificulta el reprocesamiento fiable del histórico.',
        'Correcto: separar recálculo histórico (batch) de baja latencia (velocidad) es el patrón para ambos requisitos.',
        'Solo batch no da la latencia casi en tiempo real requerida.',
        'Un CSV gigante no escala ni permite consultas eficientes.',
      ],
    },
    {
      extKey: 'iii-app-03',
      skillTag: 'Entornos de trabajo para arquitecturas Deep Learning',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Entrenas un modelo cuyos datos no caben en la memoria de una sola GPU, pero el modelo sí. ¿Qué estrategia de paralelismo aplica?',
      options: [
        'Paralelismo de modelo: repartir las capas entre GPUs.',
        'Paralelismo de datos: cada GPU tiene una copia del modelo y procesa un subconjunto del lote; se promedian los gradientes.',
        'No se puede entrenar en esa situación.',
        'Reducir el modelo hasta que quepan los datos.',
      ],
      correctIndex: 1,
      explanations: [
        'El paralelismo de modelo es para modelos que no caben en una GPU, no para datos.',
        'Correcto: si el modelo cabe pero los datos no, se replica el modelo y se reparte el lote (data parallelism).',
        'Sí se puede: es exactamente el caso del paralelismo de datos.',
        'Reducir el modelo cambia el problema; no es necesario aquí.',
      ],
    },
    {
      extKey: 'iii-app-04',
      skillTag: 'Entornos de trabajo para arquitecturas Deep Learning',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: '¿Para qué sirve una herramienta de seguimiento de experimentos (experiment tracking) al entrenar modelos?',
      options: [
        'Para acelerar el entrenamiento en la GPU.',
        'Para registrar hiperparámetros, métricas, datos y versión de código de cada corrida, y poder comparar y reproducir resultados después.',
        'Para cifrar el modelo entrenado.',
        'Para desplegar el modelo en producción.',
      ],
      correctIndex: 1,
      explanations: [
        'No influye en la velocidad de cómputo.',
        'Correcto: la trazabilidad y reproducibilidad de experimentos es su función.',
        'No tiene que ver con cifrado.',
        'El despliegue es una etapa posterior y distinta.',
      ],
    },
    {
      extKey: 'iii-app-05',
      skillTag: 'Aprendizaje Automático',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Tienes 200 millones de registros y quieres validar un modelo. Entrenar sobre todo tarda días. ¿Qué enfoque es razonable primero?',
      options: [
        'Entrenar siempre sobre el 100% para no perder información.',
        'Trabajar con una muestra representativa (estratificada por las variables clave) para iterar rápido, y confirmar el resultado final sobre el conjunto completo.',
        'Descartar el 90% de las columnas al azar.',
        'Usar solo los primeros 10 000 registros por orden de llegada.',
      ],
      correctIndex: 1,
      explanations: [
        'Entrenar sobre todo en cada iteración hace inviable la experimentación.',
        'Correcto: una muestra representativa acelera la iteración sin sesgar, y se valida al final sobre todo.',
        'Descartar columnas al azar pierde señal de forma incontrolada.',
        'Los primeros 10 000 por orden de llegada pueden no ser representativos (sesgo temporal).',
      ],
    },
    {
      extKey: 'iii-app-06',
      skillTag: 'Regresiones y series temporales autorregresivas',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Validas un modelo de pronóstico de demanda con validación cruzada aleatoria estándar y obtiene un error bajísimo. Al desplegarlo, falla. ¿Cuál es la causa más probable?',
      options: [
        'El modelo es demasiado simple.',
        'La validación aleatoria mezcló futuro y pasado (fuga temporal): el modelo "vio" datos posteriores al predecir; hay que usar validación respetando el orden del tiempo.',
        'Faltaba normalizar las variables.',
        'El conjunto de prueba era demasiado grande.',
      ],
      correctIndex: 1,
      explanations: [
        'La simplicidad no explica un error de validación bajo que luego falla.',
        'Correcto: en series temporales, barajar los datos filtra información del futuro; la validación debe ser hacia adelante en el tiempo.',
        'La normalización no causaría este patrón concreto.',
        'Un conjunto de prueba grande no infla artificialmente el rendimiento.',
      ],
    },
    {
      extKey: 'iii-app-07',
      skillTag: 'Árboles de decisión y Algoritmos',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'Un único árbol de decisión profundo memoriza casi perfectamente el conjunto de entrenamiento pero generaliza mal. Un bosque aleatorio (random forest) sobre los mismos datos generaliza mejor. ¿Por qué?',
      options: [
        'Porque el bosque usa menos datos.',
        'Porque promedia muchos árboles entrenados sobre muestras y subconjuntos de variables distintos, reduciendo la varianza (el sobreajuste de un solo árbol).',
        'Porque los árboles del bosque son más profundos.',
        'Porque el bosque no usa árboles, sino redes neuronales.',
      ],
      correctIndex: 1,
      explanations: [
        'El bosque usa remuestreo, no menos datos en total.',
        'Correcto: la agregación de árboles decorrelacionados reduce la varianza y mitiga el sobreajuste.',
        'La profundidad individual no es la razón; es la agregación.',
        'Un random forest sí es un conjunto de árboles.',
      ],
    },
    {
      extKey: 'iii-app-08',
      skillTag: 'Redes neuronales Artificiales',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'En términos conceptuales, ¿qué hace la retropropagación durante el entrenamiento de una red neuronal?',
      options: [
        'Aumenta el número de capas automáticamente.',
        'Calcula cómo contribuye cada peso al error de salida y ajusta cada peso en la dirección que reduce ese error, capa por capa hacia atrás.',
        'Elimina las neuronas que no se usan.',
        'Cifra los pesos para protegerlos.',
      ],
      correctIndex: 1,
      explanations: [
        'La arquitectura (nº de capas) la fija el diseñador, no la retropropagación.',
        'Correcto: propaga el gradiente del error hacia atrás para actualizar cada peso.',
        'La poda de neuronas es otra técnica distinta.',
        'No tiene relación con cifrado.',
      ],
    },
    {
      extKey: 'iii-app-09',
      skillTag: 'Redes neuronales Artificiales',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Añades más capas a una red y el rendimiento en entrenamiento mejora, pero en validación empeora claramente. ¿Qué está pasando y qué harías?',
      options: [
        'Sesgo alto: añadir aún más capas.',
        'Varianza alta (sobreajuste): la capacidad extra memoriza el entrenamiento; regularizar, obtener más datos o reducir capacidad.',
        'Los datos están mal etiquetados y no hay solución.',
        'Es normal: siempre pasa y no importa.',
      ],
      correctIndex: 1,
      explanations: [
        'Si entrenamiento mejora y validación empeora, no es falta de capacidad.',
        'Correcto: es la firma del sobreajuste; se ataca con regularización, más datos o menos capacidad.',
        'El sobreajuste tiene remedios; no implica etiquetas malas.',
        'La brecha entrenamiento-validación sí importa: predice el fallo en producción.',
      ],
    },
    {
      extKey: 'iii-app-10',
      skillTag: 'Aprendizaje Automático',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Al construir features para un modelo de scoring, un compañero incluye "número de reclamaciones del cliente en los últimos 12 meses", pero la etiqueta a predecir es "el cliente presentará una reclamación en los próximos 30 días". ¿Qué revisas?',
      options: [
        'Nada: más features siempre es mejor.',
        'Si esa feature incluye información posterior al momento de la predicción (los 12 meses deben terminar antes de la fecha de corte), para evitar fuga de datos.',
        'Si la feature está normalizada entre 0 y 1.',
        'Si el nombre de la columna es descriptivo.',
      ],
      correctIndex: 1,
      explanations: [
        'Features que filtran el futuro inflan el rendimiento y fallan en producción.',
        'Correcto: hay que asegurar que toda feature usa solo información disponible en el instante de predecir.',
        'La normalización no es el riesgo aquí.',
        'El nombre no afecta la validez estadística.',
      ],
    },
    {
      extKey: 'iii-app-11',
      skillTag: 'Regresiones y series temporales autorregresivas',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Un modelo autorregresivo predice el valor de mañana principalmente a partir de:',
      options: [
        'Variables completamente ajenas a la serie.',
        'Los valores pasados recientes de la propia serie (y opcionalmente variables externas).',
        'Un promedio global de todo el histórico, sin orden.',
        'La media del sector.',
      ],
      correctIndex: 1,
      explanations: [
        'Un modelo autorregresivo se basa, por definición, en la propia serie.',
        'Correcto: "autorregresivo" = regresión sobre los propios rezagos.',
        'Ignorar el orden temporal contradice la idea de serie temporal.',
        'La media del sector es un dato externo, no la base del modelo autorregresivo.',
      ],
    },
    {
      extKey: 'iii-app-12',
      skillTag: 'Arquitecturas y Soluciones de Big Data: Análisis, Procesamiento y Escalabilidad en la Era Digital',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Si el volumen de datos de tu pipeline actual se multiplica por diez de un día para otro, ¿cuál es el primer cuello de botella que anticiparías en una arquitectura típica de un solo nodo?',
      options: [
        'El color del tablero de visualización.',
        'La memoria y el disco del nodo único: las operaciones que hoy caben en RAM empiezan a paginar o a fallar, y hay que pasar a procesamiento por particiones o distribuido.',
        'La velocidad de la conexión wifi de la oficina.',
        'El número de usuarios del tablero.',
      ],
      correctIndex: 1,
      explanations: [
        'La visualización no es el cuello con ese crecimiento.',
        'Correcto: en un solo nodo, RAM y disco son el primer límite; ×10 obliga a particionar o distribuir.',
        'La red de oficina no interviene en el procesamiento del servidor.',
        'El número de usuarios del tablero es independiente del volumen de datos procesado.',
      ],
    },
    { extKey: 'iii-app-13', skillTag: 'Arquitecturas y Soluciones de Big Data: Análisis, Procesamiento y Escalabilidad en la Era Digital', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Necesitas consultar de forma analítica 40 GB de ficheros Parquet en tu portátil, una vez al día. ¿Qué herramienta pruebas primero?',
      options: ['Un clúster Spark gestionado.', 'DuckDB o Polars en local: leen Parquet eficientemente, no cargan todo en memoria y evitan la sobrecarga de un clúster para un trabajo diario.', 'Cargar todo a pandas de golpe.', 'Una base de datos relacional tradicional.'],
      correctIndex: 1,
      explanations: ['Un clúster para 40 GB diarios es sobreingeniería.', 'Correcto: motores columnares locales resuelven este volumen sin clúster.', 'pandas cargaría 40 GB en RAM y fallaría.', 'Una relacional no es óptima para consulta analítica sobre Parquet.'] },
    { extKey: 'iii-app-14', skillTag: 'Arquitecturas y Soluciones de Big Data: Análisis, Procesamiento y Escalabilidad en la Era Digital', difficulty: 'alta', cognitive: 'analisis',
      stem: 'Tu pipeline batch nocturno tarda 6 h y el negocio pide resultados a las 6:00. Empieza a las 2:00 pero a veces se retrasa. ¿Primera acción de diagnóstico?',
      options: ['Migrar todo a streaming.', 'Perfilar el pipeline para ver qué etapa consume el tiempo (lectura, join, escritura) y si el cuello es E/S, CPU o un skew de datos, antes de rediseñar.', 'Comprar más nodos sin analizar.', 'Adelantar el inicio a medianoche y no tocar nada más.'],
      correctIndex: 1,
      explanations: ['Migrar a streaming sin saber la causa es un rediseño a ciegas.', 'Correcto: primero se localiza la etapa y el tipo de cuello.', 'Más nodos sin diagnóstico puede no ayudar si el cuello es E/S o skew.', 'Adelantar el inicio no arregla la variabilidad del retraso.'] },
    { extKey: 'iii-app-15', skillTag: 'Entornos de trabajo para arquitecturas Deep Learning', difficulty: 'media', cognitive: 'comprension',
      stem: '¿Qué aporta la precisión mixta (mixed precision) al entrenar en GPU?',
      options: ['Más exactitud del modelo garantizada.', 'Menor uso de memoria y mayor velocidad al usar formatos de menor precisión donde es seguro, manteniendo la estabilidad numérica en las partes sensibles.', 'Elimina la necesidad de datos.', 'Cifra los pesos.'],
      correctIndex: 1,
      explanations: ['No garantiza más exactitud; a veces la mantiene con leve variación.', 'Correcto: reduce VRAM y acelera, con salvaguardas numéricas.', 'No tiene relación con los datos.', 'No es cifrado.'] },
    { extKey: 'iii-app-16', skillTag: 'Entornos de trabajo para arquitecturas Deep Learning', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Dos personas del equipo obtienen resultados distintos con "el mismo" experimento. ¿Qué falló probablemente?',
      options: ['La GPU de una es más rápida.', 'No hay control de versiones de datos, código y semillas aleatorias: sin registrar esos elementos, "el mismo experimento" no es reproducible.', 'Una usó más épocas por error de tipeo, y no hay forma de saberlo.', 'Ambas: falta trazabilidad de la configuración.'],
      correctIndex: 3,
      explanations: ['La velocidad de la GPU no cambia el resultado, solo el tiempo.', 'Es parte de la causa.', 'También es parte de la causa.', 'Correcto: sin seguimiento de experimentos (datos, código, semillas, hiperparámetros) no se puede saber por qué difieren ni reproducirlos.'] },
    { extKey: 'iii-app-17', skillTag: 'Aprendizaje Automático', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Tienes 500 M de filas y quieres iterar rápido sobre features. ¿Estrategia?',
      options: ['Probar cada idea sobre las 500 M.', 'Trabajar sobre una muestra representativa (estratificada por las variables clave) para iterar en minutos, y validar la versión final sobre el conjunto completo.', 'Usar solo las primeras 100 000 filas.', 'Eliminar el 90% de columnas al azar.'],
      correctIndex: 1,
      explanations: ['Iterar sobre 500 M hace inviable la experimentación.', 'Correcto: muestra representativa para iterar, conjunto completo para confirmar.', 'Las primeras filas pueden tener sesgo temporal.', 'Descartar columnas al azar pierde señal de forma incontrolada.'] },
    { extKey: 'iii-app-18', skillTag: 'Aprendizaje Automático', difficulty: 'alta', cognitive: 'analisis',
      stem: 'Al validar un modelo a gran escala con validación cruzada, cada pliegue tarda horas. ¿Cómo reduces el coste sin invalidar la estimación?',
      options: ['Usar un solo pliegue.', 'Reducir el número de pliegues (p. ej. de 10 a 3-5) y/o muestrear para la búsqueda de hiperparámetros, reservando la validación completa para el modelo candidato final.', 'Validar solo sobre entrenamiento.', 'Saltarse la validación.'],
      correctIndex: 1,
      explanations: ['Un solo pliegue da una estimación con mucha varianza.', 'Correcto: menos pliegues y muestreo para explorar, validación completa para el finalista.', 'Validar sobre entrenamiento no estima la generalización.', 'Sin validación no sabes si el modelo sirve.'] },
    { extKey: 'iii-app-19', skillTag: 'Regresiones y series temporales autorregresivas', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Vas a pronosticar la demanda semanal de un producto con fuerte estacionalidad anual. ¿Qué NO debes hacer al validar?',
      options: ['Usar validación que respete el orden temporal.', 'Barajar aleatoriamente las semanas y hacer validación cruzada estándar: mezcla futuro y pasado y sobrestima el rendimiento.', 'Reservar los últimos meses como conjunto de prueba.', 'Incluir variables de calendario (mes, festivos).'],
      correctIndex: 1,
      explanations: ['Respetar el orden temporal es lo correcto.', 'Correcto: barajar series temporales filtra información del futuro (fuga temporal).', 'Reservar el final como test es la práctica adecuada.', 'Las variables de calendario ayudan con la estacionalidad.'] },
    { extKey: 'iii-app-20', skillTag: 'Regresiones y series temporales autorregresivas', difficulty: 'baja', cognitive: 'comprension',
      stem: 'Un modelo de regresión tiene R² alto pero residuos con un patrón claro (crecen con el valor predicho). ¿Qué indica?',
      options: ['El modelo es perfecto.', 'Que el modelo no captura toda la estructura (posible relación no lineal o heterocedasticidad); el R² alto no basta, hay que mirar los residuos.', 'Que hay que subir el R² a 1.', 'Que faltan más datos siempre.'],
      correctIndex: 1,
      explanations: ['Un patrón en los residuos contradice "perfecto".', 'Correcto: los residuos con estructura señalan que falta modelar algo.', 'Perseguir R²=1 lleva al sobreajuste.', 'Más datos no corrige una forma funcional inadecuada.'] },
    { extKey: 'iii-app-21', skillTag: 'Árboles de decisión y Algoritmos', difficulty: 'media', cognitive: 'comprension',
      stem: '¿Por qué un gradient boosting suele superar a un solo árbol y a un random forest en tabla estructurada?',
      options: ['Porque usa menos datos.', 'Porque construye árboles secuencialmente, cada uno corrigiendo los errores del conjunto anterior, reduciendo el sesgo además de la varianza.', 'Porque los árboles son más profundos.', 'Porque no es un método de árboles.'],
      correctIndex: 1,
      explanations: ['Usa los mismos datos.', 'Correcto: el boosting reduce sesgo con el aprendizaje secuencial de residuos.', 'La profundidad individual suele ser baja en boosting.', 'Sí es un método basado en árboles.'] },
    { extKey: 'iii-app-22', skillTag: 'Árboles de decisión y Algoritmos', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Un cliente exige poder auditar cada decisión de aprobación. Entre un árbol de decisión poco profundo y un gradient boosting con más exactitud, ¿qué priorizas?',
      options: ['El gradient boosting siempre.', 'El árbol poco profundo: la exigencia de auditar cada decisión pesa más que un incremento marginal de exactitud de un modelo difícil de explicar caso a caso.', 'kNN.', 'Una red neuronal.'],
      correctIndex: 1,
      explanations: ['Un modelo opaco dificulta la auditoría por decisión.', 'Correcto: con explicabilidad como requisito duro se empieza por modelos legibles.', 'kNN es costoso en predicción y difícil de explicar por caso.', 'Una red profunda agrava el problema de explicabilidad.'] },
    { extKey: 'iii-app-23', skillTag: 'Redes neuronales Artificiales', difficulty: 'media', cognitive: 'comprension',
      stem: 'La "profundidad" de una red neuronal aporta, conceptualmente:',
      options: ['Más velocidad de entrenamiento.', 'La capacidad de aprender representaciones jerárquicas: capas iniciales captan rasgos simples y las profundas, combinaciones abstractas.', 'Menos parámetros.', 'Que no necesita datos.'],
      correctIndex: 1,
      explanations: ['Más profundidad suele entrenar más lento.', 'Correcto: la jerarquía de representaciones es la ventaja de la profundidad.', 'La profundidad suele añadir parámetros.', 'Sigue necesitando datos, a menudo muchos.'] },
    { extKey: 'iii-app-24', skillTag: 'Redes neuronales Artificiales', difficulty: 'alta', cognitive: 'analisis',
      stem: 'Tu red entrena bien pero el error de validación se estanca muy por encima del de entrenamiento y no baja con más épocas. ¿Qué pruebas?',
      options: ['Añadir muchas más capas.', 'Regularización (dropout, weight decay), aumento de datos o reducir la capacidad: es sobreajuste, no falta de capacidad.', 'Subir el learning rate x100.', 'Nada, es normal.'],
      correctIndex: 1,
      explanations: ['Más capas agravan el sobreajuste.', 'Correcto: la brecha estable entrenamiento-validación es sobreajuste; se ataca con regularización o más datos.', 'Un learning rate x100 desestabiliza el entrenamiento.', 'La brecha predice el fallo en producción.'] },
    { extKey: 'iii-app-25', skillTag: 'Aprendizaje Automático', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Construyes features para predecir "el pedido se entregará tarde". Incluyes "número de llamadas del cliente por retraso". ¿Riesgo?',
      options: ['Ninguno, más features mejora.', 'Fuga de datos: esa variable solo se puebla cuando el retraso ya ocurrió; usar solo información disponible en el momento de predecir.', 'Que la variable no está normalizada.', 'Que el nombre es poco claro.'],
      correctIndex: 1,
      explanations: ['Features que filtran el futuro inflan el rendimiento y fallan en producción.', 'Correcto: hay que garantizar que toda feature usa solo información previa a la predicción.', 'La normalización no es el riesgo aquí.', 'El nombre no afecta la validez.'] },
    { extKey: 'iii-app-26', skillTag: 'Arquitecturas y Soluciones de Big Data: Análisis, Procesamiento y Escalabilidad en la Era Digital', difficulty: 'baja', cognitive: 'comprension',
      stem: 'En una arquitectura por capas de Big Data, ¿cuál es el orden habitual?',
      options: ['Servicio → procesamiento → ingesta → almacenamiento.', 'Ingesta → almacenamiento → procesamiento → servicio/consumo.', 'Procesamiento → ingesta → servicio → almacenamiento.', 'No hay un orden.'],
      correctIndex: 1,
      explanations: ['Ese orden está invertido.', 'Correcto: los datos entran, se guardan, se procesan y se sirven al consumidor.', 'El procesamiento no precede a la ingesta.', 'Sí hay un flujo lógico estándar.'] },
    { extKey: 'iii-app-27', skillTag: 'Regresiones y series temporales autorregresivas', difficulty: 'media', cognitive: 'analisis',
      stem: 'Tu pronóstico funciona en histórico pero falla los primeros meses tras un cambio de política de precios. ¿Causa y respuesta?',
      options: ['El modelo es demasiado simple.', 'Cambio estructural en la serie: el patrón pasado ya no aplica; hay que reentrenar con datos posteriores al cambio y considerar una variable que marque el nuevo régimen.', 'Faltó normalizar.', 'El conjunto de prueba era grande.'],
      correctIndex: 1,
      explanations: ['La simplicidad no explica un fallo ligado a un evento concreto.', 'Correcto: un cambio estructural rompe la validez del histórico previo.', 'La normalización no causa este patrón.', 'El tamaño del test no infla el rendimiento histórico.'] },
    { extKey: 'iii-app-28', skillTag: 'Entornos de trabajo para arquitecturas Deep Learning', difficulty: 'baja', cognitive: 'comprension',
      stem: 'PyTorch y TensorFlow son, en este contexto:',
      options: ['Bases de datos.', 'Frameworks de deep learning que proveen tensores, diferenciación automática y utilidades de entrenamiento en GPU.', 'Servicios de nube.', 'Formatos de archivo de datos.'],
      correctIndex: 1,
      explanations: ['No son bases de datos.', 'Correcto: son las bibliotecas para construir y entrenar redes.', 'No son servicios de nube (aunque corran en ella).', 'No son formatos de datos.'] },
    { extKey: 'iii-app-29', skillTag: 'Árboles de decisión y Algoritmos', difficulty: 'media', cognitive: 'analisis',
      stem: 'Un random forest da 100% de exactitud en entrenamiento y 74% en test. Un solo árbol daba 82% en ambos. ¿Qué prefieres y por qué?',
      options: ['El random forest, siempre gana.', 'Depende: si necesitas generalización y el árbol único es más estable (82/82) frente al bosque sobreajustado (100/74), conviene ajustar el bosque (limitar profundidad, más árboles) o quedarte con el árbol.', 'El árbol único, siempre.', 'Ninguno sirve.'],
      correctIndex: 1,
      explanations: ['El random forest aquí está sobreajustado (brecha 26 puntos).', 'Correcto: la decisión se basa en la generalización real; el bosque necesita regularización o se prefiere el árbol estable.', 'El árbol único no siempre es mejor; aquí lo es tras el ajuste pendiente del bosque.', 'El árbol al 82/82 sí sirve.'] },
    { extKey: 'iii-app-30', skillTag: 'Redes neuronales Artificiales', difficulty: 'baja', cognitive: 'comprension',
      stem: 'La retropropagación, en una frase:',
      options: ['Añade capas automáticamente.', 'Calcula cómo contribuye cada peso al error de salida y ajusta cada peso en la dirección que reduce ese error, propagando el gradiente hacia atrás.', 'Elimina neuronas no usadas.', 'Cifra los pesos.'],
      correctIndex: 1,
      explanations: ['La arquitectura la fija el diseñador.', 'Correcto: propaga el gradiente del error hacia atrás para actualizar los pesos.', 'La poda es otra técnica.', 'No es cifrado.'] },
  ],
};
