// Banco de ítems de aplicación — Asignatura VII: Prompts multimodales y contextos complejos.
module.exports = {
  slug: 'bank-master-vii',
  title: 'Banco de ítems — Asignatura VII',
  scopeSlug: 'master-vii',
  questions: [
    {
      extKey: 'vii-app-01',
      skillTag: 'Evaluación de la usabilidad',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Cambias un prompt y "parece que responde mejor". ¿Qué necesitas para poder afirmar que mejoró y no que tuviste suerte?',
      options: [
        'La opinión de un compañero.',
        'Una batería de casos con respuesta esperada y una métrica (tasa de acierto, de reformulación) medida sobre la versión anterior y la nueva, para reportar el delta.',
        'Que el prompt sea más largo.',
        'Ejecutarlo una vez más y ver si sale igual.',
      ],
      correctIndex: 1,
      explanations: [
        'Una impresión no distingue mejora real de azar.',
        'Correcto: la evaluación sistemática con casos y métricas es lo que permite atribuir la mejora al cambio.',
        'La longitud no es indicador de calidad.',
        'Una segunda ejecución no controla la variabilidad ni compara versiones.',
      ],
    },
    {
      extKey: 'vii-app-02',
      skillTag: 'Integración de texto, imagen y sonido',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'Los modelos multimodales suelen apoyarse en un "espacio de representación compartido". En la práctica, ¿qué permite eso?',
      options: [
        'Que el modelo funcione sin datos.',
        'Relacionar contenidos de distinta modalidad (una frase y una imagen) porque se proyectan a un espacio común donde conceptos parecidos quedan cerca.',
        'Que la imagen y el texto ocupen el mismo archivo.',
        'Que el modelo no necesite entrenamiento.',
      ],
      correctIndex: 1,
      explanations: [
        'El espacio compartido se aprende con datos.',
        'Correcto: proyectar modalidades a un espacio común es lo que permite emparejar texto e imagen por significado.',
        'No es una cuestión de formato de archivo.',
        'El espacio compartido es resultado del entrenamiento.',
      ],
    },
    {
      extKey: 'vii-app-03',
      skillTag: 'Desafíos en entornos multimodales',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un asistente recibe una captura de pantalla y una instrucción de texto que se contradicen (el texto dice "el botón azul", la imagen no tiene botón azul). El sistema inventa una respuesta. ¿Qué desafío multimodal es y cómo se mitiga?',
      options: [
        'Sobreajuste; se mitiga con más capas.',
        'Desalineación entre modalidades y alucinación multimodal; se mitiga instruyendo al modelo a señalar la contradicción y pedir aclaración en vez de resolverla por su cuenta.',
        'Falta de GPU.',
        'Un error de la cámara.',
      ],
      correctIndex: 1,
      explanations: [
        'No es sobreajuste ni se resuelve con arquitectura.',
        'Correcto: la desalineación provoca alucinación; el prompt de sistema debe forzar a explicitar la contradicción.',
        'El hardware no causa la contradicción semántica.',
        'La entrada puede ser correcta; el problema es cómo el modelo maneja la incoherencia.',
      ],
    },
    {
      extKey: 'vii-app-04',
      skillTag: 'Adaptación de Prompts a Diferentes audiencias',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Debes adaptar un mismo contenido técnico para tres audiencias: dirección, equipo técnico y clientes. ¿Qué cambia de forma más determinante entre las tres versiones del prompt?',
      options: [
        'El idioma.',
        'El nivel de detalle, el vocabulario y qué se pide destacar (impacto y decisión para dirección; mecanismo y límites para el equipo; beneficio y pasos para el cliente).',
        'La fuente tipográfica de salida.',
        'El nombre del modelo usado.',
      ],
      correctIndex: 1,
      explanations: [
        'El idioma puede ser el mismo; no es lo determinante.',
        'Correcto: la adaptación de audiencia cambia detalle, registro y foco de la salida.',
        'La tipografía no es parte del contenido adaptado.',
        'El modelo no cambia por audiencia necesariamente.',
      ],
    },
    {
      extKey: 'vii-app-05',
      skillTag: 'Creación de Prompts para interfaces inteligentes',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Diseñas el prompt de sistema de un asistente de atención embebido en un producto. ¿Qué elemento es imprescindible además de la personalidad?',
      options: [
        'Un chiste de bienvenida.',
        'Límites claros: qué NO debe hacer (dar precios no confirmados, prometer plazos, salirse del dominio) y cómo manejar preguntas ambiguas o fuera de alcance.',
        'El historial completo de versiones del producto.',
        'La biografía del equipo de desarrollo.',
      ],
      correctIndex: 1,
      explanations: [
        'Un chiste no es un requisito de diseño.',
        'Correcto: los límites y el manejo de ambigüedad son tan importantes como el tono para una interfaz fiable.',
        'El historial de versiones no ayuda al comportamiento del asistente.',
        'La biografía del equipo es irrelevante para el usuario final.',
      ],
    },
    {
      extKey: 'vii-app-06',
      skillTag: 'Evaluación de la usabilidad',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un asistente tiene alta "satisfacción declarada" en encuestas pero baja "tasa de éxito de tarea" medida. ¿Qué priorizas?',
      options: [
        'La satisfacción declarada: si dicen que les gusta, está bien.',
        'La efectividad real: la satisfacción puede reflejar cortesía o novedad; si la tarea no se completa, el asistente no cumple su función.',
        'Ninguna de las dos; medir el tiempo de respuesta.',
        'Rediseñar la encuesta para que dé mejores números.',
      ],
      correctIndex: 1,
      explanations: [
        'La satisfacción sin éxito de tarea es un indicador poco fiable.',
        'Correcto: la efectividad (¿se completó la tarea?) manda sobre la satisfacción declarada.',
        'El tiempo de respuesta no dice si la tarea se logró.',
        'Manipular la encuesta oculta el problema en vez de resolverlo.',
      ],
    },
    {
      extKey: 'vii-app-07',
      skillTag: 'Aplicaciones en arte digital y transmedia',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'En generación de imagen para una campaña, tratar el prompt "como dirección de arte" significa:',
      options: [
        'Escribir la primera frase que venga a la mente.',
        'Especificar estilo, composición, luz, referencias y restricciones de forma deliberada y consistente, igual que un briefing a un ilustrador humano.',
        'Dejar que el modelo elija todo.',
        'Usar solo una palabra clave.',
      ],
      correctIndex: 1,
      explanations: [
        'La improvisación produce resultados inconsistentes.',
        'Correcto: la dirección de arte implica un briefing explícito y repetible.',
        'Delegar todo impide una identidad visual coherente.',
        'Una sola palabra deja demasiadas decisiones al azar.',
      ],
    },
    {
      extKey: 'vii-app-08',
      skillTag: 'Desafíos en entornos multimodales',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un prompt multimodal falla siempre en el mismo tipo de imagen (documentos escaneados con poca resolución). Antes de reescribir el prompt, ¿qué compruebas?',
      options: [
        'Si el prompt tiene faltas de ortografía.',
        'Si el problema está en la entrada (calidad de la imagen) o en el contexto, y no en el prompt: quizá el modelo no puede leer ese nivel de resolución y la solución es mejorar la captura, no el texto.',
        'Si el modelo tiene modo oscuro.',
        'Cambiar el orden de las palabras del prompt.',
      ],
      correctIndex: 1,
      explanations: [
        'La ortografía rara vez es la causa de un fallo sistemático por tipo de imagen.',
        'Correcto: hay que distinguir si el cuello está en la entrada/contexto o en el prompt antes de iterar.',
        'El modo oscuro no existe ni afecta a esto.',
        'Reordenar palabras no arregla una limitación de percepción del modelo.',
      ],
    },
    {
      extKey: 'vii-app-09',
      skillTag: 'Integración de texto, imagen y sonido',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'El "sesgo heredado" en un modelo multimodal se refiere a:',
      options: [
        'Un error de programación del desarrollador.',
        'Que el modelo reproduce en sus salidas los sesgos presentes en los datos de texto e imagen con que se entrenó (asociaciones estereotipadas, sub-representación).',
        'Un problema de la GPU.',
        'La preferencia del usuario por ciertos colores.',
      ],
      correctIndex: 1,
      explanations: [
        'No es un bug puntual, es un efecto de los datos.',
        'Correcto: el modelo hereda los sesgos de su corpus de entrenamiento.',
        'No tiene relación con el hardware.',
        'No se refiere a preferencias estéticas del usuario.',
      ],
    },
    {
      extKey: 'vii-app-10',
      skillTag: 'Adaptación de Prompts a Diferentes audiencias',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Debes generar una versión de un aviso para una audiencia con requisitos de accesibilidad. ¿Qué instrucción añades al prompt?',
      options: [
        'Que use más emojis.',
        'Lenguaje claro y directo, frases cortas, evitar dobles negaciones y jerga, estructura con encabezados y, si hay imágenes, texto alternativo descriptivo.',
        'Que el texto sea más largo para dar más contexto.',
        'Que incluya más tecnicismos para ser preciso.',
      ],
      correctIndex: 1,
      explanations: [
        'Los emojis pueden dificultar la lectura con lectores de pantalla.',
        'Correcto: claridad, frases cortas, estructura y textos alternativos son criterios de accesibilidad.',
        'Más longitud suele reducir la accesibilidad, no aumentarla.',
        'Los tecnicismos empeoran la comprensión de una audiencia amplia.',
      ],
    },
    {
      extKey: 'vii-app-11',
      skillTag: 'Creación de Prompts para interfaces inteligentes',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Quieres versionar tus prompts como versionas código. ¿Qué práctica es la más valiosa?',
      options: [
        'Guardar solo la última versión que funcionó.',
        'Mantener cada versión en control de versiones junto a su suite de evaluación, registrando qué cambio movió qué métrica, para poder revertir y auditar.',
        'Copiar los prompts en un documento de texto sin fecha.',
        'Memorizar el prompt.',
      ],
      correctIndex: 1,
      explanations: [
        'Guardar solo la última impide revertir y entender la evolución.',
        'Correcto: prompts en git + evaluación ejecutable + registro de deltas es la práctica del criterio de dominio.',
        'Un documento sin control de versiones no permite auditar cambios.',
        'Memorizar no escala ni deja rastro.',
      ],
    },
    {
      extKey: 'vii-app-12',
      skillTag: 'Evaluación de la usabilidad',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'La "tasa de reformulación" como métrica de un asistente mide:',
      options: [
        'Cuántas veces el modelo se reinicia.',
        'Con qué frecuencia el usuario tiene que volver a escribir su petición porque la primera respuesta no sirvió: una tasa alta indica mala comprensión o instrucciones poco claras.',
        'El número de palabras por respuesta.',
        'La velocidad de la red.',
      ],
      correctIndex: 1,
      explanations: [
        'No mide reinicios del sistema.',
        'Correcto: mide fricción; muchas reformulaciones = el asistente no entiende a la primera.',
        'La longitud de la respuesta es otra cosa.',
        'La red no es lo que mide esta métrica.',
      ],
    },
    { extKey: 'vii-app-13', skillTag: 'Evaluación de la usabilidad', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Vas a comparar 3 versiones de un prompt. ¿Qué diseño de evaluación da una conclusión defendible?',
      options: ['Probar cada uno una vez y ver cuál "va mejor".', 'Una batería de 15-20 casos con respuesta esperada, ejecutar las 3 versiones sobre los mismos casos y comparar la tasa de acierto (y su variación si el modelo es no determinista).', 'Preguntar a un compañero cuál prefiere.', 'Elegir el más largo.'],
      correctIndex: 1,
      explanations: ['Una ejecución no distingue mejora de azar.', 'Correcto: casos fijos + métrica sobre los mismos casos = comparación válida.', 'Una preferencia subjetiva no es evaluación.', 'La longitud no es un criterio.'] },
    { extKey: 'vii-app-14', skillTag: 'Evaluación de la usabilidad', difficulty: 'baja', cognitive: 'comprension',
      stem: 'La "tasa de éxito de tarea" mide:',
      options: ['Cuántas palabras genera el modelo.', 'Qué proporción de intentos del usuario terminan con la tarea completada correctamente; es la métrica de efectividad principal.', 'La velocidad de respuesta.', 'El número de tokens de entrada.'],
      correctIndex: 1,
      explanations: ['No cuenta palabras.', 'Correcto: es la métrica de si el asistente cumple su función.', 'La velocidad es otra métrica.', 'Los tokens de entrada no la miden.'] },
    { extKey: 'vii-app-15', skillTag: 'Integración de texto, imagen y sonido', difficulty: 'media', cognitive: 'comprension',
      stem: 'El entrenamiento "contrastivo" en modelos multimodales consiste, a grandes rasgos, en:',
      options: ['Etiquetar cada imagen a mano.', 'Acercar en el espacio de representación los pares que van juntos (una imagen y su descripción real) y alejar los que no, sin necesidad de etiquetas de clase.', 'Generar texto a partir de ruido.', 'Comprimir imágenes.'],
      correctIndex: 1,
      explanations: ['No requiere etiquetado manual de clases.', 'Correcto: aprende relacionando pares correctos frente a incorrectos.', 'Eso describe generación, no aprendizaje contrastivo.', 'No es compresión.'] },
    { extKey: 'vii-app-16', skillTag: 'Integración de texto, imagen y sonido', difficulty: 'baja', cognitive: 'comprension',
      stem: 'Un "espacio de representación compartido" entre texto e imagen permite:',
      options: ['Que texto e imagen ocupen el mismo archivo.', 'Emparejar contenidos de distinta modalidad por significado (buscar imágenes con una frase, o describir una imagen), porque conceptos parecidos quedan cerca.', 'Que el modelo funcione sin datos.', 'Cifrar las imágenes.'],
      correctIndex: 1,
      explanations: ['No es cuestión de formato de archivo.', 'Correcto: proyectar modalidades a un espacio común habilita el cruce por significado.', 'El espacio se aprende con datos.', 'No es cifrado.'] },
    { extKey: 'vii-app-17', skillTag: 'Aplicaciones en arte digital y transmedia', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Necesitas coherencia visual en 30 imágenes de una campaña. ¿Qué práctica de prompting aplica?',
      options: ['Improvisar cada prompt.', 'Fijar una "biblia" de estilo (paleta, iluminación, composición, referencias) y reutilizarla en todos los prompts, variando solo el contenido específico de cada pieza.', 'Usar una palabra clave distinta cada vez.', 'Dejar que el modelo elija el estilo.'],
      correctIndex: 1,
      explanations: ['Improvisar produce inconsistencia.', 'Correcto: una guía de estilo reutilizable da coherencia.', 'Cambiar de palabra clave rompe la consistencia.', 'Delegar el estilo impide una identidad coherente.'] },
    { extKey: 'vii-app-18', skillTag: 'Aplicaciones en arte digital y transmedia', difficulty: 'baja', cognitive: 'comprension',
      stem: 'Tratar el prompt "como dirección de arte" implica:',
      options: ['Escribir lo primero que venga a la mente.', 'Especificar de forma deliberada estilo, composición, luz y restricciones, como un briefing a un ilustrador humano, para poder repetir el resultado.', 'Usar solo una palabra.', 'Dejar todo al azar.'],
      correctIndex: 1,
      explanations: ['La improvisación no es dirección de arte.', 'Correcto: un briefing explícito y repetible.', 'Una palabra deja demasiado al azar.', 'El azar impide consistencia.'] },
    { extKey: 'vii-app-19', skillTag: 'Desafíos en entornos multimodales', difficulty: 'alta', cognitive: 'analisis',
      stem: 'Un asistente recibe una imagen borrosa y una instrucción que asume detalles que la imagen no muestra. Responde inventando. ¿Qué desafío es y cómo se mitiga en el prompt de sistema?',
      options: ['Sobreajuste; añadir capas.', 'Alucinación multimodal por entrada insuficiente: instruir al modelo a declarar qué no puede ver y pedir una imagen mejor o aclaración, en vez de rellenar huecos.', 'Falta de GPU.', 'Un error de la cámara únicamente.'],
      correctIndex: 1,
      explanations: ['No es arquitectura.', 'Correcto: el prompt de sistema debe forzar a reconocer la incertidumbre.', 'El hardware no es la causa.', 'La entrada puede ser mala, pero el problema es cómo el modelo la maneja.'] },
    { extKey: 'vii-app-20', skillTag: 'Desafíos en entornos multimodales', difficulty: 'media', cognitive: 'comprension',
      stem: 'El "coste" es un desafío específico de los sistemas multimodales porque:',
      options: ['Las imágenes son gratis de procesar.', 'Procesar imagen o audio de alta resolución consume muchos más recursos que texto; a escala, el coste por consulta puede ser un factor limitante del diseño.', 'El texto es más caro que la imagen.', 'No hay diferencia de coste.'],
      correctIndex: 1,
      explanations: ['La imagen no es gratis de procesar.', 'Correcto: la modalidad visual/auditiva encarece la inferencia y hay que dimensionarlo.', 'Suele ser al revés.', 'Sí hay diferencia notable.'] },
    { extKey: 'vii-app-21', skillTag: 'Adaptación de Prompts a Diferentes audiencias', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Adaptas un informe técnico para dirección. ¿Qué cambias en el prompt principalmente?',
      options: ['El idioma.', 'El foco (impacto y decisión, no mecanismo), el nivel de detalle (menos) y el vocabulario (sin jerga), pidiendo empezar por la conclusión.', 'La fuente tipográfica.', 'El modelo usado.'],
      correctIndex: 1,
      explanations: ['El idioma puede ser el mismo.', 'Correcto: la adaptación a dirección cambia foco, detalle y registro.', 'La tipografía no es contenido.', 'El modelo no cambia por audiencia.'] },
    { extKey: 'vii-app-22', skillTag: 'Adaptación de Prompts a Diferentes audiencias', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Generas una versión de un aviso para una audiencia con requisitos de accesibilidad. ¿Qué instruyes?',
      options: ['Más emojis para hacerlo ameno.', 'Lenguaje claro, frases cortas, sin dobles negaciones ni jerga, estructura con encabezados, y texto alternativo descriptivo para cualquier imagen.', 'Texto más largo para dar contexto.', 'Más tecnicismos para ser preciso.'],
      correctIndex: 1,
      explanations: ['Los emojis dificultan los lectores de pantalla.', 'Correcto: claridad, estructura y textos alternativos son criterios de accesibilidad.', 'Más longitud suele reducir accesibilidad.', 'Los tecnicismos empeoran la comprensión.'] },
    { extKey: 'vii-app-23', skillTag: 'Creación de Prompts para interfaces inteligentes', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Diseñas el prompt de sistema de un asistente embebido en un producto. Además del tono, ¿qué es imprescindible?',
      options: ['Un saludo divertido.', 'Los límites: qué NO debe hacer (dar precios no confirmados, prometer plazos, salir del dominio) y cómo manejar preguntas ambiguas o fuera de alcance.', 'El historial de versiones del producto.', 'La biografía del equipo.'],
      correctIndex: 1,
      explanations: ['Un saludo no es un requisito de diseño.', 'Correcto: los límites y el manejo de ambigüedad son tan importantes como el tono.', 'El historial de versiones no guía el comportamiento.', 'La biografía es irrelevante para el usuario.'] },
    { extKey: 'vii-app-24', skillTag: 'Creación de Prompts para interfaces inteligentes', difficulty: 'baja', cognitive: 'comprension',
      stem: 'Versionar los prompts como se versiona el código aporta:',
      options: ['Que el modelo sea más rápido.', 'Poder revertir a una versión anterior, auditar qué cambio movió qué métrica y colaborar sin pisarse, con la suite de evaluación junto a cada versión.', 'Menos tokens.', 'Cifrado.'],
      correctIndex: 1,
      explanations: ['No afecta la velocidad.', 'Correcto: control de versiones + evaluación = trazabilidad y reversión.', 'No cambia el consumo de tokens.', 'No es cifrado.'] },
    { extKey: 'vii-app-25', skillTag: 'Evaluación de la usabilidad', difficulty: 'media', cognitive: 'analisis',
      stem: 'Un asistente sube su "satisfacción declarada" tras un rediseño, pero la "tasa de éxito de tarea" baja. ¿Qué priorizas?',
      options: ['La satisfacción: si les gusta, está bien.', 'La efectividad real: si la tarea se completa menos, el asistente cumple peor su función aunque guste más; investiga por qué falla la tarea.', 'El tiempo de respuesta.', 'Rehacer la encuesta.'],
      correctIndex: 1,
      explanations: ['La satisfacción sin éxito de tarea es poco fiable.', 'Correcto: la efectividad manda sobre la satisfacción declarada.', 'El tiempo no dice si la tarea se logró.', 'Manipular la encuesta oculta el problema.'] },
    { extKey: 'vii-app-26', skillTag: 'Desafíos en entornos multimodales', difficulty: 'media', cognitive: 'analisis',
      stem: 'Tu prompt multimodal falla siempre con un tipo concreto de gráfico. Antes de reescribirlo, ¿qué compruebas?',
      options: ['Si tiene faltas de ortografía.', 'Si el modelo simplemente no puede leer ese tipo de gráfico a esa resolución/formato: el cuello puede estar en la entrada o en las capacidades del modelo, no en el prompt.', 'Si tiene modo oscuro.', 'Reordenar las palabras del prompt.'],
      correctIndex: 1,
      explanations: ['La ortografía rara vez causa un fallo sistemático por tipo de contenido.', 'Correcto: hay que distinguir si el problema es de entrada/capacidad antes de iterar el prompt.', 'El modo oscuro no aplica.', 'Reordenar no arregla una limitación de percepción.'] },
    { extKey: 'vii-app-27', skillTag: 'Adaptación de Prompts a Diferentes audiencias', difficulty: 'baja', cognitive: 'comprension',
      stem: 'La misma información para "equipo técnico" frente a "cliente" cambia sobre todo en:',
      options: ['El color.', 'El nivel de detalle del mecanismo y los límites (más para el técnico) frente al beneficio y los pasos de acción (más para el cliente).', 'El idioma.', 'El modelo.'],
      correctIndex: 1,
      explanations: ['El color no es contenido.', 'Correcto: técnico = mecanismo y límites; cliente = beneficio y pasos.', 'El idioma puede coincidir.', 'El modelo no cambia por audiencia.'] },
    { extKey: 'vii-app-28', skillTag: 'Integración de texto, imagen y sonido', difficulty: 'media', cognitive: 'comprension',
      stem: 'El "sesgo heredado" en un modelo multimodal proviene de:',
      options: ['Un error del programador.', 'Los sesgos presentes en el corpus de texto e imagen con que se entrenó (asociaciones estereotipadas, sub-representación de grupos).', 'La GPU.', 'La preferencia del usuario por ciertos colores.'],
      correctIndex: 1,
      explanations: ['No es un bug puntual.', 'Correcto: el modelo hereda los sesgos de sus datos.', 'No es del hardware.', 'No es una preferencia estética.'] },
    { extKey: 'vii-app-29', skillTag: 'Creación de Prompts para interfaces inteligentes', difficulty: 'media', cognitive: 'analisis',
      stem: 'Un usuario intenta que tu asistente embebido revele instrucciones internas o actúe fuera de su función. ¿Qué debe contemplar el diseño del prompt de sistema?',
      options: ['Confiar en que el usuario no lo hará.', 'Instrucciones robustas para no revelar el prompt de sistema, rechazar peticiones fuera de alcance y mantener el rol aun ante intentos de manipulación, además de registro de esos intentos.', 'Responder a todo lo que pida.', 'Apagar el asistente ante cualquier pregunta rara.'],
      correctIndex: 1,
      explanations: ['La confianza ciega no es una defensa.', 'Correcto: el diseño debe resistir intentos de manipulación y registrarlos.', 'Responder a todo abre la puerta al abuso.', 'Apagarlo ante cualquier duda lo hace inservible.'] },
    { extKey: 'vii-app-30', skillTag: 'Evaluación de la usabilidad', difficulty: 'media', cognitive: 'analisis',
      stem: 'Mejoras un prompt y la métrica sube, pero el mismo cambio empeora otra tarea distinta del asistente. ¿Qué concluyes?',
      options: ['La mejora es un éxito total.', 'Hay un compromiso: el prompt está optimizado para un caso a costa de otro; hay que evaluar sobre la mezcla real de tareas y decidir el equilibrio, o separar prompts por caso.', 'La segunda tarea no importa.', 'Deshacer todo.'],
      correctIndex: 1,
      explanations: ['Una mejora que rompe otra cosa no es un éxito total.', 'Correcto: la evaluación debe cubrir la mezcla real y gestionar el trade-off.', 'Ignorar la regresión es un error.', 'Deshacer sin analizar el equilibrio es precipitado.'] },
  ],
};
