// Banco de ítems de aplicación — Asignatura II: Innovación tecnológica.
module.exports = {
  slug: 'bank-master-ii',
  title: 'Banco de ítems — Asignatura II',
  scopeSlug: 'master-ii',
  questions: [
    {
      extKey: 'ii-app-01',
      skillTag: 'Conceptos fundamentales del Big Data',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un área recibe 2 GB de registros al día que hoy procesa bien en una hoja de cálculo, pero quiere "una solución de Big Data". ¿Qué respuesta es la correcta?',
      options: [
        'Montar un clúster Hadoop de inmediato: es el estándar del sector.',
        'Cuestionar la necesidad: 2 GB/día no exige tecnología distribuida; primero definir qué pregunta de negocio no se puede responder hoy y con qué volumen/velocidad real.',
        'Migrar todo a una base de datos NoSQL sin más análisis.',
        'Comprar más memoria para el equipo del analista.',
      ],
      correctIndex: 1,
      explanations: [
        'Hadoop para 2 GB/día es sobreingeniería costosa.',
        'Correcto: "Big Data" se justifica por volumen, velocidad o variedad que el enfoque actual no soporta, no por moda.',
        'Cambiar de motor sin un problema definido no resuelve nada.',
        'Puede ser suficiente, pero primero hay que saber qué se quiere lograr.',
      ],
    },
    {
      extKey: 'ii-app-02',
      skillTag: 'Conceptos fundamentales del Big Data',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Un sistema debe reaccionar a cada evento de sensor en menos de un segundo. Otro genera un informe cada noche con los datos del día. ¿Qué distinción de Big Data aplica?',
      options: [
        'Estructurado vs. no estructurado.',
        'Procesamiento en flujo (streaming) vs. por lotes (batch).',
        'Data lake vs. data warehouse.',
        'Público vs. privado.',
      ],
      correctIndex: 1,
      explanations: [
        'Ambos casos pueden usar datos estructurados; no es la distinción relevante.',
        'Correcto: la latencia exigida (tiempo real vs. diferido) define si el patrón es streaming o batch.',
        'Es una distinción de almacenamiento, no de cuándo se procesa.',
        'La distinción público/privado es de acceso, no de temporalidad.',
      ],
    },
    {
      extKey: 'ii-app-03',
      skillTag: 'Conceptos fundamentales de la Inteligencia Artificial',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Se dice que "la IA es una tecnología de propósito general, como la electricidad". ¿Qué implicación práctica tiene esa afirmación para una organización?',
      options: [
        'Que hay que adoptar todos los productos de IA disponibles.',
        'Que su valor aparece al integrarla en procesos concretos existentes (amplifica lo que ya se hace), no como un producto aislado que se "instala".',
        'Que la IA reemplazará por completo a los equipos actuales.',
        'Que no hace falta estrategia: se difundirá sola.',
      ],
      correctIndex: 1,
      explanations: [
        'Ser de propósito general no obliga a comprarlo todo.',
        'Correcto: como la electricidad, su impacto viene de rediseñar procesos para aprovecharla, caso por caso.',
        'La analogía habla de amplificación e integración, no de reemplazo total.',
        'Las tecnologías de propósito general sí requieren inversión deliberada para capturar valor.',
      ],
    },
    {
      extKey: 'ii-app-04',
      skillTag: 'Conceptos fundamentales del IoT',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Una planta quiere instalar 500 sensores de vibración que reporten cada 100 ms, pero la conexión a internet es intermitente. ¿Qué concepto de IoT resuelve el problema?',
      options: [
        'Subir todo a la nube en crudo y filtrar allí.',
        'Procesamiento en el borde (edge): agregar y filtrar localmente, enviando a la nube solo resúmenes o anomalías.',
        'Aumentar la frecuencia de muestreo a 10 ms.',
        'Usar blockchain para registrar cada lectura.',
      ],
      correctIndex: 1,
      explanations: [
        'Sin conexión estable, enviar todo en crudo es inviable y caro.',
        'Correcto: el edge computing reduce el volumen transmitido y tolera cortes de red procesando cerca del sensor.',
        'Muestrear más rápido agrava el problema de ancho de banda.',
        'Blockchain no aborda la intermitencia ni el volumen.',
      ],
    },
    {
      extKey: 'ii-app-05',
      skillTag: 'Conceptos fundamentales del IoT',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'En una arquitectura IoT típica, ¿qué papel cumple un protocolo ligero de mensajería como MQTT?',
      options: [
        'Entrenar los modelos de predicción.',
        'Transportar de forma eficiente los mensajes entre muchos dispositivos con poco ancho de banda y batería, mediante un patrón de publicación/suscripción.',
        'Almacenar los datos históricos.',
        'Visualizar los datos en un tablero.',
      ],
      correctIndex: 1,
      explanations: [
        'El transporte de mensajes no entrena modelos.',
        'Correcto: MQTT está diseñado para redes con restricciones, con un broker que desacopla emisores y receptores.',
        'El almacenamiento es otra capa (serie temporal, lago de datos).',
        'La visualización consume los datos ya transportados y almacenados.',
      ],
    },
    {
      extKey: 'ii-app-06',
      skillTag: 'Computación en la nube y su rol en el IoT',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Una startup elige un proveedor de nube y construye toda su plataforma sobre servicios propietarios de ese proveedor (colas, funciones, base de datos gestionada). ¿Cuál es el riesgo principal y su mitigación razonable?',
      options: [
        'Ninguno: usar servicios gestionados siempre es mejor.',
        'Dependencia del proveedor (lock-in): mitigable aislando la lógica de negocio detrás de interfaces y evaluando el coste real de una migración antes de que sea inasumible.',
        'Que la nube es menos segura que un servidor propio.',
        'Que los servicios gestionados son siempre más caros que gestionarlos uno mismo.',
      ],
      correctIndex: 1,
      explanations: [
        'Los servicios gestionados tienen ventajas, pero también un coste de salida.',
        'Correcto: el lock-in no se elimina, se gestiona con diseño desacoplado y conciencia del coste de cambio.',
        'La seguridad de la nube no es intrínsecamente peor; depende de la configuración.',
        'A menudo salen más baratos considerando el coste de operación propio.',
      ],
    },
    {
      extKey: 'ii-app-07',
      skillTag: 'Computación en la nube y su rol en el IoT',
      difficulty: 'baja',
      cognitive: 'aplicacion',
      stem: 'Clasifica: contratas "una API de reconocimiento de imágenes lista para usar, pagas por llamada". ¿Qué modelo de servicio es?',
      options: ['IaaS', 'PaaS', 'SaaS / API gestionada', 'On-premise'],
      correctIndex: 2,
      explanations: [
        'IaaS te daría máquinas virtuales, no una API funcional.',
        'PaaS te daría un entorno de despliegue, no la capacidad ya construida.',
        'Correcto: consumir una capacidad terminada por llamada, sin gestionar infraestructura, es el extremo SaaS/servicio gestionado.',
        'On-premise implica hardware propio en tus instalaciones.',
      ],
    },
    {
      extKey: 'ii-app-08',
      skillTag: 'Conceptos fundamentales de Blockchain',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un área propone una blockchain privada para el registro de aprobaciones internas de gasto, donde todos los participantes son de la misma empresa y hay un equipo de sistemas de confianza. ¿Cuál es la objeción técnica correcta?',
      options: [
        'La blockchain es ilegal para uso interno.',
        'Si existe una autoridad central de confianza (el equipo de sistemas), una base de datos con registro de auditoría cumple el objetivo con mucho menos coste y complejidad; blockchain resuelve la falta de confianza entre partes, que aquí no aplica.',
        'Ninguna: blockchain siempre es superior para trazabilidad.',
        'El problema es solo el consumo energético.',
      ],
      correctIndex: 1,
      explanations: [
        'No hay ilegalidad; el problema es de adecuación.',
        'Correcto: el valor diferencial de blockchain es operar sin una autoridad central; con una autoridad de confianza, una BD auditada es suficiente.',
        'Blockchain añade complejidad que solo compensa cuando no hay confianza mutua.',
        'El consumo energético depende del mecanismo de consenso; no es la objeción principal aquí.',
      ],
    },
    {
      extKey: 'ii-app-09',
      skillTag: 'Conceptos fundamentales de Blockchain',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: '¿Qué problema resuelve un mecanismo de consenso en una blockchain pública?',
      options: [
        'Cifrar los datos para que nadie los lea.',
        'Lograr que participantes que no confían entre sí acuerden un único orden válido de transacciones sin un coordinador central.',
        'Acelerar las transacciones frente a una base de datos tradicional.',
        'Reducir el coste de almacenamiento.',
      ],
      correctIndex: 1,
      explanations: [
        'El consenso no es cifrado; los datos suelen ser públicos.',
        'Correcto: el consenso resuelve el acuerdo distribuido sobre el estado sin confianza previa.',
        'Las blockchains públicas suelen ser más lentas que una BD central, no más rápidas.',
        'El almacenamiento replicado en muchos nodos suele ser más caro, no más barato.',
      ],
    },
    {
      extKey: 'ii-app-10',
      skillTag: 'El futuro de las tecnologías emergentes',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Aplicas la rejilla de la asignatura (problema / fase de expectativa / dependencias / barrera de adopción) a una tecnología muy publicitada. Encuentras que resuelve un problema real, pero depende de estándares que aún no existen y la barrera de adopción es la formación del personal. ¿Qué recomiendas?',
      options: [
        'Adoptarla ya para no quedarse atrás.',
        'Observación activa: definir qué señal (madurez del estándar, disponibilidad de talento) desencadenaría un piloto, y revisar en un plazo fijo.',
        'Descartarla permanentemente.',
        'Contratar al proveedor que más promete.',
      ],
      correctIndex: 1,
      explanations: [
        'Adoptar antes de que maduren las dependencias suele salir caro.',
        'Correcto: cuando el problema es real pero faltan condiciones, la respuesta es esperar con criterios explícitos de reactivación.',
        'Descartar algo con problema real y solo dependencias inmaduras es prematuro.',
        'La promesa del proveedor no cambia el estado de las dependencias.',
      ],
    },
    {
      extKey: 'ii-app-11',
      skillTag: 'El futuro de las tecnologías emergentes',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Revisas un informe de tendencias tecnológicas de hace cinco años. ¿Cuál es el uso más valioso de ese documento hoy?',
      options: [
        'Ignorarlo por estar desactualizado.',
        'Usarlo como objeto de crítica: ver qué predicciones fallaron y por qué, para calibrar el escepticismo ante el informe actual.',
        'Copiar sus recomendaciones tal cual.',
        'Asumir que todo lo que decía ya se cumplió.',
      ],
      correctIndex: 1,
      explanations: [
        'Un informe antiguo tiene valor precisamente por poder contrastarlo con lo ocurrido.',
        'Correcto: analizar los errores de predicción pasados es la mejor vacuna contra el entusiasmo del informe presente.',
        'Sus recomendaciones pueden estar obsoletas.',
        'Muchas predicciones de hype no se cumplen en el plazo previsto, o nunca.',
      ],
    },
    {
      extKey: 'ii-app-12',
      skillTag: 'Conceptos fundamentales de la Inteligencia Artificial',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un proveedor combina "IA + IoT + Blockchain" en su propuesta. ¿Qué análisis conviene hacer primero?',
      options: [
        'Aprobar: la combinación de tres tecnologías punteras garantiza innovación.',
        'Separar qué problema concreto resuelve cada tecnología y si las tres son necesarias, o si es un apilamiento de palabras de moda sobre un problema que una sola resolvería.',
        'Pedir que añadan también computación cuántica.',
        'Rechazar cualquier propuesta con más de una tecnología.',
      ],
      correctIndex: 1,
      explanations: [
        'Apilar tecnologías no garantiza valor; a menudo lo diluye.',
        'Correcto: la pregunta es si cada pieza aporta algo imprescindible o si es marketing.',
        'Añadir más tecnologías empeora el problema de sobreingeniería.',
        'Una combinación puede estar justificada; el criterio es la necesidad, no el número.',
      ],
    },
    {
      extKey: 'ii-app-13',
      skillTag: 'Conceptos fundamentales del Big Data',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Tu organización guarda todos los datos "por si acaso" en un data lake, sin esquema ni catálogo. Dos años después nadie sabe qué hay ni si es fiable. ¿Qué concepto se ignoró?',
      options: [
        'La velocidad de ingesta.',
        'La gobernanza del dato: sin catálogo, linaje y calidad, un lago de datos se convierte en un "pantano de datos" inutilizable.',
        'El cifrado en reposo.',
        'La elección de proveedor de nube.',
      ],
      correctIndex: 1,
      explanations: [
        'La ingesta funcionó; el problema es qué pasó después.',
        'Correcto: guardar sin gobernanza (metadatos, linaje, calidad) destruye el valor del data lake.',
        'El cifrado protege, pero no hace los datos encontrables ni fiables.',
        'El proveedor no determina si hay catálogo y gobernanza.',
      ],
    },
    {
      extKey: 'ii-app-14',
      skillTag: 'Computación en la nube y su rol en el IoT',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'La "elasticidad" de la nube significa, en términos prácticos para un proyecto IoT con picos estacionales:',
      options: [
        'Que los datos se estiran para ocupar menos espacio.',
        'Que la capacidad de cómputo y almacenamiento se ajusta hacia arriba o hacia abajo según la demanda, pagando solo por lo usado.',
        'Que el proveedor garantiza cero caídas.',
        'Que el código se adapta solo a cualquier lenguaje.',
      ],
      correctIndex: 1,
      explanations: [
        'La elasticidad no es compresión de datos.',
        'Correcto: escalar con la demanda y pagar por uso es la ventaja clave para cargas variables como los picos estacionales.',
        'La elasticidad no implica disponibilidad perfecta; eso es otro acuerdo de nivel de servicio.',
        'No tiene relación con lenguajes de programación.',
      ],
    },
    {
      extKey: 'ii-app-15',
      skillTag: 'Conceptos fundamentales de Blockchain',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un consorcio de cinco empresas competidoras quiere compartir un registro común de certificados de origen de productos, sin que ninguna controle el sistema ni pueda alterar registros ajenos. ¿Es un caso donde blockchain aporta?',
      options: [
        'No: siempre es mejor una base de datos central.',
        'Sí: hay varias partes sin confianza mutua, ninguna debe tener control unilateral y se necesita inmutabilidad verificable; es el escenario donde blockchain (permisionada) aporta valor.',
        'No: blockchain solo sirve para criptomonedas.',
        'Sí, pero solo si además emiten un token.',
      ],
      correctIndex: 1,
      explanations: [
        'Una BD central exigiría que una de las competidoras (o un tercero) la controle, lo que aquí se quiere evitar.',
        'Correcto: múltiples partes sin confianza + no control unilateral + inmutabilidad = caso legítimo de blockchain permisionada.',
        'Blockchain tiene aplicaciones más allá de las criptomonedas.',
        'Un token no es necesario para un registro compartido de certificados.',
      ],
    },
    {
      extKey: 'ii-app-16',
      skillTag: 'El futuro de las tecnologías emergentes',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Dos tecnologías tienen el mismo "problema resuelto" pero una tiene barrera de entrada alta y adopción lenta, y la otra barrera baja y adopción rápida. ¿Qué dice esto sobre dónde invertir atención ahora?',
      options: [
        'Invertir siempre en la de barrera alta: será más exclusiva.',
        'La de barrera baja y adopción rápida probablemente dará retorno antes; la de barrera alta merece seguimiento pero no inversión prioritaria hasta que la barrera baje.',
        'Ignorar ambas hasta que una sea claramente dominante.',
        'Invertir el mismo esfuerzo en las dos.',
      ],
      correctIndex: 1,
      explanations: [
        'Barrera alta no equivale a mayor retorno; a menudo significa más riesgo y horizonte más largo.',
        'Correcto: priorizar por barrera de entrada y velocidad de adopción es parte del criterio de la asignatura.',
        'Esperar a un ganador claro suele significar llegar tarde con la de adopción rápida.',
        'Repartir por igual ignora la diferencia de madurez y coste de entrada.',
      ],
    },
    {
      extKey: 'ii-app-17',
      skillTag: 'Conceptos fundamentales del Big Data',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un panel de control necesita mostrar métricas actualizadas cada 5 minutos sobre datos que llegan continuamente. ¿Batch o streaming, y por qué el matiz?',
      options: [
        'Streaming puro, evento a evento.',
        'Micro-batch (procesar en ventanas de pocos minutos): da la frescura requerida sin la complejidad operativa de gestionar estado evento a evento.',
        'Batch diario.',
        'Una hoja de cálculo.',
      ],
      correctIndex: 1,
      explanations: [
        'Streaming evento a evento es más de lo que exige un refresco de 5 minutos.',
        'Correcto: el micro-batch cubre la latencia pedida con menos complejidad que el streaming estricto.',
        'El batch diario no da frescura de 5 minutos.',
        'No escala con datos continuos.',
      ],
    },
    {
      extKey: 'ii-app-18',
      skillTag: 'Conceptos fundamentales de la Inteligencia Artificial',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Se dice que la IA "amplifica" las capacidades de una organización. ¿Qué implica esa palabra frente a "sustituye"?',
      options: [
        'Que la IA reemplaza a los equipos.',
        'Que multiplica el efecto de un proceso o una decisión existente (buena o mala): amplifica lo que ya haces, no lo crea de la nada.',
        'Que la IA solo sirve para tareas creativas.',
        'Que no aporta valor real.',
      ],
      correctIndex: 1,
      explanations: [
        '"Amplificar" no es "sustituir".',
        'Correcto: si el proceso base es malo, la IA amplifica el problema; conviene arreglar el proceso primero.',
        'La amplificación aplica a procesos analíticos y operativos, no solo creativos.',
        'La amplificación de un buen proceso sí aporta valor.',
      ],
    },
    {
      extKey: 'ii-app-19',
      skillTag: 'Conceptos fundamentales del IoT',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Instalas sensores en una flota de vehículos. La conectividad móvil es cara por megabyte. ¿Qué decisión de arquitectura reduce el coste sin perder la señal útil?',
      options: [
        'Transmitir cada lectura en crudo a la nube.',
        'Procesar en el borde: agregar por ventana, detectar eventos relevantes y enviar solo resúmenes y anomalías; el detalle crudo se guarda local y se sube bajo demanda.',
        'Aumentar la frecuencia de muestreo.',
        'Usar blockchain para cada lectura.',
      ],
      correctIndex: 1,
      explanations: [
        'Transmitir todo en crudo dispara el coste móvil.',
        'Correcto: el edge reduce el volumen transmitido conservando lo accionable.',
        'Muestrear más agrava el problema de ancho de banda.',
        'Blockchain no reduce el volumen ni el coste de transmisión.',
      ],
    },
    {
      extKey: 'ii-app-20',
      skillTag: 'Computación en la nube y su rol en el IoT',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Una carga de IoT tiene un pico diario de 2 horas y está casi inactiva el resto. ¿Qué ventaja de la nube aprovechas y qué configuras?',
      options: [
        'Comprar servidores para el pico y dejarlos encendidos.',
        'Elasticidad con autoescalado: la capacidad sube durante el pico y baja después, pagando por uso; configura límites y alertas de coste.',
        'Usar una nube privada dimensionada al pico.',
        'Procesar el pico al día siguiente.',
      ],
      correctIndex: 1,
      explanations: [
        'Dimensionar al pico y dejarlo encendido paga capacidad ociosa 22 h al día.',
        'Correcto: la elasticidad con autoescalado es exactamente para cargas con picos marcados.',
        'Una privada al pico tiene el mismo problema de capacidad ociosa.',
        'Diferir el pico contradice el requisito de procesarlo cuando llega.',
      ],
    },
    {
      extKey: 'ii-app-21',
      skillTag: 'Conceptos fundamentales de Blockchain',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un área quiere blockchain para "garantizar que los registros de calidad no se manipulen". El sistema lo gestiona un único equipo interno de confianza. ¿Qué alternativa cumple el objetivo con menos coste?',
      options: [
        'Blockchain pública con token.',
        'Una base de datos con registro de auditoría inmutable (append-only), firmas y control de accesos: si hay una autoridad de confianza, no hace falta el consenso distribuido.',
        'No se puede garantizar sin blockchain.',
        'Guardar los registros en papel.',
      ],
      correctIndex: 1,
      explanations: [
        'Una pública con token añade complejidad y coste innecesarios aquí.',
        'Correcto: el valor de blockchain es operar sin confianza mutua; con un equipo de confianza, una BD auditada basta.',
        'La inmutabilidad verificable también se logra con append-only + firmas.',
        'El papel no da verificabilidad ni consulta eficiente.',
      ],
    },
    {
      extKey: 'ii-app-22',
      skillTag: 'El futuro de las tecnologías emergentes',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Aplicas la rejilla de evaluación a una tecnología: problema real, madurez temprana, depende de un estándar aún en discusión, barrera = coste de integración. ¿Recomendación?',
      options: [
        'Adoptar ahora para ser pioneros.',
        'Observación activa con criterios explícitos: definir qué señal (estándar cerrado, caso de referencia, bajada de coste) activaría un piloto, y fijar fecha de revisión.',
        'Descartar permanentemente.',
        'Contratar al proveedor más agresivo comercialmente.',
      ],
      correctIndex: 1,
      explanations: [
        'Adoptar antes de que madure el estándar suele salir caro.',
        'Correcto: problema real + dependencias inmaduras = esperar con criterios de reactivación.',
        'Descartar algo con problema real solo por inmadurez es prematuro.',
        'La presión comercial no cambia el estado de la dependencia.',
      ],
    },
    {
      extKey: 'ii-app-23',
      skillTag: 'Conceptos fundamentales del Big Data',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Las "3 V" del Big Data son volumen, velocidad y variedad. ¿Para qué sirve tenerlas presentes al evaluar una propuesta?',
      options: [
        'Para calcular el presupuesto exacto.',
        'Para comprobar cuál de las tres es la que realmente desborda el enfoque actual: a veces el problema es la variedad de fuentes, no el volumen.',
        'Para elegir el color del tablero.',
        'Para nombrar al proveedor.',
      ],
      correctIndex: 1,
      explanations: [
        'No son una fórmula de presupuesto.',
        'Correcto: identificar cuál "V" es el cuello orienta la solución (más cómputo, streaming, o integración de fuentes).',
        'No tienen relación con la visualización.',
        'No sirven para elegir proveedor.',
      ],
    },
    {
      extKey: 'ii-app-24',
      skillTag: 'Conceptos fundamentales de la Inteligencia Artificial',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'La Asignatura I ya cubrió cómo formular un problema de IA. En II, ¿qué añade específicamente sobre la IA como tecnología disruptiva?',
      options: [
        'Cómo entrenar redes neuronales.',
        'Cómo la IA interactúa con las otras tecnologías (Big Data la alimenta, IoT le da sensores, la nube la escala) y cómo evaluarla dentro de ese ecosistema, no aislada.',
        'La historia de la IA.',
        'Nada nuevo; repite la Asignatura I.',
      ],
      correctIndex: 1,
      explanations: [
        'El entrenamiento técnico es de otras asignaturas.',
        'Correcto: II aporta la mirada de ecosistema interconectado y el criterio de evaluación de tecnologías.',
        'La historia no es el foco.',
        'II no repite: encuadra la IA junto a las demás tecnologías.',
      ],
    },
    {
      extKey: 'ii-app-25',
      skillTag: 'Conceptos fundamentales del IoT',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'El "ciclo de vida" de un dispositivo IoT incluye aprovisionamiento, operación, actualización y retirada. ¿Por qué importa para la seguridad?',
      options: [
        'No importa para la seguridad.',
        'Porque cada fase tiene riesgos: credenciales por defecto en el aprovisionamiento, firmware sin parchear en operación, dispositivos zombis tras la retirada; la seguridad se planifica para todo el ciclo.',
        'Porque los dispositivos nuevos son siempre seguros.',
        'Porque la retirada es automática.',
      ],
      correctIndex: 1,
      explanations: [
        'El ciclo de vida es central para la seguridad de una flota IoT.',
        'Correcto: cada fase introduce riesgos distintos que hay que cubrir.',
        'Los dispositivos nuevos suelen traer credenciales por defecto: un riesgo conocido.',
        'La retirada mal gestionada deja dispositivos accesibles y sin dueño.',
      ],
    },
    {
      extKey: 'ii-app-26',
      skillTag: 'Computación en la nube y su rol en el IoT',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Diferencia práctica entre PaaS y SaaS para un proyecto de IoT:',
      options: [
        'Son lo mismo.',
        'PaaS te da un entorno donde despliegas tu propio código de procesamiento de eventos; SaaS te da una aplicación de IoT ya construida que solo configuras.',
        'PaaS es hardware, SaaS es software.',
        'SaaS exige más equipo de operación.',
      ],
      correctIndex: 1,
      explanations: [
        'Son niveles distintos de la pila.',
        'Correcto: con PaaS programas la lógica; con SaaS consumes una solución terminada.',
        'PaaS no es hardware; eso sería IaaS.',
        'SaaS suele exigir menos operación, no más.',
      ],
    },
    {
      extKey: 'ii-app-27',
      skillTag: 'Conceptos fundamentales de Blockchain',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'Una blockchain permisionada (de consorcio) se diferencia de una pública en que:',
      options: [
        'No usa criptografía.',
        'Solo participantes autorizados operan nodos y validan; se usa cuando varias organizaciones sin confianza plena necesitan un registro común sin que ninguna lo controle.',
        'Es siempre más lenta que una pública.',
        'No permite contratos inteligentes.',
      ],
      correctIndex: 1,
      explanations: [
        'Sí usa criptografía.',
        'Correcto: la permisionada restringe quién valida, adecuada para consorcios de organizaciones identificadas.',
        'Suele ser más rápida que una pública, no más lenta.',
        'Puede soportar contratos inteligentes.',
      ],
    },
    {
      extKey: 'ii-app-28',
      skillTag: 'El futuro de las tecnologías emergentes',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un directivo dice: "hay que adoptar esta tecnología ya, o la competencia nos adelanta". ¿Cómo respondes con criterio?',
      options: [
        'Darle la razón y adoptar.',
        'Separar el miedo a quedarse atrás del análisis: ¿la tecnología resuelve un problema nuestro concreto?, ¿está madura?, ¿podemos operarla? Si la respuesta a alguna es no, adoptar ya es más riesgo que ventaja.',
        'Ignorar a la competencia siempre.',
        'Adoptar solo si la competencia ya lo hizo.',
      ],
      correctIndex: 1,
      explanations: [
        'El "FOMO" no es un criterio de inversión.',
        'Correcto: la decisión se toma sobre problema/madurez/capacidad, no sobre el miedo.',
        'La competencia es un dato, pero no el único.',
        'Seguir a la competencia sin análisis propio repite sus errores.',
      ],
    },
    {
      extKey: 'ii-app-29',
      skillTag: 'Conceptos fundamentales del Big Data',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Tu organización quiere combinar datos de ventas (estructurados), correos de clientes (texto) y fotos de productos (imágenes). ¿Qué "V" domina el reto y qué implica?',
      options: [
        'Volumen; comprar más disco.',
        'Variedad: fuentes heterogéneas que hay que ingerir, catalogar y relacionar con esquemas y metadatos distintos; un data lake con gobernanza es un enfoque razonable.',
        'Velocidad; montar streaming.',
        'Ninguna; usar una sola tabla.',
      ],
      correctIndex: 1,
      explanations: [
        'El reto no es el tamaño, es la heterogeneidad.',
        'Correcto: la variedad exige una capa que ingiera y catalogue formatos distintos manteniendo el linaje.',
        'No hay requisito de tiempo real en el enunciado.',
        'Una sola tabla no acomoda texto e imágenes junto a lo estructurado.',
      ],
    },
    {
      extKey: 'ii-app-30',
      skillTag: 'Conceptos fundamentales de la Inteligencia Artificial',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Al evaluar si una tecnología emergente "aporta o es ruido", ¿cuál es la primera pregunta útil?',
      options: [
        '¿Cuántas empresas la usan ya?',
        '¿Qué problema concreto y actual nuestro resolvería, y cuánto nos cuesta hoy no resolverlo?',
        '¿Quién es el CEO del proveedor?',
        '¿Está en la portada de las revistas del sector?',
      ],
      correctIndex: 1,
      explanations: [
        'La adopción ajena no dice si te sirve a ti.',
        'Correcto: sin un problema propio dimensionado, la tecnología es una solución en busca de problema.',
        'Irrelevante para la decisión técnica.',
        'La cobertura mediática es un indicador de hype, no de utilidad.',
      ],
    },
  ],
};
