// Banco de ítems de aplicación — Asignatura X: AI Platforms (nube, despliegue y operación).
module.exports = {
  slug: 'bank-master-x',
  title: 'Banco de ítems — Asignatura X',
  scopeSlug: 'master-x',
  questions: [
    {
      extKey: 'x-app-01',
      skillTag: 'Google Cloud',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Una organización que ya usa intensamente el ecosistema de ofimática y correo de Microsoft debe elegir nube para desplegar un modelo interno. Tu recomendación NO debe basarse en el precio de lista. ¿Qué factor pesa más?',
      options: [
        'Que Microsoft es la empresa más grande.',
        'La integración con la identidad, los permisos y los datos que ya viven en ese ecosistema: reduce fricción de despliegue, gobernanza y soporte, aunque otra nube tenga un servicio puntual más barato.',
        'Que Azure salió antes al mercado.',
        'El color del panel de control.',
      ],
      correctIndex: 1,
      explanations: [
        'El tamaño de la empresa no es un criterio técnico.',
        'Correcto: la integración con el ecosistema existente (identidad, permisos, datos) es un factor no-precio de primer orden.',
        'La antigüedad del servicio no determina su idoneidad.',
        'La estética del panel es irrelevante.',
      ],
    },
    {
      extKey: 'x-app-02',
      skillTag: 'Computación en la nube',
      difficulty: 'baja',
      cognitive: 'aplicacion',
      stem: 'Clasifica: "un servicio gestionado que entrena y despliega modelos, donde tú aportas el código y los datos y el proveedor gestiona la infraestructura". ¿IaaS, PaaS o SaaS?',
      options: ['IaaS', 'PaaS (plataforma de ML gestionada)', 'SaaS', 'On-premise'],
      correctIndex: 1,
      explanations: [
        'IaaS te daría solo las máquinas; aquí gestionan la plataforma de ML.',
        'Correcto: aportas código y datos, el proveedor gestiona la plataforma: es PaaS.',
        'SaaS sería consumir una capacidad ya construida sin aportar código.',
        'On-premise implica infraestructura propia.',
      ],
    },
    {
      extKey: 'x-app-03',
      skillTag: 'Arquitectura de referencia',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un diagrama de arquitectura para llevar un modelo a producción omite el "registro de modelos" (model registry). ¿Qué problema aparece con el tiempo?',
      options: [
        'Ninguno: el registro de modelos es opcional.',
        'Sin registro no hay control de versiones de modelos: no se sabe qué versión está en producción, no se puede revertir a una anterior ni auditar qué datos y métricas tenía la que se desplegó.',
        'El modelo entrena más lento.',
        'Aumenta el coste de almacenamiento de datos.',
      ],
      correctIndex: 1,
      explanations: [
        'El registro de modelos es una pieza clave de una arquitectura de producción.',
        'Correcto: sin él se pierden versionado, reversión y trazabilidad del modelo en producción.',
        'No afecta a la velocidad de entrenamiento.',
        'No es principalmente un problema de almacenamiento de datos.',
      ],
    },
    {
      extKey: 'x-app-04',
      skillTag: 'Arquitectura de referencia',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un modelo desplegado empieza a fallar semanas después sin que nadie cambie el código. La causa más probable y la pieza de arquitectura que lo habría detectado son:',
      options: [
        'Un bug en el código; pruebas unitarias.',
        'Deriva de datos (los datos de entrada en producción se alejan de los de entrenamiento); un monitoreo de deriva sobre las distribuciones de entrada y de predicción lo habría alertado.',
        'Falta de RAM; más memoria.',
        'El certificado SSL caducó; renovarlo.',
      ],
      correctIndex: 1,
      explanations: [
        'Si el código no cambió, un bug nuevo es poco probable.',
        'Correcto: la degradación sin cambios de código suele ser deriva de datos; el monitoreo de deriva la detecta.',
        'La memoria no explica una caída progresiva de calidad de predicción.',
        'Un certificado caducado daría un fallo de conexión, no de calidad del modelo.',
      ],
    },
    {
      extKey: 'x-app-05',
      skillTag: 'Principales servicios',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'Las nubes ofrecen "APIs preentrenadas" (visión, voz, lenguaje) además de plataformas para entrenar modelos propios. ¿Cuándo conviene la API preentrenada?',
      options: [
        'Siempre: es más barata.',
        'Cuando la tarea es estándar (transcribir, detectar objetos comunes, traducir), no hay ventaja competitiva en entrenar algo propio y se valora la puesta en marcha rápida sin equipo de ML.',
        'Nunca: hay que entrenar todo internamente.',
        'Solo si el proveedor lo regala.',
      ],
      correctIndex: 1,
      explanations: [
        'No siempre es más barata a gran volumen, y no siempre encaja.',
        'Correcto: para tareas estándar sin ventaja en hacerlo propio, la API preentrenada ahorra tiempo y equipo.',
        'Entrenar todo internamente es un desperdicio para tareas comunes ya resueltas.',
        'El precio no es el único criterio.',
      ],
    },
    {
      extKey: 'x-app-06',
      skillTag: 'Amazon Web Services',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La asignatura recomienda estudiar la nube "por categorías de servicio" y no memorizando nombres de producto. ¿Por qué?',
      options: [
        'Porque los nombres son difíciles de pronunciar.',
        'Porque los nombres comerciales cambian y se renuevan con frecuencia, mientras que las categorías (cómputo, almacenamiento, ML gestionado, datos, MLOps) son estables y transferibles entre proveedores.',
        'Porque AWS no publica sus nombres.',
        'Porque los nombres son secretos comerciales.',
      ],
      correctIndex: 1,
      explanations: [
        'No es una cuestión de pronunciación.',
        'Correcto: las categorías perduran; los nombres de producto caducan rápido.',
        'AWS publica sus nombres; el punto es que cambian.',
        'No son secretos.',
      ],
    },
    {
      extKey: 'x-app-07',
      skillTag: 'Microsoft Azure',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Vas a comparar AWS, Azure y GCP para un caso concreto. ¿Qué hace útil la tabla comparativa?',
      options: [
        'Copiar la tabla de características genérica de cada proveedor.',
        'Evaluar las tres nubes solo en las dimensiones que importan para ESTE caso (latencia requerida, integración existente, cumplimiento, servicios específicos necesarios, coste total de operación) y reconocer los empates técnicos donde los haya.',
        'Elegir la que tenga más servicios en total.',
        'Elegir por número de regiones geográficas, siempre.',
      ],
      correctIndex: 1,
      explanations: [
        'Una tabla genérica de marketing no orienta una decisión concreta.',
        'Correcto: la comparativa útil se restringe a las dimensiones relevantes al caso y admite empates.',
        'Tener más servicios no implica ser mejor para tu problema.',
        'El número de regiones solo importa si tu caso lo exige.',
      ],
    },
    {
      extKey: 'x-app-08',
      skillTag: 'Computación en la nube',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Tras desplegar, la factura mensual de la nube resulta el doble de lo previsto. Te piden reducirla a la mitad. ¿Qué haces primero?',
      options: [
        'Apagar el sistema.',
        'Desglosar la factura por servicio y por recurso para ver qué concentra el gasto (cómputo ocioso, almacenamiento sin ciclo de vida, endpoints sobredimensionados, transferencia de datos) y actuar sobre la palanca principal.',
        'Cambiar de proveedor de inmediato.',
        'Pedir un descuento al proveedor y no tocar nada más.',
      ],
      correctIndex: 1,
      explanations: [
        'Apagar el sistema no es una opción si está en uso.',
        'Correcto: primero se identifica dónde se concentra el coste y se actúa sobre esa palanca.',
        'Migrar de nube es un proyecto grande, no la primera acción.',
        'Un descuento no corrige un dimensionamiento ineficiente.',
      ],
    },
    {
      extKey: 'x-app-09',
      skillTag: 'Arquitectura de referencia',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'El "despliegue automático desde el repositorio" (CI/CD para modelos) aporta principalmente:',
      options: [
        'Que el modelo entrena solo sin datos.',
        'Que cada cambio validado del código o del modelo pasa a producción por un proceso repetible y auditable, reduciendo errores manuales y acelerando la reversión si algo falla.',
        'Que se elimina la necesidad de pruebas.',
        'Que baja el coste de las GPUs.',
      ],
      correctIndex: 1,
      explanations: [
        'No genera datos ni entrena solo.',
        'Correcto: CI/CD hace el despliegue repetible, auditable y reversible.',
        'CI/CD incluye las pruebas, no las elimina.',
        'No reduce directamente el coste de hardware.',
      ],
    },
    {
      extKey: 'x-app-10',
      skillTag: 'Principales servicios',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Un "endpoint" de inferencia gestionado en la nube es:',
      options: [
        'El lugar donde se guardan los datos de entrenamiento.',
        'Un servicio que expone el modelo para recibir peticiones y devolver predicciones, con escalado, versionado y monitoreo gestionados por el proveedor.',
        'El panel de facturación.',
        'La consola de administración de usuarios.',
      ],
      correctIndex: 1,
      explanations: [
        'El almacenamiento de datos es otra pieza.',
        'Correcto: el endpoint sirve predicciones del modelo con escalado y monitoreo gestionados.',
        'No es el panel de facturación.',
        'No es la gestión de usuarios.',
      ],
    },
    {
      extKey: 'x-app-11',
      skillTag: 'Google Cloud',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'La asignatura recomienda "elegir una sola nube" para certificarse y practicar. ¿Cuál es la razón práctica?',
      options: [
        'Que las otras nubes son peores.',
        'Que las tres comparten los mismos conceptos; dominar una en profundidad (con práctica real y, si aplica, certificación) transfiere el 80% del conocimiento y evita quedarse en la superficie de las tres.',
        'Que usar dos nubes es ilegal.',
        'Que solo una nube tiene servicios de ML.',
      ],
      correctIndex: 1,
      explanations: [
        'Las tres son competitivas; no se trata de calidad.',
        'Correcto: profundizar en una transfiere lo esencial; dispersarse deja el conocimiento superficial.',
        'No hay restricción legal para multi-nube.',
        'Las tres tienen servicios de ML.',
      ],
    },
    {
      extKey: 'x-app-12',
      skillTag: 'Amazon Web Services',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'El proyecto de la asignatura pide "conocer la factura mensual de lo que desplegaste". ¿Por qué es un criterio de dominio y no un detalle administrativo?',
      options: [
        'Porque hay que rendir cuentas al departamento de compras.',
        'Porque no se puede operar ni optimizar un sistema cuyo coste no se entiende: conocer el desglose y la palanca principal es lo que separa desplegar de operar de verdad.',
        'Porque el proveedor lo exige.',
        'Porque la factura contiene la contraseña del sistema.',
      ],
      correctIndex: 1,
      explanations: [
        'La rendición de cuentas es una consecuencia, no la razón de fondo.',
        'Correcto: entender el coste es parte de operar; sin ello no se puede optimizar ni tomar decisiones de arquitectura.',
        'El proveedor factura, pero el criterio es de competencia operativa.',
        'La factura no contiene credenciales.',
      ],
    },
    { extKey: 'x-app-13', skillTag: 'Computación en la nube', difficulty: 'baja', cognitive: 'comprension',
      stem: 'Contratas máquinas virtuales vacías donde tú instalas y gestionas todo. ¿Modelo de servicio?',
      options: ['SaaS', 'IaaS', 'PaaS', 'On-premise'],
      correctIndex: 1,
      explanations: ['SaaS sería una aplicación terminada.', 'Correcto: infraestructura que tú gestionas = IaaS.', 'PaaS te daría un entorno de despliegue, no VMs vacías.', 'On-premise es hardware propio.'] },
    { extKey: 'x-app-14', skillTag: 'Computación en la nube', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Tu carga tiene un pico de 3 horas al día y está casi inactiva el resto. ¿Qué configuras para no pagar capacidad ociosa?',
      options: ['Servidores dimensionados al pico, encendidos 24/7.', 'Autoescalado: la capacidad sube en el pico y baja después, con pago por uso, más alertas y límites de coste.', 'Una nube privada al tamaño del pico.', 'Procesar el pico al día siguiente.'],
      correctIndex: 1,
      explanations: ['Dimensionar al pico y dejarlo encendido paga capacidad ociosa 21 h.', 'Correcto: la elasticidad con autoescalado es para picos marcados.', 'Una privada al pico tiene el mismo problema.', 'Diferir contradice el requisito.'] },
    { extKey: 'x-app-15', skillTag: 'Computación en la nube', difficulty: 'media', cognitive: 'comprension',
      stem: 'El "lock-in" (dependencia del proveedor) se gestiona:',
      options: ['Ignorándolo, "no vamos a cambiar de nube".', 'Aislando la lógica de negocio detrás de interfaces y conociendo el coste real de una migración antes de que sea inasumible.', 'Usando solo servicios propietarios para máxima integración.', 'Cambiando de nube cada año.'],
      correctIndex: 1,
      explanations: ['Ignorarlo es lo que crea el problema.', 'Correcto: el lock-in no se elimina, se gestiona con diseño desacoplado.', 'Más servicios propietarios aumentan el lock-in.', 'Cambiar cada año es costoso e innecesario.'] },
    { extKey: 'x-app-16', skillTag: 'Arquitectura de referencia', difficulty: 'media', cognitive: 'analisis',
      stem: 'Tu arquitectura de producción no incluye monitoreo de deriva. Semanas después, el modelo empeora sin cambios de código. ¿Relación?',
      options: ['No hay relación.', 'Directa: la deriva de datos es la causa más común de degradación sin cambios de código, y el monitoreo de deriva es la pieza que la habría alertado a tiempo.', 'El problema es la RAM.', 'El certificado SSL caducó.'],
      correctIndex: 1,
      explanations: ['Sí hay relación.', 'Correcto: sin monitoreo de deriva, la degradación se descubre tarde y por sus consecuencias.', 'La RAM no explica una caída progresiva de calidad.', 'Un certificado caducado da fallo de conexión, no de calidad.'] },
    { extKey: 'x-app-17', skillTag: 'Arquitectura de referencia', difficulty: 'baja', cognitive: 'comprension',
      stem: 'Un "endpoint de inferencia" gestionado expone:',
      options: ['El almacén de datos de entrenamiento.', 'El modelo, para recibir peticiones y devolver predicciones, con escalado, versionado y monitoreo gestionados por el proveedor.', 'El panel de facturación.', 'La consola de administración de usuarios.'],
      correctIndex: 1,
      explanations: ['El almacenamiento de datos es otra pieza.', 'Correcto: el endpoint sirve predicciones del modelo.', 'No es facturación.', 'No es gestión de usuarios.'] },
    { extKey: 'x-app-18', skillTag: 'Arquitectura de referencia', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'El negocio pide poder "volver a la versión anterior del modelo en minutos" si un despliegue falla. ¿Qué pieza lo habilita?',
      options: ['Un endpoint más rápido.', 'El registro de modelos (model registry) con versionado: guarda cada versión con sus métricas y datos, y permite promover o revertir.', 'Más GPUs.', 'Un tablero de BI.'],
      correctIndex: 1,
      explanations: ['La velocidad del endpoint no da reversión.', 'Correcto: el registro versionado es lo que permite revertir.', 'Más GPUs no aportan reversión.', 'El BI no gestiona versiones de modelo.'] },
    { extKey: 'x-app-19', skillTag: 'Principales servicios', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Necesitas detectar objetos comunes en fotos de un catálogo, sin equipo de ML. ¿API preentrenada o plataforma de entrenamiento?',
      options: ['Entrenar un detector propio.', 'API preentrenada de visión: es una tarea estándar, no hay ventaja en hacerla propia y no hay equipo; puesta en marcha en días.', 'Montar un clúster de GPUs.', 'Contratar etiquetadores para 100.000 fotos.'],
      correctIndex: 1,
      explanations: ['Entrenar un detector propio de objetos comunes es reinventar la rueda.', 'Correcto: tarea estándar sin equipo = API preentrenada.', 'Infraestructura propia es desproporcionada.', 'Etiquetar en masa antes de probar la API es prematuro.'] },
    { extKey: 'x-app-20', skillTag: 'Principales servicios', difficulty: 'alta', cognitive: 'analisis',
      stem: 'Vas a poner un chatbot sobre documentación interna sensible. Comparas proveedores. ¿Qué criterio, más allá del precio, pesa más?',
      options: ['El logo más reconocido.', 'Dónde y cómo se procesan y almacenan los datos (residencia, retención, si se usan para entrenar) y si eso encaja con las obligaciones de la organización.', 'La interfaz más bonita.', 'Cuál salió primero al mercado.'],
      correctIndex: 1,
      explanations: ['La marca no dice nada sobre el tratamiento del dato.', 'Correcto: con datos sensibles, la gobernanza del dato es determinante.', 'La estética no es criterio.', 'La antigüedad no garantiza idoneidad.'] },
    { extKey: 'x-app-21', skillTag: 'Amazon Web Services', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Tu organización usa intensamente un ecosistema de ofimática de un proveedor. Debes elegir nube para un modelo interno. ¿Factor no-precio principal?',
      options: ['Que ese proveedor es el más grande.', 'La integración con la identidad, los permisos y los datos que ya viven en ese ecosistema: reduce fricción de despliegue y gobernanza, aunque otra nube tenga un servicio puntual más barato.', 'Que salió antes al mercado.', 'El color del panel.'],
      correctIndex: 1,
      explanations: ['El tamaño no es criterio técnico.', 'Correcto: la integración con el ecosistema existente es un factor de primer orden.', 'La antigüedad no determina idoneidad.', 'La estética es irrelevante.'] },
    { extKey: 'x-app-22', skillTag: 'Microsoft Azure', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Preparas una tabla comparativa AWS/Azure/GCP para un caso concreto. ¿Qué la hace útil?',
      options: ['Copiar la tabla de características genérica de cada proveedor.', 'Evaluar las tres solo en las dimensiones que importan para ESTE caso (latencia, integración existente, cumplimiento, servicio específico necesario, coste total) y reconocer los empates técnicos.', 'Elegir la que tenga más servicios en total.', 'Elegir por número de regiones geográficas siempre.'],
      correctIndex: 1,
      explanations: ['Una tabla genérica no orienta una decisión concreta.', 'Correcto: restringida a las dimensiones relevantes, con empates admitidos.', 'Más servicios no implica mejor para tu problema.', 'El número de regiones solo importa si tu caso lo exige.'] },
    { extKey: 'x-app-23', skillTag: 'Google Cloud', difficulty: 'media', cognitive: 'comprension',
      stem: 'La asignatura recomienda "elegir una sola nube" para practicar y certificarse. ¿Razón?',
      options: ['Las otras nubes son peores.', 'Las tres comparten los mismos conceptos; dominar una en profundidad transfiere la mayor parte del conocimiento y evita quedarse en la superficie de las tres.', 'Usar dos nubes es ilegal.', 'Solo una nube tiene servicios de ML.'],
      correctIndex: 1,
      explanations: ['Las tres son competitivas.', 'Correcto: profundizar en una transfiere lo esencial.', 'No hay restricción legal.', 'Las tres tienen servicios de ML.'] },
    { extKey: 'x-app-24', skillTag: 'Arquitectura de referencia', difficulty: 'media', cognitive: 'comprension',
      stem: 'El "despliegue automático desde el repositorio" (CI/CD de modelos) aporta:',
      options: ['Que el modelo entrena solo sin datos.', 'Que cada cambio validado pasa a producción por un proceso repetible y auditable, con reversión rápida si algo falla; incluye las pruebas, no las elimina.', 'Que se eliminan las pruebas.', 'Que baja el coste de las GPUs.'],
      correctIndex: 1,
      explanations: ['No entrena solo.', 'Correcto: CI/CD hace el despliegue repetible, auditable y reversible.', 'CI/CD incluye las pruebas.', 'No reduce el coste de hardware directamente.'] },
    { extKey: 'x-app-25', skillTag: 'Computación en la nube', difficulty: 'baja', cognitive: 'comprension',
      stem: 'La "elasticidad" de la nube significa, para un proyecto con picos estacionales:',
      options: ['Que los datos se comprimen.', 'Que la capacidad de cómputo y almacenamiento se ajusta arriba o abajo según la demanda, pagando solo por lo usado.', 'Que el proveedor garantiza cero caídas.', 'Que el código se adapta a cualquier lenguaje.'],
      correctIndex: 1,
      explanations: ['No es compresión.', 'Correcto: escalar con la demanda y pagar por uso.', 'La elasticidad no implica disponibilidad perfecta.', 'No tiene relación con lenguajes.'] },
    { extKey: 'x-app-26', skillTag: 'Principales servicios', difficulty: 'media', cognitive: 'analisis',
      stem: 'Un área quiere entrenar un detector de un defecto muy específico de su producto, con 4.000 imágenes etiquetadas propias. ¿API genérica o plataforma de ML?',
      options: ['API genérica de detección de objetos.', 'Plataforma de ML (o ajuste fino): el defecto es propietario y específico, no lo cubre una API genérica, y hay datos propios suficientes.', 'No hacer nada.', 'Etiquetar 100.000 imágenes más antes de probar.'],
      correctIndex: 1,
      explanations: ['Una API genérica no conoce un defecto propietario.', 'Correcto: problema específico + datos propios = modelo dedicado.', 'Hay caso y datos; no actuar lo desperdicia.', '4.000 imágenes ya pueden bastar para ajuste fino.'] },
    { extKey: 'x-app-27', skillTag: 'Amazon Web Services', difficulty: 'media', cognitive: 'comprension',
      stem: '¿Por qué estudiar la nube "por categorías" (cómputo, almacenamiento, ML gestionado, datos, MLOps) en vez de por nombres de producto?',
      options: ['Los nombres son difíciles de pronunciar.', 'Los nombres comerciales cambian y se renuevan; las categorías son estables y transferibles entre proveedores.', 'Los proveedores no publican los nombres.', 'Son secretos comerciales.'],
      correctIndex: 1,
      explanations: ['No es una cuestión de pronunciación.', 'Correcto: las categorías perduran, los nombres caducan.', 'Los publican; el punto es que cambian.', 'No son secretos.'] },
    { extKey: 'x-app-28', skillTag: 'Microsoft Azure', difficulty: 'media', cognitive: 'analisis',
      stem: 'La factura mensual de la nube resulta el doble de lo previsto. Te piden reducirla a la mitad. ¿Primera acción?',
      options: ['Apagar el sistema.', 'Desglosar la factura por servicio y recurso para ver qué concentra el gasto (cómputo ocioso, almacenamiento sin ciclo de vida, endpoints sobredimensionados, transferencia de datos) y actuar sobre la palanca principal.', 'Cambiar de proveedor de inmediato.', 'Pedir un descuento y no tocar nada más.'],
      correctIndex: 1,
      explanations: ['Apagar el sistema no es opción si está en uso.', 'Correcto: primero identificar dónde se concentra el coste.', 'Migrar de nube es un proyecto, no la primera acción.', 'Un descuento no corrige un dimensionamiento ineficiente.'] },
    { extKey: 'x-app-29', skillTag: 'Google Cloud', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Tu proyecto de la asignatura pide una recomendación de proveedor justificada por un factor que NO sea el precio de lista. ¿Cuál es un factor válido?',
      options: ['"Es el más grande del mercado."', 'La integración con la identidad y los datos que ya usas, un requisito de cumplimiento (residencia del dato) o una fortaleza específica del proveedor en el servicio clave del caso.', '"Salió primero."', '"Tiene el panel más bonito."'],
      correctIndex: 1,
      explanations: ['El tamaño no es un factor técnico.', 'Correcto: integración, cumplimiento o fortaleza específica son factores válidos no-precio.', 'La antigüedad no es criterio.', 'La estética no es criterio.'] },
    { extKey: 'x-app-30', skillTag: 'Arquitectura de referencia', difficulty: 'alta', cognitive: 'analisis',
      stem: 'El proyecto pide "conocer la factura mensual de lo que desplegaste". ¿Por qué es un criterio de dominio y no un detalle administrativo?',
      options: ['Para rendir cuentas a compras.', 'Porque no se puede operar ni optimizar un sistema cuyo coste no se entiende: conocer el desglose y la palanca principal es lo que separa desplegar de operar de verdad.', 'Porque el proveedor lo exige.', 'Porque la factura contiene la contraseña del sistema.'],
      correctIndex: 1,
      explanations: ['La rendición de cuentas es una consecuencia, no la razón.', 'Correcto: entender el coste es parte de la competencia operativa.', 'El proveedor factura, pero el criterio es de operación.', 'La factura no contiene credenciales.'] },
  ],
};
