// Banco de ítems de aplicación — Asignatura I: Artificial Intelligence.
// Ítems de escenario (aplicación/análisis), distintos de los quiz de lección.
// El examen sortea `drawSize` de aquí; cada opción lleva su "why".
// skillTag = contenidoOficial exacto (para repaso dirigido y skill_mastery).

module.exports = {
  slug: 'bank-master-i',
  title: 'Banco de ítems — Asignatura I',
  scopeSlug: 'master-i',
  questions: [
    {
      extKey: 'i-app-01',
      skillTag: 'IA y Toma de Decisiones Automatizadas',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un proveedor ofrece "una IA que entiende las quejas de los clientes y decide la compensación adecuada". El comité de compras te pide una recomendación en una frase. ¿Cuál es la respuesta técnicamente correcta?',
      options: [
        'Aprobarlo: interpretar lenguaje natural ya es una capacidad estándar.',
        'Pedir que definan la entrada exacta (texto de la queja + datos de la cuenta) y la salida exacta (una compensación de un catálogo cerrado) y muestren ejemplos históricos etiquetados; sin eso es una intención, no un proyecto.',
        'Rechazarlo: ningún sistema puede decidir compensaciones.',
        'Aprobarlo si el proveedor tiene casos de éxito en otros sectores.',
      ],
      correctIndex: 1,
      explanations: [
        '"Entender" no es una especificación; sin entrada y salida definidas no se puede evaluar ni contratar.',
        'Correcto: la prueba de si algo es un proyecto de IA evaluable es poder nombrar la entrada, la salida sobre un catálogo cerrado y los ejemplos históricos para entrenar.',
        'Sí puede, si la salida es un catálogo cerrado y hay ejemplos: el problema es que la propuesta no lo especifica.',
        'Los casos de éxito ajenos no sustituyen la definición del problema en tu contexto.',
      ],
    },
    {
      extKey: 'i-app-02',
      skillTag: 'IA y Toma de Decisiones Automatizadas',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un flujo aprueba automáticamente reembolsos < 50 € y envía el resto a un agente con una "recomendación" del modelo. Un directivo dice que "todo está automatizado por IA". ¿Cómo describes con precisión el nivel de automatización?',
      options: [
        'Automatización plena: la IA decide en todos los casos.',
        'Automatización plena en el tramo < 50 € y asistencia/recomendación (humano decide) en el resto; la responsabilidad de los casos grandes sigue siendo del agente.',
        'Solo asistencia: nunca decide sola.',
        'No es automatización porque hay reglas de por medio.',
      ],
      correctIndex: 1,
      explanations: [
        'Solo decide sola por debajo del umbral; por encima, decide el agente.',
        'Correcto: el nivel de automatización se describe por tramo, y eso determina quién responde de cada decisión.',
        'En el tramo < 50 € sí decide y ejecuta sin humano.',
        'Que haya un umbral por reglas no impide que exista automatización plena por debajo de él.',
      ],
    },
    {
      extKey: 'i-app-03',
      skillTag: 'IA y Toma de Decisiones Automatizadas',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Tu equipo quiere "usar IA para mejorar la logística". Para convertirlo en un problema evaluable, ¿qué pregunta hay que responder primero?',
      options: [
        '¿Qué proveedor de nube usamos?',
        '¿Cuál es la decisión concreta y repetible que queremos que el sistema tome, con qué entrada y qué salida?',
        '¿Cuánto presupuesto tenemos?',
        '¿Redes neuronales o árboles de decisión?',
      ],
      correctIndex: 1,
      explanations: [
        'La infraestructura viene después de saber qué se predice.',
        'Correcto: sin una decisión concreta formulada como entrada→salida no hay proyecto que dimensionar.',
        'El presupuesto depende del problema, que aún no está definido.',
        'La técnica se elige después de encuadrar el problema.',
      ],
    },
    {
      extKey: 'i-app-04',
      skillTag: 'Machine Learning',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Tienes 200 000 tickets de soporte de los últimos 3 años, cada uno con la categoría que le asignó un agente. Quieres clasificar automáticamente los nuevos. ¿Qué paradigma de aprendizaje corresponde?',
      options: [
        'No supervisado, porque hay que descubrir las categorías.',
        'Supervisado, porque cada ejemplo histórico ya viene con su etiqueta (la categoría) y quieres predecir esa etiqueta en casos nuevos.',
        'Por refuerzo, porque el sistema aprende de la interacción.',
        'Ninguno: es un problema de reglas.',
      ],
      correctIndex: 1,
      explanations: [
        'Las categorías ya existen y están asignadas; no hay que descubrirlas.',
        'Correcto: etiquetas históricas + objetivo de predecir esa etiqueta = aprendizaje supervisado (clasificación).',
        'No hay un entorno con recompensas ni acciones secuenciales.',
        'Podría intentarse con reglas, pero con 200 000 ejemplos etiquetados el enfoque natural es supervisado.',
      ],
    },
    {
      extKey: 'i-app-05',
      skillTag: 'Machine Learning',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un modelo de segmentación de clientes agrupa a los usuarios sin que nadie le diera grupos previos. El equipo comercial pregunta "¿qué precisión tiene?". ¿Cuál es la respuesta correcta?',
      options: [
        'La precisión es del 92 %.',
        'No aplica "precisión": es aprendizaje no supervisado, no hay etiqueta verdadera contra la que comparar; se evalúa por cohesión/separación de los grupos y por su utilidad para el negocio.',
        'La precisión no se puede medir en ningún modelo de clustering.',
        'Hay que etiquetar manualmente a todos los clientes primero.',
      ],
      correctIndex: 1,
      explanations: [
        'No hay etiqueta de referencia, así que "92 % de precisión" no significa nada aquí.',
        'Correcto: sin verdad de referencia se usan métricas internas (silueta, inercia) y, sobre todo, si los segmentos son accionables.',
        'Sí se puede evaluar la calidad del clustering, solo que no con "precisión".',
        'Etiquetar a todos convertiría el problema en supervisado y anularía el propósito exploratorio.',
      ],
    },
    {
      extKey: 'i-app-06',
      skillTag: 'Machine Learning',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Quieres predecir el tiempo de entrega (en horas) de cada pedido a partir de distancia, hora del día y carga del almacén. ¿Qué tipo de problema es?',
      options: [
        'Clasificación binaria (llega tarde / no llega tarde).',
        'Regresión: la salida es un número continuo (horas).',
        'Clustering de pedidos.',
        'Aprendizaje por refuerzo.',
      ],
      correctIndex: 1,
      explanations: [
        'Sería clasificación si la salida fuera una etiqueta; aquí la salida pedida es un número de horas.',
        'Correcto: predecir una cantidad continua es regresión.',
        'No se busca agrupar, se busca predecir un valor por pedido.',
        'No hay agente que tome acciones secuenciales con recompensa.',
      ],
    },
    {
      extKey: 'i-app-07',
      skillTag: 'Generative AI',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un asistente basado en un LLM responde a preguntas sobre las políticas internas de la empresa, pero a veces inventa cláusulas que no existen. ¿Cuál es la explicación más precisa y la mitigación correcta?',
      options: [
        'El modelo está mal entrenado; hay que reentrenarlo con más datos generales.',
        'Es alucinación: el modelo genera texto plausible sin acceso al documento real. La mitigación es recuperación aumentada (RAG): darle los fragmentos relevantes de la política y pedir que cite.',
        'Es un error de la interfaz; basta con cambiar el frontend.',
        'Hay que bajar la temperatura a 0 y el problema desaparece por completo.',
      ],
      correctIndex: 1,
      explanations: [
        'El problema no es falta de datos generales, es falta de acceso a la fuente concreta en el momento de responder.',
        'Correcto: RAG ancla la respuesta en el documento real y permite verificar con la cita; reduce (no elimina) la alucinación.',
        'La interfaz no es la causa; el texto inventado viene del modelo.',
        'Bajar la temperatura reduce la variabilidad pero no garantiza que el contenido sea correcto sin la fuente.',
      ],
    },
    {
      extKey: 'i-app-08',
      skillTag: 'Generative AI',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Tienes 300 ejemplos de correos de tu empresa con el "tono corporativo" deseado y quieres que un LLM escriba con ese tono de forma consistente. ¿Fine-tuning o RAG?',
      options: [
        'RAG: recuperar correos parecidos y pasarlos como contexto.',
        'Fine-tuning: el objetivo es un comportamiento/estilo estable y transversal, no responder con información puntual que cambia; 300 ejemplos consistentes son un caso razonable para ajustar.',
        'Ninguno: es imposible controlar el estilo.',
        'Ambos son equivalentes para este caso.',
      ],
      correctIndex: 1,
      explanations: [
        'RAG sirve cuando necesitas datos concretos y cambiantes en la respuesta, no para fijar un estilo permanente.',
        'Correcto: cuando quieres moldear cómo responde el modelo de forma estable, el fine-tuning es la herramienta; RAG es para qué información usa.',
        'El estilo sí es controlable con ejemplos suficientes y consistentes.',
        'No lo son: resuelven problemas distintos (comportamiento vs. conocimiento).',
      ],
    },
    {
      extKey: 'i-app-09',
      skillTag: 'Generative AI',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Un modelo discriminativo y uno generativo se enfrentan a la tarea "dado un correo, decir si es spam". ¿Cuál es la diferencia esencial de enfoque?',
      options: [
        'El generativo es siempre más preciso.',
        'El discriminativo aprende la frontera entre spam y no-spam; el generativo aprende cómo se ven los correos de cada clase y clasifica según cuál explica mejor el correo.',
        'El discriminativo no puede usarse para clasificar.',
        'No hay diferencia real, solo de nombre.',
      ],
      correctIndex: 1,
      explanations: [
        'La precisión depende del problema y los datos, no del tipo de modelo en abstracto.',
        'Correcto: discriminativo = modela P(clase|dato); generativo = modela cómo se generan los datos de cada clase.',
        'El discriminativo es precisamente el enfoque más directo para clasificar.',
        'La diferencia de enfoque tiene consecuencias prácticas (datos necesarios, capacidad de generar ejemplos).',
      ],
    },
    {
      extKey: 'i-app-10',
      skillTag: 'Ethics in AI',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un modelo de aprobación de créditos tiene 94 % de exactitud global, pero aprueba al 70 % de los solicitantes de la zona A y al 40 % de la zona B con perfiles de ingreso equivalentes. ¿Qué conclusión es correcta?',
      options: [
        'El modelo es bueno: 94 % es una exactitud alta.',
        'La exactitud agregada oculta una disparidad por grupo; hay que revisar si "zona" actúa como proxy de una característica protegida y medir métricas de equidad por subgrupo antes de desplegarlo.',
        'La disparidad es aceptable si el modelo no usa explícitamente la etnia.',
        'Basta con subir el umbral para la zona B.',
      ],
      correctIndex: 1,
      explanations: [
        'La exactitud global puede ser alta y aun así el modelo ser injusto entre grupos.',
        'Correcto: una variable como el código postal puede codificar información protegida; la equidad se evalúa por subgrupo, no solo en agregado.',
        'No usar la variable directamente no evita el sesgo si hay proxies.',
        'Ajustar umbrales por grupo es una decisión delicada con implicaciones legales; no es un "basta con".',
      ],
    },
    {
      extKey: 'i-app-11',
      skillTag: 'Ethics in AI',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Antes de desplegar un modelo de priorización de urgencias médicas, aplicas el marco de 4 preguntas de la asignatura. ¿Cuál de estas es una de esas preguntas clave?',
      options: [
        '¿Qué framework de Python usamos?',
        '¿Qué pasa con las personas a las que el modelo se equivoca, y ese error recae más sobre unos grupos que otros?',
        '¿Cuánta RAM necesita el servidor?',
        '¿El proveedor tiene certificación ISO 9001?',
      ],
      correctIndex: 1,
      explanations: [
        'La herramienta técnica no es una pregunta ética.',
        'Correcto: el impacto de los errores y su distribución entre grupos es central en la evaluación ética.',
        'La infraestructura es irrelevante para el análisis ético.',
        'Una certificación de calidad genérica no responde a las preguntas de equidad e impacto.',
      ],
    },
    {
      extKey: 'i-app-12',
      skillTag: 'Casos de Uso en Diferentes Sectores',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Clasifica según los patrones transversales de la asignatura: "un modelo que detecta transacciones anómalas en tiempo casi real para bloquearlas". ¿Qué patrón es?',
      options: [
        'Generación de contenido.',
        'Detección de anomalías / clasificación de eventos raros con costo asimétrico entre falso positivo y falso negativo.',
        'Optimización de rutas.',
        'Recomendación personalizada.',
      ],
      correctIndex: 1,
      explanations: [
        'No se genera nada; se evalúa cada transacción.',
        'Correcto: es el patrón de detección de anomalías, donde bloquear una transacción legítima (FP) y dejar pasar un fraude (FN) tienen costos muy distintos.',
        'No hay un problema de rutas ni de asignación.',
        'No se personaliza una oferta; se marca un evento como sospechoso o no.',
      ],
    },
    {
      extKey: 'i-app-13',
      skillTag: 'Casos de Uso en Diferentes Sectores',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Dos áreas distintas piden "predecir la demanda" (una de producto terminado, otra de repuestos). ¿Qué tienen en común desde el punto de vista de patrón de IA?',
      options: [
        'Nada: son sectores distintos.',
        'Ambos son problemas de pronóstico sobre series temporales: predecir una cantidad futura a partir del histórico y de variables externas.',
        'Ambos son problemas de visión por computador.',
        'Ambos requieren IA generativa.',
      ],
      correctIndex: 1,
      explanations: [
        'El dominio cambia, pero el patrón técnico es el mismo.',
        'Correcto: reconocer que dos peticiones distintas son el mismo patrón (pronóstico) permite reutilizar enfoque y equipo.',
        'No hay imágenes involucradas.',
        'El pronóstico clásico no necesita modelos generativos.',
      ],
    },
    {
      extKey: 'i-app-14',
      skillTag: 'Plataformas de Software',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Necesitas transcribir y resumir 500 audios de reuniones al mes, sin equipo de ML propio y con presupuesto ajustado. ¿Qué opción de plataforma encaja mejor?',
      options: [
        'Entrenar un modelo de reconocimiento de voz desde cero.',
        'Usar una API preentrenada de transcripción + un LLM gestionado para el resumen: sin equipo de ML, coste por uso, puesta en marcha en días.',
        'Montar un clúster de GPUs propio.',
        'Contratar a tres ingenieros de ML.',
      ],
      correctIndex: 1,
      explanations: [
        'Entrenar desde cero exige datos, equipo y tiempo que el caso no tiene.',
        'Correcto: para una tarea estándar sin equipo propio, las APIs preentrenadas y servicios gestionados son la opción proporcional.',
        'Infraestructura propia solo se justifica con volumen y requisitos que aquí no existen.',
        'Contratar un equipo es desproporcionado para una tarea resuelta por APIs.',
      ],
    },
    {
      extKey: 'i-app-15',
      skillTag: 'Plataformas de Software',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un área quiere un chatbot sobre documentación interna sensible. Evalúas plataformas. ¿Qué criterio, más allá del precio, debe pesar más en la decisión?',
      options: [
        'Qué proveedor tiene el logo más reconocido.',
        'Dónde y cómo se procesan y almacenan los datos (residencia, retención, uso para entrenamiento) y si eso encaja con las obligaciones de la organización.',
        'Qué plataforma tiene la interfaz más bonita.',
        'Cuál salió primero al mercado.',
      ],
      correctIndex: 1,
      explanations: [
        'La marca no dice nada sobre el tratamiento de datos sensibles.',
        'Correcto: con datos sensibles, la gobernanza del dato (residencia, retención, si se usan para entrenar) es determinante.',
        'La estética no es un criterio de selección para datos sensibles.',
        'La antigüedad no garantiza idoneidad para este requisito.',
      ],
    },
    {
      extKey: 'i-app-16',
      skillTag: 'IA y Toma de Decisiones Automatizadas',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Te presentan un sistema "que aprende de cada interacción y mejora solo". ¿Qué pregunta revela si es un proyecto viable o una promesa?',
      options: [
        '¿En qué lenguaje está escrito?',
        '¿Cuál es la señal de retroalimentación concreta (etiqueta, resultado observable) con la que "aprende", y con qué latencia llega?',
        '¿Cuántos usuarios tiene?',
        '¿Tiene modo oscuro?',
      ],
      correctIndex: 1,
      explanations: [
        'El lenguaje de implementación no dice si el aprendizaje continuo es real.',
        'Correcto: "aprende solo" solo es real si existe una señal de retroalimentación observable y utilizable; sin ella es marketing.',
        'La base de usuarios no valida el mecanismo de aprendizaje.',
        'Irrelevante para la viabilidad técnica.',
      ],
    },
    {
      extKey: 'i-app-17',
      skillTag: 'Ethics in AI',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un modelo de RR. HH. filtra currículos. Para reducir el riesgo de discriminación, ¿cuál es la medida más efectiva de esta lista?',
      options: [
        'Eliminar el nombre y el género del CV y asumir que ya es justo.',
        'Auditar el modelo midiendo tasas de selección y de error por subgrupo, y mantener revisión humana significativa sobre los rechazos.',
        'Aumentar el tamaño del modelo.',
        'Publicar el código fuente.',
      ],
      correctIndex: 1,
      explanations: [
        'Quitar variables directas no elimina el sesgo si hay proxies (universidad, código postal, aficiones).',
        'Correcto: medir el comportamiento por subgrupo y conservar supervisión humana sobre las decisiones negativas es lo que reduce el riesgo real.',
        'El tamaño del modelo no tiene relación con la equidad.',
        'La transparencia del código ayuda a auditar pero no corrige el sesgo por sí sola.',
      ],
    },
    {
      extKey: 'i-app-18',
      skillTag: 'Generative AI',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un modelo fundacional (foundation model) se describe como "preentrenado en un corpus enorme y adaptable a muchas tareas". ¿Qué implica esto para tu proyecto de clasificación de documentos con pocas muestras etiquetadas?',
      options: [
        'Que necesitas millones de ejemplos etiquetados igualmente.',
        'Que puedes aprovechar sus representaciones ya aprendidas y adaptarlo con relativamente pocos ejemplos (few-shot o ajuste ligero), en vez de partir de cero.',
        'Que no sirve para clasificación.',
        'Que el resultado será siempre perfecto.',
      ],
      correctIndex: 1,
      explanations: [
        'La ventaja del modelo fundacional es justamente reducir la necesidad de datos etiquetados.',
        'Correcto: partir de un modelo preentrenado permite buenos resultados con pocas muestras, que es tu situación.',
        'Los modelos fundacionales se adaptan bien a clasificación.',
        'Ninguna técnica garantiza perfección; hay que evaluar.',
      ],
    },
    {
      extKey: 'i-app-19',
      skillTag: 'IA y Toma de Decisiones Automatizadas',
      difficulty: 'baja',
      cognitive: 'aplicacion',
      stem: 'Una propuesta dice que la IA "optimizará la operación de forma integral". Para hacerla evaluable, ¿qué exiges?',
      options: [
        'Un plan de marketing.',
        'Que se descomponga en decisiones concretas y repetibles, cada una con su entrada, su salida y una métrica de éxito medible.',
        'Que se elija primero el proveedor.',
        'Que se contrate a un consultor externo.',
      ],
      correctIndex: 1,
      explanations: [
        'El marketing no convierte una intención en un proyecto.',
        'Correcto: "optimizar de forma integral" no es una tarea; hay que bajarlo a decisiones concretas evaluables.',
        'El proveedor se elige después de definir el problema.',
        'Un consultor no sustituye la definición del problema.',
      ],
    },
    {
      extKey: 'i-app-20',
      skillTag: 'IA y Toma de Decisiones Automatizadas',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un sistema recomienda a un gestor a qué clientes llamar. El gestor sigue la recomendación el 60% de las veces y usa su criterio el resto. ¿Cómo describes el nivel de automatización y su implicación?',
      options: [
        'Automatización plena: el sistema decide.',
        'Recomendación con decisión humana real: el gestor mantiene criterio efectivo, así que la responsabilidad de a quién se llama sigue siendo suya y el sistema es una ayuda, no un decisor.',
        'Solo asistencia pasiva.',
        'No es IA porque interviene una persona.',
      ],
      correctIndex: 1,
      explanations: [
        'No decide: propone y el humano acepta o no con criterio propio.',
        'Correcto: seguir el 60% con desviaciones razonadas indica supervisión humana efectiva; el nivel es recomendación.',
        'Es más que asistencia pasiva: produce una recomendación accionable.',
        'Que intervenga una persona no lo excluye de ser un sistema de IA.',
      ],
    },
    {
      extKey: 'i-app-21',
      skillTag: 'Machine Learning',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Quieres agrupar tus productos por patrón de venta para diseñar promociones, sin categorías previas. ¿Qué paradigma y qué cuidado?',
      options: [
        'Supervisado; necesitas etiquetas de "buen producto".',
        'No supervisado (clustering); el cuidado es que los grupos resultantes sean accionables para el negocio, no solo estadísticamente separados.',
        'Refuerzo; el sistema aprende de las ventas.',
        'Reglas fijas por categoría.',
      ],
      correctIndex: 1,
      explanations: [
        'No hay etiqueta que predecir; el objetivo es descubrir estructura.',
        'Correcto: es clustering, y su valor se juzga por si los segmentos permiten decidir promociones distintas.',
        'No hay un entorno con recompensas ni acciones secuenciales.',
        'Las reglas fijas contradicen el objetivo de descubrir patrones.',
      ],
    },
    {
      extKey: 'i-app-22',
      skillTag: 'Machine Learning',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un modelo supervisado tiene 88% de exactitud en entrenamiento y 63% en datos nuevos. ¿Diagnóstico y acción?',
      options: [
        'Sesgo alto; usar un modelo más simple.',
        'Varianza alta (sobreajuste): la brecha entre entrenamiento y datos nuevos es grande; regularizar, conseguir más datos o reducir la complejidad del modelo.',
        'El conjunto de prueba es demasiado grande.',
        'Es normal y no importa.',
      ],
      correctIndex: 1,
      explanations: [
        'Con 88% en entrenamiento no falta capacidad; sobra.',
        'Correcto: la brecha grande entrenamiento-validación es la firma del sobreajuste.',
        'El tamaño del test no infla artificialmente la brecha.',
        'La brecha predice el fallo en producción: sí importa.',
      ],
    },
    {
      extKey: 'i-app-23',
      skillTag: 'Generative AI',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un asistente RAG sobre tus políticas responde bien salvo cuando la política tiene tablas complejas, donde se confunde. ¿Dónde está el problema y qué revisas primero?',
      options: [
        'El modelo de lenguaje; hay que cambiarlo.',
        'Probablemente en la recuperación/preparación del contexto: cómo se fragmentan y representan las tablas antes de pasarlas al modelo; revisa el chunking y el formato del contexto.',
        'El prompt de sistema.',
        'La temperatura del modelo.',
      ],
      correctIndex: 1,
      explanations: [
        'Cambiar de modelo sin diagnóstico es prueba y error caro.',
        'Correcto: si falla solo con tablas, el cuello suele estar en cómo se trocean y se pasan al contexto, no en el modelo.',
        'El prompt no arregla un contexto mal preparado.',
        'La temperatura no explica un fallo específico por tipo de contenido.',
      ],
    },
    {
      extKey: 'i-app-24',
      skillTag: 'Generative AI',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: '¿Qué distingue a un modelo de lenguaje "instruido" (fine-tuned para seguir instrucciones) de uno solo preentrenado?',
      options: [
        'El instruido tiene más parámetros.',
        'El instruido se ajustó con ejemplos de instrucción→respuesta, de modo que sigue peticiones directas; el solo preentrenado tiende a continuar el texto sin obedecer una orden.',
        'El preentrenado no usa datos.',
        'No hay diferencia práctica.',
      ],
      correctIndex: 1,
      explanations: [
        'El tamaño no es la diferencia; el ajuste de comportamiento sí.',
        'Correcto: el ajuste por instrucciones cambia cómo responde el modelo ante una petición.',
        'El preentrenado usa muchísimos datos; lo que le falta es el ajuste de instrucción.',
        'La diferencia de comportamiento es muy relevante en la práctica.',
      ],
    },
    {
      extKey: 'i-app-25',
      skillTag: 'Ethics in AI',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Vas a operacionalizar el principio "el sistema no debe discriminar" para un modelo de asignación de turnos. ¿Cuál es el primer paso concreto?',
      options: [
        'Añadir la frase "no discriminamos" a la documentación.',
        'Elegir una métrica de equidad relevante para el caso (p. ej. diferencia máxima aceptable en turnos deseables por grupo), fijar un umbral y medirlo periódicamente.',
        'Eliminar el nombre del empleado del sistema.',
        'Confiar en que el algoritmo es neutral.',
      ],
      correctIndex: 1,
      explanations: [
        'Una declaración no cambia el comportamiento del sistema.',
        'Correcto: operacionalizar es convertir el principio en una métrica con umbral y medición.',
        'Quitar el nombre no evita el sesgo por proxies (antigüedad, área, historial).',
        'Ningún algoritmo es neutral por defecto; hay que medirlo.',
      ],
    },
    {
      extKey: 'i-app-26',
      skillTag: 'Casos de Uso en Diferentes Sectores',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Tres áreas piden proyectos distintos: "clasificar reclamaciones", "detectar equipos a punto de fallar" y "resumir informes". ¿Qué patrón comparten dos de ellos?',
      options: [
        'Los tres son generación de texto.',
        '"Clasificar reclamaciones" y "detectar equipos a punto de fallar" son ambos clasificación/predicción supervisada sobre datos históricos etiquetados; "resumir informes" es generación.',
        'Los tres son detección de anomalías.',
        'No comparten nada.',
      ],
      correctIndex: 1,
      explanations: [
        'Solo el resumen es generación.',
        'Correcto: reconocer que dos peticiones son el mismo patrón permite reutilizar enfoque, datos y equipo.',
        'Solo "detectar equipos a punto de fallar" se acerca a anomalías; clasificar reclamaciones es multiclase estándar.',
        'Dos de ellos comparten el patrón de clasificación supervisada.',
      ],
    },
    {
      extKey: 'i-app-27',
      skillTag: 'Casos de Uso en Diferentes Sectores',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Un caso de uso "asiste" un proceso, otro lo "automatiza" y otro crea un "producto nuevo". ¿Por qué importa la distinción para priorizar?',
      options: [
        'No importa, todos son IA.',
        'Porque el esfuerzo, el riesgo y el retorno son muy distintos: asistir suele ser rápido y de bajo riesgo; automatizar exige más garantías; crear un producto nuevo es una apuesta mayor.',
        'Porque la automatización siempre da más retorno.',
        'Porque los productos nuevos son ilegales.',
      ],
      correctIndex: 1,
      explanations: [
        'La categoría cambia el perfil de esfuerzo/riesgo/retorno.',
        'Correcto: clasificar por tipo de impacto ayuda a priorizar según capacidad y apetito de riesgo.',
        'La automatización no garantiza más retorno y añade riesgo.',
        'Crear productos nuevos no es ilegal por sí mismo.',
      ],
    },
    {
      extKey: 'i-app-28',
      skillTag: 'Plataformas de Software',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un área quiere entrenar su propio modelo de visión para un defecto muy específico de su producto, con 3.000 imágenes etiquetadas propias. ¿API preentrenada o plataforma de entrenamiento propia?',
      options: [
        'API preentrenada genérica de detección de objetos.',
        'Plataforma de entrenamiento (o ajuste fino): el defecto es específico del producto, no lo cubre una API genérica, y hay datos propios suficientes para un modelo dedicado.',
        'No hacer nada.',
        'Contratar una empresa externa para etiquetar 100.000 imágenes más.',
      ],
      correctIndex: 1,
      explanations: [
        'Una API genérica no conoce un defecto propietario específico.',
        'Correcto: problema específico + datos propios = caso para entrenar o ajustar un modelo dedicado.',
        'Hay un caso claro y datos; no actuar desperdicia la oportunidad.',
        '3.000 imágenes ya pueden bastar para ajuste fino; multiplicar el etiquetado sin probar es prematuro.',
      ],
    },
    {
      extKey: 'i-app-29',
      skillTag: 'Ethics in AI',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un modelo de RR. HH. mejora la exactitud global al añadir la variable "código postal". Al medir por grupo, la disparidad de selección aumenta. ¿Qué decides?',
      options: [
        'Mantener la variable: la exactitud subió.',
        'Retirar o tratar la variable: "código postal" actúa como proxy de características protegidas; una mejora de exactitud que aumenta la disparidad entre grupos no es aceptable en este uso.',
        'Añadir también la edad para compensar.',
        'Publicar el modelo y esperar quejas.',
      ],
      correctIndex: 1,
      explanations: [
        'Una exactitud mayor a costa de más disparidad es un mal intercambio en un uso de alto riesgo.',
        'Correcto: el código postal es un proxy conocido; la equidad por subgrupo pesa más que un incremento marginal de exactitud.',
        'Añadir más variables sensibles agrava el problema.',
        'Desplegar sabiendo que la disparidad empeoró es negligente.',
      ],
    },
    {
      extKey: 'i-app-30',
      skillTag: 'Machine Learning',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Predices si un cliente cancelará el servicio el próximo mes (sí/no) a partir de su uso histórico. ¿Qué tipo de problema es?',
      options: [
        'Regresión.',
        'Clasificación binaria supervisada.',
        'Clustering.',
        'Aprendizaje por refuerzo.',
      ],
      correctIndex: 1,
      explanations: [
        'La salida es una etiqueta (sí/no), no un número continuo.',
        'Correcto: predecir una de dos clases con ejemplos históricos etiquetados es clasificación binaria supervisada.',
        'No se busca agrupar sin etiquetas.',
        'No hay agente ni recompensas secuenciales.',
      ],
    },
  ],
};
