// Banco de ítems de aplicación — Asignatura III: Big Data dentro de la informática.
module.exports = {
  slug: 'bank-master-iii',
  title: 'Banco de ítems — Asignatura III',
  scopeSlug: 'master-iii',
  questions: [
    {
      extKey: 'iii-app-01',
      skillTag: 'Arquitecturas y Soluciones de Big Data: Análisis, Procesamiento y Escalabilidad',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Una agregación sobre 30 millones de filas tarda 40 s en pandas en una máquina con 32 GB de RAM y se ejecuta una vez al día. Un equipo propone migrarla a Spark en un clúster. ¿Qué análisis corresponde?',
      options: [
        'Migrar: Spark siempre es más rápido para Big Data.',
        'Probablemente no compensa: 30 M de filas caben en memoria, el trabajo es diario (no hay presión de latencia) y Spark añade sobrecarga de coordinación; conviene medir primero Polars/DuckDB en la misma máquina.',
        'Migrar a Spark pero en modo local, sin clúster.',
        'Aumentar la RAM a 128 GB sin más análisis.',
      ],
      correctIndex: 1,
      explanations: [
        'Spark tiene sobrecarga que no compensa para datos que caben en memoria y cargas no urgentes.',
        'Correcto: el punto en que Spark compensa se justifica midiendo, no por regla; a esta escala hay opciones más simples.',
        'Spark local sigue arrastrando sobrecarga sin la ventaja del clúster.',
        'Más RAM puede ayudar, pero primero hay que medir alternativas más eficientes.',
      ],
    },
    {
      extKey: 'iii-app-02',
      skillTag: 'Arquitecturas y Soluciones de Big Data: Análisis, Procesamiento y Escalabilidad',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un pipeline necesita reprocesar meses de histórico cuando se corrige un error de lógica, y a la vez servir métricas casi en tiempo real. ¿Qué arquitectura encaja?',
      options: [
        'Solo streaming, sin capa de histórico.',
        'Una arquitectura con capa batch (recálculo completo y fiable del histórico) y capa de velocidad (streaming para lo reciente), sirviendo la vista combinada.',
        'Solo batch nocturno.',
        'Guardar todo en un único CSV gigante.',
      ],
      correctIndex: 1,
      explanations: [
        'Solo streaming dificulta el reprocesamiento fiable del histórico.',
        'Correcto: separar recálculo histórico (batch) de baja latencia (velocidad) es el patrón para ambos requisitos.',
        'Solo batch no da la latencia casi en tiempo real requerida.',
        'Un CSV gigante no escala ni permite consultas eficientes.',
      ],
    },
    {
      extKey: 'iii-app-03',
      skillTag: 'Entornos de trabajo para arquitecturas Deep Learning',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Entrenas un modelo cuyos datos no caben en la memoria de una sola GPU, pero el modelo sí. ¿Qué estrategia de paralelismo aplica?',
      options: [
        'Paralelismo de modelo: repartir las capas entre GPUs.',
        'Paralelismo de datos: cada GPU tiene una copia del modelo y procesa un subconjunto del lote; se promedian los gradientes.',
        'No se puede entrenar en esa situación.',
        'Reducir el modelo hasta que quepan los datos.',
      ],
      correctIndex: 1,
      explanations: [
        'El paralelismo de modelo es para modelos que no caben en una GPU, no para datos.',
        'Correcto: si el modelo cabe pero los datos no, se replica el modelo y se reparte el lote (data parallelism).',
        'Sí se puede: es exactamente el caso del paralelismo de datos.',
        'Reducir el modelo cambia el problema; no es necesario aquí.',
      ],
    },
    {
      extKey: 'iii-app-04',
      skillTag: 'Entornos de trabajo para arquitecturas Deep Learning',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: '¿Para qué sirve una herramienta de seguimiento de experimentos (experiment tracking) al entrenar modelos?',
      options: [
        'Para acelerar el entrenamiento en la GPU.',
        'Para registrar hiperparámetros, métricas, datos y versión de código de cada corrida, y poder comparar y reproducir resultados después.',
        'Para cifrar el modelo entrenado.',
        'Para desplegar el modelo en producción.',
      ],
      correctIndex: 1,
      explanations: [
        'No influye en la velocidad de cómputo.',
        'Correcto: la trazabilidad y reproducibilidad de experimentos es su función.',
        'No tiene que ver con cifrado.',
        'El despliegue es una etapa posterior y distinta.',
      ],
    },
    {
      extKey: 'iii-app-05',
      skillTag: 'Aprendizaje Automático',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Tienes 200 millones de registros y quieres validar un modelo. Entrenar sobre todo tarda días. ¿Qué enfoque es razonable primero?',
      options: [
        'Entrenar siempre sobre el 100% para no perder información.',
        'Trabajar con una muestra representativa (estratificada por las variables clave) para iterar rápido, y confirmar el resultado final sobre el conjunto completo.',
        'Descartar el 90% de las columnas al azar.',
        'Usar solo los primeros 10 000 registros por orden de llegada.',
      ],
      correctIndex: 1,
      explanations: [
        'Entrenar sobre todo en cada iteración hace inviable la experimentación.',
        'Correcto: una muestra representativa acelera la iteración sin sesgar, y se valida al final sobre todo.',
        'Descartar columnas al azar pierde señal de forma incontrolada.',
        'Los primeros 10 000 por orden de llegada pueden no ser representativos (sesgo temporal).',
      ],
    },
    {
      extKey: 'iii-app-06',
      skillTag: 'Regresiones y series temporales autorregresivas',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Validas un modelo de pronóstico de demanda con validación cruzada aleatoria estándar y obtiene un error bajísimo. Al desplegarlo, falla. ¿Cuál es la causa más probable?',
      options: [
        'El modelo es demasiado simple.',
        'La validación aleatoria mezcló futuro y pasado (fuga temporal): el modelo "vio" datos posteriores al predecir; hay que usar validación respetando el orden del tiempo.',
        'Faltaba normalizar las variables.',
        'El conjunto de prueba era demasiado grande.',
      ],
      correctIndex: 1,
      explanations: [
        'La simplicidad no explica un error de validación bajo que luego falla.',
        'Correcto: en series temporales, barajar los datos filtra información del futuro; la validación debe ser hacia adelante en el tiempo.',
        'La normalización no causaría este patrón concreto.',
        'Un conjunto de prueba grande no infla artificialmente el rendimiento.',
      ],
    },
    {
      extKey: 'iii-app-07',
      skillTag: 'Árboles de decisión y Algoritmos',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'Un único árbol de decisión profundo memoriza casi perfectamente el conjunto de entrenamiento pero generaliza mal. Un bosque aleatorio (random forest) sobre los mismos datos generaliza mejor. ¿Por qué?',
      options: [
        'Porque el bosque usa menos datos.',
        'Porque promedia muchos árboles entrenados sobre muestras y subconjuntos de variables distintos, reduciendo la varianza (el sobreajuste de un solo árbol).',
        'Porque los árboles del bosque son más profundos.',
        'Porque el bosque no usa árboles, sino redes neuronales.',
      ],
      correctIndex: 1,
      explanations: [
        'El bosque usa remuestreo, no menos datos en total.',
        'Correcto: la agregación de árboles decorrelacionados reduce la varianza y mitiga el sobreajuste.',
        'La profundidad individual no es la razón; es la agregación.',
        'Un random forest sí es un conjunto de árboles.',
      ],
    },
    {
      extKey: 'iii-app-08',
      skillTag: 'Redes neuronales Artificiales',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'En términos conceptuales, ¿qué hace la retropropagación durante el entrenamiento de una red neuronal?',
      options: [
        'Aumenta el número de capas automáticamente.',
        'Calcula cómo contribuye cada peso al error de salida y ajusta cada peso en la dirección que reduce ese error, capa por capa hacia atrás.',
        'Elimina las neuronas que no se usan.',
        'Cifra los pesos para protegerlos.',
      ],
      correctIndex: 1,
      explanations: [
        'La arquitectura (nº de capas) la fija el diseñador, no la retropropagación.',
        'Correcto: propaga el gradiente del error hacia atrás para actualizar cada peso.',
        'La poda de neuronas es otra técnica distinta.',
        'No tiene relación con cifrado.',
      ],
    },
    {
      extKey: 'iii-app-09',
      skillTag: 'Redes neuronales Artificiales',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Añades más capas a una red y el rendimiento en entrenamiento mejora, pero en validación empeora claramente. ¿Qué está pasando y qué harías?',
      options: [
        'Sesgo alto: añadir aún más capas.',
        'Varianza alta (sobreajuste): la capacidad extra memoriza el entrenamiento; regularizar, obtener más datos o reducir capacidad.',
        'Los datos están mal etiquetados y no hay solución.',
        'Es normal: siempre pasa y no importa.',
      ],
      correctIndex: 1,
      explanations: [
        'Si entrenamiento mejora y validación empeora, no es falta de capacidad.',
        'Correcto: es la firma del sobreajuste; se ataca con regularización, más datos o menos capacidad.',
        'El sobreajuste tiene remedios; no implica etiquetas malas.',
        'La brecha entrenamiento-validación sí importa: predice el fallo en producción.',
      ],
    },
    {
      extKey: 'iii-app-10',
      skillTag: 'Aprendizaje Automático',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Al construir features para un modelo de scoring, un compañero incluye "número de reclamaciones del cliente en los últimos 12 meses", pero la etiqueta a predecir es "el cliente presentará una reclamación en los próximos 30 días". ¿Qué revisas?',
      options: [
        'Nada: más features siempre es mejor.',
        'Si esa feature incluye información posterior al momento de la predicción (los 12 meses deben terminar antes de la fecha de corte), para evitar fuga de datos.',
        'Si la feature está normalizada entre 0 y 1.',
        'Si el nombre de la columna es descriptivo.',
      ],
      correctIndex: 1,
      explanations: [
        'Features que filtran el futuro inflan el rendimiento y fallan en producción.',
        'Correcto: hay que asegurar que toda feature usa solo información disponible en el instante de predecir.',
        'La normalización no es el riesgo aquí.',
        'El nombre no afecta la validez estadística.',
      ],
    },
    {
      extKey: 'iii-app-11',
      skillTag: 'Regresiones y series temporales autorregresivas',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Un modelo autorregresivo predice el valor de mañana principalmente a partir de:',
      options: [
        'Variables completamente ajenas a la serie.',
        'Los valores pasados recientes de la propia serie (y opcionalmente variables externas).',
        'Un promedio global de todo el histórico, sin orden.',
        'La media del sector.',
      ],
      correctIndex: 1,
      explanations: [
        'Un modelo autorregresivo se basa, por definición, en la propia serie.',
        'Correcto: "autorregresivo" = regresión sobre los propios rezagos.',
        'Ignorar el orden temporal contradice la idea de serie temporal.',
        'La media del sector es un dato externo, no la base del modelo autorregresivo.',
      ],
    },
    {
      extKey: 'iii-app-12',
      skillTag: 'Arquitecturas y Soluciones de Big Data: Análisis, Procesamiento y Escalabilidad',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Si el volumen de datos de tu pipeline actual se multiplica por diez de un día para otro, ¿cuál es el primer cuello de botella que anticiparías en una arquitectura típica de un solo nodo?',
      options: [
        'El color del tablero de visualización.',
        'La memoria y el disco del nodo único: las operaciones que hoy caben en RAM empiezan a paginar o a fallar, y hay que pasar a procesamiento por particiones o distribuido.',
        'La velocidad de la conexión wifi de la oficina.',
        'El número de usuarios del tablero.',
      ],
      correctIndex: 1,
      explanations: [
        'La visualización no es el cuello con ese crecimiento.',
        'Correcto: en un solo nodo, RAM y disco son el primer límite; ×10 obliga a particionar o distribuir.',
        'La red de oficina no interviene en el procesamiento del servidor.',
        'El número de usuarios del tablero es independiente del volumen de datos procesado.',
      ],
    },
  ],
};
