// Banco de ítems de aplicación — Asignatura VIII: Design Thinking.
module.exports = {
  slug: 'bank-master-viii',
  title: 'Banco de ítems — Asignatura VIII',
  scopeSlug: 'master-viii',
  questions: [
    {
      extKey: 'viii-app-01',
      skillTag: 'Fases de empatía y definición de problemas',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un equipo hace entrevistas de empatía y su declaración de problema final es idéntica a la que escribieron antes de empezar. ¿Qué probablemente ocurrió?',
      options: [
        'Que el equipo acertó el problema a la primera; nada que revisar.',
        'Que la investigación fue superficial o sesgada hacia confirmar la idea previa: una empatía real casi siempre reencuadra el problema.',
        'Que las entrevistas fueron demasiado largas.',
        'Que faltó un prototipo.',
      ],
      correctIndex: 1,
      explanations: [
        'Que el problema no cambie es una señal de alarma, no de acierto.',
        'Correcto: si nada cambió tras investigar, probablemente se buscó confirmar en vez de descubrir.',
        'La duración no explica la falta de reencuadre.',
        'El prototipo es una fase posterior; no es la causa aquí.',
      ],
    },
    {
      extKey: 'viii-app-02',
      skillTag: 'Fundamentos de Design Thinking',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'El "sesgo de solución prematura" en Design Thinking es:',
      options: [
        'Elegir la solución más cara.',
        'Saltar a diseñar una solución antes de haber entendido bien el problema y a las personas afectadas, quedándose atado a esa primera idea.',
        'Probar demasiadas soluciones.',
        'No documentar el proceso.',
      ],
      correctIndex: 1,
      explanations: [
        'No es una cuestión de coste.',
        'Correcto: es el impulso de resolver antes de comprender, que Design Thinking combate con las fases de empatía y definición.',
        'Explorar varias ideas es deseable, no un sesgo.',
        'La falta de documentación es otro problema.',
      ],
    },
    {
      extKey: 'viii-app-03',
      skillTag: 'Fases de empatía y definición de problemas',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'En una entrevista de empatía, un usuario dice "necesito un informe más rápido". ¿Qué haces con esa afirmación?',
      options: [
        'Anotar "hacer el informe más rápido" como el problema y pasar a idear.',
        'Indagar el porqué: qué decisión toma con ese informe, qué hace mientras espera, qué pasó la última vez que llegó tarde; el "quiero X" esconde una necesidad más profunda.',
        'Descartar el comentario por poco técnico.',
        'Prometer que se hará en la mitad de tiempo.',
      ],
      correctIndex: 1,
      explanations: [
        'Tomar la petición literal salta la fase de comprensión.',
        'Correcto: la empatía busca la necesidad detrás de la solución que el usuario propone.',
        'El comentario del usuario es materia prima valiosa.',
        'Prometer sin entender el problema arriesga resolver lo equivocado.',
      ],
    },
    {
      extKey: 'viii-app-04',
      skillTag: 'Técnicas de ideación para soluciones innovadoras',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Tu sesión de ideación produce ocho ideas, pero todas son variantes de "añadir un botón". ¿Qué falló y cómo lo corriges?',
      options: [
        'Nada: ocho ideas es suficiente.',
        'Faltó divergencia real: se convergió demasiado pronto. Corregir con técnicas que fuercen perspectivas distintas (SCAMPER, "¿cómo lo haría otro sector?", peor idea posible) antes de filtrar.',
        'Había demasiada gente en la sala.',
        'La sesión fue demasiado corta.',
      ],
      correctIndex: 1,
      explanations: [
        'La cantidad no compensa la falta de variedad.',
        'Correcto: la ideación necesita divergencia genuina antes de converger; hay técnicas para provocarla.',
        'El número de participantes no es la causa directa.',
        'Alargar la sesión sin cambiar el método daría más variantes del botón.',
      ],
    },
    {
      extKey: 'viii-app-05',
      skillTag: 'Prototipado rápido y validación inicial',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Antes de validar la idea de un nuevo flujo de aprobación, el equipo construye una versión funcional pulida durante tres semanas. ¿Qué error de prototipado cometieron?',
      options: [
        'Ninguno: un prototipo debe ser funcional y pulido.',
        'Fidelidad desproporcionada a la pregunta: para saber si el flujo tiene sentido bastaba un prototipo de papel o clicable en un día; tres semanas de código antes de validar es riesgo innecesario.',
        'El prototipo era demasiado sencillo.',
        'Debieron saltarse el prototipo y lanzar directamente.',
      ],
      correctIndex: 1,
      explanations: [
        'El prototipo debe tener la fidelidad justa para responder la pregunta, no ser un producto.',
        'Correcto: sobre-invertir en fidelidad antes de validar es el error clásico.',
        'El problema es lo contrario: demasiada fidelidad, no muy poca.',
        'Lanzar sin validar es aún más arriesgado.',
      ],
    },
    {
      extKey: 'viii-app-06',
      skillTag: 'Prototipado rápido y validación inicial',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'Un prototipo "Mago de Oz" consiste en:',
      options: [
        'Un prototipo con muchos efectos visuales.',
        'Simular que una función automática existe cuando en realidad una persona ejecuta la tarea entre bastidores, para probar la experiencia sin construir la tecnología todavía.',
        'Un prototipo hecho solo con inteligencia artificial.',
        'Una maqueta impresa en 3D.',
      ],
      correctIndex: 1,
      explanations: [
        'No se trata de efectos visuales.',
        'Correcto: el usuario cree que interactúa con un sistema automático; detrás hay una persona.',
        'No implica necesariamente IA.',
        'No es una técnica de impresión física.',
      ],
    },
    {
      extKey: 'viii-app-07',
      skillTag: 'Iteración y mejoras continuas del prototipo',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Tras la primera prueba, tres usuarios dicen que no les gusta el color y uno no logra completar la tarea principal. ¿En qué te centras para iterar?',
      options: [
        'En el color, porque lo mencionaron tres personas.',
        'En que la tarea principal no se pudo completar: es un fallo de fondo (evidencia de comportamiento), más grave que una preferencia estética (opinión).',
        'En añadir más funciones.',
        'En repetir exactamente la misma prueba sin cambios.',
      ],
      correctIndex: 1,
      explanations: [
        'El color es una preferencia; que la tarea falle es un problema de utilidad.',
        'Correcto: se prioriza el cambio dirigido por evidencia de comportamiento sobre las preferencias declaradas.',
        'Añadir funciones no arregla el fallo de la tarea central.',
        'Repetir sin cambios no genera aprendizaje nuevo.',
      ],
    },
    {
      extKey: 'viii-app-08',
      skillTag: 'Iteración y mejoras continuas del prototipo',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: '"Pivotar" frente a "pulir" un prototipo significa:',
      options: [
        'Lo mismo con distinta palabra.',
        'Pulir: mejorar la ejecución de la misma idea. Pivotar: cambiar un supuesto central (el problema, el segmento, el mecanismo) porque la evidencia dice que la dirección actual no funciona.',
        'Pivotar es abandonar el proyecto.',
        'Pulir es empezar de cero.',
      ],
      correctIndex: 1,
      explanations: [
        'Son decisiones distintas ante la evidencia.',
        'Correcto: pulir es refinar; pivotar es cambiar un supuesto de fondo manteniendo lo aprendido.',
        'Pivotar no es abandonar, es cambiar de rumbo con lo aprendido.',
        'Pulir es lo contrario de empezar de cero.',
      ],
    },
    {
      extKey: 'viii-app-09',
      skillTag: 'Pruebas con usuarios y retroalimentación',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Al hacer pruebas de usuario, el facilitador pregunta "¿verdad que esto es más fácil que antes?". ¿Qué sesgo introduce y cómo lo evita?',
      options: [
        'Sesgo de confirmación del usuario; se evita repitiendo la pregunta.',
        'Sesgo de cortesía / pregunta dirigida: el usuario tiende a estar de acuerdo. Se evita con tareas concretas ("completa este trámite") y observando qué hace, con preguntas abiertas y neutrales.',
        'Ningún sesgo: es una pregunta válida.',
        'Sesgo de novedad; se evita usando un prototipo antiguo.',
      ],
      correctIndex: 1,
      explanations: [
        'El problema es cómo se formula la pregunta, no repetirla.',
        'Correcto: las preguntas dirigidas inducen acuerdo; se sustituyen por tareas y observación del comportamiento.',
        'La pregunta condiciona la respuesta: no es neutral.',
        'El sesgo de cortesía es el dominante aquí, no el de novedad.',
      ],
    },
    {
      extKey: 'viii-app-10',
      skillTag: 'Pruebas con usuarios y retroalimentación',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: '¿Por qué se dice que con unos cinco usuarios se detecta la mayoría de los problemas graves de usabilidad?',
      options: [
        'Porque cinco es un número mágico sin fundamento.',
        'Porque los problemas más severos son frecuentes y los primeros usuarios ya los revelan; añadir más participantes tiene rendimientos decrecientes para encontrar problemas nuevos.',
        'Porque más de cinco usuarios es ilegal.',
        'Porque cinco usuarios equivalen a mil por estadística.',
      ],
      correctIndex: 1,
      explanations: [
        'Tiene fundamento empírico en la frecuencia de los problemas graves.',
        'Correcto: los problemas severos se repiten y saturan pronto; el descubrimiento marginal cae rápido.',
        'No hay ninguna restricción legal.',
        'No es una equivalencia estadística; es sobre detección de problemas cualitativos.',
      ],
    },
    {
      extKey: 'viii-app-11',
      skillTag: 'Técnicas de ideación para soluciones innovadoras',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La formulación "¿Cómo podríamos…?" (HMW) se usa para:',
      options: [
        'Cerrar el problema con una única solución.',
        'Reformular un hallazgo de la investigación como un desafío abierto y accionable que invite a generar muchas soluciones, sin ser tan amplio que no oriente.',
        'Asignar tareas al equipo.',
        'Calcular el presupuesto.',
      ],
      correctIndex: 1,
      explanations: [
        'HMW abre el espacio de soluciones, no lo cierra.',
        'Correcto: convierte un insight en un reto de ideación con el nivel de amplitud adecuado.',
        'No es una herramienta de asignación de tareas.',
        'No tiene relación con presupuesto.',
      ],
    },
    {
      extKey: 'viii-app-12',
      skillTag: 'Fundamentos de Design Thinking',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Design Thinking se describe como "no lineal". ¿Qué significa en la práctica?',
      options: [
        'Que no tiene fases.',
        'Que se puede volver a una fase anterior cuando lo aprendido lo justifica (p. ej. volver a empatía tras una prueba de usuario), en vez de recorrer las fases una sola vez en orden fijo.',
        'Que el orden de las fases es aleatorio siempre.',
        'Que se hace todo a la vez.',
      ],
      correctIndex: 1,
      explanations: [
        'Sí tiene fases; lo que no es fijo es recorrerlas una sola vez.',
        'Correcto: es iterativo; se retrocede a fases previas según lo que se descubre.',
        'No es aleatorio; hay una progresión general con retornos justificados.',
        'No implica hacerlo todo simultáneamente.',
      ],
    },
    { extKey: 'viii-app-13', skillTag: 'Fundamentos de Design Thinking', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Un equipo salta directo a diseñar una app tras una reunión interna, sin hablar con usuarios. ¿Qué sesgo y qué corrección?',
      options: ['Ninguno, la reunión interna basta.', 'Sesgo de solución prematura: se corrige volviendo a las fases de empatía y definición para entender el problema real de las personas afectadas antes de idear.', 'Falta de presupuesto.', 'Demasiada gente en la reunión.'],
      correctIndex: 1,
      explanations: ['Una reunión interna no sustituye la investigación con usuarios.', 'Correcto: el sesgo de solución prematura se combate con empatía y definición.', 'No es un problema de presupuesto.', 'El número de asistentes no es la causa.'] },
    { extKey: 'viii-app-14', skillTag: 'Fundamentos de Design Thinking', difficulty: 'baja', cognitive: 'comprension',
      stem: 'Las 5 fases del Design Thinking (empatizar, definir, idear, prototipar, testear) se recorren:',
      options: ['Una sola vez, en orden estricto.', 'De forma no lineal: se puede volver a una fase anterior cuando lo aprendido lo justifica, iterando.', 'En cualquier orden aleatorio.', 'Todas a la vez.'],
      correctIndex: 1,
      explanations: ['No es una sola pasada rígida.', 'Correcto: es iterativo con retornos justificados.', 'No es aleatorio.', 'No es simultáneo.'] },
    { extKey: 'viii-app-15', skillTag: 'Fases de empatía y definición de problemas', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'En una entrevista de empatía, ¿qué pregunta genera mejor información?',
      options: ['"¿Te gustaría una app que hiciera X?"', '"Cuéntame la última vez que tuviste que hacer esta tarea: ¿qué pasó, qué te costó, qué hiciste después?"', '"¿Cuánto pagarías por una solución?"', '"¿Prefieres el botón azul o el verde?"'],
      correctIndex: 1,
      explanations: ['Es una pregunta dirigida que induce un sí de cortesía.', 'Correcto: preguntar por un episodio concreto revela comportamiento real, no opiniones.', 'El precio es prematuro y especulativo.', 'El detalle de diseño no toca la necesidad.'] },
    { extKey: 'viii-app-16', skillTag: 'Fases de empatía y definición de problemas', difficulty: 'media', cognitive: 'comprension',
      stem: 'Un "mapa de empatía" ayuda a:',
      options: ['Calcular el retorno de inversión.', 'Organizar lo que el usuario dice, hace, piensa y siente respecto a un problema, para detectar tensiones y necesidades no explícitas.', 'Definir la arquitectura técnica.', 'Priorizar el backlog.'],
      correctIndex: 1,
      explanations: ['No es una herramienta financiera.', 'Correcto: estructura la observación para revelar necesidades latentes.', 'No es diseño técnico.', 'No es priorización de backlog.'] },
    { extKey: 'viii-app-17', skillTag: 'Técnicas de ideación para soluciones innovadoras', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Tu sesión de ideación produce solo ideas incrementales. ¿Qué técnica fuerza la divergencia?',
      options: ['Votar la mejor idea de inmediato.', 'Provocaciones deliberadas: "¿cómo lo resolvería otro sector?", "¿y si fuera gratis?", "peor idea posible", SCAMPER; separar generar de filtrar.', 'Reducir el equipo a una persona.', 'Alargar la reunión sin cambiar el método.'],
      correctIndex: 1,
      explanations: ['Votar pronto mata la divergencia.', 'Correcto: las provocaciones estructuradas abren el espacio de soluciones.', 'Una sola persona limita la variedad.', 'Más tiempo con el mismo método da más de lo mismo.'] },
    { extKey: 'viii-app-18', skillTag: 'Técnicas de ideación para soluciones innovadoras', difficulty: 'baja', cognitive: 'comprension',
      stem: 'La regla "aplazar el juicio" en brainstorming significa:',
      options: ['No documentar nada.', 'Separar la fase de generar ideas (sin criticar) de la de evaluarlas, para no matar ideas prometedoras antes de desarrollarlas.', 'Que solo el líder decide.', 'Que las ideas malas se descartan al instante.'],
      correctIndex: 1,
      explanations: ['No es sobre documentación.', 'Correcto: generar y evaluar son fases distintas.', 'La decisión no es unilateral en esta fase.', 'Descartar al instante contradice la regla.'] },
    { extKey: 'viii-app-19', skillTag: 'Prototipado rápido y validación inicial', difficulty: 'alta', cognitive: 'analisis',
      stem: 'Para validar si un nuevo flujo de aprobación tiene sentido, el equipo dedica 3 semanas a construir una versión funcional pulida. ¿Error?',
      options: ['No, un prototipo debe ser funcional.', 'Fidelidad desproporcionada: la pregunta ("¿tiene sentido el flujo?") se responde con un prototipo de papel o clicable en un día; 3 semanas de código antes de validar es riesgo innecesario.', 'El prototipo era demasiado simple.', 'Debieron lanzar directamente.'],
      correctIndex: 1,
      explanations: ['El prototipo debe tener la fidelidad justa para la pregunta.', 'Correcto: sobre-invertir en fidelidad antes de validar es el error clásico.', 'El problema es lo contrario: demasiada fidelidad.', 'Lanzar sin validar es aún más arriesgado.'] },
    { extKey: 'viii-app-20', skillTag: 'Prototipado rápido y validación inicial', difficulty: 'media', cognitive: 'comprension',
      stem: 'Un prototipo "Wizard of Oz":',
      options: ['Tiene muchos efectos visuales.', 'Simula que una función automática existe, cuando en realidad una persona la ejecuta entre bastidores, para probar la experiencia sin construir la tecnología.', 'Se hace solo con IA.', 'Es una maqueta impresa en 3D.'],
      correctIndex: 1,
      explanations: ['No es sobre efectos.', 'Correcto: el usuario cree que interactúa con un sistema automático.', 'No implica IA.', 'No es impresión física.'] },
    { extKey: 'viii-app-21', skillTag: 'Iteración y mejoras continuas del prototipo', difficulty: 'media', cognitive: 'analisis',
      stem: 'Tras la primera prueba: 4 usuarios comentan el color y 1 no logra terminar la tarea principal. ¿En qué iteras?',
      options: ['En el color, lo dijeron 4 personas.', 'En la tarea que no se pudo completar: es un fallo de utilidad (evidencia de comportamiento), más grave que una preferencia estética (opinión).', 'En añadir más funciones.', 'En repetir la misma prueba sin cambios.'],
      correctIndex: 1,
      explanations: ['El color es preferencia; la tarea fallida es un problema real.', 'Correcto: se prioriza el cambio dirigido por evidencia de comportamiento.', 'Más funciones no arreglan el fallo central.', 'Repetir sin cambios no genera aprendizaje.'] },
    { extKey: 'viii-app-22', skillTag: 'Iteración y mejoras continuas del prototipo', difficulty: 'baja', cognitive: 'comprension',
      stem: '"Saturación de aprendizaje" en la iteración de un prototipo significa:',
      options: ['Que el equipo está agotado.', 'Que las últimas pruebas ya no revelan problemas nuevos: señal de que se puede pasar a la siguiente fase.', 'Que hay demasiados usuarios.', 'Que el prototipo está terminado.'],
      correctIndex: 1,
      explanations: ['No es cansancio del equipo.', 'Correcto: cuando dejan de aparecer hallazgos nuevos, la fase de descubrimiento ha rendido lo que podía.', 'No es por el número de usuarios.', 'No implica que el producto esté acabado.'] },
    { extKey: 'viii-app-23', skillTag: 'Pruebas con usuarios y retroalimentación', difficulty: 'media', cognitive: 'analisis',
      stem: 'El facilitador de una prueba pregunta "¿a que es más fácil que antes?". ¿Qué sesgo introduce y cómo lo evita?',
      options: ['Sesgo de novedad; usar un prototipo viejo.', 'Sesgo de cortesía / pregunta dirigida: el usuario tiende a asentir. Se evita con tareas concretas ("completa este trámite"), observando qué hace y con preguntas abiertas y neutrales.', 'Ninguno, es una pregunta válida.', 'Sesgo de confirmación; repetir la pregunta.'],
      correctIndex: 1,
      explanations: ['El sesgo dominante aquí es el de cortesía, por cómo se formula.', 'Correcto: preguntas neutrales + observación del comportamiento.', 'La pregunta condiciona la respuesta.', 'Repetir la pregunta no la hace neutral.'] },
    { extKey: 'viii-app-24', skillTag: 'Pruebas con usuarios y retroalimentación', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Vas a probar un prototipo con usuarios. ¿Qué les pides?',
      options: ['Su opinión general sobre si les gusta.', 'Que realicen tareas concretas ("reserva una cita para el martes"), pensando en voz alta, mientras observas dónde se atascan.', 'Que valoren de 1 a 10 el diseño.', 'Que sugieran funciones nuevas.'],
      correctIndex: 1,
      explanations: ['La opinión general no revela problemas de uso.', 'Correcto: tareas concretas + think-aloud + observación es el método.', 'Una valoración numérica del diseño no dice dónde falla la tarea.', 'Pedir funciones nuevas desvía el foco de la validación.'] },
    { extKey: 'viii-app-25', skillTag: 'Fases de empatía y definición de problemas', difficulty: 'alta', cognitive: 'analisis',
      stem: 'Tras la investigación, tu declaración de problema es palabra por palabra la que escribiste antes de empezar. ¿Qué probablemente ocurrió?',
      options: ['Acertaste el problema a la primera.', 'La investigación fue superficial o se buscó confirmar la idea previa: una empatía real casi siempre reencuadra el problema.', 'Las entrevistas fueron largas.', 'Faltó un prototipo.'],
      correctIndex: 1,
      explanations: ['Que nada cambie es una señal de alarma, no de acierto.', 'Correcto: si el problema no se movió, probablemente no hubo descubrimiento real.', 'La duración no explica la falta de reencuadre.', 'El prototipo es una fase posterior.'] },
    { extKey: 'viii-app-26', skillTag: 'Técnicas de ideación para soluciones innovadoras', difficulty: 'media', cognitive: 'comprension',
      stem: 'La formulación "¿Cómo podríamos…?" (HMW) sirve para:',
      options: ['Cerrar el problema con una única solución.', 'Reformular un hallazgo como un desafío abierto y accionable que invite a muchas soluciones, sin ser tan amplio que no oriente.', 'Asignar tareas.', 'Calcular el presupuesto.'],
      correctIndex: 1,
      explanations: ['HMW abre el espacio, no lo cierra.', 'Correcto: convierte un insight en un reto de ideación con la amplitud adecuada.', 'No es asignación de tareas.', 'No es presupuesto.'] },
    { extKey: 'viii-app-27', skillTag: 'Iteración y mejoras continuas del prototipo', difficulty: 'media', cognitive: 'comprension',
      stem: '"Pivotar" frente a "pulir":',
      options: ['Son lo mismo.', 'Pulir: refinar la ejecución de la misma idea. Pivotar: cambiar un supuesto central (problema, segmento, mecanismo) porque la evidencia dice que la dirección no funciona.', 'Pivotar es abandonar.', 'Pulir es empezar de cero.'],
      correctIndex: 1,
      explanations: ['Son decisiones distintas.', 'Correcto: pulir refina; pivotar cambia un supuesto de fondo.', 'Pivotar no es abandonar.', 'Pulir es lo contrario de empezar de cero.'] },
    { extKey: 'viii-app-28', skillTag: 'Prototipado rápido y validación inicial', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Tu pregunta de diseño es "¿los usuarios entienden el nuevo lenguaje de los mensajes de error?". ¿Qué fidelidad de prototipo necesitas?',
      options: ['Una app completamente funcional.', 'Baja fidelidad: basta mostrar los textos de error en un mockup o en papel y observar si los usuarios entienden qué hacer.', 'Un prototipo con animaciones.', 'La versión final en producción.'],
      correctIndex: 1,
      explanations: ['Una app funcional es desproporcionada para esa pregunta.', 'Correcto: la fidelidad se ajusta a lo que la pregunta necesita.', 'Las animaciones no ayudan a validar la comprensión del texto.', 'No hace falta llegar a producción para validar.'] },
    { extKey: 'viii-app-29', skillTag: 'Fundamentos de Design Thinking', difficulty: 'media', cognitive: 'analisis',
      stem: 'La mayoría de proyectos de IA de tu organización fracasan "por resolver el problema equivocado". ¿Qué fase de Design Thinking es la que más previene esto?',
      options: ['Prototipado.', 'Empatía y definición: entender bien a las personas y reencuadrar el problema real antes de construir nada.', 'Testeo.', 'Ideación.'],
      correctIndex: 1,
      explanations: ['El prototipado llega después de definir el problema.', 'Correcto: resolver el problema correcto empieza por empatizar y definir.', 'El testeo valida una solución ya construida.', 'La ideación genera soluciones a un problema que hay que haber definido bien.'] },
    { extKey: 'viii-app-30', skillTag: 'Pruebas con usuarios y retroalimentación', difficulty: 'baja', cognitive: 'comprension',
      stem: '¿Por qué con unos 5 usuarios se detecta la mayoría de problemas graves de usabilidad?',
      options: ['Es un número mágico sin fundamento.', 'Porque los problemas más severos son frecuentes y los primeros usuarios ya los revelan; añadir más participantes tiene rendimientos decrecientes para encontrar problemas nuevos.', 'Porque más de 5 es ilegal.', 'Porque 5 equivalen a 1.000 por estadística.'],
      correctIndex: 1,
      explanations: ['Tiene fundamento empírico.', 'Correcto: los problemas severos saturan pronto.', 'No hay restricción legal.', 'No es una equivalencia estadística.'] },
  ],
};
