// Banco de ítems de aplicación — Asignatura IX: IA Generativa en la Industria 4.0.
module.exports = {
  slug: 'bank-master-ix',
  title: 'Banco de ítems — Asignatura IX',
  scopeSlug: 'master-ix',
  questions: [
    {
      extKey: 'ix-app-01',
      skillTag: 'Modelos Generativos',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Necesitas generar imágenes sintéticas de defectos de fabricación para entrenar un inspector visual. Tienes poco tiempo de cómputo para inferencia en línea y necesitas variedad realista. Entre GAN, VAE y difusión, ¿cuál es el criterio de elección correcto?',
      options: [
        'Elegir difusión porque es lo más reciente.',
        'Contrapesar calidad/variedad frente a coste y estabilidad: difusión da alta calidad pero inferencia costosa; GAN es rápida en inferencia pero su entrenamiento es inestable y puede colapsar a pocas variantes; VAE es estable pero suele generar muestras más borrosas. Se elige según qué restricción es dura.',
        'Elegir siempre GAN porque genera rápido.',
        'No usar modelos generativos: pintar los defectos a mano.',
      ],
      correctIndex: 1,
      explanations: [
        'La novedad no es un criterio de ingeniería.',
        'Correcto: la elección se justifica por el trade-off estabilidad de entrenamiento / coste de inferencia / calidad, según la restricción dura del caso.',
        'La rapidez de inferencia de GAN no compensa si su entrenamiento colapsa la variedad.',
        'Pintar a mano no da el volumen ni la variedad que el modelo necesita.',
      ],
    },
    {
      extKey: 'ix-app-02',
      skillTag: 'Conceptos básicos de IA Generativa',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'En la Industria 4.0, un "gemelo digital" alimentado por IA generativa se usa principalmente para:',
      options: [
        'Sustituir físicamente la máquina.',
        'Simular el comportamiento de un activo o proceso real para probar escenarios, anticipar fallos o generar datos que serían caros o peligrosos de obtener en la planta.',
        'Almacenar los manuales en PDF.',
        'Controlar el acceso de los empleados.',
      ],
      correctIndex: 1,
      explanations: [
        'El gemelo digital acompaña al activo físico, no lo reemplaza.',
        'Correcto: es una réplica virtual para simular, anticipar y generar datos.',
        'No es un repositorio documental.',
        'No es un sistema de control de accesos.',
      ],
    },
    {
      extKey: 'ix-app-03',
      skillTag: 'Redes Neuronales Generativas',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'El "colapso de modo" (mode collapse) en una GAN se manifiesta como:',
      options: [
        'El modelo tarda demasiado en entrenar.',
        'El generador aprende a producir solo unas pocas variantes que engañan al discriminador, perdiendo diversidad respecto a los datos reales.',
        'El discriminador deja de funcionar.',
        'La imagen sale con la resolución equivocada.',
      ],
      correctIndex: 1,
      explanations: [
        'No es un problema de tiempo de entrenamiento.',
        'Correcto: el generador se atasca en pocas salidas y no cubre la variedad real.',
        'El discriminador sigue activo; el problema es la falta de diversidad del generador.',
        'La resolución es otra cuestión.',
      ],
    },
    {
      extKey: 'ix-app-04',
      skillTag: 'Paradigmas de ML en la IA Generativa',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La "autosupervisión" (self-supervised) que subyace a los grandes modelos generativos consiste en:',
      options: [
        'Etiquetar los datos manualmente antes de entrenar.',
        'Crear una tarea de pretexto a partir de los propios datos sin etiquetas (p. ej. predecir la siguiente palabra o reconstruir una parte oculta), de modo que el modelo aprende estructura del lenguaje o de la imagen.',
        'Entrenar sin datos.',
        'Copiar los pesos de otro modelo.',
      ],
      correctIndex: 1,
      explanations: [
        'Justamente evita el etiquetado manual masivo.',
        'Correcto: la señal de aprendizaje se construye a partir de los datos mismos mediante una tarea de pretexto.',
        'Sí usa datos, muchos; lo que no usa son etiquetas humanas.',
        'No es transferencia de pesos.',
      ],
    },
    {
      extKey: 'ix-app-05',
      skillTag: 'IA Generativa para contenido Multimedia y multimodal',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Vas a especificar un sistema RAG sobre la documentación técnica interna. ¿Qué métricas separan un buen diseño de una demo?',
      options: [
        'Solo el tiempo de respuesta.',
        'Precisión de recuperación (¿trae los fragmentos correctos?) separada de la calidad de generación (¿la respuesta usa bien esos fragmentos?), más tasa de alucinación medida sobre casos conocidos y coste por consulta.',
        'El número de documentos indexados.',
        'El tamaño del modelo de lenguaje.',
      ],
      correctIndex: 1,
      explanations: [
        'El tiempo de respuesta no dice si la respuesta es correcta.',
        'Correcto: hay que medir recuperación y generación por separado, más alucinación y coste.',
        'Indexar muchos documentos no garantiza recuperar el correcto.',
        'Un modelo grande no compensa una recuperación mala.',
      ],
    },
    {
      extKey: 'ix-app-06',
      skillTag: 'IA Generativa para contenido Multimedia y multimodal',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Tu sistema RAG da una respuesta incorrecta. Antes de tocar el prompt, ¿cómo diagnosticas en qué etapa falló?',
      options: [
        'Reescribir el prompt directamente y ver si mejora.',
        'Inspeccionar los fragmentos recuperados: si no contienen la información, el fallo es de recuperación (índice, chunking, consulta); si sí la contienen pero la respuesta la ignora o la tergiversa, el fallo es de generación o de cómo se pasa el contexto.',
        'Cambiar de modelo de lenguaje sin más análisis.',
        'Aumentar el número de fragmentos recuperados a 50.',
      ],
      correctIndex: 1,
      explanations: [
        'Tocar el prompt a ciegas no localiza la causa.',
        'Correcto: revisar los fragmentos recuperados separa el fallo de recuperación del de generación.',
        'Cambiar de modelo sin diagnóstico es prueba y error costosa.',
        'Recuperar 50 fragmentos puede empeorar la señal-ruido del contexto.',
      ],
    },
    {
      extKey: 'ix-app-07',
      skillTag: 'Conceptos básicos de IA Generativa',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un piloto de IA generativa funciona bien con 20 documentos de prueba. ¿Qué NO puedes concluir todavía para pasar a producción?',
      options: [
        'Que la idea tiene potencial.',
        'Que el coste por consulta, la latencia bajo carga, la tasa de alucinación con el corpus completo y el mantenimiento del índice serán aceptables a escala real.',
        'Que el equipo entendió el problema.',
        'Que hay un caso de uso.',
      ],
      correctIndex: 1,
      explanations: [
        'El potencial sí se puede intuir de un piloto.',
        'Correcto: coste a escala, latencia bajo carga, alucinación con corpus real y mantenimiento son lo que un piloto pequeño no demuestra.',
        'La comprensión del problema no depende del tamaño del piloto.',
        'La existencia del caso de uso ya está establecida.',
      ],
    },
    {
      extKey: 'ix-app-08',
      skillTag: 'Redes Neuronales Generativas',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'En un VAE, ¿qué papel juega el "espacio latente"?',
      options: [
        'Almacena las imágenes originales sin comprimir.',
        'Es una representación comprimida y continua de los datos desde la que el decodificador puede generar nuevas muestras interpolando entre puntos.',
        'Es la capa de salida final.',
        'Es donde se guardan las etiquetas.',
      ],
      correctIndex: 1,
      explanations: [
        'No guarda las imágenes en crudo.',
        'Correcto: el espacio latente es una representación comprimida y continua desde la que se generan muestras.',
        'La salida es lo que produce el decodificador a partir del latente.',
        'Un VAE típico no usa etiquetas.',
      ],
    },
    {
      extKey: 'ix-app-09',
      skillTag: 'Modelos Generativos',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un modelo de difusión produce mejores resultados que una GAN para tu caso, pero cada imagen tarda 6 segundos frente a 0,1 s. El sistema debe generar 10 000 imágenes al día en lotes nocturnos. ¿Qué eliges?',
      options: [
        'La GAN, siempre que sea más rápida.',
        'La difusión: como la generación es nocturna por lotes, el coste de 6 s por imagen es asumible (≈17 h para 10 000, ajustable con paralelismo) y se prioriza la calidad y estabilidad.',
        'Ninguno: no se puede.',
        'Generar solo 100 imágenes en vez de 10 000.',
      ],
      correctIndex: 1,
      explanations: [
        'La velocidad de la GAN no compensa si la latencia no es una restricción real (lotes nocturnos).',
        'Correcto: sin presión de latencia, se elige por calidad/estabilidad y se resuelve el volumen con paralelismo.',
        'Sí se puede: es un problema de planificación de cómputo.',
        'Reducir el volumen cambia el requisito en vez de resolverlo.',
      ],
    },
    {
      extKey: 'ix-app-10',
      skillTag: 'Tendencias y dirección futura de la IA Generativa',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'La lección sobre tendencias se declara "sujeta a cambio". Al aplicarla en un proyecto real, ¿qué actitud es la correcta?',
      options: [
        'Citar las tendencias de la lección como estado actual del arte.',
        'Usar el marco de análisis (qué madura, qué falta, qué depende de qué) pero verificar el estado concreto de modelos, costes y capacidades en el momento de decidir.',
        'Ignorar las tendencias por poco fiables.',
        'Asumir que nada ha cambiado desde que se escribió la lección.',
      ],
      correctIndex: 1,
      explanations: [
        'Las tendencias concretas envejecen rápido.',
        'Correcto: el valor duradero es el marco de análisis; los datos concretos se verifican al decidir.',
        'El marco de análisis sigue siendo útil aunque los datos cambien.',
        'En IA generativa el ritmo de cambio es alto; asumir lo contrario es arriesgado.',
      ],
    },
    {
      extKey: 'ix-app-11',
      skillTag: 'Paradigmas de ML en la IA Generativa',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'El "mantenimiento predictivo" con datos de sensores (p. ej. estimar la vida útil restante de un componente) es principalmente un problema de:',
      options: [
        'Generación de texto.',
        'Regresión / series temporales sobre señales de sensores: predecir un valor (tiempo o ciclos hasta el fallo) a partir del histórico de degradación.',
        'Clasificación de imágenes.',
        'Clustering de clientes.',
      ],
      correctIndex: 1,
      explanations: [
        'No se genera texto.',
        'Correcto: estimar la vida útil restante es regresión sobre series de sensores.',
        'No intervienen imágenes.',
        'No es segmentación de clientes.',
      ],
    },
    {
      extKey: 'ix-app-12',
      skillTag: 'IA Generativa para contenido Multimedia y multimodal',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'En la especificación de una app de IA generativa industrial, ¿dónde debe situarse explícitamente la revisión humana?',
      options: [
        'Al final, revisando una muestra del año.',
        'Antes de que la salida generada se use en un proceso con consecuencias (p. ej. antes de imprimir una pieza, de publicar documentación o de alimentar otro modelo), con un criterio de aceptación claro.',
        'Nunca: la IA generativa no necesita revisión.',
        'Solo si un cliente se queja.',
      ],
      correctIndex: 1,
      explanations: [
        'Revisar una muestra a posteriori no evita el uso de salidas erróneas.',
        'Correcto: la revisión se sitúa antes del uso con consecuencias, con criterio de aceptación explícito.',
        'La salida generativa puede contener errores o alucinaciones y sí necesita control.',
        'Esperar a la queja del cliente es reactivo y tardío.',
      ],
    },
  ],
};
