// Banco de ítems de aplicación — Asignatura VII: Prompts multimodales y contextos complejos.
module.exports = {
  slug: 'bank-master-vii',
  title: 'Banco de ítems — Asignatura VII',
  scopeSlug: 'master-vii',
  questions: [
    {
      extKey: 'vii-app-01',
      skillTag: 'Evaluación de la usabilidad',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Cambias un prompt y "parece que responde mejor". ¿Qué necesitas para poder afirmar que mejoró y no que tuviste suerte?',
      options: [
        'La opinión de un compañero.',
        'Una batería de casos con respuesta esperada y una métrica (tasa de acierto, de reformulación) medida sobre la versión anterior y la nueva, para reportar el delta.',
        'Que el prompt sea más largo.',
        'Ejecutarlo una vez más y ver si sale igual.',
      ],
      correctIndex: 1,
      explanations: [
        'Una impresión no distingue mejora real de azar.',
        'Correcto: la evaluación sistemática con casos y métricas es lo que permite atribuir la mejora al cambio.',
        'La longitud no es indicador de calidad.',
        'Una segunda ejecución no controla la variabilidad ni compara versiones.',
      ],
    },
    {
      extKey: 'vii-app-02',
      skillTag: 'Integración de texto, imagen y sonido',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'Los modelos multimodales suelen apoyarse en un "espacio de representación compartido". En la práctica, ¿qué permite eso?',
      options: [
        'Que el modelo funcione sin datos.',
        'Relacionar contenidos de distinta modalidad (una frase y una imagen) porque se proyectan a un espacio común donde conceptos parecidos quedan cerca.',
        'Que la imagen y el texto ocupen el mismo archivo.',
        'Que el modelo no necesite entrenamiento.',
      ],
      correctIndex: 1,
      explanations: [
        'El espacio compartido se aprende con datos.',
        'Correcto: proyectar modalidades a un espacio común es lo que permite emparejar texto e imagen por significado.',
        'No es una cuestión de formato de archivo.',
        'El espacio compartido es resultado del entrenamiento.',
      ],
    },
    {
      extKey: 'vii-app-03',
      skillTag: 'Desafíos en entornos multimodales',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un asistente recibe una captura de pantalla y una instrucción de texto que se contradicen (el texto dice "el botón azul", la imagen no tiene botón azul). El sistema inventa una respuesta. ¿Qué desafío multimodal es y cómo se mitiga?',
      options: [
        'Sobreajuste; se mitiga con más capas.',
        'Desalineación entre modalidades y alucinación multimodal; se mitiga instruyendo al modelo a señalar la contradicción y pedir aclaración en vez de resolverla por su cuenta.',
        'Falta de GPU.',
        'Un error de la cámara.',
      ],
      correctIndex: 1,
      explanations: [
        'No es sobreajuste ni se resuelve con arquitectura.',
        'Correcto: la desalineación provoca alucinación; el prompt de sistema debe forzar a explicitar la contradicción.',
        'El hardware no causa la contradicción semántica.',
        'La entrada puede ser correcta; el problema es cómo el modelo maneja la incoherencia.',
      ],
    },
    {
      extKey: 'vii-app-04',
      skillTag: 'Adaptación de Prompts a Diferentes audiencias',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Debes adaptar un mismo contenido técnico para tres audiencias: dirección, equipo técnico y clientes. ¿Qué cambia de forma más determinante entre las tres versiones del prompt?',
      options: [
        'El idioma.',
        'El nivel de detalle, el vocabulario y qué se pide destacar (impacto y decisión para dirección; mecanismo y límites para el equipo; beneficio y pasos para el cliente).',
        'La fuente tipográfica de salida.',
        'El nombre del modelo usado.',
      ],
      correctIndex: 1,
      explanations: [
        'El idioma puede ser el mismo; no es lo determinante.',
        'Correcto: la adaptación de audiencia cambia detalle, registro y foco de la salida.',
        'La tipografía no es parte del contenido adaptado.',
        'El modelo no cambia por audiencia necesariamente.',
      ],
    },
    {
      extKey: 'vii-app-05',
      skillTag: 'Creación de Prompts para interfaces inteligentes',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Diseñas el prompt de sistema de un asistente de atención embebido en un producto. ¿Qué elemento es imprescindible además de la personalidad?',
      options: [
        'Un chiste de bienvenida.',
        'Límites claros: qué NO debe hacer (dar precios no confirmados, prometer plazos, salirse del dominio) y cómo manejar preguntas ambiguas o fuera de alcance.',
        'El historial completo de versiones del producto.',
        'La biografía del equipo de desarrollo.',
      ],
      correctIndex: 1,
      explanations: [
        'Un chiste no es un requisito de diseño.',
        'Correcto: los límites y el manejo de ambigüedad son tan importantes como el tono para una interfaz fiable.',
        'El historial de versiones no ayuda al comportamiento del asistente.',
        'La biografía del equipo es irrelevante para el usuario final.',
      ],
    },
    {
      extKey: 'vii-app-06',
      skillTag: 'Evaluación de la usabilidad',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un asistente tiene alta "satisfacción declarada" en encuestas pero baja "tasa de éxito de tarea" medida. ¿Qué priorizas?',
      options: [
        'La satisfacción declarada: si dicen que les gusta, está bien.',
        'La efectividad real: la satisfacción puede reflejar cortesía o novedad; si la tarea no se completa, el asistente no cumple su función.',
        'Ninguna de las dos; medir el tiempo de respuesta.',
        'Rediseñar la encuesta para que dé mejores números.',
      ],
      correctIndex: 1,
      explanations: [
        'La satisfacción sin éxito de tarea es un indicador poco fiable.',
        'Correcto: la efectividad (¿se completó la tarea?) manda sobre la satisfacción declarada.',
        'El tiempo de respuesta no dice si la tarea se logró.',
        'Manipular la encuesta oculta el problema en vez de resolverlo.',
      ],
    },
    {
      extKey: 'vii-app-07',
      skillTag: 'Aplicaciones en arte digital y transmedia',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'En generación de imagen para una campaña, tratar el prompt "como dirección de arte" significa:',
      options: [
        'Escribir la primera frase que venga a la mente.',
        'Especificar estilo, composición, luz, referencias y restricciones de forma deliberada y consistente, igual que un briefing a un ilustrador humano.',
        'Dejar que el modelo elija todo.',
        'Usar solo una palabra clave.',
      ],
      correctIndex: 1,
      explanations: [
        'La improvisación produce resultados inconsistentes.',
        'Correcto: la dirección de arte implica un briefing explícito y repetible.',
        'Delegar todo impide una identidad visual coherente.',
        'Una sola palabra deja demasiadas decisiones al azar.',
      ],
    },
    {
      extKey: 'vii-app-08',
      skillTag: 'Desafíos en entornos multimodales',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un prompt multimodal falla siempre en el mismo tipo de imagen (documentos escaneados con poca resolución). Antes de reescribir el prompt, ¿qué compruebas?',
      options: [
        'Si el prompt tiene faltas de ortografía.',
        'Si el problema está en la entrada (calidad de la imagen) o en el contexto, y no en el prompt: quizá el modelo no puede leer ese nivel de resolución y la solución es mejorar la captura, no el texto.',
        'Si el modelo tiene modo oscuro.',
        'Cambiar el orden de las palabras del prompt.',
      ],
      correctIndex: 1,
      explanations: [
        'La ortografía rara vez es la causa de un fallo sistemático por tipo de imagen.',
        'Correcto: hay que distinguir si el cuello está en la entrada/contexto o en el prompt antes de iterar.',
        'El modo oscuro no existe ni afecta a esto.',
        'Reordenar palabras no arregla una limitación de percepción del modelo.',
      ],
    },
    {
      extKey: 'vii-app-09',
      skillTag: 'Integración de texto, imagen y sonido',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'El "sesgo heredado" en un modelo multimodal se refiere a:',
      options: [
        'Un error de programación del desarrollador.',
        'Que el modelo reproduce en sus salidas los sesgos presentes en los datos de texto e imagen con que se entrenó (asociaciones estereotipadas, sub-representación).',
        'Un problema de la GPU.',
        'La preferencia del usuario por ciertos colores.',
      ],
      correctIndex: 1,
      explanations: [
        'No es un bug puntual, es un efecto de los datos.',
        'Correcto: el modelo hereda los sesgos de su corpus de entrenamiento.',
        'No tiene relación con el hardware.',
        'No se refiere a preferencias estéticas del usuario.',
      ],
    },
    {
      extKey: 'vii-app-10',
      skillTag: 'Adaptación de Prompts a Diferentes audiencias',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Debes generar una versión de un aviso para una audiencia con requisitos de accesibilidad. ¿Qué instrucción añades al prompt?',
      options: [
        'Que use más emojis.',
        'Lenguaje claro y directo, frases cortas, evitar dobles negaciones y jerga, estructura con encabezados y, si hay imágenes, texto alternativo descriptivo.',
        'Que el texto sea más largo para dar más contexto.',
        'Que incluya más tecnicismos para ser preciso.',
      ],
      correctIndex: 1,
      explanations: [
        'Los emojis pueden dificultar la lectura con lectores de pantalla.',
        'Correcto: claridad, frases cortas, estructura y textos alternativos son criterios de accesibilidad.',
        'Más longitud suele reducir la accesibilidad, no aumentarla.',
        'Los tecnicismos empeoran la comprensión de una audiencia amplia.',
      ],
    },
    {
      extKey: 'vii-app-11',
      skillTag: 'Creación de Prompts para interfaces inteligentes',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Quieres versionar tus prompts como versionas código. ¿Qué práctica es la más valiosa?',
      options: [
        'Guardar solo la última versión que funcionó.',
        'Mantener cada versión en control de versiones junto a su suite de evaluación, registrando qué cambio movió qué métrica, para poder revertir y auditar.',
        'Copiar los prompts en un documento de texto sin fecha.',
        'Memorizar el prompt.',
      ],
      correctIndex: 1,
      explanations: [
        'Guardar solo la última impide revertir y entender la evolución.',
        'Correcto: prompts en git + evaluación ejecutable + registro de deltas es la práctica del criterio de dominio.',
        'Un documento sin control de versiones no permite auditar cambios.',
        'Memorizar no escala ni deja rastro.',
      ],
    },
    {
      extKey: 'vii-app-12',
      skillTag: 'Evaluación de la usabilidad',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'La "tasa de reformulación" como métrica de un asistente mide:',
      options: [
        'Cuántas veces el modelo se reinicia.',
        'Con qué frecuencia el usuario tiene que volver a escribir su petición porque la primera respuesta no sirvió: una tasa alta indica mala comprensión o instrucciones poco claras.',
        'El número de palabras por respuesta.',
        'La velocidad de la red.',
      ],
      correctIndex: 1,
      explanations: [
        'No mide reinicios del sistema.',
        'Correcto: mide fricción; muchas reformulaciones = el asistente no entiende a la primera.',
        'La longitud de la respuesta es otra cosa.',
        'La red no es lo que mide esta métrica.',
      ],
    },
  ],
};
