// Banco de ítems de aplicación — Asignatura IV: Metodologías Ágiles.
module.exports = {
  slug: 'bank-master-iv',
  title: 'Banco de ítems — Asignatura IV',
  scopeSlug: 'master-iv',
  questions: [
    {
      extKey: 'iv-app-01',
      skillTag: 'Principios y fundamentos de la agilidad',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un equipo dice que "es ágil" porque hace reuniones diarias de pie, pero el alcance y la fecha están fijados de antemano y no se entrega nada hasta el final. ¿Qué falla respecto a los fundamentos de la agilidad?',
      options: [
        'Nada: las reuniones diarias son la esencia de lo ágil.',
        'Falta la entrega incremental de valor y la capacidad de ajustar el alcance ante lo aprendido; la ceremonia sin entregas ni adaptación no es agilidad.',
        'Que las reuniones deberían ser sentados.',
        'Que falta un director de proyecto tradicional.',
      ],
      correctIndex: 1,
      explanations: [
        'La reunión diaria es una práctica, no el fundamento.',
        'Correcto: agilidad es entregar incrementos y adaptarse a lo aprendido; sin eso, es cascada con rituales.',
        'La postura de la reunión es irrelevante.',
        'La agilidad reduce, no añade, la figura del director de mando y control.',
      ],
    },
    {
      extKey: 'iv-app-02',
      skillTag: 'Comparativa de marcos ágiles (Scrum, Kanban, Lean)',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un equipo de soporte recibe trabajo impredecible (incidencias) que no se puede planificar en bloques de dos semanas. ¿Qué marco encaja mejor y por qué?',
      options: [
        'Scrum: da estructura de sprints.',
        'Kanban: flujo continuo con límite de trabajo en curso, adecuado para demanda impredecible y prioridades cambiantes, sin comprometer un alcance fijo por iteración.',
        'Cascada: planificar todo el año.',
        'Ninguno: el soporte no puede ser ágil.',
      ],
      correctIndex: 1,
      explanations: [
        'Scrum asume un alcance comprometido por sprint, difícil con incidencias impredecibles.',
        'Correcto: Kanban gestiona flujo continuo y prioridades cambiantes con límites de WIP.',
        'Planificar un año de incidencias imprevisibles no es viable.',
        'El soporte se beneficia especialmente de Kanban.',
      ],
    },
    {
      extKey: 'iv-app-03',
      skillTag: 'Roles y eventos en Scrum',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'En Scrum, ¿quién decide qué elementos del backlog entran en el sprint y en qué orden de prioridad de producto?',
      options: [
        'El Scrum Master.',
        'El Product Owner define la prioridad; el equipo de desarrollo decide cuánto puede comprometer.',
        'La dirección de la empresa, directamente.',
        'Se sortea al azar.',
      ],
      correctIndex: 1,
      explanations: [
        'El Scrum Master facilita el proceso, no prioriza el producto.',
        'Correcto: el Product Owner ordena el valor; el equipo estima su capacidad.',
        'La dirección influye vía el Product Owner, no imponiendo el backlog del sprint.',
        'La selección es deliberada, no aleatoria.',
      ],
    },
    {
      extKey: 'iv-app-04',
      skillTag: 'Roles y eventos en Scrum',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'A mitad de sprint, un directivo pide meter "una tarea urgente" que desplaza el objetivo del sprint. Según Scrum, ¿cuál es la respuesta adecuada?',
      options: [
        'Aceptar siempre lo urgente sin discusión.',
        'Proteger el objetivo del sprint: evaluar con el Product Owner si el cambio justifica cancelar o renegociar el sprint; los cambios no se cuelan sin coste explícito.',
        'Rechazar cualquier cambio pase lo que pase.',
        'Añadir la tarea y ampliar el sprint una semana.',
      ],
      correctIndex: 1,
      explanations: [
        'Aceptar todo destruye la previsibilidad del sprint.',
        'Correcto: el objetivo del sprint se protege; un cambio grande se negocia explícitamente con el Product Owner.',
        'Scrum no prohíbe cambios; los hace visibles y con coste.',
        'Alargar el sprint arbitrariamente rompe la cadencia y la medición.',
      ],
    },
    {
      extKey: 'iv-app-05',
      skillTag: 'Prácticas de planificación y seguimiento en Scrum',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Tu equipo completó 20, 24 y 22 puntos en los últimos tres sprints. Quedan 130 puntos de backlog. ¿Cuál es la estimación defendible del cierre?',
      options: [
        'Dos sprints, porque el equipo "se esforzará más".',
        'Unos 6 sprints, tomando la velocidad media medida (~22) como base, con un rango por la variabilidad observada.',
        'Un sprint, si trabajan horas extra.',
        'No se puede estimar en absoluto.',
      ],
      correctIndex: 1,
      explanations: [
        'Estimar por deseo (esforzarse más) ignora la evidencia.',
        'Correcto: la estimación se basa en la velocidad medida (throughput), no en el optimismo; ~130/22 ≈ 6 sprints.',
        'Las horas extra no son sostenibles ni una base de planificación.',
        'Con datos de velocidad sí se puede estimar con un rango.',
      ],
    },
    {
      extKey: 'iv-app-06',
      skillTag: 'Prácticas de planificación y seguimiento en Scrum',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: '¿Qué representa la Definición de Hecho (Definition of Done) en Scrum?',
      options: [
        'La fecha límite del proyecto.',
        'El conjunto de criterios que un incremento debe cumplir para considerarse terminado y potencialmente entregable (probado, documentado, integrado…).',
        'El número de historias por sprint.',
        'La lista de asistentes a la retrospectiva.',
      ],
      correctIndex: 1,
      explanations: [
        'No es una fecha.',
        'Correcto: la DoD fija qué significa "hecho" de forma común y verificable.',
        'Eso es el alcance del sprint, no la DoD.',
        'No tiene relación con la asistencia a ceremonias.',
      ],
    },
    {
      extKey: 'iv-app-07',
      skillTag: 'Ciclos iterativos para la mejora de productos y procesos',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Vas a lanzar una funcionalidad grande. Aplicando construir-medir-aprender, ¿qué haces primero?',
      options: [
        'Construir la versión completa y pulida antes de mostrarla a nadie.',
        'Definir la hipótesis (qué esperas que cambie), construir la versión mínima que permita comprobarla, medir con usuarios reales y decidir con esos datos.',
        'Preguntar a la dirección si les gusta la idea.',
        'Copiar exactamente lo que hace un competidor.',
      ],
      correctIndex: 1,
      explanations: [
        'Construir todo antes de validar arriesga meses de trabajo sobre una suposición.',
        'Correcto: el bucle empieza por una hipótesis y el mínimo necesario para probarla con datos reales.',
        'La opinión de la dirección no sustituye la evidencia de uso.',
        'Copiar no valida que la funcionalidad resuelva tu problema.',
      ],
    },
    {
      extKey: 'iv-app-08',
      skillTag: 'Evaluación y ajuste continuo en proyectos ágiles',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Las retrospectivas de tu equipo siempre concluyen "todo bien, seguir igual". Tres sprints después, la calidad ha bajado. ¿Qué diagnóstico es correcto?',
      options: [
        'El equipo es perfecto y no hay nada que cambiar.',
        'Las retrospectivas no están cumpliendo su función: una retrospectiva sin al menos un problema real identificado y una acción concreta no genera mejora.',
        'Hay que eliminar las retrospectivas.',
        'La calidad bajó por causas externas ajenas al equipo.',
      ],
      correctIndex: 1,
      explanations: [
        'Si la calidad baja, "todo bien" es una señal de retrospectiva vacía.',
        'Correcto: una retrospectiva útil produce hallazgos incómodos y acciones verificables; sin ellos, es una felicitación.',
        'El problema es cómo se hacen, no que existan.',
        'Atribuir todo a lo externo evita la mejora que la retrospectiva debería impulsar.',
      ],
    },
    {
      extKey: 'iv-app-09',
      skillTag: 'Comparativa de marcos ágiles (Scrum, Kanban, Lean)',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un equipo con Kanban tiene 15 tarjetas "en progreso" a la vez y nada se termina. ¿Qué ajuste concreto propone Kanban?',
      options: [
        'Contratar más gente inmediatamente.',
        'Bajar el límite de trabajo en curso (WIP) para forzar a terminar antes de empezar, reduciendo el tiempo de ciclo.',
        'Añadir más columnas al tablero.',
        'Pasar a sprints de un mes.',
      ],
      correctIndex: 1,
      explanations: [
        'Más gente sin límite de WIP suele multiplicar el trabajo a medias.',
        'Correcto: reducir el WIP es la palanca central de Kanban para mejorar el flujo.',
        'Más columnas no reduce el trabajo simultáneo.',
        'Cambiar de marco no resuelve el problema de flujo por sí solo.',
      ],
    },
    {
      extKey: 'iv-app-10',
      skillTag: 'Evaluación y ajuste continuo en proyectos ágiles',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Las métricas DORA (frecuencia de despliegue, tiempo de entrega, tasa de fallo de cambios, tiempo de restauración) sirven principalmente para:',
      options: [
        'Medir cuántas reuniones hace el equipo.',
        'Evaluar el rendimiento de entrega de software de un equipo de forma equilibrada entre velocidad y estabilidad.',
        'Calcular el salario de los desarrolladores.',
        'Contar líneas de código escritas.',
      ],
      correctIndex: 1,
      explanations: [
        'No miden reuniones.',
        'Correcto: DORA equilibra rapidez (frecuencia, lead time) con estabilidad (fallo de cambios, recuperación).',
        'No son una base salarial.',
        'Las líneas de código no son una métrica DORA ni de valor.',
      ],
    },
    {
      extKey: 'iv-app-11',
      skillTag: 'Principios y fundamentos de la agilidad',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'El manifiesto ágil valora "responder al cambio sobre seguir un plan". Un stakeholder lo interpreta como "no hace falta planificar". ¿Cómo lo corriges?',
      options: [
        'Tiene razón: en ágil no se planifica.',
        'Es una preferencia relativa, no absoluta: se planifica, pero el plan es una hipótesis que se revisa con lo aprendido, no un contrato inamovible.',
        'El manifiesto está equivocado en ese punto.',
        'Hay que planificar todo el proyecto al detalle desde el inicio.',
      ],
      correctIndex: 1,
      explanations: [
        'El manifiesto valora ambos lados; prioriza uno.',
        'Correcto: "sobre" indica preferencia relativa; la planificación sigue siendo necesaria, pero adaptable.',
        'No es un error del manifiesto, es una lectura errónea.',
        'La planificación total por adelantado es justo lo que la agilidad matiza.',
      ],
    },
    {
      extKey: 'iv-app-12',
      skillTag: 'Prácticas de planificación y seguimiento en Scrum',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'En una estimación con planning poker, dos personas dan 3 puntos y una da 13. ¿Qué hace el equipo?',
      options: [
        'Tomar el promedio (≈6) y seguir.',
        'Conversar: la diferencia grande indica que entienden la historia de forma distinta; se aclara el alcance y se vuelve a estimar.',
        'Ignorar a la persona que dio 13.',
        'Asignar 13 por seguridad, sin discutir.',
      ],
      correctIndex: 1,
      explanations: [
        'El promedio oculta el desacuerdo de comprensión, que es la información valiosa.',
        'Correcto: el planning poker usa la divergencia como disparador de conversación para alinear el entendimiento.',
        'La estimación alta suele reflejar un riesgo o requisito que los demás no vieron.',
        'Tomar el número alto sin entender por qué no resuelve la ambigüedad.',
      ],
    },
    { extKey: 'iv-app-13', skillTag: 'Principios y fundamentos de la agilidad', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Un proyecto de datos tiene alta incertidumbre: no se sabe si el modelo funcionará hasta probarlo. ¿Qué principio ágil aplica más directamente?',
      options: ['Fijar todo el alcance y la fecha por adelantado.', 'Entregar incrementos pequeños y validados pronto, para aprender y ajustar antes de comprometer más esfuerzo.', 'Documentar exhaustivamente antes de empezar.', 'Añadir más personas al equipo.'],
      correctIndex: 1,
      explanations: ['Fijar todo por adelantado es lo contrario de gestionar la incertidumbre.', 'Correcto: incrementos pequeños permiten aprender pronto en un contexto incierto.', 'La documentación previa no reduce la incertidumbre técnica.', 'Más personas no reducen la incertidumbre y añaden coordinación.'] },
    { extKey: 'iv-app-14', skillTag: 'Principios y fundamentos de la agilidad', difficulty: 'baja', cognitive: 'comprension',
      stem: 'El manifiesto ágil valora "software funcionando sobre documentación extensiva". ¿Interpretación correcta?',
      options: ['No hay que documentar nada.', 'La documentación necesaria sí se hace; lo que se prioriza es entregar valor funcionando por encima de generar documentos que nadie usa.', 'Solo se documenta al final.', 'La documentación está prohibida.'],
      correctIndex: 1,
      explanations: ['"Sobre" es preferencia relativa, no negación.', 'Correcto: se documenta lo útil; no se sustituye la entrega por documentos.', 'La documentación útil se hace cuando aporta, no solo al final.', 'No está prohibida.'] },
    { extKey: 'iv-app-15', skillTag: 'Comparativa de marcos ágiles (Scrum, Kanban, Lean)', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Un equipo con trabajo planificable en bloques de 2 semanas y objetivos claros por iteración. ¿Marco?',
      options: ['Kanban, siempre.', 'Scrum: encaja cuando el trabajo se puede comprometer por sprint y se busca cadencia y objetivos de iteración.', 'Cascada.', 'Ninguno.'],
      correctIndex: 1,
      explanations: ['Kanban es mejor para flujo impredecible.', 'Correcto: Scrum aporta la estructura de sprint con objetivo.', 'Cascada no es iterativo.', 'Scrum es adecuado aquí.'] },
    { extKey: 'iv-app-16', skillTag: 'Comparativa de marcos ágiles (Scrum, Kanban, Lean)', difficulty: 'media', cognitive: 'comprension',
      stem: '"Lean" aporta al desarrollo, sobre todo:',
      options: ['Reuniones diarias de pie.', 'El foco en eliminar desperdicio (trabajo a medias, esperas, retrabajo) y en el ciclo construir-medir-aprender para validar hipótesis.', 'Sprints de 4 semanas.', 'Un tablero con columnas.'],
      correctIndex: 1,
      explanations: ['La reunión diaria es de Scrum.', 'Correcto: Lean se centra en reducir desperdicio y aprender rápido.', 'Los sprints son de Scrum.', 'El tablero es de Kanban.'] },
    { extKey: 'iv-app-17', skillTag: 'Roles y eventos en Scrum', difficulty: 'baja', cognitive: 'comprension',
      stem: '¿Cuál es el propósito de la revisión de sprint (sprint review)?',
      options: ['Repartir tareas del siguiente sprint.', 'Inspeccionar el incremento con las partes interesadas y adaptar el backlog según su retroalimentación.', 'Evaluar el desempeño individual del equipo.', 'Decidir despidos.'],
      correctIndex: 1,
      explanations: ['Eso es la planificación.', 'Correcto: la review es para mostrar el incremento y recoger retroalimentación que ajusta el backlog.', 'No es una evaluación de personas.', 'No tiene relación con recursos humanos.'] },
    { extKey: 'iv-app-18', skillTag: 'Roles y eventos en Scrum', difficulty: 'media', cognitive: 'analisis',
      stem: 'El Product Owner está poco disponible y el equipo decide por su cuenta qué construir. ¿Riesgo?',
      options: ['Ninguno, el equipo es autónomo.', 'Se construye lo que el equipo cree valioso, no necesariamente lo que aporta más valor de negocio; falta el rol que prioriza el retorno.', 'Que el sprint dure más.', 'Que haya menos reuniones.'],
      correctIndex: 1,
      explanations: ['La autonomía técnica no sustituye la priorización de valor.', 'Correcto: sin un PO efectivo, la priorización por valor de negocio se pierde.', 'La duración del sprint es fija.', 'El problema no es el número de reuniones.'] },
    { extKey: 'iv-app-19', skillTag: 'Prácticas de planificación y seguimiento en Scrum', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'El burndown del sprint es plano los primeros 6 días y luego cae en picado el último. ¿Qué señala?',
      options: ['El equipo trabaja de forma óptima.', 'Trabajo apilado sin terminar hasta el final: alto riesgo de no completar y de integración tardía; conviene dividir historias y cerrar antes de empezar nuevas.', 'Que el sprint es demasiado corto.', 'Que hay demasiadas historias.'],
      correctIndex: 1,
      explanations: ['Un burndown así indica riesgo, no salud.', 'Correcto: nada "hecho" hasta el final es una señal de flujo problemático.', 'La duración no es el problema principal.', 'El problema es cómo se cierra el trabajo, no cuántas historias hay.'] },
    { extKey: 'iv-app-20', skillTag: 'Prácticas de planificación y seguimiento en Scrum', difficulty: 'baja', cognitive: 'comprension',
      stem: 'La "velocidad" del equipo sirve para:',
      options: ['Comparar equipos entre sí.', 'Estimar cuánto trabajo puede completar ESE equipo en próximos sprints, a partir de su histórico; no es comparable entre equipos.', 'Calcular salarios.', 'Medir la calidad del código.'],
      correctIndex: 1,
      explanations: ['La velocidad no es comparable entre equipos (estiman distinto).', 'Correcto: es una herramienta de planificación interna del equipo.', 'No es una métrica salarial.', 'No mide calidad.'] },
    { extKey: 'iv-app-21', skillTag: 'Ciclos iterativos para la mejora de productos y procesos', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Vas a validar si una nueva función reduce el tiempo de una tarea. ¿Qué defines antes de construir el MVP?',
      options: ['El diseño visual final.', 'La hipótesis medible: "esperamos que el tiempo medio baje de X a Y"; y cómo lo vas a medir con usuarios reales.', 'El nombre de la función.', 'El presupuesto de marketing.'],
      correctIndex: 1,
      explanations: ['El diseño final viene después de validar la hipótesis.', 'Correcto: el bucle empieza por una hipótesis medible y su método de medición.', 'El nombre no valida nada.', 'El marketing es posterior.'] },
    { extKey: 'iv-app-22', skillTag: 'Ciclos iterativos para la mejora de productos y procesos', difficulty: 'media', cognitive: 'comprension',
      stem: 'Un MVP (producto mínimo viable) es:',
      options: ['Una versión con todas las funciones pero fea.', 'La versión más pequeña que permite aprender algo real sobre si la idea funciona, con usuarios reales.', 'Un prototipo que nadie usa.', 'La versión final sin pulir.'],
      correctIndex: 1,
      explanations: ['No es "todo pero feo".', 'Correcto: el MVP se define por lo que permite aprender, no por su acabado.', 'El MVP se pone frente a usuarios; ese es su propósito.', 'No es la versión final.'] },
    { extKey: 'iv-app-23', skillTag: 'Evaluación y ajuste continuo en proyectos ágiles', difficulty: 'media', cognitive: 'analisis',
      stem: 'La retrospectiva genera siempre las mismas acciones que nunca se implementan. ¿Qué cambias?',
      options: ['Eliminar la retrospectiva.', 'Convertir cada acción en un elemento del backlog con dueño y tamaño, y revisar en la siguiente retro si se hizo; sin seguimiento, la retro no mejora nada.', 'Hacerla más larga.', 'Cambiar de facilitador cada vez.'],
      correctIndex: 1,
      explanations: ['El problema es el seguimiento, no que exista.', 'Correcto: las acciones deben entrar en el flujo de trabajo con dueño y verificación.', 'Más duración no garantiza ejecución.', 'Rotar facilitador no aborda la falta de seguimiento.'] },
    { extKey: 'iv-app-24', skillTag: 'Evaluación y ajuste continuo en proyectos ágiles', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Tu equipo despliega una vez al mes y cada despliegue causa incidencias. Según las métricas DORA, ¿qué mejora atacar primero?',
      options: ['Ninguna, un despliegue al mes es lo normal.', 'Aumentar la frecuencia de despliegue con lotes más pequeños: reduce el tamaño del cambio y, con ello, la tasa de fallo y el tiempo de recuperación.', 'Reducir a un despliegue al trimestre.', 'Dejar de medir DORA.'],
      correctIndex: 1,
      explanations: ['Lotes grandes y raros correlacionan con más incidencias.', 'Correcto: desplegar más a menudo con cambios pequeños mejora estabilidad y velocidad a la vez.', 'Menos frecuencia empeora el problema.', 'DORA es justo lo que te está señalando el problema.'] },
    { extKey: 'iv-app-25', skillTag: 'Comparativa de marcos ágiles (Scrum, Kanban, Lean)', difficulty: 'media', cognitive: 'analisis',
      stem: 'Un equipo hace "Scrum" pero cambia el alcance del sprint cada dos días por peticiones urgentes. ¿Qué encaja mejor y por qué?',
      options: ['Seguir con Scrum y aguantar.', 'Kanban: si las prioridades cambian constantemente, el compromiso por sprint no funciona; el flujo continuo con límites de WIP se adapta mejor.', 'Cascada.', 'Dejar de usar cualquier marco.'],
      correctIndex: 1,
      explanations: ['Scrum con el alcance cambiando cada dos días no da previsibilidad.', 'Correcto: Kanban gestiona prioridades cambiantes sin comprometer un alcance fijo.', 'Cascada es aún menos flexible.', 'Un marco adecuado (Kanban) sí ayuda.'] },
    { extKey: 'iv-app-26', skillTag: 'Roles y eventos en Scrum', difficulty: 'baja', cognitive: 'comprension',
      stem: 'El Scrum Master, ante un impedimento externo que bloquea al equipo, debe:',
      options: ['Ignorarlo, no es su problema.', 'Facilitar su eliminación: escalar, coordinar con quien corresponda y proteger al equipo para que pueda avanzar.', 'Asignar la culpa a un miembro del equipo.', 'Cancelar el sprint.'],
      correctIndex: 1,
      explanations: ['Eliminar impedimentos es una función central del rol.', 'Correcto: el Scrum Master trabaja para desbloquear al equipo.', 'No es un rol de asignación de culpas.', 'Cancelar el sprint es una medida extrema, no la primera respuesta.'] },
    { extKey: 'iv-app-27', skillTag: 'Prácticas de planificación y seguimiento en Scrum', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Quedan 130 puntos de backlog y tu velocidad de los últimos 4 sprints es 18, 22, 20, 24. ¿Cómo comunicas la fecha estimada?',
      options: ['"Dos sprints si nos esforzamos."', '"Unos 6 sprints tomando la velocidad media (~21), con un rango de 5 a 7 por la variabilidad observada."', '"Un sprint con horas extra."', '"Imposible de estimar."'],
      correctIndex: 1,
      explanations: ['Estimar por deseo ignora la evidencia.', 'Correcto: se usa la velocidad medida y se comunica con rango.', 'Las horas extra no son sostenibles ni base de plan.', 'Con datos de velocidad sí se puede estimar con rango.'] },
    { extKey: 'iv-app-28', skillTag: 'Principios y fundamentos de la agilidad', difficulty: 'media', cognitive: 'analisis',
      stem: '"Somos ágiles porque no planificamos, improvisamos". ¿Corrección?',
      options: ['Correcto, así es la agilidad.', 'La agilidad planifica, pero trata el plan como una hipótesis que se revisa con lo aprendido; improvisar sin plan no es agilidad, es ausencia de método.', 'La agilidad prohíbe planificar.', 'Da igual el enfoque.'],
      correctIndex: 1,
      explanations: ['No es correcto.', 'Correcto: plan adaptable, no ausencia de plan.', 'La agilidad no prohíbe planificar.', 'El método importa.'] },
    { extKey: 'iv-app-29', skillTag: 'Ciclos iterativos para la mejora de productos y procesos', difficulty: 'media', cognitive: 'analisis',
      stem: 'Tras 3 iteraciones, los datos de uso no mejoran pese a los cambios. ¿Pivotar o pulir?',
      options: ['Pulir: seguir refinando la misma idea.', 'Evaluar pivotar: si la evidencia repetida dice que la dirección no funciona, cambiar un supuesto central (problema, segmento o mecanismo) manteniendo lo aprendido.', 'Abandonar el proyecto.', 'Repetir la misma iteración.'],
      correctIndex: 1,
      explanations: ['Pulir algo que no funciona repite el resultado.', 'Correcto: la evidencia repetida sin mejora es la señal para pivotar.', 'Pivotar no es abandonar.', 'Repetir sin cambios no genera aprendizaje.'] },
    { extKey: 'iv-app-30', skillTag: 'Evaluación y ajuste continuo en proyectos ágiles', difficulty: 'baja', cognitive: 'comprension',
      stem: 'El "lead time" de una tarjeta en un tablero Kanban mide:',
      options: ['Cuántas personas la tocaron.', 'El tiempo total desde que se solicitó hasta que se entregó; junto al throughput permite estimar plazos con datos.', 'El número de comentarios.', 'La complejidad estimada.'],
      correctIndex: 1,
      explanations: ['No cuenta personas.', 'Correcto: lead time = tiempo de extremo a extremo de la tarjeta.', 'No cuenta comentarios.', 'No es una estimación de complejidad.'] },
  ],
};
