// Banco de ítems de aplicación — Asignatura X: AI Platforms (nube, despliegue y operación).
module.exports = {
  slug: 'bank-master-x',
  title: 'Banco de ítems — Asignatura X',
  scopeSlug: 'master-x',
  questions: [
    {
      extKey: 'x-app-01',
      skillTag: 'Google Cloud',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Una organización que ya usa intensamente el ecosistema de ofimática y correo de Microsoft debe elegir nube para desplegar un modelo interno. Tu recomendación NO debe basarse en el precio de lista. ¿Qué factor pesa más?',
      options: [
        'Que Microsoft es la empresa más grande.',
        'La integración con la identidad, los permisos y los datos que ya viven en ese ecosistema: reduce fricción de despliegue, gobernanza y soporte, aunque otra nube tenga un servicio puntual más barato.',
        'Que Azure salió antes al mercado.',
        'El color del panel de control.',
      ],
      correctIndex: 1,
      explanations: [
        'El tamaño de la empresa no es un criterio técnico.',
        'Correcto: la integración con el ecosistema existente (identidad, permisos, datos) es un factor no-precio de primer orden.',
        'La antigüedad del servicio no determina su idoneidad.',
        'La estética del panel es irrelevante.',
      ],
    },
    {
      extKey: 'x-app-02',
      skillTag: 'Computación en la nube',
      difficulty: 'baja',
      cognitive: 'aplicacion',
      stem: 'Clasifica: "un servicio gestionado que entrena y despliega modelos, donde tú aportas el código y los datos y el proveedor gestiona la infraestructura". ¿IaaS, PaaS o SaaS?',
      options: ['IaaS', 'PaaS (plataforma de ML gestionada)', 'SaaS', 'On-premise'],
      correctIndex: 1,
      explanations: [
        'IaaS te daría solo las máquinas; aquí gestionan la plataforma de ML.',
        'Correcto: aportas código y datos, el proveedor gestiona la plataforma: es PaaS.',
        'SaaS sería consumir una capacidad ya construida sin aportar código.',
        'On-premise implica infraestructura propia.',
      ],
    },
    {
      extKey: 'x-app-03',
      skillTag: 'Arquitectura de referencia',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un diagrama de arquitectura para llevar un modelo a producción omite el "registro de modelos" (model registry). ¿Qué problema aparece con el tiempo?',
      options: [
        'Ninguno: el registro de modelos es opcional.',
        'Sin registro no hay control de versiones de modelos: no se sabe qué versión está en producción, no se puede revertir a una anterior ni auditar qué datos y métricas tenía la que se desplegó.',
        'El modelo entrena más lento.',
        'Aumenta el coste de almacenamiento de datos.',
      ],
      correctIndex: 1,
      explanations: [
        'El registro de modelos es una pieza clave de una arquitectura de producción.',
        'Correcto: sin él se pierden versionado, reversión y trazabilidad del modelo en producción.',
        'No afecta a la velocidad de entrenamiento.',
        'No es principalmente un problema de almacenamiento de datos.',
      ],
    },
    {
      extKey: 'x-app-04',
      skillTag: 'Arquitectura de referencia',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un modelo desplegado empieza a fallar semanas después sin que nadie cambie el código. La causa más probable y la pieza de arquitectura que lo habría detectado son:',
      options: [
        'Un bug en el código; pruebas unitarias.',
        'Deriva de datos (los datos de entrada en producción se alejan de los de entrenamiento); un monitoreo de deriva sobre las distribuciones de entrada y de predicción lo habría alertado.',
        'Falta de RAM; más memoria.',
        'El certificado SSL caducó; renovarlo.',
      ],
      correctIndex: 1,
      explanations: [
        'Si el código no cambió, un bug nuevo es poco probable.',
        'Correcto: la degradación sin cambios de código suele ser deriva de datos; el monitoreo de deriva la detecta.',
        'La memoria no explica una caída progresiva de calidad de predicción.',
        'Un certificado caducado daría un fallo de conexión, no de calidad del modelo.',
      ],
    },
    {
      extKey: 'x-app-05',
      skillTag: 'Principales servicios',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'Las nubes ofrecen "APIs preentrenadas" (visión, voz, lenguaje) además de plataformas para entrenar modelos propios. ¿Cuándo conviene la API preentrenada?',
      options: [
        'Siempre: es más barata.',
        'Cuando la tarea es estándar (transcribir, detectar objetos comunes, traducir), no hay ventaja competitiva en entrenar algo propio y se valora la puesta en marcha rápida sin equipo de ML.',
        'Nunca: hay que entrenar todo internamente.',
        'Solo si el proveedor lo regala.',
      ],
      correctIndex: 1,
      explanations: [
        'No siempre es más barata a gran volumen, y no siempre encaja.',
        'Correcto: para tareas estándar sin ventaja en hacerlo propio, la API preentrenada ahorra tiempo y equipo.',
        'Entrenar todo internamente es un desperdicio para tareas comunes ya resueltas.',
        'El precio no es el único criterio.',
      ],
    },
    {
      extKey: 'x-app-06',
      skillTag: 'Amazon Web Services',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La asignatura recomienda estudiar la nube "por categorías de servicio" y no memorizando nombres de producto. ¿Por qué?',
      options: [
        'Porque los nombres son difíciles de pronunciar.',
        'Porque los nombres comerciales cambian y se renuevan con frecuencia, mientras que las categorías (cómputo, almacenamiento, ML gestionado, datos, MLOps) son estables y transferibles entre proveedores.',
        'Porque AWS no publica sus nombres.',
        'Porque los nombres son secretos comerciales.',
      ],
      correctIndex: 1,
      explanations: [
        'No es una cuestión de pronunciación.',
        'Correcto: las categorías perduran; los nombres de producto caducan rápido.',
        'AWS publica sus nombres; el punto es que cambian.',
        'No son secretos.',
      ],
    },
    {
      extKey: 'x-app-07',
      skillTag: 'Microsoft Azure',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Vas a comparar AWS, Azure y GCP para un caso concreto. ¿Qué hace útil la tabla comparativa?',
      options: [
        'Copiar la tabla de características genérica de cada proveedor.',
        'Evaluar las tres nubes solo en las dimensiones que importan para ESTE caso (latencia requerida, integración existente, cumplimiento, servicios específicos necesarios, coste total de operación) y reconocer los empates técnicos donde los haya.',
        'Elegir la que tenga más servicios en total.',
        'Elegir por número de regiones geográficas, siempre.',
      ],
      correctIndex: 1,
      explanations: [
        'Una tabla genérica de marketing no orienta una decisión concreta.',
        'Correcto: la comparativa útil se restringe a las dimensiones relevantes al caso y admite empates.',
        'Tener más servicios no implica ser mejor para tu problema.',
        'El número de regiones solo importa si tu caso lo exige.',
      ],
    },
    {
      extKey: 'x-app-08',
      skillTag: 'Computación en la nube',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Tras desplegar, la factura mensual de la nube resulta el doble de lo previsto. Te piden reducirla a la mitad. ¿Qué haces primero?',
      options: [
        'Apagar el sistema.',
        'Desglosar la factura por servicio y por recurso para ver qué concentra el gasto (cómputo ocioso, almacenamiento sin ciclo de vida, endpoints sobredimensionados, transferencia de datos) y actuar sobre la palanca principal.',
        'Cambiar de proveedor de inmediato.',
        'Pedir un descuento al proveedor y no tocar nada más.',
      ],
      correctIndex: 1,
      explanations: [
        'Apagar el sistema no es una opción si está en uso.',
        'Correcto: primero se identifica dónde se concentra el coste y se actúa sobre esa palanca.',
        'Migrar de nube es un proyecto grande, no la primera acción.',
        'Un descuento no corrige un dimensionamiento ineficiente.',
      ],
    },
    {
      extKey: 'x-app-09',
      skillTag: 'Arquitectura de referencia',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'El "despliegue automático desde el repositorio" (CI/CD para modelos) aporta principalmente:',
      options: [
        'Que el modelo entrena solo sin datos.',
        'Que cada cambio validado del código o del modelo pasa a producción por un proceso repetible y auditable, reduciendo errores manuales y acelerando la reversión si algo falla.',
        'Que se elimina la necesidad de pruebas.',
        'Que baja el coste de las GPUs.',
      ],
      correctIndex: 1,
      explanations: [
        'No genera datos ni entrena solo.',
        'Correcto: CI/CD hace el despliegue repetible, auditable y reversible.',
        'CI/CD incluye las pruebas, no las elimina.',
        'No reduce directamente el coste de hardware.',
      ],
    },
    {
      extKey: 'x-app-10',
      skillTag: 'Principales servicios',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Un "endpoint" de inferencia gestionado en la nube es:',
      options: [
        'El lugar donde se guardan los datos de entrenamiento.',
        'Un servicio que expone el modelo para recibir peticiones y devolver predicciones, con escalado, versionado y monitoreo gestionados por el proveedor.',
        'El panel de facturación.',
        'La consola de administración de usuarios.',
      ],
      correctIndex: 1,
      explanations: [
        'El almacenamiento de datos es otra pieza.',
        'Correcto: el endpoint sirve predicciones del modelo con escalado y monitoreo gestionados.',
        'No es el panel de facturación.',
        'No es la gestión de usuarios.',
      ],
    },
    {
      extKey: 'x-app-11',
      skillTag: 'Google Cloud',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'La asignatura recomienda "elegir una sola nube" para certificarse y practicar. ¿Cuál es la razón práctica?',
      options: [
        'Que las otras nubes son peores.',
        'Que las tres comparten los mismos conceptos; dominar una en profundidad (con práctica real y, si aplica, certificación) transfiere el 80% del conocimiento y evita quedarse en la superficie de las tres.',
        'Que usar dos nubes es ilegal.',
        'Que solo una nube tiene servicios de ML.',
      ],
      correctIndex: 1,
      explanations: [
        'Las tres son competitivas; no se trata de calidad.',
        'Correcto: profundizar en una transfiere lo esencial; dispersarse deja el conocimiento superficial.',
        'No hay restricción legal para multi-nube.',
        'Las tres tienen servicios de ML.',
      ],
    },
    {
      extKey: 'x-app-12',
      skillTag: 'Amazon Web Services',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'El proyecto de la asignatura pide "conocer la factura mensual de lo que desplegaste". ¿Por qué es un criterio de dominio y no un detalle administrativo?',
      options: [
        'Porque hay que rendir cuentas al departamento de compras.',
        'Porque no se puede operar ni optimizar un sistema cuyo coste no se entiende: conocer el desglose y la palanca principal es lo que separa desplegar de operar de verdad.',
        'Porque el proveedor lo exige.',
        'Porque la factura contiene la contraseña del sistema.',
      ],
      correctIndex: 1,
      explanations: [
        'La rendición de cuentas es una consecuencia, no la razón de fondo.',
        'Correcto: entender el coste es parte de operar; sin ello no se puede optimizar ni tomar decisiones de arquitectura.',
        'El proveedor factura, pero el criterio es de competencia operativa.',
        'La factura no contiene credenciales.',
      ],
    },
  ],
};
