// Banco de ítems de aplicación — Asignatura V: Ética y regulaciones en el uso de la IA.
module.exports = {
  slug: 'bank-master-v',
  title: 'Banco de ítems — Asignatura V',
  scopeSlug: 'master-v',
  questions: [
    {
      extKey: 'v-app-01',
      skillTag: 'Regulación jurídica de la IA',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un sistema de IA decide la prioridad de atención en un servicio esencial y puede afectar derechos de las personas. Bajo un enfoque regulatorio por niveles de riesgo, ¿en qué categoría lo situarías y qué implica?',
      options: [
        'Riesgo mínimo: basta con informar al usuario.',
        'Riesgo alto: exige evaluación de conformidad, documentación técnica, supervisión humana significativa, registro y gestión de riesgos antes y durante el despliegue.',
        'Riesgo inaceptable: queda prohibido en todos los casos.',
        'No aplica ninguna regulación porque es un sistema interno.',
      ],
      correctIndex: 1,
      explanations: [
        'Un sistema que afecta derechos en un servicio esencial no es de riesgo mínimo.',
        'Correcto: los sistemas de alto riesgo acarrean obligaciones reforzadas de gobernanza, documentación y supervisión.',
        'Priorizar atención no es una práctica intrínsecamente prohibida; es de alto riesgo, no inaceptable.',
        'Ser interno no exime de las obligaciones cuando hay impacto sobre personas.',
      ],
    },
    {
      extKey: 'v-app-02',
      skillTag: 'Consideraciones éticas en el uso de la IA',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un modelo de selección tiene una exactitud del 90% en ambos grupos A y B, pero su tasa de falsos rechazos es del 5% en A y del 20% en B. ¿Qué principio ético está comprometido y cómo se verifica?',
      options: [
        'Ninguno: la exactitud es igual en ambos grupos.',
        'La equidad: exactitudes iguales pueden ocultar errores repartidos de forma desigual; se verifica midiendo métricas por subgrupo (tasas de error, de selección) y no solo el agregado.',
        'La privacidad, porque el modelo usa datos personales.',
        'La transparencia, que se resuelve publicando el código.',
      ],
      correctIndex: 1,
      explanations: [
        'La exactitud igual no garantiza equidad si los errores no se distribuyen igual.',
        'Correcto: la equidad se evalúa por subgrupo; una disparidad de 4× en falsos rechazos es un problema serio.',
        'La privacidad es otro asunto; aquí el problema es la disparidad de impacto.',
        'Publicar el código no corrige una disparidad de resultados.',
      ],
    },
    {
      extKey: 'v-app-03',
      skillTag: 'Modelo de Gobernanza de la IA. Big Data, Blockchain y otras tecnologías disruptivas',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Tu organización tiene un SGSI ISO 27001 en marcha y va a desplegar su primer modelo de IA. ¿Cuál es el enfoque de gobernanza más eficiente?',
      options: [
        'Crear un sistema de gestión totalmente separado, sin relación con el SGSI.',
        'Integrar los controles específicos de IA (inventario de sistemas, gestión de riesgos de IA, trazabilidad, revisión periódica) como una extensión del SGSI existente, mapeando ISO 42001 contra el Anexo A ya implementado.',
        'No hacer nada hasta que haya diez modelos.',
        'Delegar toda la gobernanza en el proveedor del modelo.',
      ],
      correctIndex: 1,
      explanations: [
        'Un sistema paralelo duplica esfuerzo y crea inconsistencias.',
        'Correcto: la gobernanza de IA se apalanca en el SGSI existente, añadiendo lo específico y mapeando 42001↔Anexo A.',
        'Esperar a tener muchos modelos deja el primero sin control.',
        'La responsabilidad de gobernanza no es transferible al proveedor.',
      ],
    },
    {
      extKey: 'v-app-04',
      skillTag: 'Regulación jurídica de la IA',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'El contenido de esta asignatura evita citar números de artículo y versiones concretas de normas. ¿Qué debe hacer el estudiante que va a redactar una política de uso de IA real para su organización?',
      options: [
        'Usar los ejemplos genéricos de la asignatura como si fueran la norma vigente.',
        'Verificar en fuentes primarias el estado y el texto actual de las normas aplicables (reglamento europeo, marco NIST, ISO 42001/23894, normativa nacional de protección de datos y política de IA vigente) en el momento de redactar.',
        'Asumir que la regulación no cambia.',
        'Copiar la política de otra empresa sin adaptarla.',
      ],
      correctIndex: 1,
      explanations: [
        'Los ejemplos de la asignatura ilustran el enfoque, no sustituyen el texto legal vigente.',
        'Correcto: la regulación de IA evoluciona; hay que contrastar contra fuentes primarias actuales.',
        'La regulación de IA está en cambio activo.',
        'Copiar sin adaptar ignora el contexto y los riesgos propios.',
      ],
    },
    {
      extKey: 'v-app-05',
      skillTag: 'Inteligencia Artificial aplicada para la detección y prevención de riesgos',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un detector de fraude basado en IA marca el 2% de las operaciones. El equipo empieza a aprobar automáticamente el 98% restante "porque el modelo ya las revisó". ¿Qué riesgo se ha introducido?',
      options: [
        'Ninguno: automatizar lo que el modelo no marca es eficiente.',
        'Sobre-confianza en el detector: los falsos negativos (fraude no marcado) ahora pasan sin ninguna revisión humana; hay que mantener muestreo aleatorio y vigilar la deriva del modelo.',
        'Que el modelo consume demasiada CPU.',
        'Que el 2% marcado es demasiado alto.',
      ],
      correctIndex: 1,
      explanations: [
        'Confiar ciegamente en "lo no marcado" elimina la última red de seguridad ante los falsos negativos.',
        'Correcto: el detector reduce carga, no la elimina; el fraude que no detecta ahora no lo ve nadie.',
        'El consumo de CPU no es el riesgo de gobernanza aquí.',
        'El 2% puede ser razonable; el problema es qué se hace con el 98%.',
      ],
    },
    {
      extKey: 'v-app-06',
      skillTag: 'Principales Retos y desafíos en el uso de IA',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: '¿Qué se entiende por "cadena de responsabilidad" difusa como reto organizacional de la IA?',
      options: [
        'Que el modelo se entrena en cadena, capa por capa.',
        'Que cuando un sistema de IA causa un daño, no está claro quién responde: quien lo entrenó, quien lo integró, quien decidió usarlo o quien lo operó; hay que asignarlo explícitamente antes del despliegue.',
        'Que hay que usar blockchain para todo.',
        'Que los datos vienen de muchas fuentes.',
      ],
      correctIndex: 1,
      explanations: [
        'No se refiere al entrenamiento por capas.',
        'Correcto: la responsabilidad se diluye entre actores; la gobernanza exige asignarla de forma explícita.',
        'Blockchain no resuelve la asignación de responsabilidad legal.',
        'La variedad de fuentes de datos es otro problema distinto.',
      ],
    },
    {
      extKey: 'v-app-07',
      skillTag: 'Modelo de Gobernanza de la IA. Big Data, Blockchain y otras tecnologías disruptivas',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Estás redactando el entregable de esta asignatura. ¿Cuál de estos elementos es imprescindible según su criterio de dominio?',
      options: [
        'Una revisión histórica de la filosofía de la ética.',
        'El punto exacto del flujo del sistema donde debe intervenir un humano con capacidad real de veto, no solo la frase "debe haber supervisión humana".',
        'Un glosario de términos de IA.',
        'La biografía de los autores de las normas citadas.',
      ],
      correctIndex: 1,
      explanations: [
        'Una revisión filosófica no es lo que pide el entregable.',
        'Correcto: el criterio de dominio exige señalar el punto concreto de intervención humana, con poder de veto.',
        'Un glosario no es el núcleo del entregable de gobernanza.',
        'Las biografías no aportan al análisis de riesgo y cumplimiento.',
      ],
    },
    {
      extKey: 'v-app-08',
      skillTag: 'Consideraciones éticas en el uso de la IA',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un principio ético dice "la IA debe ser justa". Para convertirlo en una práctica verificable, ¿qué haces?',
      options: [
        'Añadir la frase "somos justos" a la política y darlo por hecho.',
        'Definir métricas concretas de equidad para el caso (p. ej. diferencia máxima aceptable en tasa de error entre grupos), medirlas periódicamente y fijar un umbral de acción.',
        'Confiar en que el proveedor ya lo garantizó.',
        'Eliminar todas las variables demográficas del modelo y cerrar el tema.',
      ],
      correctIndex: 1,
      explanations: [
        'Una declaración no es una práctica verificable.',
        'Correcto: los principios se operacionalizan con métricas, medición periódica y umbrales de acción.',
        'La garantía del proveedor no exime de verificar en tu contexto.',
        'Quitar variables directas no elimina el sesgo por proxies; hay que medir.',
      ],
    },
    {
      extKey: 'v-app-09',
      skillTag: 'Introducción a la Inteligencia Artificial',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Para un rol de gobierno de la información, ¿por qué se dice que la IA "necesita gobernanza propia" y no basta con la gobernanza de datos existente?',
      options: [
        'Porque la IA no usa datos.',
        'Porque añade riesgos específicos: opacidad de las decisiones, escala del impacto, deriva del comportamiento con el tiempo y asimetría de información entre quien decide y quien es afectado.',
        'Porque la gobernanza de datos es obsoleta.',
        'Porque la IA siempre es ilegal sin permiso.',
      ],
      correctIndex: 1,
      explanations: [
        'La IA depende intensamente de datos; el punto es que añade riesgos nuevos.',
        'Correcto: opacidad, escala, deriva y asimetría son riesgos que la gobernanza de datos clásica no cubre.',
        'La gobernanza de datos sigue siendo la base; la de IA la extiende.',
        'La IA no es ilegal por defecto.',
      ],
    },
    {
      extKey: 'v-app-10',
      skillTag: 'Inteligencia Artificial aplicada para la detección y prevención de riesgos',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Al desplegar un modelo de detección de anomalías para riesgos, el equipo puede revisar 30 alertas al día. El modelo genera 200. ¿Qué decisión de gobernanza corresponde?',
      options: [
        'Ignorar 170 alertas al azar cada día.',
        'Calibrar el umbral del modelo a la capacidad real de respuesta (para que las ~30 alertas del día sean las de mayor riesgo esperado) y documentar qué se hace con la cola no atendida.',
        'Contratar 6 personas más de inmediato sin análisis de coste.',
        'Apagar el modelo hasta tener capacidad para 200.',
      ],
      correctIndex: 1,
      explanations: [
        'Descartar al azar deja pasar los casos de mayor riesgo.',
        'Correcto: el umbral se ajusta a la capacidad de respuesta y se documenta el tratamiento de lo no atendido.',
        'Ampliar el equipo puede ser válido, pero requiere análisis; no es la primera decisión.',
        'Apagar el modelo elimina una capa de detección útil.',
      ],
    },
    {
      extKey: 'v-app-11',
      skillTag: 'Regulación jurídica de la IA',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'El entregable de la asignatura debe redactarse como anexo integrable a un SGSI ISO 27001. ¿Qué tabla no puede faltar?',
      options: [
        'Una tabla de precios de proveedores de IA.',
        'Una tabla de correspondencia entre controles de ISO 42001 y controles del Anexo A de ISO 27001, señalando dónde hay equivalencia, dónde hay vacío y qué añadir al SGSI.',
        'Un cronograma de reuniones del comité.',
        'Un listado de modelos de lenguaje del mercado.',
      ],
      correctIndex: 1,
      explanations: [
        'Los precios no forman parte del anexo de gobernanza.',
        'Correcto: el mapeo 42001↔Anexo A con identificación de brechas es el núcleo exigido.',
        'El cronograma es un detalle operativo, no la tabla clave.',
        'El catálogo de modelos no aporta al anexo.',
      ],
    },
    {
      extKey: 'v-app-12',
      skillTag: 'Principales Retos y desafíos en el uso de IA',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: '"Fatiga de cumplimiento" en un equipo que gestiona varios marcos (protección de datos, seguridad, IA) se refiere a:',
      options: [
        'El cansancio físico de trabajar de noche.',
        'La sobrecarga de controles, evidencias y auditorías solapadas que lleva a cumplir de forma mecánica o a saltarse pasos; se mitiga integrando marcos y reutilizando controles comunes.',
        'La falta de presupuesto para software.',
        'El exceso de reuniones de retrospectiva.',
      ],
      correctIndex: 1,
      explanations: [
        'No es cansancio físico por horario.',
        'Correcto: es la saturación por controles redundantes entre marcos; la respuesta es integrarlos.',
        'El presupuesto es otro problema.',
        'Las retrospectivas son de metodología ágil, no de cumplimiento normativo.',
      ],
    },
  ],
};
