// Banco de ítems de aplicación — Asignatura XI: IA aplicada a entornos seguros.
module.exports = {
  slug: 'bank-master-xi',
  title: 'Banco de ítems — Asignatura XI',
  scopeSlug: 'master-xi',
  questions: [
    {
      extKey: 'xi-app-01',
      skillTag: 'Introducción a la Inteligencia Artificial y aprendizaje automático',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La asignatura distingue "seguridad mediante IA" de "seguridad de la IA". ¿Cuál es la diferencia?',
      options: [
        'Son sinónimos.',
        'Seguridad mediante IA: usar IA para defender (detección de amenazas, correlación de eventos). Seguridad de la IA: proteger a los propios sistemas de IA de ataques (envenenamiento, evasión, inyección de prompt, robo de modelo).',
        'La primera es para hardware y la segunda para software.',
        'La primera la hace el equipo rojo y la segunda el azul.',
      ],
      correctIndex: 1,
      explanations: [
        'Son dos disciplinas distintas.',
        'Correcto: una usa IA como herramienta defensiva; la otra trata la IA como superficie de ataque a proteger.',
        'No es una distinción hardware/software.',
        'Ambos equipos pueden intervenir en las dos.',
      ],
    },
    {
      extKey: 'xi-app-02',
      skillTag: 'Modelos predictivos en ciberseguridad',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un detector de anomalías de red genera 800 alertas al día y el equipo puede investigar 40. Subir el umbral reduce las alertas a 40, pero deja fuera ataques lentos y sigilosos. ¿Cómo se calibra?',
      options: [
        'Dejar el umbral bajo y descartar 760 alertas sin criterio.',
        'Calibrar el umbral a la capacidad de respuesta priorizando por riesgo esperado, y complementar con reglas específicas para los patrones sigilosos que el umbral general se perdería, además de muestreo aleatorio de lo no investigado.',
        'Apagar el detector.',
        'Contratar 20 analistas más esa misma semana.',
      ],
      correctIndex: 1,
      explanations: [
        'Descartar sin criterio deja pasar lo más peligroso.',
        'Correcto: se calibra por capacidad y riesgo, con reglas dedicadas para lo sigiloso y muestreo de la cola.',
        'Apagarlo elimina la detección.',
        'Ampliar el equipo requiere análisis de coste; no es la primera palanca.',
      ],
    },
    {
      extKey: 'xi-app-03',
      skillTag: 'Modelos predictivos en ciberseguridad',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'En detección de intrusiones, un falso positivo hace perder 15 minutos a un analista; un falso negativo puede costar una brecha. ¿Qué implica esta asimetría para el diseño del modelo?',
      options: [
        'Nada: hay que minimizar el error total sin más.',
        'El umbral de decisión debe favorecer la sensibilidad (reducir falsos negativos) hasta el límite que el equipo puede absorber en falsos positivos; optimizar la exactitud a secas sería un error.',
        'Hay que eliminar todas las alertas dudosas.',
        'El modelo debe ser una red neuronal profunda obligatoriamente.',
      ],
      correctIndex: 1,
      explanations: [
        'Con costes asimétricos, "minimizar el error total" da un umbral equivocado.',
        'Correcto: se prioriza no perder ataques, aceptando más falsos positivos hasta la capacidad del equipo.',
        'Eliminar lo dudoso aumenta los falsos negativos, justo lo más caro.',
        'La arquitectura del modelo no se deriva de la asimetría de costes.',
      ],
    },
    {
      extKey: 'xi-app-04',
      skillTag: 'Manejo y procesamiento de datos',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'En un SIEM, ¿por qué es crítica la "normalización" de los eventos de distintas fuentes antes de correlacionarlos?',
      options: [
        'Para reducir el tamaño de los logs.',
        'Porque cada fuente registra los mismos hechos con formatos, nombres de campo y zonas horarias distintos; sin un esquema común no se pueden cruzar eventos ni detectar patrones que abarcan varias fuentes.',
        'Para cifrar los datos.',
        'Para acelerar el disco.',
      ],
      correctIndex: 1,
      explanations: [
        'La normalización no es principalmente compresión.',
        'Correcto: unificar formato, campos y tiempo es lo que permite la correlación entre fuentes.',
        'La normalización no es cifrado.',
        'No es una optimización de hardware.',
      ],
    },
    {
      extKey: 'xi-app-05',
      skillTag: 'Introducción a los modelos generativos en Inteligencia Artificial',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Tu organización desplegó un asistente RAG interno (asignatura IX). Desde seguridad, ¿cuál es un vector de ataque específico y su mitigación?',
      options: [
        'Que el modelo consuma mucha CPU; añadir más servidores.',
        'Inyección de prompt: un documento o entrada manipulada hace que el asistente ignore sus instrucciones o revele contexto sensible. Mitigación: aislar instrucciones de datos, filtrar y validar el contexto recuperado, limitar lo que el asistente puede hacer y registrar/alertar sobre intentos.',
        'Que el índice ocupe mucho disco; comprimirlo.',
        'Que los usuarios escriban con faltas de ortografía; corregir el texto.',
      ],
      correctIndex: 1,
      explanations: [
        'El consumo de CPU no es un ataque.',
        'Correcto: la inyección de prompt es el vector propio de estos sistemas; se mitiga con aislamiento, validación de contexto, mínimo privilegio y monitoreo.',
        'El tamaño del índice no es un vector de ataque.',
        'Las faltas de ortografía no comprometen la seguridad.',
      ],
    },
    {
      extKey: 'xi-app-06',
      skillTag: 'Retos y oportunidades de la Inteligencia Artificial en el contexto de la ciberseguridad',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La IA generativa "de doble filo" en ciberseguridad se refiere a que la misma capacidad puede:',
      options: [
        'Ser rápida y lenta a la vez.',
        'Servir para defender (generar datos sintéticos de ataque para entrenar detectores, resumir incidentes) y para atacar (phishing dirigido convincente, deepfakes, malware polimórfico); el defensor debe anticipar ambos usos.',
        'Funcionar solo los días pares.',
        'Ejecutarse solo en la nube.',
      ],
      correctIndex: 1,
      explanations: [
        'No es una cuestión de velocidad.',
        'Correcto: la misma tecnología habilita defensa y ataque; hay que planificar frente a ambos.',
        'No tiene relación con el calendario.',
        'No depende del lugar de ejecución.',
      ],
    },
    {
      extKey: 'xi-app-07',
      skillTag: 'Principios y aplicaciones Big Data en la ciberseguridad',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un equipo de seguridad guarda todos los eventos "por si acaso" pero nunca los consulta hasta que hay un incidente, y entonces descubre que faltan campos clave y que la retención borró lo relevante. ¿Qué principio se ignoró?',
      options: [
        'La velocidad de ingesta.',
        'Diseñar la recolección desde las preguntas de investigación (qué campos, qué retención, qué integridad) que se necesitarán en un incidente, incluyendo cadena de custodia; recolectar sin ese diseño produce datos inútiles cuando importan.',
        'El cifrado en tránsito.',
        'La elección de proveedor de SIEM.',
      ],
      correctIndex: 1,
      explanations: [
        'La ingesta funcionó; el diseño de qué y cuánto guardar, no.',
        'Correcto: la recolección debe planificarse desde las preguntas forenses futuras y la cadena de custodia.',
        'El cifrado protege pero no hace los datos completos ni retenidos el tiempo adecuado.',
        'El proveedor no determina si el esquema de recolección es adecuado.',
      ],
    },
    {
      extKey: 'xi-app-08',
      skillTag: 'Modelos predictivos en ciberseguridad',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La "explicabilidad de la alerta" es importante en un modelo de detección de amenazas porque:',
      options: [
        'Hace que el modelo sea más rápido.',
        'El analista necesita saber por qué se disparó la alerta (qué señales, qué desviación) para triarla, decidir si escalar y responder; una alerta sin contexto es difícil de accionar y erosiona la confianza en el sistema.',
        'Reduce el tamaño del modelo.',
        'Es un requisito estético del panel.',
      ],
      correctIndex: 1,
      explanations: [
        'La explicabilidad no acelera la inferencia.',
        'Correcto: la alerta debe ser accionable; sin el porqué, el analista no puede triarla eficazmente.',
        'No afecta al tamaño del modelo.',
        'No es una cuestión estética.',
      ],
    },
    {
      extKey: 'xi-app-09',
      skillTag: 'Retos y oportunidades de la Inteligencia Artificial en el contexto de la ciberseguridad',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'El proyecto de la asignatura pide "romper tu propio sistema antes de que lo haga otro". Aplicado a un modelo de clasificación de correos, ¿qué ejercicio ofensivo tiene sentido?',
      options: [
        'Comprobar que el servidor tiene antivirus.',
        'Intentar un ataque de evasión: construir correos maliciosos con pequeñas perturbaciones (sinónimos, formato, texto oculto) que el modelo clasifique como legítimos, documentar los que funcionan con criticidad y proponer mitigaciones (reentrenamiento adversarial, reglas complementarias).',
        'Cambiar la contraseña del administrador.',
        'Aumentar la RAM del servidor.',
      ],
      correctIndex: 1,
      explanations: [
        'El antivirus del servidor no prueba la robustez del clasificador.',
        'Correcto: el ejercicio ofensivo propio es un ataque de evasión documentado como un pentest, con mitigaciones.',
        'Cambiar contraseñas no evalúa el modelo.',
        'El hardware no tiene que ver con la robustez adversarial.',
      ],
    },
    {
      extKey: 'xi-app-10',
      skillTag: 'Introducción a la Inteligencia Artificial y aprendizaje automático',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'El informe de red team de la asignatura debe tener "formato de pentesting". ¿Qué campos no pueden faltar por hallazgo?',
      options: [
        'Solo una descripción libre del problema.',
        'Hallazgo, criticidad, evidencia/escenario de explotación, activo afectado y mitigación; además, mapeo de los controles resultantes a ISO 27001 y 42001.',
        'El nombre del analista y la fecha, nada más.',
        'Un resumen ejecutivo de una línea sin detalle.',
      ],
      correctIndex: 1,
      explanations: [
        'Una descripción libre no permite priorizar ni actuar.',
        'Correcto: criticidad, evidencia, activo y mitigación por hallazgo, más el mapeo a controles, es el formato exigido.',
        'Metadatos sin contenido técnico no sirven.',
        'Un resumen sin detalle no es un informe de red team.',
      ],
    },
    {
      extKey: 'xi-app-11',
      skillTag: 'Manejo y procesamiento de datos',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'El "enriquecimiento" de eventos en un pipeline de seguridad consiste en:',
      options: [
        'Borrar los eventos poco importantes.',
        'Añadir a cada evento contexto adicional (geolocalización de una IP, reputación conocida, propietario del activo, si el usuario está de baja) para que la correlación y el triaje sean más rápidos y precisos.',
        'Comprimir los logs.',
        'Traducir los logs a otro idioma.',
      ],
      correctIndex: 1,
      explanations: [
        'No es filtrado.',
        'Correcto: enriquecer es agregar contexto útil a cada evento.',
        'No es compresión.',
        'No es traducción.',
      ],
    },
    {
      extKey: 'xi-app-12',
      skillTag: 'Principios y aplicaciones Big Data en la ciberseguridad',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La "fatiga de alertas" en un centro de operaciones de seguridad describe:',
      options: [
        'El cansancio de los servidores por exceso de tráfico.',
        'La desensibilización del equipo ante un volumen alto de alertas, muchas de ellas falsos positivos, que lleva a ignorar o cerrar alertas sin investigar, incluidas algunas reales.',
        'Un ataque de denegación de servicio.',
        'Un fallo del SIEM al arrancar.',
      ],
      correctIndex: 1,
      explanations: [
        'No es un problema de hardware.',
        'Correcto: es la pérdida de atención del equipo por saturación de alertas, con riesgo de pasar por alto las verdaderas.',
        'No es un ataque DoS.',
        'No es un fallo de arranque del sistema.',
      ],
    },
    { extKey: 'xi-app-13', skillTag: 'Introducción a la Inteligencia Artificial y aprendizaje automático', difficulty: 'media', cognitive: 'analisis',
      stem: 'Un atacante manipula ligeramente correos para que tu clasificador los marque como legítimos. ¿Qué tipo de ataque es y a qué letra de la triada CIA afecta?',
      options: ['Extracción del modelo; confidencialidad.', 'Ataque de evasión; afecta a la integridad, porque altera las decisiones del sistema sin tocar sus datos internos.', 'Denegación de servicio; disponibilidad.', 'Envenenamiento; disponibilidad.'],
      correctIndex: 1,
      explanations: ['La extracción robaría el modelo, no burlaría su decisión.', 'Correcto: la evasión con entradas manipuladas es un ataque a la integridad de la decisión.', 'No satura el servicio.', 'El envenenamiento contamina el entrenamiento, no la inferencia puntual.'] },
    { extKey: 'xi-app-14', skillTag: 'Introducción a la Inteligencia Artificial y aprendizaje automático', difficulty: 'baja', cognitive: 'comprension',
      stem: '"Seguridad de la IA" (frente a "seguridad mediante IA") se refiere a:',
      options: ['Usar IA para detectar amenazas.', 'Proteger los propios sistemas de IA de ataques: envenenamiento, evasión, extracción del modelo, inyección de prompt.', 'Cifrar la base de datos.', 'Formar a los empleados.'],
      correctIndex: 1,
      explanations: ['Eso es "seguridad mediante IA".', 'Correcto: la seguridad de la IA trata el modelo como activo a proteger.', 'El cifrado de la BD es un control general, no específico de IA.', 'La formación es un control, no la definición.'] },
    { extKey: 'xi-app-15', skillTag: 'Principios y aplicaciones Big Data en la ciberseguridad', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Un ataque real se ve así: login desde un país nuevo + acceso a un recurso sensible + tráfico saliente inusual, en 10 minutos. Ninguna fuente por sí sola lo delata. ¿Qué capacidad lo detecta?',
      options: ['Un antivirus en el endpoint.', 'La correlación de eventos entre fuentes (identidad + acceso + red): el patrón vive en la secuencia, no en un evento aislado.', 'Más retención de logs.', 'Un firewall más rápido.'],
      correctIndex: 1,
      explanations: ['El antivirus no ve el contexto de identidad y red.', 'Correcto: solo cruzando fuentes se reconstruye la secuencia del ataque.', 'La retención ayuda a investigar después, no a detectar en el momento.', 'La velocidad del firewall no correlaciona eventos.'] },
    { extKey: 'xi-app-16', skillTag: 'Principios y aplicaciones Big Data en la ciberseguridad', difficulty: 'media', cognitive: 'analisis',
      stem: 'Tu SOC recibe 4.000 alertas/día y puede investigar 250. Alguien propone subir la sensibilidad de todos los detectores. ¿Qué adviertes?',
      options: ['Que mejorará la detección.', 'Que agrava la fatiga de alertas: más alertas que capacidad lleva a cerrarlas en bloque sin investigar, incluidas algunas reales; hay que calibrar a la capacidad y priorizar por riesgo.', 'Que el equipo trabajará más rápido.', 'Que desaparecerán los falsos positivos.'],
      correctIndex: 1,
      explanations: ['Más alertas sin capacidad no mejora la detección efectiva.', 'Correcto: la fatiga de alertas es un fallo de proceso.', 'La capacidad del equipo no crece por decreto.', 'Subir sensibilidad aumenta los falsos positivos.'] },
    { extKey: 'xi-app-17', skillTag: 'Manejo y procesamiento de datos', difficulty: 'media', cognitive: 'comprension',
      stem: '¿Por qué es crítica la normalización de eventos en un SIEM?',
      options: ['Para reducir el tamaño de los logs.', 'Porque cada fuente usa formatos, nombres de campo y zonas horarias distintos; sin un esquema común no se pueden correlacionar eventos entre fuentes.', 'Para cifrar los datos.', 'Para acelerar el disco.'],
      correctIndex: 1,
      explanations: ['No es principalmente compresión.', 'Correcto: unificar formato y campos habilita la correlación.', 'No es cifrado.', 'No es una optimización de hardware.'] },
    { extKey: 'xi-app-18', skillTag: 'Manejo y procesamiento de datos', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Fijas la retención de logs de autenticación en 30 días por coste. Se descubre una intrusión que empezó hace 4 meses. ¿Qué principio se ignoró?',
      options: ['La velocidad de ingesta.', 'Diseñar la retención desde las preguntas de investigación futuras: las intrusiones se descubren tarde, así que la ventana debe cubrir ese retraso.', 'El cifrado en tránsito.', 'La normalización.'],
      correctIndex: 1,
      explanations: ['La ingesta funcionó.', 'Correcto: la retención se decide por cuánto hacia atrás necesitarás investigar.', 'El cifrado protege pero no retiene.', 'La normalización es otro asunto.'] },
    { extKey: 'xi-app-19', skillTag: 'Manejo y procesamiento de datos', difficulty: 'baja', cognitive: 'comprension',
      stem: 'La "cadena de custodia" de evidencia digital importa cuando:',
      options: ['Los logs ocupan mucho espacio.', 'La evidencia puede acabar en un proceso legal: hay que poder demostrar que no se alteró y saber quién la manejó.', 'Se usa la nube.', 'Hay más de una fuente de datos.'],
      correctIndex: 1,
      explanations: ['No es por el volumen.', 'Correcto: la cadena de custodia asegura la integridad y trazabilidad de manejo de la evidencia.', 'No depende de dónde se aloje.', 'No depende del número de fuentes.'] },
    { extKey: 'xi-app-20', skillTag: 'Modelos predictivos en ciberseguridad', difficulty: 'media', cognitive: 'comprension',
      stem: 'La detección de anomalías (no supervisada) frente a la clasificación de amenazas conocidas (supervisada):',
      options: ['Son intercambiables.', 'La primera cubre lo desconocido (aprende lo normal y marca lo raro) pero genera falsos positivos cuando lo normal cambia; la segunda es precisa con lo conocido pero ciega ante variantes nuevas. Se combinan.', 'La supervisada no necesita datos.', 'La no supervisada usa firmas.'],
      correctIndex: 1,
      explanations: ['No son intercambiables; se complementan.', 'Correcto: cada enfoque cubre una parte y se usan juntos.', 'La supervisada necesita datos etiquetados.', 'Las firmas son del enfoque de amenazas conocidas.'] },
    { extKey: 'xi-app-21', skillTag: 'Modelos predictivos en ciberseguridad', difficulty: 'alta', cognitive: 'analisis',
      stem: 'En tu detector, un falso negativo puede ser una brecha y un falso positivo son 20 minutos de un analista. ¿Cómo calibras el umbral?',
      options: ['Minimizar el error total tratando ambos por igual.', 'Favorecer la sensibilidad (menos falsos negativos) hasta el límite de falsos positivos que el equipo puede investigar, y documentar qué se hace con el resto.', 'Eliminar todas las alertas dudosas.', 'Umbral fijo en 0,5.'],
      correctIndex: 1,
      explanations: ['Los costes asimétricos hacen que "minimizar el error total" dé un umbral equivocado.', 'Correcto: priorizar no perder ataques, acotado por la capacidad de respuesta.', 'Eliminar lo dudoso aumenta los falsos negativos.', 'Un umbral fijo ignora la asimetría.'] },
    { extKey: 'xi-app-22', skillTag: 'Modelos predictivos en ciberseguridad', difficulty: 'media', cognitive: 'analisis',
      stem: '"Alerta: riesgo 0,89". ¿Por qué es una mala alerta para el analista?',
      options: ['El número es alto.', 'No es explicable: no dice qué señales la dispararon, qué activo ni qué usuario, así que el analista no puede triarla ni responder, y termina ignorándola.', 'Debería ser 0,90.', 'Falta el color rojo.'],
      correctIndex: 1,
      explanations: ['El valor por sí solo no es el problema.', 'Correcto: una alerta accionable indica señales, desviación, activo y usuario.', 'Un umbral distinto no la hace explicable.', 'El color no aporta contexto.'] },
    { extKey: 'xi-app-23', skillTag: 'Introducción a los modelos generativos en Inteligencia Artificial', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Tu organización tiene un asistente RAG interno. Desde seguridad, ¿cuál es un vector de ataque propio y su mitigación?',
      options: ['Que consuma mucha CPU; más servidores.', 'Inyección de prompt: una entrada o documento manipulado hace que el asistente ignore sus instrucciones o revele contexto sensible. Mitigación: aislar instrucciones de datos, validar el contexto recuperado, mínimo privilegio y registro de intentos.', 'Que el índice ocupe disco; comprimirlo.', 'Faltas de ortografía de los usuarios.'],
      correctIndex: 1,
      explanations: ['El consumo de CPU no es un ataque.', 'Correcto: la inyección de prompt es el vector propio de estos sistemas.', 'El tamaño del índice no es un vector.', 'La ortografía no compromete la seguridad.'] },
    { extKey: 'xi-app-24', skillTag: 'Introducción a los modelos generativos en Inteligencia Artificial', difficulty: 'media', cognitive: 'comprension',
      stem: 'El malware polimórfico asistido por IA refuerza el argumento de que la defensa no puede depender solo de:',
      options: ['La formación del personal.', 'Firmas estáticas: si el código cambia en cada infección, hay que combinar con detección de comportamiento y de anomalías.', 'Los cortafuegos.', 'La segmentación de red.'],
      correctIndex: 1,
      explanations: ['La formación es útil, pero el punto es la detección técnica.', 'Correcto: contra código que muta, se detecta lo que hace, no cómo se ve.', 'Los cortafuegos siguen siendo útiles.', 'La segmentación sigue siendo útil.'] },
    { extKey: 'xi-app-25', skillTag: 'Introducción a los modelos generativos en Inteligencia Artificial', difficulty: 'media', cognitive: 'analisis',
      stem: 'La formación anti-phishing de tu empresa se basa en "detectar faltas de ortografía y saludos genéricos". Con phishing generado por IA, ¿sigue bastando?',
      options: ['Sí, es lo esencial.', 'No: la IA produce correos personalizados y sin errores; la defensa debe apoyarse en verificación de canal (confirmación fuera de banda), controles de proceso y detección de patrones anómalos de solicitud.', 'Sí, si se actualiza cada año.', 'Solo para correos en inglés.'],
      correctIndex: 1,
      explanations: ['El phishing por IA elimina las pistas superficiales.', 'Correcto: hace falta defensa en profundidad y verificación fuera del canal.', 'Actualizarla no cambia que ya no hay errores que detectar.', 'Aplica en cualquier idioma.'] },
    { extKey: 'xi-app-26', skillTag: 'Retos y oportunidades de la Inteligencia Artificial en el contexto de la ciberseguridad', difficulty: 'media', cognitive: 'comprension',
      stem: 'La "carrera armamentista" entre atacantes y defensores implica que:',
      options: ['Con inversión suficiente se alcanza un estado seguro estable.', 'No hay estado final: cada mejora provoca adaptación del otro lado; la seguridad es un proceso continuo con inversión sostenida, no un proyecto que se cierra.', 'Los atacantes siempre ganan.', 'Los defensores siempre ganan.'],
      correctIndex: 1,
      explanations: ['No hay meta estable.', 'Correcto: la ventaja es siempre temporal.', 'No es determinista a favor del atacante.', 'Ni del defensor.'] },
    { extKey: 'xi-app-27', skillTag: 'Retos y oportunidades de la Inteligencia Artificial en el contexto de la ciberseguridad', difficulty: 'media', cognitive: 'analisis',
      stem: '"Nuestro detector no puede ser injusto porque protege a todos por igual". ¿Correcto?',
      options: ['Sí, la seguridad es neutral.', 'No: un detector puede generar más falsos positivos sobre ciertos usuarios o roles legítimos, sometiéndolos a más fricción y vigilancia; hay que medir la tasa de falsos positivos por subgrupo.', 'Sí, si no usa datos personales.', 'Solo si el modelo es supervisado.'],
      correctIndex: 1,
      explanations: ['La seguridad no es neutral por definición.', 'Correcto: la equidad aplica también a la detección; el impacto desigual de los falsos positivos es real.', 'No usar la variable directa no garantiza equidad.', 'Aplica sea supervisado o no.'] },
    { extKey: 'xi-app-28', skillTag: 'Retos y oportunidades de la Inteligencia Artificial en el contexto de la ciberseguridad', difficulty: 'alta', cognitive: 'analisis',
      stem: 'El proyecto integrador pide analizar un sistema real desde defensa y ataque. Un compañero entrega "una lista de cosas que podrían salir mal". ¿Qué le falta según el formato pedido?',
      options: ['Que sea más larga.', 'Formato de informe: cada hallazgo con criticidad, evidencia/escenario de explotación, activo afectado y una mitigación concreta, además del mapeo de controles a ISO 27001/42001.', 'Un resumen ejecutivo más corto.', 'Poner los hallazgos en orden alfabético.'],
      correctIndex: 1,
      explanations: ['La longitud no es el criterio.', 'Correcto: el entregable exige criticidad, evidencia, activo, mitigación y mapeo a controles.', 'El problema no es el resumen.', 'El orden alfabético no aporta.'] },
    { extKey: 'xi-app-29', skillTag: 'Modelos predictivos en ciberseguridad', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Un detector de anomalías de red empieza a disparar muchos falsos positivos tras un despliegue de infraestructura legítimo. ¿Qué falló y qué haces?',
      options: ['El modelo está roto; reemplazarlo.', 'La línea base de "lo normal" quedó obsoleta al cambiar la infraestructura; hay que reentrenar o recalibrar la línea base con el nuevo estado normal.', 'Bajar la sensibilidad a cero.', 'Ignorar todas las alertas una semana.'],
      correctIndex: 1,
      explanations: ['El modelo no está roto; su referencia de normalidad cambió.', 'Correcto: un cambio legítimo del entorno exige actualizar la línea base.', 'Sensibilidad a cero deja de detectar.', 'Ignorar alertas es peligroso.'] },
    { extKey: 'xi-app-30', skillTag: 'Introducción a la Inteligencia Artificial y aprendizaje automático', difficulty: 'media', cognitive: 'comprension',
      stem: 'Un atacante consigue introducir ejemplos falsos en el dataset con el que se reentrena tu detector cada mes. ¿Qué tipo de ataque y a qué letra de la triada afecta?',
      options: ['Evasión; disponibilidad.', 'Envenenamiento de datos; afecta a la integridad, porque corrompe las decisiones futuras del modelo.', 'Extracción; confidencialidad.', 'Denegación de servicio; disponibilidad.'],
      correctIndex: 1,
      explanations: ['La evasión manipula la entrada en inferencia, no el entrenamiento.', 'Correcto: contaminar el reentrenamiento es envenenamiento, un ataque a la integridad.', 'La extracción robaría el modelo.', 'No satura el servicio.'] },
  ],
};
