// Banco de ítems de aplicación — Asignatura VI: Machine Learning.
module.exports = {
  slug: 'bank-master-vi',
  title: 'Banco de ítems — Asignatura VI',
  scopeSlug: 'master-vi',
  questions: [
    {
      extKey: 'vi-app-01',
      skillTag: 'Introducción a Machine Learning',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un modelo de detección de una enfermedad rara (1 caso por cada 1000) reporta 99% de exactitud. ¿Por qué esa cifra puede ser un desastre?',
      options: [
        'Porque 99% es una exactitud baja.',
        'Porque un modelo que siempre dice "sano" ya acierta el 99,9%; la exactitud es engañosa con clases muy desbalanceadas y hay que mirar sensibilidad, precisión y el coste de cada tipo de error.',
        'Porque el modelo usa demasiadas variables.',
        'Porque el conjunto de prueba era pequeño.',
      ],
      correctIndex: 1,
      explanations: [
        '99% suena alto, pero el problema es que no dice nada útil aquí.',
        'Correcto: con un 0,1% de positivos, "siempre negativo" alcanza 99,9%; hay que evaluar por sensibilidad y coste de FN.',
        'El número de variables no explica esta paradoja.',
        'El tamaño del conjunto de prueba no es la causa del problema conceptual.',
      ],
    },
    {
      extKey: 'vi-app-02',
      skillTag: 'Aprendizaje Supervisado',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Vas a clasificar solicitudes en "aprobar / revisar / rechazar" con datos etiquetados históricos y necesitas poder explicar cada decisión a un auditor. Entre logística, kNN y un árbol, ¿cuál priorizas de partida y por qué?',
      options: [
        'kNN, porque no necesita entrenamiento.',
        'Un modelo interpretable por diseño (regresión logística o árbol poco profundo): la exigencia de explicar cada decisión a un auditor pesa más que un pequeño incremento de exactitud de un modelo opaco.',
        'Una red neuronal profunda siempre.',
        'kNN, porque es el más preciso en todos los casos.',
      ],
      correctIndex: 1,
      explanations: [
        'kNN es costoso en predicción y difícil de explicar caso a caso.',
        'Correcto: cuando la explicabilidad es un requisito duro, se empieza por modelos interpretables por diseño.',
        'Una red profunda agrava el problema de explicabilidad ante el auditor.',
        'kNN no es universalmente el más preciso; depende del problema.',
      ],
    },
    {
      extKey: 'vi-app-03',
      skillTag: 'Aprendizaje supervisado de regresión',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un modelo de regresión de tiempos de entrega tiene un R² de 0,85 pero se equivoca sistemáticamente por 40 minutos en los pedidos de fin de semana, que son los críticos para el negocio. ¿Qué conclusión sacas?',
      options: [
        'El modelo es bueno: R² de 0,85 es alto.',
        'Una métrica global agregada oculta un fallo en el segmento que más importa; hay que evaluar el error por segmento (fin de semana) y quizá modelar ese caso aparte.',
        'Hay que subir el R² a 0,99 sin más.',
        'El R² es la única métrica que importa.',
      ],
      correctIndex: 1,
      explanations: [
        'Un R² alto no garantiza rendimiento donde el negocio lo necesita.',
        'Correcto: el error hay que desglosarlo por segmento relevante, no solo mirar el agregado.',
        'Perseguir un R² mayor no ataca el sesgo sistemático en un segmento.',
        'El R² por sí solo no revela sesgos por segmento ni la escala del error en minutos.',
      ],
    },
    {
      extKey: 'vi-app-04',
      skillTag: 'Aprendizaje no supervisado',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Aplicas k-means para segmentar clientes con 60 variables y los grupos salen sin sentido. ¿Qué revisas primero?',
      options: [
        'El color del gráfico de dispersión.',
        'La maldición de la dimensionalidad y la escala: con 60 variables las distancias pierden significado; conviene escalar las variables y reducir dimensiones (p. ej. PCA) antes de agrupar.',
        'Aumentar k a 100.',
        'Cambiar a un lenguaje de programación distinto.',
      ],
      correctIndex: 1,
      explanations: [
        'El color no afecta al resultado del clustering.',
        'Correcto: en alta dimensión y sin escalar, las distancias se degradan; escalar y reducir dimensiones es el primer paso.',
        'Un k enorme fragmenta sin resolver el problema de fondo.',
        'El lenguaje no cambia la matemática del algoritmo.',
      ],
    },
    {
      extKey: 'vi-app-05',
      skillTag: 'Aprendizaje semi-supervisado y por Refuerzo',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'Tienes 500 ejemplos etiquetados y 50 000 sin etiquetar, y etiquetar es caro. ¿Qué familia de técnicas puede aprovechar los datos sin etiquetar?',
      options: [
        'Aprendizaje por refuerzo puro.',
        'Aprendizaje semi-supervisado (p. ej. self-training): usar el modelo entrenado con lo poco etiquetado para etiquetar lo más fiable del resto y reentrenar, con cuidado de no amplificar errores.',
        'Descartar los 50 000 sin etiquetar.',
        'Etiquetar los 50 000 a mano igualmente.',
      ],
      correctIndex: 1,
      explanations: [
        'El refuerzo requiere un entorno con recompensas, no es este caso.',
        'Correcto: el semi-supervisado explota los datos sin etiqueta cuando etiquetar es costoso.',
        'Descartarlos desaprovecha información útil.',
        'Etiquetar 50 000 a mano es justo lo que se quiere evitar por coste.',
      ],
    },
    {
      extKey: 'vi-app-06',
      skillTag: 'Interpretabilidad de Modelos',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Usas SHAP sobre un modelo de riesgo y descubres que la variable con mayor importancia es "días desde el último contacto con soporte", que en tu proceso solo se llena cuando ya hay un problema. ¿Qué implica?',
      options: [
        'Que el modelo es excelente: encontró la variable clave.',
        'Que probablemente hay fuga de datos: esa variable codifica información del propio resultado que se quiere predecir; hay que revisar cuándo se rellena respecto al momento de la predicción.',
        'Que hay que eliminar SHAP porque confunde.',
        'Que la variable debe multiplicarse por dos.',
      ],
      correctIndex: 1,
      explanations: [
        'Una importancia altísima de una variable sospechosa suele indicar fuga, no mérito.',
        'Correcto: la interpretabilidad sirve precisamente para detectar que el modelo se apoya en algo que no estará disponible al predecir.',
        'SHAP está haciendo su trabajo: revelar el problema.',
        'Escalar la variable no corrige la fuga temporal.',
      ],
    },
    {
      extKey: 'vi-app-07',
      skillTag: 'Aprendizaje Supervisado',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'En un problema de clasificación con clases 95%/5%, ¿qué métrica y qué ajuste conviene mirar antes de entrenar?',
      options: [
        'Solo la exactitud; sin ajustes.',
        'Precisión y exhaustividad (o F1) de la clase minoritaria, y decidir el umbral de decisión según el coste relativo de falsos positivos y negativos, no dejarlo en 0,5 por defecto.',
        'El tiempo de entrenamiento.',
        'El número de líneas del script.',
      ],
      correctIndex: 1,
      explanations: [
        'La exactitud es engañosa con ese desbalanceo.',
        'Correcto: se mira el rendimiento en la clase rara y se calibra el umbral según los costes del negocio.',
        'El tiempo de entrenamiento no informa sobre la calidad de las predicciones.',
        'La longitud del código es irrelevante.',
      ],
    },
    {
      extKey: 'vi-app-08',
      skillTag: 'Introducción a Machine Learning',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'El compromiso sesgo-varianza dice que, al aumentar la complejidad del modelo:',
      options: [
        'Siempre mejora tanto en entrenamiento como en datos nuevos.',
        'El error por sesgo tiende a bajar, pero el error por varianza tiende a subir; el objetivo es el punto donde el error total en datos no vistos es mínimo.',
        'Solo importa el error en entrenamiento.',
        'La varianza y el sesgo son lo mismo.',
      ],
      correctIndex: 1,
      explanations: [
        'Más complejidad mejora el entrenamiento pero puede empeorar la generalización.',
        'Correcto: es un compromiso; se busca minimizar el error de generalización, no el de entrenamiento.',
        'El error en entrenamiento por sí solo no predice el rendimiento real.',
        'Sesgo (error sistemático) y varianza (sensibilidad a los datos) son distintos.',
      ],
    },
    {
      extKey: 'vi-app-09',
      skillTag: 'Aprendizaje supervisado de regresión',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: '¿Qué efecto tiene la regularización L2 (ridge) sobre un modelo de regresión con muchas variables correlacionadas?',
      options: [
        'Elimina variables poniendo sus coeficientes exactamente a cero.',
        'Reduce la magnitud de los coeficientes de forma suave, repartiéndolos entre variables correlacionadas y reduciendo la varianza del modelo.',
        'Aumenta el sobreajuste.',
        'No tiene ningún efecto si hay correlación.',
      ],
      correctIndex: 1,
      explanations: [
        'Poner coeficientes exactamente a cero es más propio de L1 (lasso).',
        'Correcto: L2 encoge coeficientes de forma continua y estabiliza el modelo ante colinealidad.',
        'La regularización reduce, no aumenta, el sobreajuste.',
        'L2 es especialmente útil precisamente cuando hay variables correlacionadas.',
      ],
    },
    {
      extKey: 'vi-app-10',
      skillTag: 'Interpretabilidad de Modelos',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: '¿Cuál es la diferencia entre interpretabilidad "por diseño" y "post-hoc"?',
      options: [
        'No hay diferencia real.',
        'Por diseño: el modelo es inherentemente legible (regresión lineal, árbol pequeño). Post-hoc: se aplica una técnica externa (LIME, SHAP) para explicar un modelo opaco después de entrenarlo.',
        'Post-hoc significa antes de entrenar.',
        'Por diseño significa sin entrenamiento.',
      ],
      correctIndex: 1,
      explanations: [
        'Son enfoques claramente distintos.',
        'Correcto: uno es transparencia intrínseca; el otro, explicación aproximada añadida a posteriori.',
        'Post-hoc es después de entrenar, por definición.',
        'Un modelo interpretable por diseño también se entrena.',
      ],
    },
    {
      extKey: 'vi-app-11',
      skillTag: 'Aprendizaje no supervisado',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'PCA se usa principalmente para:',
      options: [
        'Etiquetar automáticamente los datos.',
        'Reducir la dimensionalidad proyectando los datos sobre las direcciones de mayor varianza, conservando la mayor parte de la información con menos variables.',
        'Aumentar el número de variables.',
        'Cifrar el conjunto de datos.',
      ],
      correctIndex: 1,
      explanations: [
        'PCA no genera etiquetas.',
        'Correcto: es una técnica de reducción de dimensionalidad basada en la varianza.',
        'PCA reduce, no aumenta, el número de dimensiones.',
        'No tiene relación con cifrado.',
      ],
    },
    {
      extKey: 'vi-app-12',
      skillTag: 'Aprendizaje semi-supervisado y por Refuerzo',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'En aprendizaje por refuerzo, el "dilema exploración-explotación" aparece cuando un agente de recomendación:',
      options: [
        'No tiene datos de ningún tipo.',
        'Debe decidir entre repetir la opción que hoy da mejor recompensa conocida (explotar) o probar opciones poco vistas que podrían ser mejores (explorar).',
        'Solo puede usar reglas fijas.',
        'Tiene demasiadas GPUs.',
      ],
      correctIndex: 1,
      explanations: [
        'El dilema aparece justamente porque hay datos y recompensas parciales.',
        'Correcto: es el equilibrio entre aprovechar lo conocido y descubrir algo potencialmente mejor.',
        'Con reglas fijas no hay aprendizaje ni dilema.',
        'El hardware no define este dilema conceptual.',
      ],
    },
    { extKey: 'vi-app-13', skillTag: 'Introducción a Machine Learning', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Quieres predecir la probabilidad de impago (0 a 1) y necesitas un número calibrado, no solo un sí/no. ¿Qué priorizas al elegir métrica?',
      options: ['Exactitud (accuracy).', 'Una métrica de calibración (p. ej. Brier score, curva de calibración) además de discriminación (AUC): que el 0,7 signifique de verdad un 70% de riesgo.', 'El tiempo de entrenamiento.', 'El número de variables.'],
      correctIndex: 1,
      explanations: ['La exactitud no evalúa si las probabilidades están bien calibradas.', 'Correcto: si necesitas una probabilidad interpretable, hay que medir la calibración.', 'El tiempo no informa de la calidad.', 'El número de variables no es una métrica.'] },
    { extKey: 'vi-app-14', skillTag: 'Introducción a Machine Learning', difficulty: 'baja', cognitive: 'comprension',
      stem: 'El descenso de gradiente, conceptualmente:',
      options: ['Prueba todas las combinaciones de parámetros.', 'Ajusta los parámetros dando pasos en la dirección que más reduce la función de pérdida, iterando hasta un mínimo.', 'Elimina variables poco útiles.', 'Cifra el modelo.'],
      correctIndex: 1,
      explanations: ['No es búsqueda exhaustiva.', 'Correcto: sigue la pendiente de la pérdida para minimizarla.', 'La selección de variables es otra cosa.', 'No es cifrado.'] },
    { extKey: 'vi-app-15', skillTag: 'Aprendizaje Supervisado', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Tu clasificación tiene clases 90/10 y el coste de un falso negativo (no detectar la clase rara) es alto. ¿Qué ajustas?',
      options: ['Dejar el umbral de decisión en 0,5.', 'Bajar el umbral para la clase rara y/o usar pesos de clase, priorizando recall, y evaluar con F1 o con precision-recall en vez de accuracy.', 'Eliminar la clase minoritaria.', 'Duplicar el modelo.'],
      correctIndex: 1,
      explanations: ['0,5 por defecto ignora el desbalanceo y el coste asimétrico.', 'Correcto: se ajusta el umbral/pesos y se evalúa con métricas adecuadas a la clase rara.', 'Eliminar la clase rara anula el objetivo.', 'Duplicar el modelo no cambia nada.'] },
    { extKey: 'vi-app-16', skillTag: 'Aprendizaje Supervisado', difficulty: 'media', cognitive: 'comprension',
      stem: 'La "frontera de decisión" de un modelo de clasificación es:',
      options: ['El número máximo de clases.', 'La superficie en el espacio de features que separa las regiones que el modelo asigna a cada clase.', 'El tiempo límite de entrenamiento.', 'El conjunto de prueba.'],
      correctIndex: 1,
      explanations: ['No es un conteo de clases.', 'Correcto: es dónde el modelo cambia su predicción de una clase a otra.', 'No es una restricción temporal.', 'No es el conjunto de prueba.'] },
    { extKey: 'vi-app-17', skillTag: 'Aprendizaje supervisado de regresión', difficulty: 'media', cognitive: 'analisis',
      stem: 'Tu modelo de regresión tiene RMSE bajo pero el MAE cuenta una historia distinta (peor). ¿Qué indica y qué revisas?',
      options: ['Que el modelo es perfecto.', 'Que hay errores grandes en pocos casos (outliers) que el RMSE penaliza menos de lo esperado o el MAE más; revisa la distribución de residuos y decide qué métrica refleja el coste real del negocio.', 'Que hay que subir el R².', 'Que faltan datos.'],
      correctIndex: 1,
      explanations: ['Una discrepancia RMSE/MAE señala estructura en los errores.', 'Correcto: RMSE y MAE penalizan distinto los errores grandes; elegir según el coste real.', 'El R² no resuelve la discrepancia.', 'No es necesariamente falta de datos.'] },
    { extKey: 'vi-app-18', skillTag: 'Aprendizaje supervisado de regresión', difficulty: 'baja', cognitive: 'comprension',
      stem: 'La regularización L1 (lasso) frente a L2 (ridge):',
      options: ['No hay diferencia.', 'L1 tiende a llevar coeficientes exactamente a cero (selección de variables); L2 los encoge de forma suave sin anularlos.', 'L1 aumenta el sobreajuste.', 'L2 solo funciona con una variable.'],
      correctIndex: 1,
      explanations: ['Sí hay diferencia práctica.', 'Correcto: L1 hace selección, L2 estabiliza.', 'La regularización reduce el sobreajuste.', 'L2 es útil justamente con muchas variables.'] },
    { extKey: 'vi-app-19', skillTag: 'Aprendizaje no supervisado', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Aplicas k-means y el "codo" del gráfico de inercia no es claro. ¿Qué haces?',
      options: ['Elegir k al azar.', 'Complementar con silueta, estabilidad de los grupos ante remuestreo y, sobre todo, con el criterio de negocio: cuántos segmentos son accionables.', 'Poner k igual al número de filas.', 'Abandonar el clustering.'],
      correctIndex: 1,
      explanations: ['Elegir k al azar no es defendible.', 'Correcto: se combinan métricas internas con el criterio de accionabilidad.', 'k = nº de filas no segmenta nada.', 'El clustering sí sirve; solo hay que elegir k con criterio.'] },
    { extKey: 'vi-app-20', skillTag: 'Aprendizaje no supervisado', difficulty: 'media', cognitive: 'comprension',
      stem: 'La "maldición de la dimensionalidad" afecta a k-means porque:',
      options: ['El algoritmo es lento.', 'En muchas dimensiones las distancias entre puntos se vuelven parecidas entre sí, y k-means depende de esas distancias para formar grupos.', 'k-means no usa distancias.', 'Solo afecta a datos de texto.'],
      correctIndex: 1,
      explanations: ['No es solo cuestión de velocidad.', 'Correcto: en alta dimensión las distancias pierden poder discriminante.', 'k-means se basa en distancias.', 'Afecta a cualquier dato de alta dimensión.'] },
    { extKey: 'vi-app-21', skillTag: 'Aprendizaje semi-supervisado y por Refuerzo', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Tienes 300 ejemplos etiquetados y 40.000 sin etiquetar; etiquetar cuesta mucho. Aplicas self-training. ¿Qué cuidado es clave?',
      options: ['Ninguno, cuantos más pseudo-etiquetados mejor.', 'Añadir solo las predicciones de mayor confianza y vigilar que el modelo no amplifique sus propios errores al reentrenar con ellas.', 'Etiquetar los 40.000 a mano.', 'Descartar los 300 reales.'],
      correctIndex: 1,
      explanations: ['Añadir todo, incluidas predicciones dudosas, propaga errores.', 'Correcto: el riesgo del self-training es reforzar los sesgos del propio modelo.', 'Etiquetar todo a mano es lo que se quiere evitar.', 'Los 300 reales son el ancla; no se descartan.'] },
    { extKey: 'vi-app-22', skillTag: 'Aprendizaje semi-supervisado y por Refuerzo', difficulty: 'baja', cognitive: 'comprension',
      stem: 'Un proceso de decisión de Markov (MDP) modela:',
      options: ['Una única decisión sin consecuencias.', 'Una secuencia de estados, acciones y recompensas donde la mejor acción depende del estado actual, base del aprendizaje por refuerzo.', 'Un problema de clustering.', 'Una regresión lineal.'],
      correctIndex: 1,
      explanations: ['El MDP es sobre decisiones secuenciales.', 'Correcto: estados, acciones y recompensas es el marco del refuerzo.', 'No es clustering.', 'No es regresión.'] },
    { extKey: 'vi-app-23', skillTag: 'Interpretabilidad de Modelos', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Un regulador te pide "explicar" un modelo de scoring. Entregas un informe de importancia global de variables. ¿Es suficiente?',
      options: ['Sí, con eso basta.', 'No del todo: la importancia global describe el modelo, pero el regulador y las personas afectadas suelen necesitar explicaciones locales (por qué esta decisión concreta), p. ej. con SHAP.', 'Sí, si el modelo es lineal.', 'La explicabilidad no es exigible.'],
      correctIndex: 1,
      explanations: ['La importancia global no explica decisiones individuales.', 'Correcto: hace falta explicación local para responder por casos concretos.', 'Incluso lineal, la explicación por caso ayuda.', 'La explicabilidad sí es exigible en usos regulados.'] },
    { extKey: 'vi-app-24', skillTag: 'Interpretabilidad de Modelos', difficulty: 'media', cognitive: 'comprension',
      stem: 'LIME y SHAP son ejemplos de interpretabilidad:',
      options: ['Por diseño.', 'Post-hoc: se aplican a un modelo ya entrenado (a menudo opaco) para aproximar por qué produjo una salida.', 'De entrenamiento.', 'De despliegue.'],
      correctIndex: 1,
      explanations: ['Por diseño sería un modelo inherentemente legible.', 'Correcto: son técnicas post-hoc.', 'No son parte del entrenamiento.', 'No son de despliegue.'] },
    { extKey: 'vi-app-25', skillTag: 'Introducción a Machine Learning', difficulty: 'alta', cognitive: 'analisis',
      stem: 'Un compañero justifica usar accuracy diciendo "es la métrica estándar". El problema tiene 97% de una clase. ¿Cómo lo corriges?',
      options: ['Tiene razón, accuracy es estándar.', 'Con 97% de una clase, predecir siempre esa clase da 97% de accuracy sin aprender nada; hay que usar métricas que reflejen el rendimiento en la clase minoritaria y el coste de los errores.', 'Subir la accuracy a 99%.', 'Cambiar de dataset.'],
      correctIndex: 1,
      explanations: ['"Estándar" no significa adecuada.', 'Correcto: con ese desbalanceo la accuracy es engañosa.', 'Perseguir accuracy mayor no ataca el problema.', 'El dataset refleja la realidad; el problema es la métrica.'] },
    { extKey: 'vi-app-26', skillTag: 'Aprendizaje Supervisado', difficulty: 'media', cognitive: 'analisis',
      stem: 'Tu modelo tiene precisión alta y recall bajo en la clase positiva. Para el negocio, no detectar un positivo es muy caro. ¿Qué ajustas?',
      options: ['Nada, la precisión es alta.', 'Bajar el umbral de decisión para capturar más positivos (sube recall), aceptando algo más de falsos positivos, y revisar el equilibrio con el coste real de cada error.', 'Subir el umbral.', 'Quitar la clase positiva.'],
      correctIndex: 1,
      explanations: ['Precisión alta con recall bajo significa que se te escapan muchos positivos.', 'Correcto: si el falso negativo es caro, se prioriza recall bajando el umbral.', 'Subir el umbral reduce aún más el recall.', 'No tiene sentido quitar la clase de interés.'] },
    { extKey: 'vi-app-27', skillTag: 'Aprendizaje supervisado de regresión', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Añades un término polinómico de grado 8 y el error de entrenamiento baja casi a cero, pero el de validación se dispara. ¿Qué haces?',
      options: ['Subir a grado 16.', 'Reducir el grado o regularizar: es sobreajuste; el modelo memoriza el entrenamiento y no generaliza.', 'Nada, grado 8 es normal.', 'Eliminar la validación.'],
      correctIndex: 1,
      explanations: ['Más grado empeora el sobreajuste.', 'Correcto: bajar complejidad o regularizar.', 'La brecha entrenamiento-validación indica un problema.', 'La validación es la que revela el problema.'] },
    { extKey: 'vi-app-28', skillTag: 'Aprendizaje no supervisado', difficulty: 'baja', cognitive: 'comprension',
      stem: 'El objetivo de PCA es:',
      options: ['Clasificar automáticamente.', 'Reducir dimensiones proyectando sobre las direcciones de mayor varianza, conservando la mayor parte de la información con menos variables.', 'Aumentar el número de variables.', 'Etiquetar los datos.'],
      correctIndex: 1,
      explanations: ['PCA no clasifica.', 'Correcto: es reducción de dimensionalidad por varianza.', 'Reduce, no aumenta.', 'No genera etiquetas.'] },
    { extKey: 'vi-app-29', skillTag: 'Aprendizaje semi-supervisado y por Refuerzo', difficulty: 'media', cognitive: 'analisis',
      stem: 'Un sistema de recomendación por refuerzo siempre muestra la opción con mejor recompensa histórica y nunca prueba otras. ¿Qué le falta y por qué importa?',
      options: ['Más recompensa.', 'Exploración: sin probar opciones poco vistas, el sistema puede quedarse atascado en un óptimo local y no descubrir alternativas mejores.', 'Menos datos.', 'Un modelo más grande.'],
      correctIndex: 1,
      explanations: ['El problema no es la magnitud de la recompensa.', 'Correcto: sin exploración no se descubren mejores opciones (dilema exploración-explotación).', 'Menos datos no ayuda.', 'El tamaño no resuelve la falta de exploración.'] },
    { extKey: 'vi-app-30', skillTag: 'Interpretabilidad de Modelos', difficulty: 'alta', cognitive: 'analisis',
      stem: 'SHAP indica que la variable con mayor impacto en tu modelo de rotación de personal es "ha solicitado carta de recomendación". ¿Qué sospechas?',
      options: ['Que el modelo es excelente.', 'Fuga de datos: solicitar una carta suele ser posterior a la decisión de irse; la variable filtra el resultado que quieres predecir. Revisar el corte temporal.', 'Que hay que darle más peso.', 'Que SHAP se equivoca.'],
      correctIndex: 1,
      explanations: ['Una variable tan cercana al resultado es sospechosa, no un mérito.', 'Correcto: la interpretabilidad acaba de revelar una probable fuga temporal.', 'Darle más peso empeora la fuga.', 'SHAP está haciendo su trabajo: mostrar el problema.'] },
  ],
};
