// Banco de ítems de aplicación — Asignatura VIII: Design Thinking.
module.exports = {
  slug: 'bank-master-viii',
  title: 'Banco de ítems — Asignatura VIII',
  scopeSlug: 'master-viii',
  questions: [
    {
      extKey: 'viii-app-01',
      skillTag: 'Fases de empatía y definición de problemas',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un equipo hace entrevistas de empatía y su declaración de problema final es idéntica a la que escribieron antes de empezar. ¿Qué probablemente ocurrió?',
      options: [
        'Que el equipo acertó el problema a la primera; nada que revisar.',
        'Que la investigación fue superficial o sesgada hacia confirmar la idea previa: una empatía real casi siempre reencuadra el problema.',
        'Que las entrevistas fueron demasiado largas.',
        'Que faltó un prototipo.',
      ],
      correctIndex: 1,
      explanations: [
        'Que el problema no cambie es una señal de alarma, no de acierto.',
        'Correcto: si nada cambió tras investigar, probablemente se buscó confirmar en vez de descubrir.',
        'La duración no explica la falta de reencuadre.',
        'El prototipo es una fase posterior; no es la causa aquí.',
      ],
    },
    {
      extKey: 'viii-app-02',
      skillTag: 'Fundamentos de Design Thinking',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'El "sesgo de solución prematura" en Design Thinking es:',
      options: [
        'Elegir la solución más cara.',
        'Saltar a diseñar una solución antes de haber entendido bien el problema y a las personas afectadas, quedándose atado a esa primera idea.',
        'Probar demasiadas soluciones.',
        'No documentar el proceso.',
      ],
      correctIndex: 1,
      explanations: [
        'No es una cuestión de coste.',
        'Correcto: es el impulso de resolver antes de comprender, que Design Thinking combate con las fases de empatía y definición.',
        'Explorar varias ideas es deseable, no un sesgo.',
        'La falta de documentación es otro problema.',
      ],
    },
    {
      extKey: 'viii-app-03',
      skillTag: 'Fases de empatía y definición de problemas',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'En una entrevista de empatía, un usuario dice "necesito un informe más rápido". ¿Qué haces con esa afirmación?',
      options: [
        'Anotar "hacer el informe más rápido" como el problema y pasar a idear.',
        'Indagar el porqué: qué decisión toma con ese informe, qué hace mientras espera, qué pasó la última vez que llegó tarde; el "quiero X" esconde una necesidad más profunda.',
        'Descartar el comentario por poco técnico.',
        'Prometer que se hará en la mitad de tiempo.',
      ],
      correctIndex: 1,
      explanations: [
        'Tomar la petición literal salta la fase de comprensión.',
        'Correcto: la empatía busca la necesidad detrás de la solución que el usuario propone.',
        'El comentario del usuario es materia prima valiosa.',
        'Prometer sin entender el problema arriesga resolver lo equivocado.',
      ],
    },
    {
      extKey: 'viii-app-04',
      skillTag: 'Técnicas de ideación para soluciones innovadoras',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Tu sesión de ideación produce ocho ideas, pero todas son variantes de "añadir un botón". ¿Qué falló y cómo lo corriges?',
      options: [
        'Nada: ocho ideas es suficiente.',
        'Faltó divergencia real: se convergió demasiado pronto. Corregir con técnicas que fuercen perspectivas distintas (SCAMPER, "¿cómo lo haría otro sector?", peor idea posible) antes de filtrar.',
        'Había demasiada gente en la sala.',
        'La sesión fue demasiado corta.',
      ],
      correctIndex: 1,
      explanations: [
        'La cantidad no compensa la falta de variedad.',
        'Correcto: la ideación necesita divergencia genuina antes de converger; hay técnicas para provocarla.',
        'El número de participantes no es la causa directa.',
        'Alargar la sesión sin cambiar el método daría más variantes del botón.',
      ],
    },
    {
      extKey: 'viii-app-05',
      skillTag: 'Prototipado rápido y validación inicial',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Antes de validar la idea de un nuevo flujo de aprobación, el equipo construye una versión funcional pulida durante tres semanas. ¿Qué error de prototipado cometieron?',
      options: [
        'Ninguno: un prototipo debe ser funcional y pulido.',
        'Fidelidad desproporcionada a la pregunta: para saber si el flujo tiene sentido bastaba un prototipo de papel o clicable en un día; tres semanas de código antes de validar es riesgo innecesario.',
        'El prototipo era demasiado sencillo.',
        'Debieron saltarse el prototipo y lanzar directamente.',
      ],
      correctIndex: 1,
      explanations: [
        'El prototipo debe tener la fidelidad justa para responder la pregunta, no ser un producto.',
        'Correcto: sobre-invertir en fidelidad antes de validar es el error clásico.',
        'El problema es lo contrario: demasiada fidelidad, no muy poca.',
        'Lanzar sin validar es aún más arriesgado.',
      ],
    },
    {
      extKey: 'viii-app-06',
      skillTag: 'Prototipado rápido y validación inicial',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'Un prototipo "Mago de Oz" consiste en:',
      options: [
        'Un prototipo con muchos efectos visuales.',
        'Simular que una función automática existe cuando en realidad una persona ejecuta la tarea entre bastidores, para probar la experiencia sin construir la tecnología todavía.',
        'Un prototipo hecho solo con inteligencia artificial.',
        'Una maqueta impresa en 3D.',
      ],
      correctIndex: 1,
      explanations: [
        'No se trata de efectos visuales.',
        'Correcto: el usuario cree que interactúa con un sistema automático; detrás hay una persona.',
        'No implica necesariamente IA.',
        'No es una técnica de impresión física.',
      ],
    },
    {
      extKey: 'viii-app-07',
      skillTag: 'Iteración y mejoras continuas del prototipo',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Tras la primera prueba, tres usuarios dicen que no les gusta el color y uno no logra completar la tarea principal. ¿En qué te centras para iterar?',
      options: [
        'En el color, porque lo mencionaron tres personas.',
        'En que la tarea principal no se pudo completar: es un fallo de fondo (evidencia de comportamiento), más grave que una preferencia estética (opinión).',
        'En añadir más funciones.',
        'En repetir exactamente la misma prueba sin cambios.',
      ],
      correctIndex: 1,
      explanations: [
        'El color es una preferencia; que la tarea falle es un problema de utilidad.',
        'Correcto: se prioriza el cambio dirigido por evidencia de comportamiento sobre las preferencias declaradas.',
        'Añadir funciones no arregla el fallo de la tarea central.',
        'Repetir sin cambios no genera aprendizaje nuevo.',
      ],
    },
    {
      extKey: 'viii-app-08',
      skillTag: 'Iteración y mejoras continuas del prototipo',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: '"Pivotar" frente a "pulir" un prototipo significa:',
      options: [
        'Lo mismo con distinta palabra.',
        'Pulir: mejorar la ejecución de la misma idea. Pivotar: cambiar un supuesto central (el problema, el segmento, el mecanismo) porque la evidencia dice que la dirección actual no funciona.',
        'Pivotar es abandonar el proyecto.',
        'Pulir es empezar de cero.',
      ],
      correctIndex: 1,
      explanations: [
        'Son decisiones distintas ante la evidencia.',
        'Correcto: pulir es refinar; pivotar es cambiar un supuesto de fondo manteniendo lo aprendido.',
        'Pivotar no es abandonar, es cambiar de rumbo con lo aprendido.',
        'Pulir es lo contrario de empezar de cero.',
      ],
    },
    {
      extKey: 'viii-app-09',
      skillTag: 'Pruebas con usuarios y retroalimentación',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Al hacer pruebas de usuario, el facilitador pregunta "¿verdad que esto es más fácil que antes?". ¿Qué sesgo introduce y cómo lo evita?',
      options: [
        'Sesgo de confirmación del usuario; se evita repitiendo la pregunta.',
        'Sesgo de cortesía / pregunta dirigida: el usuario tiende a estar de acuerdo. Se evita con tareas concretas ("completa este trámite") y observando qué hace, con preguntas abiertas y neutrales.',
        'Ningún sesgo: es una pregunta válida.',
        'Sesgo de novedad; se evita usando un prototipo antiguo.',
      ],
      correctIndex: 1,
      explanations: [
        'El problema es cómo se formula la pregunta, no repetirla.',
        'Correcto: las preguntas dirigidas inducen acuerdo; se sustituyen por tareas y observación del comportamiento.',
        'La pregunta condiciona la respuesta: no es neutral.',
        'El sesgo de cortesía es el dominante aquí, no el de novedad.',
      ],
    },
    {
      extKey: 'viii-app-10',
      skillTag: 'Pruebas con usuarios y retroalimentación',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: '¿Por qué se dice que con unos cinco usuarios se detecta la mayoría de los problemas graves de usabilidad?',
      options: [
        'Porque cinco es un número mágico sin fundamento.',
        'Porque los problemas más severos son frecuentes y los primeros usuarios ya los revelan; añadir más participantes tiene rendimientos decrecientes para encontrar problemas nuevos.',
        'Porque más de cinco usuarios es ilegal.',
        'Porque cinco usuarios equivalen a mil por estadística.',
      ],
      correctIndex: 1,
      explanations: [
        'Tiene fundamento empírico en la frecuencia de los problemas graves.',
        'Correcto: los problemas severos se repiten y saturan pronto; el descubrimiento marginal cae rápido.',
        'No hay ninguna restricción legal.',
        'No es una equivalencia estadística; es sobre detección de problemas cualitativos.',
      ],
    },
    {
      extKey: 'viii-app-11',
      skillTag: 'Técnicas de ideación para soluciones innovadoras',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La formulación "¿Cómo podríamos…?" (HMW) se usa para:',
      options: [
        'Cerrar el problema con una única solución.',
        'Reformular un hallazgo de la investigación como un desafío abierto y accionable que invite a generar muchas soluciones, sin ser tan amplio que no oriente.',
        'Asignar tareas al equipo.',
        'Calcular el presupuesto.',
      ],
      correctIndex: 1,
      explanations: [
        'HMW abre el espacio de soluciones, no lo cierra.',
        'Correcto: convierte un insight en un reto de ideación con el nivel de amplitud adecuado.',
        'No es una herramienta de asignación de tareas.',
        'No tiene relación con presupuesto.',
      ],
    },
    {
      extKey: 'viii-app-12',
      skillTag: 'Fundamentos de Design Thinking',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Design Thinking se describe como "no lineal". ¿Qué significa en la práctica?',
      options: [
        'Que no tiene fases.',
        'Que se puede volver a una fase anterior cuando lo aprendido lo justifica (p. ej. volver a empatía tras una prueba de usuario), en vez de recorrer las fases una sola vez en orden fijo.',
        'Que el orden de las fases es aleatorio siempre.',
        'Que se hace todo a la vez.',
      ],
      correctIndex: 1,
      explanations: [
        'Sí tiene fases; lo que no es fijo es recorrerlas una sola vez.',
        'Correcto: es iterativo; se retrocede a fases previas según lo que se descubre.',
        'No es aleatorio; hay una progresión general con retornos justificados.',
        'No implica hacerlo todo simultáneamente.',
      ],
    },
  ],
};
