// Banco de ítems de aplicación — Asignatura IX: IA Generativa en la Industria 4.0.
module.exports = {
  slug: 'bank-master-ix',
  title: 'Banco de ítems — Asignatura IX',
  scopeSlug: 'master-ix',
  questions: [
    {
      extKey: 'ix-app-01',
      skillTag: 'Modelos Generativos',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Necesitas generar imágenes sintéticas de defectos de fabricación para entrenar un inspector visual. Tienes poco tiempo de cómputo para inferencia en línea y necesitas variedad realista. Entre GAN, VAE y difusión, ¿cuál es el criterio de elección correcto?',
      options: [
        'Elegir difusión porque es lo más reciente.',
        'Contrapesar calidad/variedad frente a coste y estabilidad: difusión da alta calidad pero inferencia costosa; GAN es rápida en inferencia pero su entrenamiento es inestable y puede colapsar a pocas variantes; VAE es estable pero suele generar muestras más borrosas. Se elige según qué restricción es dura.',
        'Elegir siempre GAN porque genera rápido.',
        'No usar modelos generativos: pintar los defectos a mano.',
      ],
      correctIndex: 1,
      explanations: [
        'La novedad no es un criterio de ingeniería.',
        'Correcto: la elección se justifica por el trade-off estabilidad de entrenamiento / coste de inferencia / calidad, según la restricción dura del caso.',
        'La rapidez de inferencia de GAN no compensa si su entrenamiento colapsa la variedad.',
        'Pintar a mano no da el volumen ni la variedad que el modelo necesita.',
      ],
    },
    {
      extKey: 'ix-app-02',
      skillTag: 'Conceptos básicos de IA Generativa',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'En la Industria 4.0, un "gemelo digital" alimentado por IA generativa se usa principalmente para:',
      options: [
        'Sustituir físicamente la máquina.',
        'Simular el comportamiento de un activo o proceso real para probar escenarios, anticipar fallos o generar datos que serían caros o peligrosos de obtener en la planta.',
        'Almacenar los manuales en PDF.',
        'Controlar el acceso de los empleados.',
      ],
      correctIndex: 1,
      explanations: [
        'El gemelo digital acompaña al activo físico, no lo reemplaza.',
        'Correcto: es una réplica virtual para simular, anticipar y generar datos.',
        'No es un repositorio documental.',
        'No es un sistema de control de accesos.',
      ],
    },
    {
      extKey: 'ix-app-03',
      skillTag: 'Redes Neuronales Generativas',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'El "colapso de modo" (mode collapse) en una GAN se manifiesta como:',
      options: [
        'El modelo tarda demasiado en entrenar.',
        'El generador aprende a producir solo unas pocas variantes que engañan al discriminador, perdiendo diversidad respecto a los datos reales.',
        'El discriminador deja de funcionar.',
        'La imagen sale con la resolución equivocada.',
      ],
      correctIndex: 1,
      explanations: [
        'No es un problema de tiempo de entrenamiento.',
        'Correcto: el generador se atasca en pocas salidas y no cubre la variedad real.',
        'El discriminador sigue activo; el problema es la falta de diversidad del generador.',
        'La resolución es otra cuestión.',
      ],
    },
    {
      extKey: 'ix-app-04',
      skillTag: 'Paradigmas de ML en la IA Generativa',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La "autosupervisión" (self-supervised) que subyace a los grandes modelos generativos consiste en:',
      options: [
        'Etiquetar los datos manualmente antes de entrenar.',
        'Crear una tarea de pretexto a partir de los propios datos sin etiquetas (p. ej. predecir la siguiente palabra o reconstruir una parte oculta), de modo que el modelo aprende estructura del lenguaje o de la imagen.',
        'Entrenar sin datos.',
        'Copiar los pesos de otro modelo.',
      ],
      correctIndex: 1,
      explanations: [
        'Justamente evita el etiquetado manual masivo.',
        'Correcto: la señal de aprendizaje se construye a partir de los datos mismos mediante una tarea de pretexto.',
        'Sí usa datos, muchos; lo que no usa son etiquetas humanas.',
        'No es transferencia de pesos.',
      ],
    },
    {
      extKey: 'ix-app-05',
      skillTag: 'IA Generativa para contenido Multimedia y multimodal',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Vas a especificar un sistema RAG sobre la documentación técnica interna. ¿Qué métricas separan un buen diseño de una demo?',
      options: [
        'Solo el tiempo de respuesta.',
        'Precisión de recuperación (¿trae los fragmentos correctos?) separada de la calidad de generación (¿la respuesta usa bien esos fragmentos?), más tasa de alucinación medida sobre casos conocidos y coste por consulta.',
        'El número de documentos indexados.',
        'El tamaño del modelo de lenguaje.',
      ],
      correctIndex: 1,
      explanations: [
        'El tiempo de respuesta no dice si la respuesta es correcta.',
        'Correcto: hay que medir recuperación y generación por separado, más alucinación y coste.',
        'Indexar muchos documentos no garantiza recuperar el correcto.',
        'Un modelo grande no compensa una recuperación mala.',
      ],
    },
    {
      extKey: 'ix-app-06',
      skillTag: 'IA Generativa para contenido Multimedia y multimodal',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Tu sistema RAG da una respuesta incorrecta. Antes de tocar el prompt, ¿cómo diagnosticas en qué etapa falló?',
      options: [
        'Reescribir el prompt directamente y ver si mejora.',
        'Inspeccionar los fragmentos recuperados: si no contienen la información, el fallo es de recuperación (índice, chunking, consulta); si sí la contienen pero la respuesta la ignora o la tergiversa, el fallo es de generación o de cómo se pasa el contexto.',
        'Cambiar de modelo de lenguaje sin más análisis.',
        'Aumentar el número de fragmentos recuperados a 50.',
      ],
      correctIndex: 1,
      explanations: [
        'Tocar el prompt a ciegas no localiza la causa.',
        'Correcto: revisar los fragmentos recuperados separa el fallo de recuperación del de generación.',
        'Cambiar de modelo sin diagnóstico es prueba y error costosa.',
        'Recuperar 50 fragmentos puede empeorar la señal-ruido del contexto.',
      ],
    },
    {
      extKey: 'ix-app-07',
      skillTag: 'Conceptos básicos de IA Generativa',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un piloto de IA generativa funciona bien con 20 documentos de prueba. ¿Qué NO puedes concluir todavía para pasar a producción?',
      options: [
        'Que la idea tiene potencial.',
        'Que el coste por consulta, la latencia bajo carga, la tasa de alucinación con el corpus completo y el mantenimiento del índice serán aceptables a escala real.',
        'Que el equipo entendió el problema.',
        'Que hay un caso de uso.',
      ],
      correctIndex: 1,
      explanations: [
        'El potencial sí se puede intuir de un piloto.',
        'Correcto: coste a escala, latencia bajo carga, alucinación con corpus real y mantenimiento son lo que un piloto pequeño no demuestra.',
        'La comprensión del problema no depende del tamaño del piloto.',
        'La existencia del caso de uso ya está establecida.',
      ],
    },
    {
      extKey: 'ix-app-08',
      skillTag: 'Redes Neuronales Generativas',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'En un VAE, ¿qué papel juega el "espacio latente"?',
      options: [
        'Almacena las imágenes originales sin comprimir.',
        'Es una representación comprimida y continua de los datos desde la que el decodificador puede generar nuevas muestras interpolando entre puntos.',
        'Es la capa de salida final.',
        'Es donde se guardan las etiquetas.',
      ],
      correctIndex: 1,
      explanations: [
        'No guarda las imágenes en crudo.',
        'Correcto: el espacio latente es una representación comprimida y continua desde la que se generan muestras.',
        'La salida es lo que produce el decodificador a partir del latente.',
        'Un VAE típico no usa etiquetas.',
      ],
    },
    {
      extKey: 'ix-app-09',
      skillTag: 'Modelos Generativos',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un modelo de difusión produce mejores resultados que una GAN para tu caso, pero cada imagen tarda 6 segundos frente a 0,1 s. El sistema debe generar 10 000 imágenes al día en lotes nocturnos. ¿Qué eliges?',
      options: [
        'La GAN, siempre que sea más rápida.',
        'La difusión: como la generación es nocturna por lotes, el coste de 6 s por imagen es asumible (≈17 h para 10 000, ajustable con paralelismo) y se prioriza la calidad y estabilidad.',
        'Ninguno: no se puede.',
        'Generar solo 100 imágenes en vez de 10 000.',
      ],
      correctIndex: 1,
      explanations: [
        'La velocidad de la GAN no compensa si la latencia no es una restricción real (lotes nocturnos).',
        'Correcto: sin presión de latencia, se elige por calidad/estabilidad y se resuelve el volumen con paralelismo.',
        'Sí se puede: es un problema de planificación de cómputo.',
        'Reducir el volumen cambia el requisito en vez de resolverlo.',
      ],
    },
    {
      extKey: 'ix-app-10',
      skillTag: 'Tendencias y dirección futura de la IA Generativa',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'La lección sobre tendencias se declara "sujeta a cambio". Al aplicarla en un proyecto real, ¿qué actitud es la correcta?',
      options: [
        'Citar las tendencias de la lección como estado actual del arte.',
        'Usar el marco de análisis (qué madura, qué falta, qué depende de qué) pero verificar el estado concreto de modelos, costes y capacidades en el momento de decidir.',
        'Ignorar las tendencias por poco fiables.',
        'Asumir que nada ha cambiado desde que se escribió la lección.',
      ],
      correctIndex: 1,
      explanations: [
        'Las tendencias concretas envejecen rápido.',
        'Correcto: el valor duradero es el marco de análisis; los datos concretos se verifican al decidir.',
        'El marco de análisis sigue siendo útil aunque los datos cambien.',
        'En IA generativa el ritmo de cambio es alto; asumir lo contrario es arriesgado.',
      ],
    },
    {
      extKey: 'ix-app-11',
      skillTag: 'Paradigmas de ML en la IA Generativa',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'El "mantenimiento predictivo" con datos de sensores (p. ej. estimar la vida útil restante de un componente) es principalmente un problema de:',
      options: [
        'Generación de texto.',
        'Regresión / series temporales sobre señales de sensores: predecir un valor (tiempo o ciclos hasta el fallo) a partir del histórico de degradación.',
        'Clasificación de imágenes.',
        'Clustering de clientes.',
      ],
      correctIndex: 1,
      explanations: [
        'No se genera texto.',
        'Correcto: estimar la vida útil restante es regresión sobre series de sensores.',
        'No intervienen imágenes.',
        'No es segmentación de clientes.',
      ],
    },
    {
      extKey: 'ix-app-12',
      skillTag: 'IA Generativa para contenido Multimedia y multimodal',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'En la especificación de una app de IA generativa industrial, ¿dónde debe situarse explícitamente la revisión humana?',
      options: [
        'Al final, revisando una muestra del año.',
        'Antes de que la salida generada se use en un proceso con consecuencias (p. ej. antes de imprimir una pieza, de publicar documentación o de alimentar otro modelo), con un criterio de aceptación claro.',
        'Nunca: la IA generativa no necesita revisión.',
        'Solo si un cliente se queja.',
      ],
      correctIndex: 1,
      explanations: [
        'Revisar una muestra a posteriori no evita el uso de salidas erróneas.',
        'Correcto: la revisión se sitúa antes del uso con consecuencias, con criterio de aceptación explícito.',
        'La salida generativa puede contener errores o alucinaciones y sí necesita control.',
        'Esperar a la queja del cliente es reactivo y tardío.',
      ],
    },
    { extKey: 'ix-app-13', skillTag: 'Conceptos básicos de IA Generativa', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Un área quiere "entrenar nuestro propio modelo de lenguaje" para responder sobre normativa interna. ¿Qué recomiendas?',
      options: ['Preentrenar un modelo desde cero.', 'Partir de un modelo general y usar RAG (información cambiante) o ajuste fino (estilo estable); preentrenar desde cero es inviable en coste y datos para este caso.', 'No hacer nada.', 'Contratar 20 lingüistas.'],
      correctIndex: 1,
      explanations: ['Preentrenar exige recursos y datos fuera de alcance.', 'Correcto: RAG o ajuste fino sobre un modelo existente.', 'Hay un caso claro; no actuar lo desperdicia.', 'Contratar lingüistas no es la solución técnica.'] },
    { extKey: 'ix-app-14', skillTag: 'Conceptos básicos de IA Generativa', difficulty: 'baja', cognitive: 'comprension',
      stem: 'Un "modelo fundacional" (foundation model) se caracteriza por:',
      options: ['Estar entrenado solo para una tarea.', 'Estar preentrenado en un corpus enorme y ser adaptable a muchas tareas con relativamente pocos ejemplos (few-shot o ajuste ligero).', 'No usar datos.', 'Ser siempre pequeño.'],
      correctIndex: 1,
      explanations: ['Es lo contrario: sirve para muchas tareas.', 'Correcto: preentrenamiento amplio + adaptación eficiente.', 'Usa muchísimos datos.', 'Suelen ser grandes.'] },
    { extKey: 'ix-app-15', skillTag: 'Paradigmas de ML en la IA Generativa', difficulty: 'media', cognitive: 'comprension',
      stem: 'La "tarea de pretexto" en autosupervisión es:',
      options: ['La tarea final de negocio.', 'Una tarea auxiliar generada de los datos (predecir la siguiente palabra, reconstruir una parte oculta) que, al resolverla, hace que el modelo aprenda estructura útil.', 'Un examen del modelo.', 'El etiquetado manual.'],
      correctIndex: 1,
      explanations: ['No es la tarea de negocio.', 'Correcto: es el andamio de entrenamiento.', 'No es un examen.', 'No es etiquetado manual.'] },
    { extKey: 'ix-app-16', skillTag: 'Paradigmas de ML en la IA Generativa', difficulty: 'media', cognitive: 'analisis',
      stem: 'Un proveedor promete que su modelo "tiene capacidades emergentes que aún estamos descubriendo". ¿Cómo lo evalúas?',
      options: ['Confiar: las capacidades emergentes son buenas.', 'Con escepticismo práctico: pedir evidencia de las capacidades concretas que te interesan, medidas sobre tus casos; "emergente" también puede traer comportamientos no deseados difíciles de anticipar.', 'Rechazar cualquier modelo grande.', 'Comprarlo por si acaso.'],
      correctIndex: 1,
      explanations: ['La emergencia no garantiza utilidad para tu caso.', 'Correcto: se evalúa por capacidades demostradas sobre tus casos, y se vigilan los efectos no deseados.', 'El tamaño no es el criterio.', 'Comprar por si acaso no es una decisión informada.'] },
    { extKey: 'ix-app-17', skillTag: 'Redes Neuronales Generativas', difficulty: 'media', cognitive: 'comprension',
      stem: 'En una GAN, el generador aprende de:',
      options: ['Los ejemplos reales directamente.', 'Solo la señal del discriminador: qué tan bien engañó a la red que distingue real de falso.', 'Etiquetas humanas.', 'Un modelo de lenguaje.'],
      correctIndex: 1,
      explanations: ['El generador nunca ve los datos reales.', 'Correcto: se ajusta según el veredicto del discriminador.', 'No usa etiquetas humanas.', 'No usa un LLM.'] },
    { extKey: 'ix-app-18', skillTag: 'Redes Neuronales Generativas', difficulty: 'alta', cognitive: 'analisis',
      stem: 'Tu GAN genera imágenes de piezas realistas pero, al inspeccionar el conjunto, casi todas son variaciones de 3 formas. ¿Qué es y cómo lo detectaste que no verías mirando una sola imagen?',
      options: ['Sobreajuste del discriminador; se ve en cada imagen.', 'Colapso de modo: calidad individual alta pero variedad baja; solo se detecta midiendo la diversidad del conjunto generado frente a los datos reales.', 'Falta de GPU.', 'El dataset real es demasiado grande.'],
      correctIndex: 1,
      explanations: ['El colapso no se ve en una imagen aislada.', 'Correcto: es el fallo característico de las GAN; hay que medir diversidad del conjunto.', 'El hardware no lo causa.', 'El tamaño del dataset real no provoca colapso.'] },
    { extKey: 'ix-app-19', skillTag: 'Modelos Generativos', difficulty: 'media', cognitive: 'comprension',
      stem: 'Por qué un VAE puede generar ejemplos nuevos coherentes y un autoencoder básico no:',
      options: ['El VAE tiene más capas.', 'El VAE regulariza el espacio latente para que siga una distribución conocida; muestrear de ella produce ejemplos coherentes. El autoencoder básico deja huecos en el latente.', 'El autoencoder no comprime.', 'Son equivalentes.'],
      correctIndex: 1,
      explanations: ['No es cuestión de capas.', 'Correcto: la regularización probabilística hace el latente "muestreadable".', 'El autoencoder sí comprime.', 'No son equivalentes para generar.'] },
    { extKey: 'ix-app-20', skillTag: 'Modelos Generativos', difficulty: 'alta', cognitive: 'analisis',
      stem: 'Un servicio de generación debe responder en <500 ms por petición, en línea, cara al usuario. ¿Qué arquitectura descartas de entrada y por qué?',
      options: ['GAN, por inestable.', 'Difusión con muchos pasos de inferencia: aunque da la mejor calidad, cada muestra requiere decenas de pasos y difícilmente cumple 500 ms; hay que buscar variantes aceleradas o GAN/VAE.', 'VAE, por borroso.', 'Ninguna; todas cumplen.'],
      correctIndex: 1,
      explanations: ['La GAN es rápida en inferencia; no se descarta por latencia.', 'Correcto: la difusión estándar es costosa por muestra y choca con el requisito de latencia.', 'El VAE es rápido en inferencia.', 'La difusión estándar no cumple ese requisito fácilmente.'] },
    { extKey: 'ix-app-21', skillTag: 'IA Generativa para contenido Multimedia y multimodal', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Especificas un sistema RAG sobre documentación interna. ¿Qué métricas separan un buen diseño de una demo?',
      options: ['Solo el tiempo de respuesta.', 'Precisión de recuperación (¿trae los fragmentos correctos?) separada de la calidad de generación (¿los usa bien?), más tasa de alucinación sobre casos conocidos y coste por consulta.', 'El número de documentos indexados.', 'El tamaño del modelo.'],
      correctIndex: 1,
      explanations: ['El tiempo no dice si la respuesta es correcta.', 'Correcto: recuperación y generación por separado, más alucinación y coste.', 'Indexar mucho no garantiza recuperar lo correcto.', 'Un modelo grande no compensa una recuperación mala.'] },
    { extKey: 'ix-app-22', skillTag: 'IA Generativa para contenido Multimedia y multimodal', difficulty: 'alta', cognitive: 'analisis',
      stem: 'Tu RAG da una respuesta incorrecta. Antes de tocar el prompt, ¿cómo localizas la etapa que falló?',
      options: ['Reescribir el prompt y ver si mejora.', 'Inspeccionar los fragmentos recuperados: si no contienen la información, el fallo es de recuperación; si la contienen pero la respuesta la ignora o tergiversa, es de generación o de cómo se pasa el contexto.', 'Cambiar de modelo sin más.', 'Recuperar 50 fragmentos en vez de 5.'],
      correctIndex: 1,
      explanations: ['Tocar el prompt a ciegas no localiza la causa.', 'Correcto: revisar los fragmentos separa recuperación de generación.', 'Cambiar de modelo sin diagnóstico es prueba y error.', 'Más fragmentos empeora la relación señal-ruido.'] },
    { extKey: 'ix-app-23', skillTag: 'Tendencias y dirección futura de la IA Generativa', difficulty: 'media', cognitive: 'aplicacion',
      stem: 'Para una tarea industrial concreta y acotada, ¿modelo grande generalista o pequeño especializado?',
      options: ['Siempre el más grande.', 'A menudo el pequeño especializado: más barato, más rápido, más controlable y con menos alucinaciones en el dominio; el grande solo si la tarea exige su versatilidad.', 'Siempre el más pequeño.', 'Da igual, rinden lo mismo.'],
      correctIndex: 1,
      explanations: ['El tamaño no es garantía de idoneidad.', 'Correcto: el modelo adecuado a la tarea, no el mayor.', 'No siempre el más pequeño; depende de la tarea.', 'No rinden lo mismo en general.'] },
    { extKey: 'ix-app-24', skillTag: 'Tendencias y dirección futura de la IA Generativa', difficulty: 'media', cognitive: 'analisis',
      stem: 'Un proveedor ofrece integrar generación de vídeo para tus manuales de formación. ¿Cómo lo evalúas con el criterio del programa?',
      options: ['Adoptar para no quedarse atrás.', 'Aplicar la rejilla: ¿qué problema real resuelve (coste de producir vídeos)?, ¿madurez (coherencia temporal, control)?, ¿dependencias (guion, revisión)?, ¿barrera de adopción (quién revisa cada vídeo)? Piloto acotado o esperar con fecha de revisión.', 'Rechazar cualquier generación de vídeo.', 'Adoptar solo si la competencia ya lo usa.'],
      correctIndex: 1,
      explanations: ['El FOMO no es criterio.', 'Correcto: problema / madurez / dependencias / barrera antes de adoptar.', 'Rechazar sin evaluar tampoco es criterio.', 'La competencia es un dato, no la decisión.'] },
    { extKey: 'ix-app-25', skillTag: 'Conceptos básicos de IA Generativa', difficulty: 'media', cognitive: 'analisis',
      stem: 'Un piloto de generación de datos sintéticos mejora el detector de defectos con 200 imágenes de prueba. ¿Qué NO puedes concluir para producción?',
      options: ['Que la técnica tiene potencial.', 'Que los sintéticos capturan la variabilidad real a escala, que el coste de generación es asumible y que el detector generaliza a defectos reales no vistos.', 'Que el equipo entendió el problema.', 'Que hay un caso de uso.'],
      correctIndex: 1,
      explanations: ['El potencial sí se intuye.', 'Correcto: representatividad a escala, coste y generalización a lo real son lo que el piloto pequeño no demuestra.', 'La comprensión no depende del tamaño del piloto.', 'El caso ya está establecido.'] },
    { extKey: 'ix-app-26', skillTag: 'Paradigmas de ML en la IA Generativa', difficulty: 'baja', cognitive: 'comprension',
      stem: 'Diferencia entre preentrenamiento y ajuste fino:',
      options: ['Son sinónimos.', 'Preentrenamiento: aprender capacidades generales de un corpus enorme. Ajuste fino: adaptar ese modelo a un dominio o comportamiento con muchos menos datos.', 'El ajuste fino usa más datos que el preentrenamiento.', 'El preentrenamiento no usa datos.'],
      correctIndex: 1,
      explanations: ['No son sinónimos.', 'Correcto: capacidad general vs. adaptación específica.', 'El ajuste fino usa muchos menos datos.', 'El preentrenamiento usa muchísimos datos.'] },
    { extKey: 'ix-app-27', skillTag: 'Redes Neuronales Generativas', difficulty: 'media', cognitive: 'comprension',
      stem: 'El "entrenamiento adversarial" de una GAN es inestable porque:',
      options: ['Usa poca memoria.', 'La mejora de una red es la pérdida de la otra; si una domina demasiado pronto (p. ej. el discriminador se vuelve perfecto), la otra deja de recibir señal útil y el entrenamiento se estanca.', 'No usa gradientes.', 'Solo funciona con imágenes.'],
      correctIndex: 1,
      explanations: ['No es cuestión de memoria.', 'Correcto: la competencia entre redes hace el equilibrio delicado.', 'Sí usa gradientes.', 'Las GAN se aplican a más que imágenes.'] },
    { extKey: 'ix-app-28', skillTag: 'Modelos Generativos', difficulty: 'media', cognitive: 'analisis',
      stem: 'Debes generar 10.000 muestras/día en lotes nocturnos, sin requisito de tiempo real, priorizando calidad. ¿Difusión o GAN?',
      options: ['GAN, siempre que sea más rápida.', 'Difusión: sin presión de latencia, se prioriza calidad y estabilidad; el coste por muestra se absorbe con cómputo nocturno y paralelismo.', 'Ninguna sirve.', 'Reducir a 100 muestras.'],
      correctIndex: 1,
      explanations: ['La velocidad de la GAN solo compensa si la latencia es una restricción real.', 'Correcto: lotes nocturnos permiten priorizar calidad con difusión.', 'Sí sirve; es un problema de planificación de cómputo.', 'Reducir el volumen cambia el requisito.'] },
    { extKey: 'ix-app-29', skillTag: 'IA Generativa para contenido Multimedia y multimodal', difficulty: 'media', cognitive: 'aplicacion',
      stem: '¿Dónde se sitúa la revisión humana en una app de IA generativa industrial?',
      options: ['Al final, revisando una muestra anual.', 'Antes de que la salida generada se use en un proceso con consecuencias (imprimir una pieza, publicar documentación, alimentar otro modelo), con un criterio de aceptación claro y un bucle para las salidas rechazadas.', 'Nunca, no hace falta.', 'Solo si un cliente se queja.'],
      correctIndex: 1,
      explanations: ['Revisar a posteriori no evita el uso de salidas erróneas.', 'Correcto: antes del uso con consecuencias, con criterio explícito.', 'La salida generativa puede alucinar; necesita control.', 'Esperar la queja es reactivo.'] },
    { extKey: 'ix-app-30', skillTag: 'Tendencias y dirección futura de la IA Generativa', difficulty: 'baja', cognitive: 'comprension',
      stem: 'Un "agente autónomo" basado en un modelo generativo se diferencia de un asistente que solo responde en que:',
      options: ['Es más grande.', 'Planifica y ejecuta una secuencia de acciones (consultar, calcular, llamar a herramientas) para lograr un objetivo, lo que amplía el alcance pero también la superficie de error y de riesgo.', 'No usa datos.', 'Responde más rápido.'],
      correctIndex: 1,
      explanations: ['No es cuestión de tamaño.', 'Correcto: el agente actúa en varios pasos, con más alcance y más riesgo.', 'Sí usa datos.', 'No necesariamente responde más rápido.'] },
  ],
};
