// Banco de ítems de aplicación — Asignatura XI: IA aplicada a entornos seguros.
module.exports = {
  slug: 'bank-master-xi',
  title: 'Banco de ítems — Asignatura XI',
  scopeSlug: 'master-xi',
  questions: [
    {
      extKey: 'xi-app-01',
      skillTag: 'Introducción a la Inteligencia Artificial y aprendizaje automático',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La asignatura distingue "seguridad mediante IA" de "seguridad de la IA". ¿Cuál es la diferencia?',
      options: [
        'Son sinónimos.',
        'Seguridad mediante IA: usar IA para defender (detección de amenazas, correlación de eventos). Seguridad de la IA: proteger a los propios sistemas de IA de ataques (envenenamiento, evasión, inyección de prompt, robo de modelo).',
        'La primera es para hardware y la segunda para software.',
        'La primera la hace el equipo rojo y la segunda el azul.',
      ],
      correctIndex: 1,
      explanations: [
        'Son dos disciplinas distintas.',
        'Correcto: una usa IA como herramienta defensiva; la otra trata la IA como superficie de ataque a proteger.',
        'No es una distinción hardware/software.',
        'Ambos equipos pueden intervenir en las dos.',
      ],
    },
    {
      extKey: 'xi-app-02',
      skillTag: 'Modelos predictivos en ciberseguridad',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Un detector de anomalías de red genera 800 alertas al día y el equipo puede investigar 40. Subir el umbral reduce las alertas a 40, pero deja fuera ataques lentos y sigilosos. ¿Cómo se calibra?',
      options: [
        'Dejar el umbral bajo y descartar 760 alertas sin criterio.',
        'Calibrar el umbral a la capacidad de respuesta priorizando por riesgo esperado, y complementar con reglas específicas para los patrones sigilosos que el umbral general se perdería, además de muestreo aleatorio de lo no investigado.',
        'Apagar el detector.',
        'Contratar 20 analistas más esa misma semana.',
      ],
      correctIndex: 1,
      explanations: [
        'Descartar sin criterio deja pasar lo más peligroso.',
        'Correcto: se calibra por capacidad y riesgo, con reglas dedicadas para lo sigiloso y muestreo de la cola.',
        'Apagarlo elimina la detección.',
        'Ampliar el equipo requiere análisis de coste; no es la primera palanca.',
      ],
    },
    {
      extKey: 'xi-app-03',
      skillTag: 'Modelos predictivos en ciberseguridad',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'En detección de intrusiones, un falso positivo hace perder 15 minutos a un analista; un falso negativo puede costar una brecha. ¿Qué implica esta asimetría para el diseño del modelo?',
      options: [
        'Nada: hay que minimizar el error total sin más.',
        'El umbral de decisión debe favorecer la sensibilidad (reducir falsos negativos) hasta el límite que el equipo puede absorber en falsos positivos; optimizar la exactitud a secas sería un error.',
        'Hay que eliminar todas las alertas dudosas.',
        'El modelo debe ser una red neuronal profunda obligatoriamente.',
      ],
      correctIndex: 1,
      explanations: [
        'Con costes asimétricos, "minimizar el error total" da un umbral equivocado.',
        'Correcto: se prioriza no perder ataques, aceptando más falsos positivos hasta la capacidad del equipo.',
        'Eliminar lo dudoso aumenta los falsos negativos, justo lo más caro.',
        'La arquitectura del modelo no se deriva de la asimetría de costes.',
      ],
    },
    {
      extKey: 'xi-app-04',
      skillTag: 'Manejo y procesamiento de datos',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'En un SIEM, ¿por qué es crítica la "normalización" de los eventos de distintas fuentes antes de correlacionarlos?',
      options: [
        'Para reducir el tamaño de los logs.',
        'Porque cada fuente registra los mismos hechos con formatos, nombres de campo y zonas horarias distintos; sin un esquema común no se pueden cruzar eventos ni detectar patrones que abarcan varias fuentes.',
        'Para cifrar los datos.',
        'Para acelerar el disco.',
      ],
      correctIndex: 1,
      explanations: [
        'La normalización no es principalmente compresión.',
        'Correcto: unificar formato, campos y tiempo es lo que permite la correlación entre fuentes.',
        'La normalización no es cifrado.',
        'No es una optimización de hardware.',
      ],
    },
    {
      extKey: 'xi-app-05',
      skillTag: 'Introducción a los modelos generativos en Inteligencia Artificial',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'Tu organización desplegó un asistente RAG interno (asignatura IX). Desde seguridad, ¿cuál es un vector de ataque específico y su mitigación?',
      options: [
        'Que el modelo consuma mucha CPU; añadir más servidores.',
        'Inyección de prompt: un documento o entrada manipulada hace que el asistente ignore sus instrucciones o revele contexto sensible. Mitigación: aislar instrucciones de datos, filtrar y validar el contexto recuperado, limitar lo que el asistente puede hacer y registrar/alertar sobre intentos.',
        'Que el índice ocupe mucho disco; comprimirlo.',
        'Que los usuarios escriban con faltas de ortografía; corregir el texto.',
      ],
      correctIndex: 1,
      explanations: [
        'El consumo de CPU no es un ataque.',
        'Correcto: la inyección de prompt es el vector propio de estos sistemas; se mitiga con aislamiento, validación de contexto, mínimo privilegio y monitoreo.',
        'El tamaño del índice no es un vector de ataque.',
        'Las faltas de ortografía no comprometen la seguridad.',
      ],
    },
    {
      extKey: 'xi-app-06',
      skillTag: 'Retos y oportunidades de la Inteligencia Artificial en el contexto de la ciberseguridad',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La IA generativa "de doble filo" en ciberseguridad se refiere a que la misma capacidad puede:',
      options: [
        'Ser rápida y lenta a la vez.',
        'Servir para defender (generar datos sintéticos de ataque para entrenar detectores, resumir incidentes) y para atacar (phishing dirigido convincente, deepfakes, malware polimórfico); el defensor debe anticipar ambos usos.',
        'Funcionar solo los días pares.',
        'Ejecutarse solo en la nube.',
      ],
      correctIndex: 1,
      explanations: [
        'No es una cuestión de velocidad.',
        'Correcto: la misma tecnología habilita defensa y ataque; hay que planificar frente a ambos.',
        'No tiene relación con el calendario.',
        'No depende del lugar de ejecución.',
      ],
    },
    {
      extKey: 'xi-app-07',
      skillTag: 'Principios y aplicaciones Big Data en la ciberseguridad',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un equipo de seguridad guarda todos los eventos "por si acaso" pero nunca los consulta hasta que hay un incidente, y entonces descubre que faltan campos clave y que la retención borró lo relevante. ¿Qué principio se ignoró?',
      options: [
        'La velocidad de ingesta.',
        'Diseñar la recolección desde las preguntas de investigación (qué campos, qué retención, qué integridad) que se necesitarán en un incidente, incluyendo cadena de custodia; recolectar sin ese diseño produce datos inútiles cuando importan.',
        'El cifrado en tránsito.',
        'La elección de proveedor de SIEM.',
      ],
      correctIndex: 1,
      explanations: [
        'La ingesta funcionó; el diseño de qué y cuánto guardar, no.',
        'Correcto: la recolección debe planificarse desde las preguntas forenses futuras y la cadena de custodia.',
        'El cifrado protege pero no hace los datos completos ni retenidos el tiempo adecuado.',
        'El proveedor no determina si el esquema de recolección es adecuado.',
      ],
    },
    {
      extKey: 'xi-app-08',
      skillTag: 'Modelos predictivos en ciberseguridad',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La "explicabilidad de la alerta" es importante en un modelo de detección de amenazas porque:',
      options: [
        'Hace que el modelo sea más rápido.',
        'El analista necesita saber por qué se disparó la alerta (qué señales, qué desviación) para triarla, decidir si escalar y responder; una alerta sin contexto es difícil de accionar y erosiona la confianza en el sistema.',
        'Reduce el tamaño del modelo.',
        'Es un requisito estético del panel.',
      ],
      correctIndex: 1,
      explanations: [
        'La explicabilidad no acelera la inferencia.',
        'Correcto: la alerta debe ser accionable; sin el porqué, el analista no puede triarla eficazmente.',
        'No afecta al tamaño del modelo.',
        'No es una cuestión estética.',
      ],
    },
    {
      extKey: 'xi-app-09',
      skillTag: 'Retos y oportunidades de la Inteligencia Artificial en el contexto de la ciberseguridad',
      difficulty: 'alta',
      cognitive: 'analisis',
      stem: 'El proyecto de la asignatura pide "romper tu propio sistema antes de que lo haga otro". Aplicado a un modelo de clasificación de correos, ¿qué ejercicio ofensivo tiene sentido?',
      options: [
        'Comprobar que el servidor tiene antivirus.',
        'Intentar un ataque de evasión: construir correos maliciosos con pequeñas perturbaciones (sinónimos, formato, texto oculto) que el modelo clasifique como legítimos, documentar los que funcionan con criticidad y proponer mitigaciones (reentrenamiento adversarial, reglas complementarias).',
        'Cambiar la contraseña del administrador.',
        'Aumentar la RAM del servidor.',
      ],
      correctIndex: 1,
      explanations: [
        'El antivirus del servidor no prueba la robustez del clasificador.',
        'Correcto: el ejercicio ofensivo propio es un ataque de evasión documentado como un pentest, con mitigaciones.',
        'Cambiar contraseñas no evalúa el modelo.',
        'El hardware no tiene que ver con la robustez adversarial.',
      ],
    },
    {
      extKey: 'xi-app-10',
      skillTag: 'Introducción a la Inteligencia Artificial y aprendizaje automático',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'El informe de red team de la asignatura debe tener "formato de pentesting". ¿Qué campos no pueden faltar por hallazgo?',
      options: [
        'Solo una descripción libre del problema.',
        'Hallazgo, criticidad, evidencia/escenario de explotación, activo afectado y mitigación; además, mapeo de los controles resultantes a ISO 27001 y 42001.',
        'El nombre del analista y la fecha, nada más.',
        'Un resumen ejecutivo de una línea sin detalle.',
      ],
      correctIndex: 1,
      explanations: [
        'Una descripción libre no permite priorizar ni actuar.',
        'Correcto: criticidad, evidencia, activo y mitigación por hallazgo, más el mapeo a controles, es el formato exigido.',
        'Metadatos sin contenido técnico no sirven.',
        'Un resumen sin detalle no es un informe de red team.',
      ],
    },
    {
      extKey: 'xi-app-11',
      skillTag: 'Manejo y procesamiento de datos',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'El "enriquecimiento" de eventos en un pipeline de seguridad consiste en:',
      options: [
        'Borrar los eventos poco importantes.',
        'Añadir a cada evento contexto adicional (geolocalización de una IP, reputación conocida, propietario del activo, si el usuario está de baja) para que la correlación y el triaje sean más rápidos y precisos.',
        'Comprimir los logs.',
        'Traducir los logs a otro idioma.',
      ],
      correctIndex: 1,
      explanations: [
        'No es filtrado.',
        'Correcto: enriquecer es agregar contexto útil a cada evento.',
        'No es compresión.',
        'No es traducción.',
      ],
    },
    {
      extKey: 'xi-app-12',
      skillTag: 'Principios y aplicaciones Big Data en la ciberseguridad',
      difficulty: 'media',
      cognitive: 'comprension',
      stem: 'La "fatiga de alertas" en un centro de operaciones de seguridad describe:',
      options: [
        'El cansancio de los servidores por exceso de tráfico.',
        'La desensibilización del equipo ante un volumen alto de alertas, muchas de ellas falsos positivos, que lleva a ignorar o cerrar alertas sin investigar, incluidas algunas reales.',
        'Un ataque de denegación de servicio.',
        'Un fallo del SIEM al arrancar.',
      ],
      correctIndex: 1,
      explanations: [
        'No es un problema de hardware.',
        'Correcto: es la pérdida de atención del equipo por saturación de alertas, con riesgo de pasar por alto las verdaderas.',
        'No es un ataque DoS.',
        'No es un fallo de arranque del sistema.',
      ],
    },
  ],
};
