// Banco de ítems de aplicación — Asignatura IV: Metodologías Ágiles.
module.exports = {
  slug: 'bank-master-iv',
  title: 'Banco de ítems — Asignatura IV',
  scopeSlug: 'master-iv',
  questions: [
    {
      extKey: 'iv-app-01',
      skillTag: 'Principios y fundamentos de la agilidad',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Un equipo dice que "es ágil" porque hace reuniones diarias de pie, pero el alcance y la fecha están fijados de antemano y no se entrega nada hasta el final. ¿Qué falla respecto a los fundamentos de la agilidad?',
      options: [
        'Nada: las reuniones diarias son la esencia de lo ágil.',
        'Falta la entrega incremental de valor y la capacidad de ajustar el alcance ante lo aprendido; la ceremonia sin entregas ni adaptación no es agilidad.',
        'Que las reuniones deberían ser sentados.',
        'Que falta un director de proyecto tradicional.',
      ],
      correctIndex: 1,
      explanations: [
        'La reunión diaria es una práctica, no el fundamento.',
        'Correcto: agilidad es entregar incrementos y adaptarse a lo aprendido; sin eso, es cascada con rituales.',
        'La postura de la reunión es irrelevante.',
        'La agilidad reduce, no añade, la figura del director de mando y control.',
      ],
    },
    {
      extKey: 'iv-app-02',
      skillTag: 'Comparativa de marcos ágiles (Scrum, Kanban, Lean)',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un equipo de soporte recibe trabajo impredecible (incidencias) que no se puede planificar en bloques de dos semanas. ¿Qué marco encaja mejor y por qué?',
      options: [
        'Scrum: da estructura de sprints.',
        'Kanban: flujo continuo con límite de trabajo en curso, adecuado para demanda impredecible y prioridades cambiantes, sin comprometer un alcance fijo por iteración.',
        'Cascada: planificar todo el año.',
        'Ninguno: el soporte no puede ser ágil.',
      ],
      correctIndex: 1,
      explanations: [
        'Scrum asume un alcance comprometido por sprint, difícil con incidencias impredecibles.',
        'Correcto: Kanban gestiona flujo continuo y prioridades cambiantes con límites de WIP.',
        'Planificar un año de incidencias imprevisibles no es viable.',
        'El soporte se beneficia especialmente de Kanban.',
      ],
    },
    {
      extKey: 'iv-app-03',
      skillTag: 'Roles y eventos en Scrum',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'En Scrum, ¿quién decide qué elementos del backlog entran en el sprint y en qué orden de prioridad de producto?',
      options: [
        'El Scrum Master.',
        'El Product Owner define la prioridad; el equipo de desarrollo decide cuánto puede comprometer.',
        'La dirección de la empresa, directamente.',
        'Se sortea al azar.',
      ],
      correctIndex: 1,
      explanations: [
        'El Scrum Master facilita el proceso, no prioriza el producto.',
        'Correcto: el Product Owner ordena el valor; el equipo estima su capacidad.',
        'La dirección influye vía el Product Owner, no imponiendo el backlog del sprint.',
        'La selección es deliberada, no aleatoria.',
      ],
    },
    {
      extKey: 'iv-app-04',
      skillTag: 'Roles y eventos en Scrum',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'A mitad de sprint, un directivo pide meter "una tarea urgente" que desplaza el objetivo del sprint. Según Scrum, ¿cuál es la respuesta adecuada?',
      options: [
        'Aceptar siempre lo urgente sin discusión.',
        'Proteger el objetivo del sprint: evaluar con el Product Owner si el cambio justifica cancelar o renegociar el sprint; los cambios no se cuelan sin coste explícito.',
        'Rechazar cualquier cambio pase lo que pase.',
        'Añadir la tarea y ampliar el sprint una semana.',
      ],
      correctIndex: 1,
      explanations: [
        'Aceptar todo destruye la previsibilidad del sprint.',
        'Correcto: el objetivo del sprint se protege; un cambio grande se negocia explícitamente con el Product Owner.',
        'Scrum no prohíbe cambios; los hace visibles y con coste.',
        'Alargar el sprint arbitrariamente rompe la cadencia y la medición.',
      ],
    },
    {
      extKey: 'iv-app-05',
      skillTag: 'Prácticas de planificación y seguimiento en Scrum',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Tu equipo completó 20, 24 y 22 puntos en los últimos tres sprints. Quedan 130 puntos de backlog. ¿Cuál es la estimación defendible del cierre?',
      options: [
        'Dos sprints, porque el equipo "se esforzará más".',
        'Unos 6 sprints, tomando la velocidad media medida (~22) como base, con un rango por la variabilidad observada.',
        'Un sprint, si trabajan horas extra.',
        'No se puede estimar en absoluto.',
      ],
      correctIndex: 1,
      explanations: [
        'Estimar por deseo (esforzarse más) ignora la evidencia.',
        'Correcto: la estimación se basa en la velocidad medida (throughput), no en el optimismo; ~130/22 ≈ 6 sprints.',
        'Las horas extra no son sostenibles ni una base de planificación.',
        'Con datos de velocidad sí se puede estimar con un rango.',
      ],
    },
    {
      extKey: 'iv-app-06',
      skillTag: 'Prácticas de planificación y seguimiento en Scrum',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: '¿Qué representa la Definición de Hecho (Definition of Done) en Scrum?',
      options: [
        'La fecha límite del proyecto.',
        'El conjunto de criterios que un incremento debe cumplir para considerarse terminado y potencialmente entregable (probado, documentado, integrado…).',
        'El número de historias por sprint.',
        'La lista de asistentes a la retrospectiva.',
      ],
      correctIndex: 1,
      explanations: [
        'No es una fecha.',
        'Correcto: la DoD fija qué significa "hecho" de forma común y verificable.',
        'Eso es el alcance del sprint, no la DoD.',
        'No tiene relación con la asistencia a ceremonias.',
      ],
    },
    {
      extKey: 'iv-app-07',
      skillTag: 'Ciclos iterativos para la mejora de productos y procesos',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Vas a lanzar una funcionalidad grande. Aplicando construir-medir-aprender, ¿qué haces primero?',
      options: [
        'Construir la versión completa y pulida antes de mostrarla a nadie.',
        'Definir la hipótesis (qué esperas que cambie), construir la versión mínima que permita comprobarla, medir con usuarios reales y decidir con esos datos.',
        'Preguntar a la dirección si les gusta la idea.',
        'Copiar exactamente lo que hace un competidor.',
      ],
      correctIndex: 1,
      explanations: [
        'Construir todo antes de validar arriesga meses de trabajo sobre una suposición.',
        'Correcto: el bucle empieza por una hipótesis y el mínimo necesario para probarla con datos reales.',
        'La opinión de la dirección no sustituye la evidencia de uso.',
        'Copiar no valida que la funcionalidad resuelva tu problema.',
      ],
    },
    {
      extKey: 'iv-app-08',
      skillTag: 'Evaluación y ajuste continuo en proyectos ágiles',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'Las retrospectivas de tu equipo siempre concluyen "todo bien, seguir igual". Tres sprints después, la calidad ha bajado. ¿Qué diagnóstico es correcto?',
      options: [
        'El equipo es perfecto y no hay nada que cambiar.',
        'Las retrospectivas no están cumpliendo su función: una retrospectiva sin al menos un problema real identificado y una acción concreta no genera mejora.',
        'Hay que eliminar las retrospectivas.',
        'La calidad bajó por causas externas ajenas al equipo.',
      ],
      correctIndex: 1,
      explanations: [
        'Si la calidad baja, "todo bien" es una señal de retrospectiva vacía.',
        'Correcto: una retrospectiva útil produce hallazgos incómodos y acciones verificables; sin ellos, es una felicitación.',
        'El problema es cómo se hacen, no que existan.',
        'Atribuir todo a lo externo evita la mejora que la retrospectiva debería impulsar.',
      ],
    },
    {
      extKey: 'iv-app-09',
      skillTag: 'Comparativa de marcos ágiles (Scrum, Kanban, Lean)',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'Un equipo con Kanban tiene 15 tarjetas "en progreso" a la vez y nada se termina. ¿Qué ajuste concreto propone Kanban?',
      options: [
        'Contratar más gente inmediatamente.',
        'Bajar el límite de trabajo en curso (WIP) para forzar a terminar antes de empezar, reduciendo el tiempo de ciclo.',
        'Añadir más columnas al tablero.',
        'Pasar a sprints de un mes.',
      ],
      correctIndex: 1,
      explanations: [
        'Más gente sin límite de WIP suele multiplicar el trabajo a medias.',
        'Correcto: reducir el WIP es la palanca central de Kanban para mejorar el flujo.',
        'Más columnas no reduce el trabajo simultáneo.',
        'Cambiar de marco no resuelve el problema de flujo por sí solo.',
      ],
    },
    {
      extKey: 'iv-app-10',
      skillTag: 'Evaluación y ajuste continuo en proyectos ágiles',
      difficulty: 'baja',
      cognitive: 'comprension',
      stem: 'Las métricas DORA (frecuencia de despliegue, tiempo de entrega, tasa de fallo de cambios, tiempo de restauración) sirven principalmente para:',
      options: [
        'Medir cuántas reuniones hace el equipo.',
        'Evaluar el rendimiento de entrega de software de un equipo de forma equilibrada entre velocidad y estabilidad.',
        'Calcular el salario de los desarrolladores.',
        'Contar líneas de código escritas.',
      ],
      correctIndex: 1,
      explanations: [
        'No miden reuniones.',
        'Correcto: DORA equilibra rapidez (frecuencia, lead time) con estabilidad (fallo de cambios, recuperación).',
        'No son una base salarial.',
        'Las líneas de código no son una métrica DORA ni de valor.',
      ],
    },
    {
      extKey: 'iv-app-11',
      skillTag: 'Principios y fundamentos de la agilidad',
      difficulty: 'media',
      cognitive: 'analisis',
      stem: 'El manifiesto ágil valora "responder al cambio sobre seguir un plan". Un stakeholder lo interpreta como "no hace falta planificar". ¿Cómo lo corriges?',
      options: [
        'Tiene razón: en ágil no se planifica.',
        'Es una preferencia relativa, no absoluta: se planifica, pero el plan es una hipótesis que se revisa con lo aprendido, no un contrato inamovible.',
        'El manifiesto está equivocado en ese punto.',
        'Hay que planificar todo el proyecto al detalle desde el inicio.',
      ],
      correctIndex: 1,
      explanations: [
        'El manifiesto valora ambos lados; prioriza uno.',
        'Correcto: "sobre" indica preferencia relativa; la planificación sigue siendo necesaria, pero adaptable.',
        'No es un error del manifiesto, es una lectura errónea.',
        'La planificación total por adelantado es justo lo que la agilidad matiza.',
      ],
    },
    {
      extKey: 'iv-app-12',
      skillTag: 'Prácticas de planificación y seguimiento en Scrum',
      difficulty: 'media',
      cognitive: 'aplicacion',
      stem: 'En una estimación con planning poker, dos personas dan 3 puntos y una da 13. ¿Qué hace el equipo?',
      options: [
        'Tomar el promedio (≈6) y seguir.',
        'Conversar: la diferencia grande indica que entienden la historia de forma distinta; se aclara el alcance y se vuelve a estimar.',
        'Ignorar a la persona que dio 13.',
        'Asignar 13 por seguridad, sin discutir.',
      ],
      correctIndex: 1,
      explanations: [
        'El promedio oculta el desacuerdo de comprensión, que es la información valiosa.',
        'Correcto: el planning poker usa la divergencia como disparador de conversación para alinear el entendimiento.',
        'La estimación alta suele reflejar un riesgo o requisito que los demás no vieron.',
        'Tomar el número alto sin entender por qué no resuelve la ambigüedad.',
      ],
    },
  ],
};
