// Lectura guiada — Asignatura III: Big Data. Las 6 lecciones.
const F = {
  kleppmann: { titulo: 'Designing Data-Intensive Applications — Martin Kleppmann' },
  islp: { titulo: 'An Introduction to Statistical Learning (Python)', url: 'https://www.statlearning.com/' },
  fpp3: { titulo: 'Forecasting: Principles and Practice (3ª ed.) — Hyndman & Athanasopoulos', url: 'https://otexts.com/fpp3/' },
  geron: { titulo: 'Hands-On Machine Learning 3e — Aurélien Géron', url: 'https://github.com/ageron/handson-ml3' },
  polars: { titulo: 'Polars — documentación', url: 'https://docs.pola.rs/' },
  duckdb: { titulo: 'DuckDB — documentación', url: 'https://duckdb.org/docs/' },
  spark: { titulo: 'Learning Spark 2e (Databricks)', url: 'https://www.databricks.com/resources/ebook/learning-spark' },
};

module.exports = {
  'Arquitecturas y Soluciones de Big Data: Análisis, Procesamiento y Escalabilidad en la Era Digital': {
    objetivo: 'Distinguir batch de streaming por el costo real y saber cuándo un problema deja de necesitar procesamiento distribuido.',
    terminos: [
      {
        n: 1,
        termino: 'Procesamiento por lotes (batch) frente a en flujo (streaming)',
        definicionTextual: 'Batch: se procesa un conjunto acumulado de datos de forma periódica. Streaming: se procesa cada evento a medida que llega.',
        fuente: F.kleppmann.titulo,
        idea: ['Streaming añade complejidad operativa y de gestión de estado que solo compensa si el problema exige latencia baja de verdad. "Suena más avanzado" no es una razón.'],
        ejemplo: 'Un informe diario de ventas: batch. Bloquear una transacción sospechosa en el momento: streaming.',
        errorComun: 'Elegir streaming por defecto para todo, asumiendo un coste operativo que el caso no justifica.',
        fraseClave: 'Streaming se paga; úsalo cuando el reloj lo exija.',
      },
      {
        n: 2,
        termino: 'Sobrecarga de coordinación en sistemas distribuidos',
        definicionTextual: 'El coste de repartir el trabajo entre varios nodos: comunicación, sincronización, tolerancia a fallos y movimiento de datos entre máquinas.',
        fuente: F.spark.titulo,
        idea: ['Para datos que caben en la memoria de una máquina, esa sobrecarga puede hacer que Spark sea más lento que pandas, Polars o DuckDB en local.'],
        ejemplo: 'Una agregación sobre 30 M de filas puede tardar más en Spark que en DuckDB en el mismo equipo.',
        errorComun: 'Suponer que "distribuido = más rápido" sin medir en el volumen concreto.',
        fraseClave: 'Distribuir tiene peaje; a veces el peaje es mayor que el ahorro.',
      },
      {
        n: 3,
        termino: 'El punto donde un problema deja de necesitar Spark',
        definicionTextual: 'El volumen (o la complejidad) a partir del cual el procesamiento distribuido compensa su sobrecarga; por debajo, herramientas de un solo nodo son más rápidas y sencillas.',
        fuente: F.polars.titulo,
        idea: ['Ese punto no es una regla fija: se determina midiendo tiempo y memoria de cada opción en tu caso, no citando una cifra aprendida.'],
        ejemplo: 'Medir la misma agregación en pandas, Polars, DuckDB y Spark y ver dónde Spark empieza a ganar.',
        errorComun: 'Justificar "usamos Spark" con "porque son muchos datos" sin haber medido.',
        fraseClave: 'El umbral se mide, no se recita.',
      },
      {
        n: 4,
        termino: 'Data lake frente a data warehouse',
        definicionTextual: 'Data lake: almacena datos en crudo, de cualquier formato, para uso flexible posterior. Data warehouse: datos estructurados y modelados para consulta analítica eficiente.',
        fuente: F.kleppmann.titulo,
        idea: ['Un lake sin gobernanza (catálogo, linaje, calidad) se convierte en un "pantano de datos" inutilizable; el warehouse impone estructura a cambio de rigidez.'],
        ejemplo: 'El lake guarda los logs en crudo; el warehouse guarda las tablas de ventas listas para el BI.',
        errorComun: 'Volcar todo al lake "por si acaso" sin catálogo ni control de calidad.',
        fraseClave: 'Lake sin gobierno es pantano.',
      },
    ],
    casoCompleto: {
      escenario: 'Un área quiere "una solución de Big Data" para 2 GB de datos al día que hoy procesa en una hoja de cálculo.',
      pasos: [
        { titulo: 'Cuestionar', texto: '2 GB/día no exige tecnología distribuida; define primero qué pregunta no se puede responder hoy.' },
        { titulo: 'Medir', texto: 'Prueba pandas/Polars/DuckDB en una máquina antes de plantear un clúster.' },
        { titulo: 'Batch o streaming', texto: '¿El proceso es diario o exige reacción inmediata? Eso decide el patrón.' },
        { titulo: 'Almacenamiento', texto: 'Si vas a lake, define desde el día 1 el catálogo y la calidad.' },
      ],
    },
    preguntas: [
      {
        q: 'Una agregación sobre 30 M de filas tarda 40 s en pandas en una máquina de 32 GB, y se ejecuta una vez al día. Un equipo propone migrarla a un clúster Spark. ¿Qué haces?',
        opts: [
          'Migrar: Spark siempre es más rápido para Big Data.',
          'Probablemente no compensa: cabe en memoria, no hay presión de latencia y Spark añade sobrecarga; mide primero Polars/DuckDB en la misma máquina.',
          'Migrar a Spark pero sin clúster.',
          'Comprar 128 GB de RAM sin medir.',
        ],
        a: 1,
        why: 'El punto en que Spark compensa se justifica midiendo; a esta escala hay opciones más simples y probablemente más rápidas.',
      },
      {
        q: '¿Por qué un data lake sin gobernanza se vuelve un problema?',
        opts: [
          'Porque ocupa poco espacio.',
          'Porque sin catálogo, linaje y control de calidad nadie sabe qué hay ni si es fiable: se convierte en un "pantano de datos".',
          'Porque el streaming lo llena.',
          'Porque necesita cifrado.',
        ],
        a: 1,
        why: 'El valor del lake depende de poder encontrar y confiar en los datos; eso lo da la gobernanza, no el almacenamiento.',
      },
    ],
    fuentes: [F.kleppmann, F.polars, F.duckdb, F.spark],
  },

  'Entornos de trabajo para arquitecturas Deep Learning': {
    objetivo: 'Distinguir paralelismo de datos y de modelo, y por qué el seguimiento de experimentos es parte del trabajo, no un extra.',
    terminos: [
      {
        n: 1,
        termino: 'Paralelismo de datos',
        definicionTextual: 'Cada GPU tiene una copia completa del modelo y procesa un subconjunto del lote; los gradientes se promedian entre GPUs.',
        fuente: F.spark.titulo,
        idea: ['Es la estrategia cuando el modelo cabe en una GPU pero los datos o el lote no. Es la más común.'],
        ejemplo: '4 GPUs, cada una con el mismo modelo, procesando 1/4 del lote y sincronizando gradientes.',
        errorComun: 'Confundirlo con paralelismo de modelo cuando el problema es solo el tamaño del lote.',
        fraseClave: 'Modelo cabe, datos no: reparte los datos.',
      },
      {
        n: 2,
        termino: 'Paralelismo de modelo',
        definicionTextual: 'El modelo se reparte entre varias GPUs (unas capas en cada una) porque no cabe entero en una sola.',
        fuente: F.spark.titulo,
        idea: ['Más complejo y con más comunicación entre GPUs; se usa cuando el modelo es demasiado grande para una GPU.'],
        ejemplo: 'Un modelo de lenguaje muy grande con las primeras capas en la GPU 0 y las últimas en la GPU 1.',
        errorComun: 'Usar paralelismo de modelo por defecto cuando bastaba con paralelismo de datos.',
        fraseClave: 'Modelo no cabe: reparte el modelo.',
      },
      {
        n: 3,
        termino: 'Seguimiento de experimentos (experiment tracking)',
        definicionTextual: 'Registrar, para cada corrida de entrenamiento, los hiperparámetros, las métricas, la versión de los datos y del código.',
        fuente: F.islp.titulo,
        idea: ['Sin este registro no se pueden comparar corridas ni reproducir un resultado bueno tres semanas después. Es parte del método, no un lujo.'],
        ejemplo: 'Una herramienta que guarda "corrida 47: learning rate 0,001, 12 épocas, F1 0,82, dataset v3, commit abc123".',
        errorComun: 'Anotar los resultados "a mano" en un documento y perder la trazabilidad de qué produjo qué.',
        fraseClave: 'Si no lo registras, no lo puedes reproducir.',
      },
      {
        n: 4,
        termino: 'Gestión de la memoria de GPU',
        definicionTextual: 'El límite práctico del entrenamiento suele ser la VRAM: modelo + activaciones + gradientes + optimizador deben caber.',
        fuente: F.spark.titulo,
        idea: ['Cuando no cabe, las palancas son: bajar el tamaño de lote, usar precisión mixta, acumular gradientes o repartir (paralelismo).'],
        ejemplo: 'Un entrenamiento que falla con "out of memory" y se resuelve bajando el batch de 64 a 16.',
        errorComun: 'Asumir que "más épocas" o "más capas" es gratis mientras la GPU aguante, sin planificar la memoria.',
        fraseClave: 'La VRAM es el techo; planifícala.',
      },
    ],
    casoCompleto: {
      escenario: 'Vas a entrenar un modelo cuyo dataset no cabe en la memoria de una GPU, pero el modelo sí.',
      pasos: [
        { titulo: 'Estrategia', texto: 'Paralelismo de datos: copia del modelo en cada GPU, reparto del lote.' },
        { titulo: 'Memoria', texto: 'Ajusta el tamaño de lote por GPU para no exceder la VRAM.' },
        { titulo: 'Tracking', texto: 'Registra cada corrida (hiperparámetros, métricas, versión de datos) desde el principio.' },
        { titulo: 'Comparar', texto: 'Usa el registro para elegir la mejor configuración con evidencia, no por impresión.' },
      ],
    },
    preguntas: [
      {
        q: 'El modelo cabe en una GPU pero el dataset no. ¿Qué paralelismo usas?',
        opts: [
          'De modelo: repartir las capas.',
          'De datos: copia del modelo en cada GPU, cada una procesa parte del lote y se promedian los gradientes.',
          'No se puede entrenar.',
          'Reducir el modelo hasta que quepan los datos.',
        ],
        a: 1,
        why: 'El paralelismo de modelo es para modelos que no caben; aquí el problema es el volumen de datos.',
      },
      {
        q: '¿Por qué el seguimiento de experimentos no es opcional?',
        opts: [
          'Acelera el entrenamiento.',
          'Sin registrar hiperparámetros, métricas, datos y código de cada corrida no se puede comparar ni reproducir un buen resultado después.',
          'Cifra el modelo.',
          'Reduce el uso de VRAM.',
        ],
        a: 1,
        why: 'La reproducibilidad y la comparación de corridas son parte del método experimental.',
      },
    ],
    fuentes: [F.spark, F.islp, F.kleppmann],
  },

  'Aprendizaje Automático': {
    objetivo: 'Decidir cuándo un problema de aprendizaje necesita de verdad procesamiento distribuido y cuándo un muestreo representativo rinde casi igual a mucho menor coste.',
    terminos: [
      {
        n: 1,
        termino: 'Escalabilidad horizontal de un algoritmo de aprendizaje',
        definicionTextual: 'La propiedad de un algoritmo de repartir su cómputo entre muchas máquinas de forma casi lineal. No todos la tienen: algunos exigen ver todos los datos a la vez o hacen muchas pasadas dependientes.',
        fuente: F.spark.titulo,
        idea: ['Antes de elegir "entrenar en Spark", comprueba si el algoritmo tiene una versión distribuida real (MLlib y equivalentes) o si estás forzando algo que no escala.'],
        ejemplo: 'La regresión logística y los árboles por gradiente tienen versiones distribuidas maduras; muchos métodos de kernel no.',
        errorComun: 'Suponer que cualquier algoritmo "escala solo" por ejecutarlo en un clúster.',
        fraseClave: 'Distribuir el cómputo solo funciona si el algoritmo fue diseñado para ello.',
      },
      {
        n: 2,
        termino: 'Muestreo representativo frente a usar todo el dato',
        definicionTextual: 'Trabajar con una muestra estratificada por las variables clave, en lugar del conjunto completo, para iterar rápido; el resultado final se confirma una vez sobre todo el dato.',
        fuente: F.islp.titulo,
        idea: ['A partir de cierto tamaño, añadir más filas casi no mejora la métrica (rendimientos decrecientes), pero sí multiplica el coste y el tiempo de cada iteración.'],
        ejemplo: 'Ajustar hiperparámetros sobre 2 M de filas muestreadas y validar el modelo elegido sobre los 200 M completos.',
        errorComun: 'Iterar sobre el dataset entero "para no perder información" y hacer una décima parte de los experimentos posibles.',
        fraseClave: 'Itera sobre una muestra; confirma sobre el todo.',
      },
      {
        n: 3,
        termino: 'Ingeniería de características a escala',
        definicionTextual: 'La transformación de datos crudos en variables útiles (agregados, ventanas temporales, codificaciones) cuando el volumen obliga a hacerlo con procesamiento distribuido y no con operaciones triviales en memoria.',
        fuente: F.geron.titulo,
        idea: ['La calidad de las características suele mover más la métrica que cambiar de algoritmo; a gran escala, esas transformaciones son en sí mismas un problema de ingeniería de datos.'],
        ejemplo: 'Calcular, para 500 M de transacciones, el gasto medio del cliente en los 30 días previos a cada una.',
        errorComun: 'Calcular una característica usando información posterior al momento de predicción (fuga temporal) al agregar sin cuidar la ventana.',
        fraseClave: 'A escala, crear las variables es la mitad del trabajo.',
      },
      {
        n: 4,
        termino: 'Validación cruzada distribuida y fuga entre particiones',
        definicionTextual: 'Repartir los pliegues de validación entre nodos para acelerarla, cuidando que datos relacionados (mismo cliente, misma ventana temporal) no queden a la vez en entrenamiento y en prueba.',
        fuente: F.islp.titulo,
        idea: ['Una partición aleatoria ingenua puede meter el pasado y el futuro del mismo cliente en pliegues distintos y dar una métrica optimista que no se replica en producción.'],
        ejemplo: 'Validar un modelo de rotación agrupando por cliente (todos sus registros en el mismo pliegue), no fila a fila.',
        errorComun: 'Partir por filas al azar cuando hay estructura (cliente, tiempo, grupo) que crea dependencia.',
        fraseClave: 'La partición debe respetar la estructura que crea dependencia.',
      },
    ],
    casoCompleto: {
      escenario: 'Tienes 300 M de filas y un equipo que quiere entrenar "sobre todo" en un clúster grande para el primer modelo.',
      pasos: [
        { titulo: 'Muestrear', texto: 'Extrae una muestra estratificada de 2–5 M de filas para toda la fase de exploración e hiperparámetros.' },
        { titulo: 'Elegir algoritmo', texto: 'Comprueba que el algoritmo tiene versión distribuida real antes de comprometerte con Spark.' },
        { titulo: 'Características', texto: 'Define las transformaciones con ventanas temporales explícitas para evitar fuga.' },
        { titulo: 'Confirmar', texto: 'Entrena el modelo elegido una vez sobre el conjunto completo y compara la métrica con la de la muestra.' },
      ],
    },
    preguntas: [
      {
        q: 'Tu métrica sobre una muestra de 2 M de filas es F1 0,81; sobre los 300 M completos es 0,82, a 60× el coste de cómputo. ¿Qué concluyes?',
        opts: [
          'Hay que entrenar siempre sobre el total: 0,01 de mejora importa.',
          'Los rendimientos son decrecientes: la muestra es suficiente para iterar; se confirma sobre el total solo el modelo final.',
          'La muestra está mal hecha.',
          'El algoritmo no escala.',
        ],
        a: 1,
        why: 'Cuando añadir 150× más datos mueve la métrica una centésima, el coste de iterar sobre el total no compensa; la muestra representativa es la herramienta correcta.',
      },
      {
        q: '¿Por qué una validación cruzada con partición aleatoria por filas puede dar una métrica engañosamente alta?',
        opts: [
          'Porque usa menos memoria.',
          'Porque datos dependientes (mismo cliente o misma ventana temporal) pueden quedar a la vez en entrenamiento y prueba, y el modelo "reconoce" en vez de generalizar.',
          'Porque los pliegues son demasiado grandes.',
          'Porque no usa GPU.',
        ],
        a: 1,
        why: 'La validación debe agrupar por la unidad que crea la dependencia (cliente, tiempo) para estimar el rendimiento real sobre datos nuevos.',
      },
    ],
    fuentes: [F.spark, F.islp, F.geron],
  },

  'Regresiones y series temporales autorregresivas': {
    objetivo: 'Usar la interpretabilidad de la regresión lineal como una ventaja real y validar series temporales con corte temporal, nunca con partición aleatoria.',
    terminos: [
      {
        n: 1,
        termino: 'Coeficiente de una regresión lineal',
        definicionTextual: 'El cambio esperado en la variable de salida por cada unidad de aumento de una variable de entrada, manteniendo el resto constante.',
        fuente: F.islp.titulo,
        idea: ['Esa lectura directa ("cada año extra de antigüedad sube el precio estimado en X") hace de la regresión lineal la opción de referencia en contextos donde hay que explicar y defender cada predicción.'],
        ejemplo: 'Un modelo de precio de vivienda cuyo coeficiente de "m²" dice cuánto añade cada metro cuadrado al precio estimado.',
        errorComun: 'Interpretar un coeficiente como causal cuando el modelo solo capta correlación, o cuando hay variables muy correlacionadas entre sí (multicolinealidad).',
        fraseClave: 'El coeficiente se lee, pero no siempre se lee como causa.',
      },
      {
        n: 2,
        termino: 'Modelo autorregresivo (AR)',
        definicionTextual: 'Un modelo que predice el valor futuro de una serie a partir de sus propios valores pasados recientes.',
        fuente: F.fpp3.titulo,
        idea: ['Captura tendencia e inercia; combinado con componentes estacionales y de media móvil (ARIMA), es una línea base honesta antes de plantear modelos más complejos.'],
        ejemplo: 'Predecir la demanda de mañana como una combinación de la demanda de los últimos 7 días.',
        errorComun: 'Saltar a un modelo sofisticado sin comprobar antes si un AR o un ARIMA simple ya resuelve el problema.',
        fraseClave: 'El pasado reciente de la serie es la primera pista del futuro.',
      },
      {
        n: 3,
        termino: 'Validación temporal (rolling / hold-out por fecha)',
        definicionTextual: 'Entrenar con datos hasta una fecha de corte y evaluar sobre el periodo posterior, repitiendo el corte hacia delante. Nunca se mezcla información futura en el entrenamiento.',
        fuente: F.fpp3.titulo,
        idea: ['Una partición aleatoria en series temporales deja al modelo "ver" el futuro durante el entrenamiento y produce una métrica que no se repite en producción.'],
        ejemplo: 'Entrenar con 2019–2023, validar 2024; luego entrenar con 2019–2024 y validar el primer trimestre de 2025.',
        errorComun: 'Usar train_test_split aleatorio con datos que tienen orden temporal.',
        fraseClave: 'En series temporales, el futuro nunca entrena.',
      },
      {
        n: 4,
        termino: 'Estacionariedad y estacionalidad',
        definicionTextual: 'Estacionalidad: patrones que se repiten con periodo fijo (semana, mes, año). Estacionariedad: que las propiedades estadísticas de la serie (media, varianza) no cambien con el tiempo; muchos modelos AR/ARIMA la asumen tras diferenciar.',
        fuente: F.fpp3.titulo,
        idea: ['Ignorar la estacionalidad hace que el modelo "descubra" cada año que diciembre sube; modelarla explícitamente libera al modelo para capturar lo que sí es señal.'],
        ejemplo: 'Ventas minoristas con un pico anual en diciembre y otro semanal los sábados.',
        errorComun: 'Ajustar un AR sobre una serie con fuerte tendencia y estacionalidad sin transformarla primero.',
        fraseClave: 'Modela lo que se repite; deja al modelo lo que no.',
      },
    ],
    casoCompleto: {
      escenario: 'Un modelo de demanda semanal da un error de validación excelente, pero en producción falla sistemáticamente los lunes y en enero.',
      pasos: [
        { titulo: 'Revisar la partición', texto: 'Comprueba si la validación fue aleatoria; si mezcló semanas futuras y pasadas, la métrica es ficticia.' },
        { titulo: 'Rehacer con corte temporal', texto: 'Valida entrenando hasta una fecha y evaluando el periodo siguiente.' },
        { titulo: 'Estacionalidad', texto: 'Añade componentes semanal y anual explícitos (o usa ARIMA estacional).' },
        { titulo: 'Línea base', texto: 'Compara siempre contra un AR/ARIMA simple: si no lo bates, no justifiques la complejidad.' },
      ],
    },
    preguntas: [
      {
        q: 'Vas a validar un modelo de predicción de demanda diaria. ¿Cómo partes los datos?',
        opts: [
          'train_test_split(test_size=0.2, shuffle=True).',
          'Corte temporal: entrenar hasta una fecha, evaluar el periodo posterior, repitiendo el corte hacia delante.',
          '80% de los días al azar para entrenar.',
          'Da igual el orden.',
        ],
        a: 1,
        why: 'Con orden temporal, cualquier mezcla de futuro y pasado en el entrenamiento produce una estimación optimista que no se replica al predecir de verdad.',
      },
      {
        q: '¿Por qué la regresión lineal sigue siendo una opción de referencia en contextos regulados?',
        opts: [
          'Porque es la más precisa que existe.',
          'Porque sus coeficientes son directamente interpretables: se puede explicar y defender el efecto de cada variable sobre la predicción.',
          'Porque no necesita datos.',
          'Porque no se puede sobreajustar.',
        ],
        a: 1,
        why: 'La exigencia de explicar cada decisión hace de la transparencia intrínseca una ventaja, aunque otro modelo tenga algo más de exactitud.',
      },
    ],
    fuentes: [F.islp, F.fpp3],
  },

  'Árboles de decisión y Algoritmos': {
    objetivo: 'Entender por qué un árbol individual sobreajusta y cómo un bosque aleatorio lo corrige, y leer la importancia de variables con sano escepticismo.',
    terminos: [
      {
        n: 1,
        termino: 'Criterio de división e impureza',
        definicionTextual: 'En cada nodo, el árbol elige la variable y el umbral que más reducen la "impureza" (mezcla de clases o dispersión) de los grupos resultantes. Medidas habituales: índice de Gini, entropía, varianza.',
        fuente: F.islp.titulo,
        idea: ['El árbol es codicioso: optimiza cada división localmente sin mirar el efecto global, lo que lo hace rápido pero también propenso a estructuras frágiles.'],
        ejemplo: 'Un nodo divide por "antigüedad > 3 años" porque esa pregunta separa mejor a quienes renuevan de quienes no.',
        errorComun: 'Interpretar la primera división como "la variable más importante" sin más análisis.',
        fraseClave: 'El árbol pregunta lo que más separa aquí y ahora.',
      },
      {
        n: 2,
        termino: 'Sobreajuste de un árbol individual',
        definicionTextual: 'Un árbol sin límite de profundidad puede crear una hoja por cada ejemplo de entrenamiento: memoriza el ruido en vez de aprender el patrón, y falla en datos nuevos.',
        fuente: F.geron.titulo,
        idea: ['Se controla con profundidad máxima, mínimo de muestras por hoja o poda; pero la mejor defensa práctica es no usar un árbol solo.'],
        ejemplo: 'Un árbol con 100% de acierto en entrenamiento y 62% en prueba.',
        errorComun: 'Aumentar la profundidad para "mejorar" viendo solo la métrica de entrenamiento.',
        fraseClave: 'Un árbol perfecto en entrenamiento casi siempre es un árbol que memorizó.',
      },
      {
        n: 3,
        termino: 'Bosque aleatorio (random forest)',
        definicionTextual: 'Un conjunto de muchos árboles entrenados cada uno sobre una muestra distinta de filas (bagging) y considerando en cada división solo un subconjunto aleatorio de variables; la predicción es el promedio o el voto.',
        fuente: F.geron.titulo,
        idea: ['La aleatoriedad hace que los errores de los árboles individuales sean poco correlacionados, y al promediarlos se cancelan: menos varianza, mejor generalización.'],
        ejemplo: '300 árboles votando la clase; ninguno perfecto, el conjunto robusto.',
        errorComun: 'Esperar interpretabilidad de árbol único en un bosque: el conjunto ya no se lee como una sola secuencia de reglas.',
        fraseClave: 'Muchos árboles imperfectos y poco correlacionados baten a uno "perfecto".',
      },
      {
        n: 4,
        termino: 'Importancia de variables',
        definicionTextual: 'Una medida de cuánto contribuye cada variable a reducir la impureza (o a la exactitud, en la variante por permutación) a lo largo de todos los árboles del bosque.',
        fuente: F.geron.titulo,
        idea: ['Es una guía global útil, pero se infla con variables de alta cardinalidad y se reparte de forma arbitraria entre variables correlacionadas; la variante por permutación es más fiable.'],
        ejemplo: 'La importancia dice que "código postal" domina; puede ser señal real o solo que tiene miles de valores.',
        errorComun: 'Eliminar variables "poco importantes" sin comprobar que no están correlacionadas con las que sí puntúan alto.',
        fraseClave: 'La importancia orienta, no dictamina.',
      },
    ],
    casoCompleto: {
      escenario: 'Un árbol de decisión da 98% en entrenamiento y 66% en validación. El equipo quiere podarlo hasta que ambos números se acerquen.',
      pasos: [
        { titulo: 'Diagnóstico', texto: 'La brecha entrenamiento–validación es sobreajuste clásico de árbol único.' },
        { titulo: 'Primera opción', texto: 'Sustituir por un bosque aleatorio antes de dedicar tiempo a podar el árbol solo.' },
        { titulo: 'Si se necesita el árbol', texto: 'Limitar profundidad y mínimo de muestras por hoja con validación cruzada.' },
        { titulo: 'Variables', texto: 'Usar importancia por permutación y revisar correlaciones antes de descartar variables.' },
      ],
    },
    preguntas: [
      {
        q: 'Un árbol tiene 100% de acierto en entrenamiento y 60% en prueba. ¿Qué pasa y qué haces?',
        opts: [
          'El modelo es excelente; publícalo.',
          'Sobreajuste: memorizó el entrenamiento. Prueba un bosque aleatorio o limita la profundidad con validación.',
          'Faltan datos de prueba.',
          'Hay que subir la profundidad.',
        ],
        a: 1,
        why: 'Acierto perfecto en entrenamiento con caída fuerte en prueba es la firma del sobreajuste; el bosque reduce la varianza promediando árboles poco correlacionados.',
      },
      {
        q: '¿Por qué un bosque aleatorio generaliza mejor que un árbol individual?',
        opts: [
          'Porque cada árbol es más profundo.',
          'Porque promedia muchos árboles cuyos errores están poco correlacionados (muestras y variables distintas), y al promediar se cancelan.',
          'Porque usa menos variables en total.',
          'Porque no puede sobreajustar nunca.',
        ],
        a: 1,
        why: 'La aleatoriedad en filas y variables descorrelaciona los errores; el promedio de estimadores poco correlacionados tiene menos varianza.',
      },
    ],
    fuentes: [F.islp, F.geron],
  },

  'Redes neuronales Artificiales': {
    objetivo: 'Entender por qué apilar capas con no linealidad amplía lo que una red puede representar, y qué hace exactamente la retropropagación.',
    terminos: [
      {
        n: 1,
        termino: 'Perceptrón y separabilidad lineal',
        definicionTextual: 'La unidad mínima: suma ponderada de las entradas más un sesgo, pasada por una función de activación. Un perceptrón solo puede separar clases que una recta (o hiperplano) separa.',
        fuente: F.geron.titulo,
        idea: ['El límite del perceptrón (no puede aprender un XOR) es exactamente lo que resuelve apilar varias capas con activaciones no lineales.'],
        ejemplo: 'Un perceptrón clasifica bien "aprobado/suspenso" si la frontera es una recta en el plano nota–asistencia.',
        errorComun: 'Esperar que una sola capa aprenda relaciones curvas o con interacciones.',
        fraseClave: 'Una capa lineal solo traza rectas.',
      },
      {
        n: 2,
        termino: 'No linealidad y capas ocultas',
        definicionTextual: 'Sin una función de activación no lineal (ReLU, sigmoide, tanh) entre capas, apilar capas equivale a una sola transformación lineal. La no linealidad es lo que da poder de representación.',
        fuente: F.geron.titulo,
        idea: ['Cada capa oculta compone transformaciones: en imágenes, de bordes a texturas a partes a objetos; esa jerarquía es lo que hace potente al "deep".'],
        ejemplo: 'Una red de 3 capas con ReLU que aprende la frontera curva que un perceptrón no podía.',
        errorComun: 'Añadir capas sin activación no lineal y no entender por qué no mejora.',
        fraseClave: 'Sin no linealidad, muchas capas siguen siendo una.',
      },
      {
        n: 3,
        termino: 'Retropropagación (backpropagation)',
        definicionTextual: 'El algoritmo que calcula, mediante la regla de la cadena, cuánto contribuyó cada peso de la red al error de la predicción final, propagando ese gradiente desde la salida hacia la entrada, capa por capa.',
        fuente: F.geron.titulo,
        idea: ['No es "cómo aprende la red" en abstracto: es el mecanismo concreto que reparte la culpa del error entre millones de pesos para que el optimizador los ajuste.'],
        ejemplo: 'Tras una predicción errónea, la retropropagación indica que el peso w del nodo 3 de la capa 2 debe bajar un poco.',
        errorComun: 'Confundir retropropagación (cálculo del gradiente) con descenso de gradiente (el paso de actualización que lo usa).',
        fraseClave: 'La retropropagación reparte la culpa; el optimizador aplica la corrección.',
      },
      {
        n: 4,
        termino: 'Profundidad, datos y sobreajuste',
        definicionTextual: 'Más capas aumentan la capacidad de representación pero también el número de parámetros; sin datos suficientes y sin regularización (dropout, early stopping, weight decay) la red memoriza.',
        fuente: F.geron.titulo,
        idea: ['La profundidad útil está acotada por los datos disponibles y por el cómputo; esto conecta directamente con las arquitecturas de GPU y Big Data del inicio de la asignatura.'],
        ejemplo: 'Una red muy profunda con 5.000 ejemplos que da 99% en entrenamiento y 70% en validación.',
        errorComun: 'Aumentar la profundidad como primera respuesta a un rendimiento bajo, sin más datos ni regularización.',
        fraseClave: 'Más profundidad exige más datos; si no, memoriza.',
      },
    ],
    casoCompleto: {
      escenario: 'Una red de una sola capa no consigue separar dos clases que forman dos anillos concéntricos.',
      pasos: [
        { titulo: 'Diagnóstico', texto: 'La frontera necesaria es curva; una sola capa lineal no puede representarla.' },
        { titulo: 'Añadir capas ocultas', texto: 'Dos o tres capas con activación ReLU permiten componer una frontera no lineal.' },
        { titulo: 'Comprobar la activación', texto: 'Sin no linealidad entre capas, seguiría siendo un modelo lineal.' },
        { titulo: 'Vigilar el sobreajuste', texto: 'Con pocos datos, añadir dropout y early stopping antes de crecer más la red.' },
      ],
    },
    preguntas: [
      {
        q: 'Apilas 4 capas densas pero sin función de activación no lineal entre ellas. ¿Qué has construido?',
        opts: [
          'Una red profunda potente.',
          'El equivalente a un único modelo lineal: sin no linealidad, componer capas lineales sigue siendo una transformación lineal.',
          'Una red que solo funciona con imágenes.',
          'Un árbol de decisión.',
        ],
        a: 1,
        why: 'La no linealidad entre capas es lo que da poder de representación; sin ella, la profundidad no aporta nada.',
      },
      {
        q: '¿Qué hace exactamente la retropropagación?',
        opts: [
          'Actualiza los pesos con un paso de aprendizaje.',
          'Calcula, con la regla de la cadena, el gradiente del error respecto a cada peso, propagándolo de la salida hacia la entrada; el optimizador es quien luego actualiza.',
          'Genera los datos de entrenamiento.',
          'Elige la arquitectura de la red.',
        ],
        a: 1,
        why: 'Retropropagación = cálculo del gradiente; descenso de gradiente = el paso de actualización que consume ese gradiente.',
      },
    ],
    fuentes: [F.geron, F.islp],
  },
};
