// Lectura guiada — Asignatura XI: Principios de IA aplicada a entornos seguros.
const F = {
  atlas: { titulo: 'MITRE ATLAS — tácticas y técnicas de ataque a sistemas de IA', url: 'https://atlas.mitre.org/' },
  owasp: { titulo: 'OWASP Top 10 for LLM Applications', url: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/' },
  nist2: { titulo: 'NIST AI 100-2 — Adversarial Machine Learning (taxonomía)', url: 'https://csrc.nist.gov/pubs/ai/100/2/e2023/final' },
  chio: { titulo: 'Machine Learning and Security — Chio & Freeman (O’Reilly)' },
  ids: { titulo: 'CIC-IDS2017 / UNSW-NB15 — datasets de tráfico de red etiquetado' },
};

module.exports = {
  'Introducción a IA y aprendizaje automático': {
    objetivo: 'Fijar la distinción entre "seguridad mediante IA" y "seguridad de la IA", y encuadrarla en la triada CIA.',
    terminos: [
      {
        n: 1,
        termino: 'IA como herramienta defensiva',
        definicionTextual: 'Uso de modelos para detectar amenazas, correlacionar eventos, priorizar alertas o asistir al analista.',
        fuente: F.chio.titulo,
        idea: ['La IA defensiva reduce la carga del equipo y acelera la detección, pero no elimina la necesidad de criterio humano ni de reglas complementarias.'],
        ejemplo: 'Un modelo que marca conexiones de red anómalas para que un analista las revise.',
        errorComun: 'Tratar el detector como una capa que "ya cubre" todo lo que no marca.',
        fraseClave: 'La IA defensiva ayuda a mirar; no exime de mirar.',
      },
      {
        n: 2,
        termino: 'IA como superficie de ataque (el modelo como activo vulnerable)',
        definicionTextual: 'El propio sistema de IA puede ser atacado: envenenamiento de datos, evasión (entradas manipuladas), extracción del modelo o inyección de prompt.',
        fuente: F.atlas.titulo,
        idea: ['Cada modelo en producción añade una nueva superficie que hay que modelar como cualquier otro activo: qué se puede robar, romper o manipular.'],
        ejemplo: 'Un atacante ajusta ligeramente un correo para que el clasificador de spam lo marque como legítimo (evasión).',
        errorComun: 'Auditar la infraestructura y olvidar que el modelo mismo es un objetivo.',
        fraseClave: 'Un modelo en producción es un activo que atacar.',
      },
      {
        n: 3,
        termino: 'Triada de seguridad: confidencialidad, integridad, disponibilidad',
        definicionTextual: 'Confidencialidad: solo quien debe accede. Integridad: los datos y decisiones no se alteran indebidamente. Disponibilidad: el servicio funciona cuando se necesita.',
        fuente: F.nist2.titulo,
        idea: ['Los ataques a IA se pueden mapear a la triada: extracción del modelo golpea confidencialidad; envenenamiento, integridad; inundar de peticiones caras, disponibilidad.'],
        ejemplo: 'Envenenar el dataset de reentrenamiento para degradar el detector = ataque a la integridad.',
        errorComun: 'Pensar solo en confidencialidad (fuga de datos) y descuidar integridad y disponibilidad del modelo.',
        fraseClave: 'Cada ataque a un modelo cae en una de las tres letras.',
      },
      {
        n: 4,
        termino: 'Diferencia entre seguridad de la IA y seguridad mediante IA',
        definicionTextual: 'Seguridad mediante IA: usar IA para defender. Seguridad de la IA: proteger los sistemas de IA de ataques.',
        fuente: F.chio.titulo,
        idea: ['Son dos programas de trabajo distintos que a menudo caen en el mismo equipo; confundirlos lleva a cubrir uno y dejar el otro en blanco.'],
        ejemplo: 'Montar un SIEM con ML (seguridad mediante IA) y no tener ningún control sobre cómo se podría atacar ese propio modelo (seguridad de la IA).',
        errorComun: 'Decir "ya hacemos seguridad con IA" para dar por cubierta la seguridad de la IA.',
        fraseClave: 'Defender con IA no es lo mismo que defender la IA.',
      },
    ],
    casoCompleto: {
      escenario: 'Tu equipo despliega un clasificador de correos maliciosos.',
      pasos: [
        { titulo: 'Mediante IA', texto: 'El clasificador reduce la carga del analista filtrando lo evidente.' },
        { titulo: 'De la IA', texto: 'Modela cómo un atacante intentaría evadirlo (perturbar el texto) o envenenarlo (falsos ejemplos en el reentrenamiento).' },
        { titulo: 'Triada', texto: 'Confidencialidad: ¿se puede extraer el modelo? Integridad: ¿se puede envenenar? Disponibilidad: ¿se puede saturar?' },
        { titulo: 'Controles', texto: 'Reglas complementarias, muestreo de lo no marcado, validación del pipeline de reentrenamiento.' },
      ],
    },
    preguntas: [
      {
        q: '"Ya hacemos detección de amenazas con machine learning, así que la seguridad de nuestra IA está cubierta". ¿Correcto?',
        opts: [
          'Sí, es lo mismo.',
          'No: usar IA para defender (seguridad mediante IA) no dice nada sobre proteger ese modelo de ataques (seguridad de la IA); son dos trabajos distintos.',
          'Sí, si el modelo es supervisado.',
          'Depende del proveedor.',
        ],
        a: 1,
        why: 'Defender con IA y defender la IA son programas separados; cubrir uno no cubre el otro.',
      },
      {
        q: 'Un atacante consigue introducir ejemplos falsos en el dataset de reentrenamiento del detector. ¿Qué letra de la triada golpea?',
        opts: ['Confidencialidad', 'Integridad', 'Disponibilidad', 'Ninguna'],
        a: 1,
        why: 'Envenenar los datos altera las decisiones futuras del modelo: es un ataque a la integridad.',
      },
    ],
    fuentes: [F.atlas, F.nist2, F.chio],
  },

  'Big Data en ciberseguridad': {
    objetivo: 'Entender por qué la seguridad es un problema de Big Data y qué es la fatiga de alertas.',
    terminos: [
      {
        n: 1,
        termino: 'Volumen de eventos de seguridad',
        definicionTextual: 'Una organización media genera millones de eventos al día entre logs de sistemas, tráfico de red, autenticaciones y actividad en la nube.',
        fuente: F.chio.titulo,
        idea: ['A ese volumen, la detección manual es imposible; hace falta agregación, correlación y priorización automáticas. Pero más recolección sin capacidad de análisis solo agrava el problema.'],
        ejemplo: 'Un cortafuegos que registra 5 millones de líneas al día; nadie las lee una a una.',
        errorComun: 'Aumentar la recolección de logs sin aumentar la capacidad de procesarlos.',
        fraseClave: 'Recolectar sin analizar es acumular problemas.',
      },
      {
        n: 2,
        termino: 'Velocidad: detección en tiempo real frente a análisis posterior',
        definicionTextual: 'Algunas amenazas exigen reacción en segundos (bloquear una conexión); otras se investigan después con más contexto (análisis forense).',
        fuente: F.ids.titulo,
        idea: ['El diseño combina ambas: reglas rápidas en el flujo para lo urgente, y análisis por lotes con más señal para lo sofisticado.'],
        ejemplo: 'Bloquear en tiempo real una IP conocida como maliciosa; investigar por lotes patrones de exfiltración lenta.',
        errorComun: 'Intentar que todo sea en tiempo real, sacrificando la profundidad del análisis.',
        fraseClave: 'Lo urgente en el flujo; lo sutil por lotes.',
      },
      {
        n: 3,
        termino: 'Correlación de eventos entre fuentes',
        definicionTextual: 'Combinar señales de red, endpoint, identidad y nube para reconstruir un ataque que ninguna fuente por sí sola revela.',
        fuente: F.chio.titulo,
        idea: ['Un evento aislado puede parecer benigno; la secuencia (login raro + descarga + conexión saliente) es la que delata el ataque.'],
        ejemplo: 'Login desde un país nuevo + acceso a un recurso sensible + tráfico saliente inusual, en 10 minutos.',
        errorComun: 'Analizar cada fuente en su propio silo sin cruzarlas.',
        fraseClave: 'El ataque vive en la unión de las fuentes.',
      },
      {
        n: 4,
        termino: 'Fatiga de alertas (alert fatigue)',
        definicionTextual: 'La desensibilización de un equipo ante un volumen alto de alertas, muchas de ellas falsos positivos, que lleva a ignorar o cerrar alertas sin investigar.',
        fuente: F.nist2.titulo,
        idea: ['Es un fallo de proceso, no de personas: si el sistema genera 10 veces más alertas de las que el equipo puede atender, algunas reales pasarán.'],
        ejemplo: 'Un SOC que recibe 3.000 alertas/día y puede investigar 200; las 2.800 restantes se cierran en bloque.',
        errorComun: 'Subir la sensibilidad del detector sin considerar la capacidad de respuesta del equipo.',
        fraseClave: 'Más alertas de las que puedes atender = ceguera.',
      },
    ],
    casoCompleto: {
      escenario: 'Diseñas la ingesta de eventos para un SOC pequeño (capacidad: 150 alertas/día).',
      pasos: [
        { titulo: 'Volumen', texto: 'Define qué fuentes ingerir según lo que aportan, no "todas por si acaso".' },
        { titulo: 'Velocidad', texto: 'Reglas rápidas para lo crítico; análisis por lotes para lo sutil.' },
        { titulo: 'Correlación', texto: 'Prioriza reglas que cruzan fuentes (identidad + red + endpoint).' },
        { titulo: 'Fatiga', texto: 'Calibra el umbral a las 150 alertas/día por riesgo esperado; documenta qué se hace con la cola.' },
      ],
    },
    preguntas: [
      {
        q: 'El SOC recibe 3.000 alertas/día y puede investigar 200. Subes la sensibilidad y ahora recibe 6.000. ¿Qué pasa?',
        opts: [
          'Mejora la detección.',
          'Empeora: la fatiga de alertas se agrava, se cierran más alertas sin investigar y aumenta la probabilidad de pasar por alto una real.',
          'El equipo trabaja el doble de rápido.',
          'Los falsos positivos desaparecen.',
        ],
        a: 1,
        why: 'La detección solo sirve si el equipo puede actuar sobre ella; más alertas que capacidad = ceguera de proceso.',
      },
      {
        q: '¿Por qué es clave la correlación entre fuentes?',
        opts: [
          'Para reducir el almacenamiento.',
          'Porque un ataque suele ser una secuencia de eventos que, aislados, parecen benignos; solo cruzando red, identidad y endpoint se ve el patrón.',
          'Porque las fuentes se validan entre sí.',
          'Para acelerar el disco.',
        ],
        a: 1,
        why: 'El valor está en reconstruir la secuencia; ninguna fuente por sí sola revela el ataque completo.',
      },
    ],
    fuentes: [F.chio, F.ids, F.nist2],
  },

  'Manejo y procesamiento de datos': {
    objetivo: 'Fijar el flujo SIEM (recolección → normalización → enriquecimiento) y la exigencia de cadena de custodia.',
    terminos: [
      {
        n: 1,
        termino: 'Recolección centralizada de logs (SIEM)',
        definicionTextual: 'Sistema que agrega los eventos de todas las fuentes en un único repositorio consultable, base de la detección y de la investigación.',
        fuente: F.chio.titulo,
        idea: ['El SIEM no detecta por sí solo: es la infraestructura sobre la que corren las reglas y los modelos. Su valor depende de qué fuentes cubre y de la calidad de lo que ingiere.'],
        ejemplo: 'Enviar los logs de firewall, VPN, Active Directory y la nube al mismo SIEM.',
        errorComun: 'Comprar el SIEM y dejar fuera fuentes clave (nube, identidad) por complejidad de integración.',
        fraseClave: 'El SIEM ve lo que le enchufas, ni más ni menos.',
      },
      {
        n: 2,
        termino: 'Normalización de formatos heterogéneos',
        definicionTextual: 'Traducir los eventos de cada fuente, con sus formatos, nombres de campo y zonas horarias distintos, a un esquema común.',
        fuente: F.ids.titulo,
        idea: ['Sin normalización no se puede correlacionar: "usuario", "user", "account_name" y "UPN" tienen que ser el mismo campo para cruzar eventos.'],
        ejemplo: 'Mapear el campo de IP de origen de tres firewalls distintos a un único campo src_ip.',
        errorComun: 'Guardar los logs en crudo y pretender correlacionarlos después sin esquema común.',
        fraseClave: 'Sin campos comunes no hay correlación.',
      },
      {
        n: 3,
        termino: 'Enriquecimiento con contexto (inteligencia de amenazas)',
        definicionTextual: 'Añadir a cada evento información externa o interna: reputación de una IP, si un dominio es conocido como malicioso, el dueño del activo, si el usuario está de baja.',
        fuente: F.chio.titulo,
        idea: ['El enriquecimiento convierte un evento neutro ("conexión a 203.0.113.5") en accionable ("conexión a un servidor de comando y control conocido").'],
        ejemplo: 'Marcar automáticamente los eventos que involucran cuentas de empleados que ya no trabajan en la empresa.',
        errorComun: 'Enriquecer con listas de amenazas desactualizadas, que generan ruido o falsa tranquilidad.',
        fraseClave: 'El contexto es lo que hace accionable una alerta.',
      },
      {
        n: 4,
        termino: 'Retención y cadena de custodia',
        definicionTextual: 'Retención: cuánto tiempo se conservan los eventos (ataques que se descubren meses después). Cadena de custodia: garantizar que la evidencia no se altera y que se sabe quién la manejó, si va a usarse legalmente.',
        fuente: F.nist2.titulo,
        idea: ['La retención se diseña desde las preguntas de investigación futuras; la cadena de custodia, desde el posible uso probatorio.'],
        ejemplo: 'Retener 12 meses los logs de autenticación porque las intrusiones se detectan tarde; con firma e integridad si pueden acabar en un proceso.',
        errorComun: 'Fijar una retención de 30 días por coste y descubrir que la intrusión empezó hace 4 meses.',
        fraseClave: 'Guarda pensando en la investigación que aún no ha empezado.',
      },
    ],
    casoCompleto: {
      escenario: 'Un incidente se descubre y necesitas reconstruir qué pasó hace tres meses.',
      pasos: [
        { titulo: 'SIEM', texto: '¿Estaban todas las fuentes relevantes enviando eventos entonces?' },
        { titulo: 'Normalización', texto: '¿Puedes cruzar identidad y red con campos comunes en los datos de esa fecha?' },
        { titulo: 'Retención', texto: '¿Se conservan los eventos de hace 3 meses o la retención los borró?' },
        { titulo: 'Custodia', texto: 'Si va a haber acciones legales, ¿la evidencia tiene integridad verificable y registro de manejo?' },
      ],
    },
    preguntas: [
      {
        q: 'Fijas la retención de logs en 30 días por coste. Se descubre una intrusión que empezó hace 4 meses. ¿Qué principio se ignoró?',
        opts: [
          'La velocidad de ingesta.',
          'Diseñar la retención desde las preguntas de investigación futuras: las intrusiones se detectan tarde, así que la ventana debe cubrir ese retraso.',
          'El cifrado en tránsito.',
          'La normalización.',
        ],
        a: 1,
        why: 'La retención se decide por cuánto tiempo hacia atrás necesitarás investigar, no solo por el coste de almacenamiento.',
      },
      {
        q: '¿Qué convierte un evento neutro en una alerta accionable?',
        opts: [
          'Comprimirlo.',
          'El enriquecimiento con contexto: reputación de la IP, dueño del activo, estado del usuario; sin contexto, el analista no puede triarlo.',
          'Traducirlo a otro idioma.',
          'Guardarlo dos veces.',
        ],
        a: 1,
        why: 'El contexto transforma "conexión a una IP" en "conexión a un servidor malicioso conocido en un activo crítico".',
      },
    ],
    fuentes: [F.chio, F.ids, F.nist2],
  },

  'Modelos predictivos en ciberseguridad': {
    objetivo: 'Aplicar detección de anomalías y clasificación con costes asimétricos, y exigir explicabilidad de la alerta.',
    terminos: [
      {
        n: 1,
        termino: 'Detección de anomalías (no supervisado)',
        definicionTextual: 'Aprender el comportamiento normal de un sistema y marcar lo que se desvía, sin necesidad de ejemplos etiquetados de ataques.',
        fuente: F.ids.titulo,
        idea: ['Útil para amenazas nuevas que no están en ninguna firma, pero genera falsos positivos cuando lo "normal" cambia legítimamente (un despliegue, un pico estacional).'],
        ejemplo: 'Marcar que un servidor que nunca envía datos al exterior de repente lo hace.',
        errorComun: 'No reentrenar la línea base cuando el sistema cambia de forma legítima, disparando falsos positivos.',
        fraseClave: 'Detecta lo nuevo, se confunde con lo que cambió sin avisar.',
      },
      {
        n: 2,
        termino: 'Clasificación de amenazas conocidas (supervisado)',
        definicionTextual: 'Entrenar con ejemplos etiquetados de ataques conocidos para reconocerlos rápido y con precisión.',
        fuente: F.chio.titulo,
        idea: ['Muy preciso para lo que ya se ha visto; ciego ante variantes nuevas. Se combina con la detección de anomalías, que cubre lo desconocido.'],
        ejemplo: 'Reconocer una familia de malware por su patrón de tráfico característico.',
        errorComun: 'Confiar solo en la clasificación supervisada y no cubrir las amenazas fuera del conjunto de entrenamiento.',
        fraseClave: 'Preciso con lo conocido; combínalo con anomalías para lo nuevo.',
      },
      {
        n: 3,
        termino: 'Falsos positivos frente a falsos negativos: costos asimétricos',
        definicionTextual: 'Falso positivo: alerta que no era amenaza (coste: tiempo del analista, fricción). Falso negativo: amenaza no detectada (coste: la brecha completa).',
        fuente: F.nist2.titulo,
        idea: ['En seguridad, un falso negativo suele costar mucho más. El umbral se calibra favoreciendo la sensibilidad, pero solo hasta donde el equipo puede absorber los falsos positivos.'],
        ejemplo: 'Preferir 50 falsos positivos investigables a un falso negativo que era una intrusión.',
        errorComun: 'Optimizar para minimizar el "error total" como si ambos errores pesaran igual.',
        fraseClave: 'En seguridad, no ver el ataque cuesta más que la falsa alarma.',
      },
      {
        n: 4,
        termino: 'Explicabilidad de una alerta para el analista humano',
        definicionTextual: 'La alerta debe decir por qué se disparó: qué señales, qué desviación respecto a lo normal, qué activo y qué usuario.',
        fuente: F.chio.titulo,
        idea: ['Una alerta sin el porqué es casi inservible: el analista no puede triarla, decidir si escalar ni responder, y termina ignorándola.'],
        ejemplo: '"Alerta: conexión anómala" es inútil; "el host X, que nunca contacta el exterior, envió 2 GB a una IP de mala reputación a las 3:00" es accionable.',
        errorComun: 'Entregar un score numérico sin contexto ("riesgo: 0,87") y llamarlo alerta.',
        fraseClave: 'Sin el porqué, la alerta se ignora.',
      },
    ],
    casoCompleto: {
      escenario: 'Despliegas un modelo de detección para tu red con un equipo que investiga 40 alertas/día.',
      pasos: [
        { titulo: 'Enfoque doble', texto: 'Clasificación supervisada para amenazas conocidas + anomalías para lo nuevo.' },
        { titulo: 'Umbral', texto: 'Favorece la sensibilidad (no perder ataques) hasta el límite de 40 alertas/día.' },
        { titulo: 'Priorización', texto: 'Ordena por riesgo esperado; las 40 investigadas son las de mayor riesgo.' },
        { titulo: 'Explicabilidad', texto: 'Cada alerta incluye señales, desviación, activo y usuario.' },
        { titulo: 'Cola', texto: 'Define qué se hace con lo no investigado: reglas dedicadas + muestreo.' },
      ],
    },
    preguntas: [
      {
        q: 'En detección de intrusiones, ¿cómo calibras el umbral dado que un falso negativo puede ser una brecha y un falso positivo son 15 minutos de un analista?',
        opts: [
          'Minimizar el error total tratando ambos errores igual.',
          'Favorecer la sensibilidad (reducir falsos negativos) hasta el límite de falsos positivos que el equipo puede investigar, y documentar qué se hace con el resto.',
          'Eliminar todas las alertas dudosas.',
          'Fijar el umbral en 0,5 siempre.',
        ],
        a: 1,
        why: 'Los costes asimétricos exigen priorizar no perder ataques, acotado por la capacidad de respuesta del equipo.',
      },
      {
        q: '"Alerta: riesgo 0,91". ¿Por qué es una mala alerta?',
        opts: [
          'El número es demasiado alto.',
          'No es explicable: el analista no sabe qué señales la dispararon, qué activo ni qué usuario, así que no puede triarla ni responder.',
          'Debería ser 0,90.',
          'Falta el color rojo.',
        ],
        a: 1,
        why: 'Una alerta accionable indica el porqué: señales, desviación, activo y usuario; un score aislado no.',
      },
    ],
    fuentes: [F.ids, F.chio, F.nist2],
  },

  'Modelos generativos (intro)': {
    objetivo: 'Ver la simetría de la IA generativa en seguridad: la misma tecnología defiende y ataca.',
    terminos: [
      {
        n: 1,
        termino: 'Generación de datos sintéticos de ataques para entrenamiento',
        definicionTextual: 'Crear ejemplos artificiales de ataques (variantes de malware, tráfico de intrusión) para entrenar detectores cuando los ejemplos reales son escasos.',
        fuente: F.chio.titulo,
        idea: ['Mejora la cobertura del detector frente a variantes, siempre que los sintéticos capturen la variabilidad real del ataque.'],
        ejemplo: 'Generar variantes de un patrón de exfiltración para que el modelo aprenda a detectarlo aunque cambie el ritmo o el destino.',
        errorComun: 'Entrenar solo con sintéticos y no validar contra ataques reales.',
        fraseClave: 'Sintético para cubrir variantes que aún no has visto de verdad.',
      },
      {
        n: 2,
        termino: 'Uso ofensivo: phishing generado y deepfakes',
        definicionTextual: 'La IA generativa produce correos de phishing personalizados, convincentes y sin errores, y audio o vídeo falso de personas concretas.',
        fuente: F.owasp.titulo,
        idea: ['Baja la barrera del atacante: campañas de phishing dirigidas antes reservadas a grupos sofisticados ahora son accesibles y baratas.'],
        ejemplo: 'Un audio falso del director financiero autorizando una transferencia.',
        errorComun: 'Confiar en la formación anti-phishing basada en "detectar faltas de ortografía"; ya no las hay.',
        fraseClave: 'El phishing ya no se delata por los errores.',
      },
      {
        n: 3,
        termino: 'Malware polimórfico asistido por IA generativa',
        definicionTextual: 'Malware que cambia su código en cada infección para evadir la detección por firma, con la variación generada por un modelo.',
        fuente: F.atlas.titulo,
        idea: ['Refuerza el argumento de por qué la defensa no puede depender solo de firmas: hay que combinar con detección de comportamiento y de anomalías.'],
        ejemplo: 'Cada copia del malware tiene un aspecto distinto pero el mismo comportamiento en ejecución.',
        errorComun: 'Basar la detección solo en firmas estáticas.',
        fraseClave: 'Si el código cambia siempre, detecta lo que hace, no cómo se ve.',
      },
      {
        n: 4,
        termino: 'Simetría de la tecnología: mismo modelo, dos propósitos',
        definicionTextual: 'El mismo tipo de modelo generativo sirve para defender (datos de entrenamiento, resumen de incidentes) y para atacar (phishing, deepfakes); la tecnología es neutral, el uso no.',
        fuente: F.owasp.titulo,
        idea: ['El defensor debe planificar frente a ambos usos: asumir que el atacante tiene las mismas herramientas y adelantarse.'],
        ejemplo: 'Tu asistente de IA para analistas y el generador de phishing del atacante pueden ser el mismo modelo base.',
        errorComun: 'Ver la IA generativa solo como herramienta propia y no como capacidad del adversario.',
        fraseClave: 'La misma herramienta está en las dos manos.',
      },
    ],
    casoCompleto: {
      escenario: 'Evalúas el riesgo de que la IA generativa se use contra tu proceso de autorización de pagos.',
      pasos: [
        { titulo: 'Vector', texto: 'Deepfake de voz del responsable financiero autorizando una transferencia urgente.' },
        { titulo: 'Por qué funciona', texto: 'El proceso confía en la voz; la formación anti-phishing tradicional no cubre este caso.' },
        { titulo: 'Mitigación', texto: 'Segundo canal de confirmación independiente para importes altos, con código o contacto directo verificado.' },
        { titulo: 'Simetría', texto: 'Usa IA para detectar patrones anómalos de solicitud de pago (importe, urgencia, hora).' },
      ],
    },
    preguntas: [
      {
        q: 'La formación anti-phishing de tu empresa enseña a "detectar faltas de ortografía y saludos genéricos". ¿Sigue siendo suficiente?',
        opts: [
          'Sí, es lo esencial.',
          'No: la IA generativa produce correos personalizados y sin errores; la defensa debe apoyarse en verificación de canal, comportamiento y controles de proceso, no en detectar errores.',
          'Sí, si se actualiza cada año.',
          'Solo para correos en inglés.',
        ],
        a: 1,
        why: 'El phishing generado por IA elimina las pistas superficiales; hace falta defensa en profundidad y verificación fuera del canal.',
      },
      {
        q: '¿Qué implica la "simetría" de la IA generativa en seguridad?',
        opts: [
          'Que funciona igual de día y de noche.',
          'Que la misma tecnología sirve para defender y para atacar; el defensor debe asumir que el adversario tiene las mismas capacidades y adelantarse a ambos usos.',
          'Que hay que usar dos modelos.',
          'Que solo se ejecuta en la nube.',
        ],
        a: 1,
        why: 'La tecnología es neutral; planificar la defensa exige contemplar el uso ofensivo con las mismas herramientas.',
      },
    ],
    fuentes: [F.owasp, F.atlas, F.chio],
  },

  'Retos y oportunidades en ciberseguridad': {
    objetivo: 'Cerrar el programa: la carrera atacante-defensor, la escasez de talento híbrido y el sesgo en la detección.',
    terminos: [
      {
        n: 1,
        termino: 'Carrera armamentista entre atacantes y defensores',
        definicionTextual: 'Cada mejora defensiva provoca una adaptación ofensiva y viceversa; no hay un estado final "seguro", solo una ventaja temporal.',
        fuente: F.atlas.titulo,
        idea: ['Implica que la seguridad es un proceso continuo con inversión sostenida, no un proyecto que se cierra.'],
        ejemplo: 'Se despliega un detector de anomalías; los atacantes aprenden a moverse "dentro de lo normal" (living off the land).',
        errorComun: 'Tratar una nueva capacidad defensiva como una solución permanente.',
        fraseClave: 'No hay meta, solo ventaja temporal.',
      },
      {
        n: 2,
        termino: 'Escasez de talento especializado en IA + seguridad',
        definicionTextual: 'Faltan perfiles que dominen a la vez el modelado, el riesgo de seguridad y el marco regulatorio.',
        fuente: F.chio.titulo,
        idea: ['Es el mismo cuello de botella que en gobernanza (Asignatura V): el perfil puente escasea más que el técnico puro.'],
        ejemplo: 'El equipo puede construir un detector, pero no sabe evaluar cómo se atacaría ese detector.',
        errorComun: 'Cubrir la vacante con un perfil solo técnico o solo de seguridad y esperar que aprenda la otra mitad sobre la marcha.',
        fraseClave: 'El perfil híbrido es el recurso escaso.',
      },
      {
        n: 3,
        termino: 'Sesgo y equidad en sistemas de detección (falsos positivos desiguales)',
        definicionTextual: 'Un detector puede generar más falsos positivos sobre ciertos usuarios, equipos o comportamientos legítimos, sometiéndolos a más fricción y vigilancia.',
        fuente: F.nist2.titulo,
        idea: ['La equidad también aplica a la seguridad: hay que medir la tasa de falsos positivos por grupo y por rol, no solo la global.'],
        ejemplo: 'Un modelo que marca sistemáticamente como sospechoso el trabajo de un equipo que usa herramientas poco comunes pero legítimas.',
        errorComun: 'Asumir que un sistema de seguridad "no puede ser injusto" porque su objetivo es proteger.',
        fraseClave: 'Un detector también puede discriminar.',
      },
      {
        n: 4,
        termino: 'Síntesis del programa completo aplicada a un dominio crítico',
        definicionTextual: 'La Asignatura XI reúne datos (III), ML (VI), generativa (IX), ética y gobernanza (V) y criterio de evaluación (II) sobre un dominio donde el error tiene consecuencias graves.',
        fuente: 'Síntesis del programa',
        idea: ['El proyecto pide analizar un sistema real desde la defensa y el ataque, con mitigaciones concretas y controles mapeados a ISO 27001/42001: es el ejercicio integrador del máster.'],
        ejemplo: 'Modelo de amenazas de tu proceso de pagos: cómo lo defiende la IA y cómo lo atacaría la IA generativa, con una mitigación real.',
        errorComun: 'Tratar el proyecto como una lista de miedos en vez de un informe con criticidad, evidencia y mitigación.',
        fraseClave: 'Aquí se junta todo el programa sobre un problema que importa.',
      },
    ],
    casoCompleto: {
      escenario: 'Preparas el proyecto integrador: modelo de amenazas de un proceso real desde los dos ángulos.',
      pasos: [
        { titulo: 'Defensa', texto: 'Cómo la IA detectaría o clasificaría la amenaza sobre ese proceso.' },
        { titulo: 'Ataque', texto: 'Cómo la IA generativa lo atacaría (phishing dirigido, deepfake, evasión).' },
        { titulo: 'Mitigación', texto: 'Al menos una medida concreta que dificulte el ataque, con su coste y fricción.' },
        { titulo: 'Controles', texto: 'Mapea la mitigación a un control de ISO 27001 y 42001.' },
        { titulo: 'Equidad', texto: 'Comprueba que el detector propuesto no penaliza de forma desigual a usuarios legítimos.' },
      ],
    },
    preguntas: [
      {
        q: '"Nuestro sistema de detección no puede ser injusto porque su objetivo es proteger a todos". ¿Correcto?',
        opts: [
          'Sí, la seguridad es neutral por definición.',
          'No: un detector puede generar más falsos positivos sobre ciertos grupos o roles legítimos, sometiéndolos a más fricción; hay que medir la tasa de falsos positivos por subgrupo.',
          'Sí, si no usa datos personales.',
          'Solo si el modelo es supervisado.',
        ],
        a: 1,
        why: 'La equidad aplica también a la seguridad: el impacto desigual de los falsos positivos es un problema real que hay que medir.',
      },
      {
        q: 'La "carrera armamentista" entre atacantes y defensores implica que:',
        opts: [
          'Con suficiente inversión se alcanza un estado seguro y estable.',
          'No hay estado final: cada mejora provoca adaptación del otro lado; la seguridad es un proceso continuo con inversión sostenida, no un proyecto que se cierra.',
          'Los atacantes siempre ganan.',
          'Los defensores siempre ganan.',
        ],
        a: 1,
        why: 'La ventaja es siempre temporal; tratar una capacidad defensiva como solución permanente es el error típico.',
      },
    ],
    fuentes: [F.atlas, F.chio, F.nist2, F.owasp],
  },
};
