// Lectura guiada — Asignatura IX: IA Generativa en la Industria 4.0.
const F = {
  hf: { titulo: 'LLM Course (Hugging Face)', url: 'https://huggingface.co/learn' },
  raschka: { titulo: 'Build a Large Language Model (From Scratch) — Sebastian Raschka' },
  dlai: { titulo: 'Cursos cortos DeepLearning.AI (RAG, evaluación de LLMs, agentes)', url: 'https://www.deeplearning.ai/short-courses/' },
  cmapss: { titulo: 'NASA C-MAPSS — degradación de turbofán (dataset)', url: 'https://www.nasa.gov/intelligent-systems-division/discovery-and-systems-health/pcoe/pcoe-data-set-repository/' },
  anthropicctx: { titulo: 'Contextual Retrieval (Anthropic)', url: 'https://www.anthropic.com/news/contextual-retrieval' },
};

module.exports = {
  'Conceptos básicos de IA Generativa': {
    objetivo: 'Situar la IA generativa en la Industria 4.0 y distinguir un piloto de un sistema en producción.',
    terminos: [
      {
        n: 1,
        termino: 'Diseño generativo (generative design)',
        definicionTextual: 'Uso de modelos que proponen múltiples variantes de un diseño (una pieza, un plano, un layout) a partir de restricciones y objetivos, para que un ingeniero elija y refine.',
        fuente: 'DeepLearning.AI — cursos de IA generativa aplicada',
        idea: ['El modelo no sustituye al ingeniero: amplía el espacio de opciones exploradas y acorta la iteración. La decisión y la validación siguen siendo humanas.'],
        ejemplo: 'Un software propone 40 geometrías de un soporte que cumplen el peso y la resistencia; el ingeniero descarta 37 por fabricabilidad.',
        errorComun: 'Tratar la salida del diseño generativo como un plano final en vez de como un punto de partida a validar.',
        fraseClave: 'Genera opciones, no decisiones.',
      },
      {
        n: 2,
        termino: 'Datos sintéticos para entrenamiento',
        definicionTextual: 'Datos generados artificialmente que imitan la distribución de datos reales, usados para entrenar cuando los reales son escasos, caros o sensibles.',
        fuente: F.hf.titulo,
        idea: ['Su valor depende de cuánto se parezcan a los reales en lo que importa para la tarea. Un modelo entrenado solo con sintéticos puede fallar en producción si la síntesis omitió un patrón real.'],
        ejemplo: 'Generar variantes sintéticas de un defecto de soldadura raro para que el inspector visual lo aprenda a detectar.',
        errorComun: 'Asumir que "más datos sintéticos" siempre mejora; si no aportan variabilidad real, solo refuerzan lo que el modelo ya sabía.',
        fraseClave: 'Sintético sirve si captura lo que el real tiene y tú necesitas.',
      },
      {
        n: 3,
        termino: 'Gemelos digitales enriquecidos con contenido generado',
        definicionTextual: 'Réplicas virtuales de un activo o proceso a las que la IA generativa añade escenarios simulados (fallos, condiciones extremas) que serían caros o peligrosos de reproducir físicamente.',
        fuente: 'Bibliografía de Industria 4.0 de la asignatura',
        idea: ['El gemelo digital simula; la IA generativa amplía qué escenarios puede simular con realismo.'],
        ejemplo: 'Simular en el gemelo cómo se degradaría una bomba bajo 200 combinaciones de temperatura y carga generadas por el modelo.',
        errorComun: 'Confundir el gemelo digital con un panel de monitoreo; el gemelo permite simular el futuro, no solo ver el presente.',
        fraseClave: 'El gemelo prueba escenarios que la planta no te deja probar.',
      },
      {
        n: 4,
        termino: 'Madurez de la aplicación: piloto frente a producción',
        definicionTextual: 'Piloto: demuestra que la idea funciona en condiciones controladas. Producción: opera de forma fiable, a coste conocido, con mantenimiento y supervisión.',
        fuente: F.dlai.titulo,
        idea: ['El salto de piloto a producción concentra la mayor parte del esfuerzo real: coste a escala, latencia bajo carga, mantenimiento del sistema y del corpus, y control de la salida generada.'],
        ejemplo: 'Un asistente RAG que responde bien con 20 documentos de prueba puede tener una tasa de alucinación inaceptable con los 5.000 reales.',
        errorComun: 'Presentar el piloto como si fuera producción y sorprenderse cuando el coste o la calidad no aguantan a escala.',
        fraseClave: 'El piloto demuestra; producción cuesta.',
      },
    ],
    casoCompleto: {
      escenario: 'Propones una aplicación de IA generativa para acelerar la documentación técnica de tu planta.',
      pasos: [
        { titulo: 'Diseño generativo', texto: 'El modelo redacta borradores de procedimiento a partir de datos del equipo; un técnico valida.' },
        { titulo: 'Datos', texto: 'Necesitas un corpus de procedimientos existentes; evalúa si hay suficientes y de calidad.' },
        { titulo: 'Piloto', texto: 'Prueba con 3 tipos de equipo y mide tiempo ahorrado y correcciones necesarias.' },
        { titulo: 'Producción', texto: 'Antes de escalar: coste por documento, quién mantiene el corpus, y el punto de revisión humana antes de publicar.' },
      ],
    },
    preguntas: [
      {
        q: 'Un piloto de RAG funciona bien con 20 documentos. ¿Qué NO puedes concluir para producción?',
        opts: [
          'Que la idea tiene potencial.',
          'Que el coste por consulta, la latencia bajo carga y la tasa de alucinación con el corpus completo serán aceptables a escala.',
          'Que el equipo entendió el problema.',
          'Que existe un caso de uso.',
        ],
        a: 1,
        why: 'El piloto pequeño no demuestra el comportamiento a escala: coste, latencia, alucinación con el corpus real y mantenimiento.',
      },
      {
        q: '¿Cuándo aportan valor los datos sintéticos?',
        opts: [
          'Siempre que se generen muchos.',
          'Cuando capturan la variabilidad real que importa para la tarea y que los datos reales no cubren (p. ej. un defecto raro).',
          'Solo si son idénticos a los reales.',
          'Nunca; siempre degradan el modelo.',
        ],
        a: 1,
        why: 'El valor está en aportar variabilidad realista ausente en los datos reales, no en el volumen.',
      },
    ],
    fuentes: [F.hf, F.dlai, F.raschka],
  },

  'Paradigmas de ML en la IA Generativa': {
    objetivo: 'Entender por qué la autosupervisión permite entrenar a escala sin etiquetas y qué son las capacidades emergentes.',
    terminos: [
      {
        n: 1,
        termino: 'Aprendizaje autosupervisado (self-supervised)',
        definicionTextual: 'Entrenamiento en el que la señal de aprendizaje se construye a partir de los propios datos, sin etiquetas humanas.',
        fuente: F.raschka.titulo,
        idea: ['Elimina el cuello de botella del etiquetado manual: cualquier texto o imagen sirve como material de entrenamiento.'],
        ejemplo: 'Ocultar una palabra de una frase y pedir al modelo que la prediga; la frase original es la "respuesta".',
        errorComun: 'Confundirlo con "no supervisado": la autosupervisión sí tiene una tarea con respuesta correcta, solo que la genera de los datos.',
        fraseClave: 'Los datos se etiquetan a sí mismos.',
      },
      {
        n: 2,
        termino: 'Tarea de pretexto (pretext task)',
        definicionTextual: 'La tarea auxiliar que se le pone al modelo (predecir la siguiente palabra, reconstruir una región oculta) para que, al resolverla, aprenda estructura útil.',
        fuente: F.hf.titulo,
        idea: ['La tarea de pretexto no es el objetivo final; es el andamio. Resolver "predice la siguiente palabra" obliga al modelo a aprender gramática, hechos y razonamiento.'],
        ejemplo: 'La tarea de pretexto de un modelo de imágenes puede ser recolorear una foto en blanco y negro.',
        errorComun: 'Evaluar el modelo por su rendimiento en la tarea de pretexto en vez de por la tarea real que interesa.',
        fraseClave: 'La tarea de pretexto es el medio, no el fin.',
      },
      {
        n: 3,
        termino: 'Preentrenamiento a gran escala frente a ajuste fino específico',
        definicionTextual: 'Preentrenamiento: aprender capacidades generales de un corpus enorme. Ajuste fino: adaptar ese modelo a un dominio o comportamiento concreto con muchos menos datos.',
        fuente: F.dlai.titulo,
        idea: ['Para un proyecto industrial casi nunca se preentrena desde cero: se parte de un modelo general y se ajusta o se le da contexto (RAG).'],
        ejemplo: 'Un modelo general de lenguaje ajustado con 500 informes de tu sector para que use su terminología.',
        errorComun: 'Plantear "entrenar nuestro propio modelo" cuando lo que se necesita es ajuste fino o RAG sobre uno existente.',
        fraseClave: 'Preentrenas capacidad; ajustas comportamiento.',
      },
      {
        n: 4,
        termino: 'Emergencia de capacidades no programadas explícitamente',
        definicionTextual: 'Habilidades (traducir, razonar en pasos, seguir instrucciones) que aparecen al escalar el modelo y los datos, sin que nadie las entrenara de forma directa.',
        fuente: F.raschka.titulo,
        idea: ['La emergencia es a la vez la promesa y el riesgo: capacidades útiles no previstas, pero también comportamientos no deseados difíciles de anticipar.'],
        ejemplo: 'Un modelo entrenado solo para predecir texto resulta capaz de resolver problemas aritméticos sencillos.',
        errorComun: 'Asumir que si una capacidad no se entrenó, no existe; o al revés, esperar capacidades que el modelo no tiene.',
        fraseClave: 'Escalar trae capacidades que nadie pidió, buenas y malas.',
      },
    ],
    casoCompleto: {
      escenario: 'Tu área quiere un asistente que responda preguntas sobre normativa interna con el lenguaje de la casa.',
      pasos: [
        { titulo: 'No preentrenar', texto: 'Parte de un modelo general; preentrenar desde cero es inviable.' },
        { titulo: 'RAG o ajuste', texto: 'Si la información cambia, usa RAG; si quieres fijar el estilo, ajuste fino con ejemplos.' },
        { titulo: 'Evaluar la tarea real', texto: 'Mide aciertos sobre preguntas reales, no la perplejidad del modelo.' },
        { titulo: 'Vigilar emergencia', texto: 'Prueba comportamientos no deseados (responder fuera de alcance, inventar cláusulas).' },
      ],
    },
    preguntas: [
      {
        q: 'Necesitas que un LLM responda con datos internos que cambian cada semana. ¿RAG o ajuste fino?',
        opts: [
          'Ajuste fino: reentrenar cada semana.',
          'RAG: recuperar los fragmentos actuales y pasarlos como contexto; el ajuste fino es para fijar estilo/comportamiento estable, no información cambiante.',
          'Ninguno funciona.',
          'Preentrenar un modelo propio.',
        ],
        a: 1,
        why: 'RAG separa el conocimiento (cambiante, en el índice) del comportamiento (estable, en el modelo).',
      },
      {
        q: '¿Qué es la "tarea de pretexto"?',
        opts: [
          'La tarea final que interesa al negocio.',
          'La tarea auxiliar generada de los datos (predecir la siguiente palabra, reconstruir una parte oculta) que, al resolverse, hace que el modelo aprenda estructura útil.',
          'Un examen para el modelo.',
          'La tarea de etiquetado manual.',
        ],
        a: 1,
        why: 'Es el andamio de entrenamiento: resolverla obliga al modelo a aprender lo que luego se aprovecha en la tarea real.',
      },
    ],
    fuentes: [F.raschka, F.hf, F.dlai],
  },

  'Redes Neuronales Generativas': {
    objetivo: 'Entender el entrenamiento adversarial de las GAN y su fallo característico, el colapso de modo.',
    terminos: [
      {
        n: 1,
        termino: 'Generador y discriminador',
        definicionTextual: 'La GAN entrena dos redes en competencia: el generador crea muestras falsas y el discriminador intenta distinguir las falsas de las reales.',
        fuente: F.hf.titulo,
        idea: ['Cada red mejora forzando a la otra a mejorar: si el discriminador acierta mucho, el generador aprende a engañarlo mejor.'],
        ejemplo: 'Generador: crea imágenes de piezas. Discriminador: dice "esta pieza es real / generada".',
        errorComun: 'Pensar que el generador aprende de ejemplos reales directamente; aprende solo de la señal del discriminador.',
        fraseClave: 'Dos redes que se entrenan peleando.',
      },
      {
        n: 2,
        termino: 'Entrenamiento adversarial',
        definicionTextual: 'El proceso de optimización en el que la mejora de una red es la pérdida de la otra, buscando un equilibrio.',
        fuente: F.raschka.titulo,
        idea: ['Es inestable por naturaleza: si una red domina a la otra demasiado pronto, el entrenamiento se estanca o colapsa.'],
        ejemplo: 'Si el discriminador se vuelve perfecto, el generador deja de recibir señal útil y no aprende.',
        errorComun: 'Esperar que el entrenamiento adversarial converja suave como el de un modelo supervisado.',
        fraseClave: 'La inestabilidad no es un bug de las GAN, es su naturaleza.',
      },
      {
        n: 3,
        termino: 'Colapso de modo (mode collapse)',
        definicionTextual: 'El generador aprende a producir solo unas pocas variantes que engañan bien al discriminador, perdiendo la diversidad de los datos reales.',
        fuente: F.dlai.titulo,
        idea: ['Es el fallo característico de las GAN: el modelo "acierta" pero repite. En una aplicación industrial significa datos sintéticos poco variados y por tanto poco útiles.'],
        ejemplo: 'Un generador de defectos que solo produce el mismo tipo de grieta una y otra vez.',
        errorComun: 'No detectar el colapso porque las muestras individuales se ven bien; hay que medir la diversidad del conjunto.',
        fraseClave: 'Muestras buenas, variedad nula: eso es colapso de modo.',
      },
      {
        n: 4,
        termino: 'Aplicaciones industriales de GAN',
        definicionTextual: 'Generación de datos sintéticos para aumentar conjuntos de entrenamiento, mejora de resolución de imágenes de inspección, simulación de condiciones raras.',
        fuente: 'Bibliografía de la asignatura',
        idea: ['Cuando la restricción es la velocidad de inferencia y se tolera cierta inestabilidad en el entrenamiento, la GAN sigue siendo competitiva frente a la difusión.'],
        ejemplo: 'Aumentar un dataset de 200 imágenes de una avería infrecuente a 2.000 para entrenar un detector.',
        errorComun: 'Usar GAN por defecto sin comparar con VAE o difusión según el trade-off del caso.',
        fraseClave: 'GAN cuando la inferencia rápida pesa más que la estabilidad del entrenamiento.',
      },
    ],
    casoCompleto: {
      escenario: 'Quieres generar imágenes sintéticas de un defecto raro para entrenar un inspector visual.',
      pasos: [
        { titulo: 'Elección', texto: 'GAN si necesitas inferencia rápida y toleras un entrenamiento delicado; difusión si priorizas calidad y variedad.' },
        { titulo: 'Entrenamiento', texto: 'Vigila que el discriminador no domine demasiado pronto.' },
        { titulo: 'Colapso', texto: 'Mide la diversidad del conjunto generado, no solo la calidad de cada imagen.' },
        { titulo: 'Validación', texto: 'Comprueba que el detector entrenado con sintéticos generaliza a defectos reales.' },
      ],
    },
    preguntas: [
      {
        q: 'Tu GAN genera imágenes realistas pero todas muy parecidas entre sí. ¿Qué está pasando?',
        opts: [
          'Sobreajuste del discriminador; añade capas.',
          'Colapso de modo: el generador produce solo unas pocas variantes; hay que medir y forzar diversidad, no solo calidad individual.',
          'Falta de GPU.',
          'El dataset real es demasiado grande.',
        ],
        a: 1,
        why: 'Calidad alta + variedad nula es la firma del colapso de modo, el fallo característico de las GAN.',
      },
      {
        q: '¿De qué aprende el generador de una GAN?',
        opts: [
          'De los ejemplos reales directamente.',
          'Solo de la señal del discriminador: qué tan bien o mal engañó a la red que intenta distinguir real de falso.',
          'De etiquetas humanas.',
          'De un modelo de lenguaje.',
        ],
        a: 1,
        why: 'El generador nunca ve los datos reales; ajusta sus salidas según si el discriminador las clasifica como reales o falsas.',
      },
    ],
    fuentes: [F.hf, F.raschka, F.dlai],
  },

  'Modelos Generativos': {
    objetivo: 'Comparar autoencoders, VAE y difusión por el trade-off estabilidad / coste de inferencia / calidad.',
    terminos: [
      {
        n: 1,
        termino: 'Autoencoder y espacio latente',
        definicionTextual: 'Un autoencoder comprime la entrada a una representación pequeña (el espacio latente) y luego la reconstruye; el latente captura los rasgos esenciales.',
        fuente: F.raschka.titulo,
        idea: ['El autoencoder básico reconstruye pero no genera muestras nuevas coherentes: el espacio latente tiene "huecos".'],
        ejemplo: 'Comprimir una imagen de 1 MB a 64 números y volver a expandirla con pérdida controlada.',
        errorComun: 'Esperar que un autoencoder simple genere ejemplos nuevos plausibles muestreando el latente al azar.',
        fraseClave: 'Comprime y reconstruye; generar es otra cosa.',
      },
      {
        n: 2,
        termino: 'Autoencoder variacional (VAE) y su regularización probabilística',
        definicionTextual: 'Un VAE fuerza a que el espacio latente siga una distribución conocida (normalmente una gaussiana), de modo que muestrear de esa distribución produce ejemplos nuevos coherentes.',
        fuente: F.hf.titulo,
        idea: ['Es estable de entrenar y permite interpolar entre ejemplos, pero sus muestras suelen ser algo borrosas frente a GAN o difusión.'],
        ejemplo: 'Generar variantes intermedias entre dos diseños de pieza recorriendo el latente.',
        errorComun: 'Descartar el VAE por "borroso" sin considerar que su estabilidad y su latente estructurado son ventajas reales.',
        fraseClave: 'VAE: estable y explorable, a cambio de algo de nitidez.',
      },
      {
        n: 3,
        termino: 'Modelo de difusión: ruido progresivo y su reversión',
        definicionTextual: 'La difusión aprende a quitar ruido paso a paso: se entrena añadiendo ruido a datos reales y enseñando al modelo a revertirlo; genera partiendo de ruido puro.',
        fuente: F.dlai.titulo,
        idea: ['Da la mayor calidad y diversidad, pero cada muestra requiere muchos pasos de inferencia, lo que la hace costosa en tiempo y cómputo.'],
        ejemplo: 'Generar una imagen de alta calidad en 50 pasos de "quitar un poco de ruido" cada vez.',
        errorComun: 'Elegir difusión para un caso con requisito estricto de latencia sin evaluar el coste por muestra.',
        fraseClave: 'Difusión: máxima calidad, máxima factura de inferencia.',
      },
      {
        n: 4,
        termino: 'Costo computacional en inferencia frente a entrenamiento',
        definicionTextual: 'Coste de entrenamiento: una vez, al construir el modelo. Coste de inferencia: cada vez que se genera una muestra en producción.',
        fuente: 'Bibliografía de la asignatura',
        idea: ['La elección de arquitectura debe pesar dónde está la restricción: si generas millones de muestras al día, el coste de inferencia domina la decisión.'],
        ejemplo: 'GAN entrena mal pero infiere en milisegundos; difusión entrena mejor pero cada muestra tarda segundos.',
        errorComun: 'Comparar arquitecturas solo por la calidad de la muestra, ignorando cuántas vas a generar y con qué latencia.',
        fraseClave: 'Elige por dónde te va a doler el coste: al construir o al usar.',
      },
    ],
    casoCompleto: {
      escenario: 'Debes elegir arquitectura para generar 10.000 imágenes sintéticas al día en lotes nocturnos.',
      pasos: [
        { titulo: 'Latencia', texto: 'Lotes nocturnos: la latencia por muestra no es una restricción dura.' },
        { titulo: 'Calidad y variedad', texto: 'Sí importan: priorizas difusión o VAE frente a GAN.' },
        { titulo: 'Coste de inferencia', texto: '10.000 muestras/día con difusión: calcula horas de cómputo y si lo resuelves con paralelismo.' },
        { titulo: 'Decisión', texto: 'Difusión si el cómputo nocturno lo aguanta; VAE si buscas estabilidad y latente explorable con menos coste.' },
      ],
    },
    preguntas: [
      {
        q: 'Sistema que genera 10.000 imágenes/día en lotes nocturnos, sin requisito de tiempo real. ¿Difusión o GAN?',
        opts: [
          'GAN, siempre que sea más rápida.',
          'Difusión: sin presión de latencia, se prioriza calidad y estabilidad; el coste de inferencia se absorbe con el cómputo nocturno y paralelismo.',
          'Ninguna sirve.',
          'Reducir a 100 imágenes.',
        ],
        a: 1,
        why: 'La velocidad de la GAN solo compensa si la latencia es una restricción real, que aquí no lo es.',
      },
      {
        q: '¿Por qué un autoencoder básico no sirve para generar ejemplos nuevos y un VAE sí?',
        opts: [
          'El VAE tiene más capas.',
          'El VAE regulariza el espacio latente para que siga una distribución conocida; muestrear de ella produce ejemplos coherentes. El autoencoder básico deja huecos en el latente.',
          'El autoencoder no comprime.',
          'Son equivalentes.',
        ],
        a: 1,
        why: 'La regularización probabilística del VAE es lo que hace que el latente sea "muestreadable".',
      },
    ],
    fuentes: [F.raschka, F.hf, F.dlai],
  },

  'IA Generativa para contenido Multimedia y multimodal': {
    objetivo: 'Ver el flujo generativo de extremo a extremo aplicado a documentación y operación de planta.',
    terminos: [
      {
        n: 1,
        termino: 'Generación de documentación técnica multimodal',
        definicionTextual: 'Producir procedimientos, fichas y manuales combinando texto generado, diagramas y, si aplica, imágenes o audio, a partir de datos del equipo y de plantillas.',
        fuente: F.anthropicctx.titulo,
        idea: ['Acelera el borrador; la revisión técnica humana antes de publicar es innegociable, porque un procedimiento erróneo tiene consecuencias físicas.'],
        ejemplo: 'A partir de la ficha técnica de una bomba, generar el borrador del procedimiento de mantenimiento preventivo.',
        errorComun: 'Publicar la salida generada sin que un técnico responsable la valide.',
        fraseClave: 'La IA hace el borrador; la firma es humana.',
      },
      {
        n: 2,
        termino: 'Síntesis de voz para instrucciones de planta',
        definicionTextual: 'Convertir instrucciones escritas en audio claro para operarios que trabajan con las manos ocupadas o en entornos donde leer no es práctico.',
        fuente: F.dlai.titulo,
        idea: ['El valor está en la accesibilidad operativa; el riesgo, en errores de pronunciación de términos técnicos o de números críticos.'],
        ejemplo: 'Instrucciones de par de apriete leídas por audio mientras el operario usa la llave dinamométrica.',
        errorComun: 'No revisar cómo el sintetizador lee unidades, tolerancias y códigos de pieza.',
        fraseClave: 'Verifica cómo suena un número antes de confiar en el audio.',
      },
      {
        n: 3,
        termino: 'Traducción y localización automática de manuales',
        definicionTextual: 'Adaptar documentación a otros idiomas y contextos, manteniendo la terminología técnica y las unidades correctas.',
        fuente: F.hf.titulo,
        idea: ['La traducción genérica falla en el vocabulario de dominio; conviene un glosario fijo y revisión por alguien que conozca el equipo en el idioma destino.'],
        ejemplo: 'Traducir el manual de una línea de envasado del inglés al español de planta, respetando los nombres de los componentes.',
        errorComun: 'Confiar en la traducción automática para seguridad y advertencias sin revisión especializada.',
        fraseClave: 'El manual traducido necesita un revisor que conozca la máquina.',
      },
      {
        n: 4,
        termino: 'Flujo de trabajo generativo de extremo a extremo',
        definicionTextual: 'La cadena completa: datos del equipo → generación de borrador → revisión humana → publicación → actualización cuando el equipo o el proceso cambian.',
        fuente: F.anthropicctx.titulo,
        idea: ['El flujo no termina en la generación: incluye el mantenimiento del contenido y del sistema. Sin ese cierre, la documentación generada envejece igual que la escrita a mano.'],
        ejemplo: 'Cuando se cambia una pieza, el flujo dispara la regeneración del procedimiento afectado y su revisión.',
        errorComun: 'Montar la generación y olvidar el paso de actualización ante cambios.',
        fraseClave: 'Generar es un paso del flujo, no el flujo entero.',
      },
    ],
    casoCompleto: {
      escenario: 'Diseñas el flujo generativo para mantener al día 400 procedimientos de planta.',
      pasos: [
        { titulo: 'Entrada', texto: 'Fichas técnicas y datos de equipos como fuente estructurada.' },
        { titulo: 'Generación', texto: 'Borradores de procedimiento con plantilla fija y terminología controlada.' },
        { titulo: 'Revisión', texto: 'Un técnico responsable valida y firma antes de publicar.' },
        { titulo: 'Multimodal', texto: 'Versión en audio para tareas manuales, con revisión de cómo se leen números y unidades.' },
        { titulo: 'Mantenimiento', texto: 'Cambio de pieza → regeneración del procedimiento afectado → nueva revisión.' },
      ],
    },
    preguntas: [
      {
        q: '¿Cuál es el paso innegociable al generar documentación técnica de planta?',
        opts: [
          'Que el texto sea largo.',
          'La revisión y firma de un técnico responsable antes de publicar, porque un procedimiento erróneo tiene consecuencias físicas.',
          'Que se genere en varios idiomas a la vez.',
          'Que use el modelo más grande.',
        ],
        a: 1,
        why: 'La generación acelera el borrador, pero la responsabilidad del contenido publicado es humana.',
      },
      {
        q: 'Montas la generación de procedimientos pero no un mecanismo de actualización. ¿Qué ocurre?',
        opts: [
          'Nada, la documentación generada no envejece.',
          'La documentación generada queda obsoleta igual que la escrita a mano cuando el equipo o el proceso cambian; el flujo debe incluir la actualización.',
          'El modelo se corrige solo.',
          'Los procedimientos se borran automáticamente.',
        ],
        a: 1,
        why: 'El flujo de extremo a extremo incluye el mantenimiento; sin él, el beneficio inicial se pierde con el tiempo.',
      },
    ],
    fuentes: [F.anthropicctx, F.hf, F.dlai],
  },

  'Tendencias y dirección futura de la IA Generativa': {
    objetivo: 'Aplicar el criterio de evaluación de tecnologías emergentes a la IA generativa, sin quedarse en el titular.',
    terminos: [
      {
        n: 1,
        termino: 'Modelos más pequeños y eficientes (frente a más grandes)',
        definicionTextual: 'Tendencia a modelos que, con menos parámetros, alcanzan un rendimiento suficiente para la tarea, con menor coste de inferencia y posibilidad de ejecución local.',
        fuente: F.dlai.titulo,
        idea: ['Para un caso industrial concreto, un modelo pequeño especializado suele ser mejor decisión que el mayor modelo generalista: más barato, más rápido, más controlable.'],
        ejemplo: 'Un modelo pequeño ajustado a la terminología de tu sector que corre en un servidor propio.',
        errorComun: 'Elegir el modelo más grande "por si acaso" cuando la tarea no lo necesita.',
        fraseClave: 'Grande impresiona; el pequeño adecuado resuelve.',
      },
      {
        n: 2,
        termino: 'Agentes autónomos que ejecutan tareas de varios pasos',
        definicionTextual: 'Sistemas en los que el modelo planifica y ejecuta una secuencia de acciones (consultar, calcular, llamar a una herramienta) para lograr un objetivo, no solo responder.',
        fuente: F.dlai.titulo,
        idea: ['Aumentan el alcance pero también la superficie de error y de riesgo: cada paso puede fallar o desviarse; requieren límites, registro y revisión.'],
        ejemplo: 'Un agente que, ante una alerta, consulta el histórico, propone una causa y redacta el informe preliminar.',
        errorComun: 'Dar a un agente autónomo permisos amplios sin límites ni trazabilidad de lo que hace.',
        fraseClave: 'Más autonomía, más que vigilar.',
      },
      {
        n: 3,
        termino: 'Modelos especializados por dominio industrial',
        definicionTextual: 'Modelos ajustados o entrenados con datos de un sector (energía, farma, automoción) que entienden su vocabulario, sus normas y sus procesos.',
        fuente: F.hf.titulo,
        idea: ['La especialización reduce alucinaciones en el dominio y mejora la utilidad, a cambio de menos versatilidad fuera de él.'],
        ejemplo: 'Un modelo que conoce la nomenclatura de fallos de tu tipo de maquinaria.',
        errorComun: 'Esperar que un modelo generalista rinda como uno especializado en tareas de nicho.',
        fraseClave: 'En tu dominio, el especialista gana al generalista.',
      },
      {
        n: 4,
        termino: 'Aplicar el criterio de evaluación de tecnologías emergentes',
        definicionTextual: 'La rejilla del programa: qué problema resuelve, en qué fase de expectativa está, de qué depende y cuál es la barrera de adopción real.',
        fuente: 'Asignatura II del programa (recurrente)',
        idea: ['Ante cada nueva ola generativa (video, agentes, modelos multimodales grandes), la pregunta no es "¿es impresionante?" sino "¿resuelve un problema mío y puedo adoptarlo?".'],
        ejemplo: 'La generación de video: problema real en formación y marketing, pero coste, control y coherencia temporal aún inmaduros para muchos usos.',
        errorComun: 'Adoptar la última capacidad generativa por no "quedarse atrás", antes de que madure la dependencia o baje la barrera.',
        fraseClave: 'La pregunta es "¿me sirve y puedo?", no "¿mola?".',
      },
    ],
    casoCompleto: {
      escenario: 'Un proveedor te ofrece integrar generación de video para tus manuales de formación.',
      pasos: [
        { titulo: 'Problema', texto: '¿Los vídeos de formación son un cuello real hoy? ¿Cuánto cuesta producirlos a mano?' },
        { titulo: 'Madurez', texto: 'Evalúa coherencia temporal, control del contenido y coste por minuto en el estado actual.' },
        { titulo: 'Dependencias', texto: '¿Necesitas guion estructurado, avatares, revisión? ¿Está todo disponible?' },
        { titulo: 'Barrera', texto: '¿Quién revisa cada vídeo? ¿Tu equipo sabe operar la herramienta? Esa es la barrera real.' },
        { titulo: 'Decisión', texto: 'Piloto acotado con criterios de reactivación, o esperar con fecha de revisión.' },
      ],
    },
    preguntas: [
      {
        q: 'Para una tarea industrial concreta y acotada, ¿modelo grande generalista o pequeño especializado?',
        opts: [
          'Siempre el más grande.',
          'A menudo el pequeño especializado: más barato, más rápido, más controlable y con menos alucinaciones en el dominio; el grande solo si la tarea exige su versatilidad.',
          'Siempre el más pequeño.',
          'Da igual, rinden lo mismo.',
        ],
        a: 1,
        why: 'La tendencia y el criterio de ingeniería favorecen el modelo adecuado a la tarea, no el mayor disponible.',
      },
      {
        q: 'Ante una nueva capacidad generativa muy publicitada, ¿qué preguntas primero según el criterio del programa?',
        opts: [
          '¿Es la más avanzada del mercado?',
          '¿Resuelve un problema real que tengo, en qué fase de madurez está, de qué depende y cuál es la barrera de adopción organizacional?',
          '¿La usa la competencia?',
          '¿Cuántos parámetros tiene?',
        ],
        a: 1,
        why: 'La rejilla problema / madurez / dependencias / barrera es la que evita adoptar por moda.',
      },
    ],
    fuentes: [F.dlai, F.hf, F.raschka],
  },
};
