// Lectura guiada — Asignatura X: AI Platforms (lecciones densas L1-L3).
const F = {
  huyen: { titulo: 'Designing Machine Learning Systems — Chip Huyen' },
  madewithml: { titulo: 'Made With ML', url: 'https://madewithml.com/' },
  mlflow: { titulo: 'MLflow — documentación', url: 'https://mlflow.org/docs/latest/index.html' },
};

module.exports = {
  'Computación en la nube': {
    objetivo: 'Fijar los modelos de servicio (IaaS/PaaS/SaaS), la elasticidad y el riesgo de dependencia del proveedor.',
    terminos: [
      {
        n: 1,
        termino: 'IaaS, PaaS y SaaS',
        definicionTextual: 'IaaS: alquilas infraestructura (máquinas, red, almacenamiento). PaaS: alquilas un entorno donde despliegas tu código. SaaS: consumes una capacidad ya construida.',
        fuente: F.huyen.titulo,
        idea: ['Cuanto más arriba en la pila (hacia SaaS), menos gestionas y menos controlas; la elección depende de cuánto control necesitas y cuánto equipo tienes para operar.'],
        ejemplo: 'IaaS: una VM vacía. PaaS: un servicio que ejecuta tu contenedor. SaaS: una API de transcripción por llamada.',
        errorComun: 'Elegir IaaS "para tener control" cuando no hay equipo para operarlo, o SaaS cuando el caso exige control del dato.',
        fraseClave: 'Más arriba en la pila: menos trabajo, menos control.',
      },
      {
        n: 2,
        termino: 'Elasticidad',
        definicionTextual: 'La capacidad de cómputo y almacenamiento se ajusta hacia arriba o hacia abajo según la demanda, y se paga por lo usado.',
        fuente: F.madewithml.titulo,
        idea: ['Es la ventaja clave para cargas variables (picos estacionales, lotes nocturnos): no pagas por capacidad ociosa. También es la fuente de facturas sorpresa si no se controla.'],
        ejemplo: 'Un servicio que escala de 2 a 20 instancias durante la campaña de fin de año y vuelve a 2 después.',
        errorComun: 'Confundir elasticidad con "cero caídas": la disponibilidad garantizada es otro acuerdo distinto.',
        fraseClave: 'Pagas por lo que usas; vigila cuánto usas.',
      },
      {
        n: 3,
        termino: 'Dependencia del proveedor (lock-in)',
        definicionTextual: 'El coste de cambiar de proveedor cuando la plataforma se construyó sobre servicios propietarios (colas, funciones, bases de datos gestionadas específicas).',
        fuente: F.huyen.titulo,
        idea: ['El lock-in no se elimina, se gestiona: aislar la lógica de negocio detrás de interfaces y conocer el coste real de una migración antes de que sea inasumible.'],
        ejemplo: 'Una plataforma entera sobre servicios propietarios de una nube: migrar exigiría reescribir la mitad.',
        errorComun: 'Ignorar el lock-in porque "no vamos a cambiar de nube" — hasta que el precio sube o el servicio se retira.',
        fraseClave: 'El lock-in se gestiona, no desaparece.',
      },
      {
        n: 4,
        termino: 'Nube pública, privada e híbrida',
        definicionTextual: 'Pública: infraestructura compartida del proveedor. Privada: infraestructura dedicada (propia o alojada). Híbrida: combinación, según sensibilidad y coste de cada carga.',
        fuente: F.madewithml.titulo,
        idea: ['La decisión suele ser por carga, no global: datos muy sensibles en privada, cómputo elástico en pública.'],
        ejemplo: 'Entrenar en la nube pública con datos anonimizados; servir el modelo en infraestructura privada junto a los datos reales.',
        errorComun: 'Plantear "todo público" o "todo privado" en vez de decidir carga por carga.',
        fraseClave: 'La nube se elige por carga, no de una vez para todo.',
      },
    ],
    casoCompleto: {
      escenario: 'Tu organización, sin experiencia previa en nube, quiere desplegar un modelo interno con datos sensibles.',
      pasos: [
        { titulo: 'Modelo de servicio', texto: 'PaaS o ML gestionado si no hay equipo para operar infraestructura desde cero.' },
        { titulo: 'Elasticidad', texto: 'Aprovecha el pago por uso, pero configura alertas de coste desde el día 1.' },
        { titulo: 'Datos sensibles', texto: 'Evalúa residencia y retención; quizá híbrida (cómputo en pública, datos en privada).' },
        { titulo: 'Lock-in', texto: 'Aísla la lógica de negocio para no quedar atado a servicios propietarios sin salida.' },
      ],
    },
    preguntas: [
      {
        q: 'Contratas "una API de reconocimiento de imágenes lista para usar, pagas por llamada". ¿Qué modelo de servicio es?',
        opts: ['IaaS', 'PaaS', 'SaaS / API gestionada', 'Nube privada'],
        a: 2,
        why: 'Consumir una capacidad terminada por llamada, sin gestionar infraestructura ni desplegar código, es el extremo SaaS.',
      },
      {
        q: 'Una startup construye toda su plataforma sobre servicios propietarios de una nube. ¿Cuál es el riesgo y su mitigación razonable?',
        opts: [
          'Ninguno: los servicios gestionados siempre son mejores.',
          'Dependencia del proveedor (lock-in): se mitiga aislando la lógica de negocio detrás de interfaces y conociendo el coste real de una migración antes de que sea inasumible.',
          'Que la nube es menos segura.',
          'Que siempre sale más caro que gestionarlo uno mismo.',
        ],
        a: 1,
        why: 'El lock-in tiene un coste de salida real que hay que gestionar con diseño desacoplado y conciencia del coste de cambio.',
      },
    ],
    fuentes: [F.huyen, F.madewithml],
  },

  'Arquitectura de referencia': {
    objetivo: 'Conocer las piezas de una arquitectura para llevar un modelo a producción y por qué el registro de modelos y el monitoreo de deriva no son opcionales.',
    terminos: [
      {
        n: 1,
        termino: 'Registro de modelos (model registry)',
        definicionTextual: 'Un catálogo versionado de los modelos entrenados: qué datos y métricas tenía cada versión, cuál está en producción y cómo revertir a una anterior.',
        fuente: F.mlflow.titulo,
        idea: ['Sin registro no se sabe qué versión sirve, no se puede revertir ni auditar; es la pieza que hace trazable el modelo en producción.'],
        ejemplo: 'La versión 2.4 está en producción desde el 3 de marzo; se puede volver a la 2.3 en minutos si la 2.4 falla.',
        errorComun: 'Desplegar "el modelo" sin versionar ni registrar sus métricas y datos de entrenamiento.',
        fraseClave: 'Sin registro no hay reversión ni auditoría.',
      },
      {
        n: 2,
        termino: 'Endpoint de inferencia',
        definicionTextual: 'El servicio que expone el modelo para recibir peticiones y devolver predicciones, con escalado, versionado y monitoreo gestionados.',
        fuente: F.huyen.titulo,
        idea: ['El endpoint es donde el modelo "toca" el mundo; su latencia, disponibilidad y coste son métricas de operación, no detalles.'],
        ejemplo: 'Una API REST que recibe los datos de una transacción y devuelve la probabilidad de fraude en 50 ms.',
        errorComun: 'Medir solo la exactitud del modelo y no la latencia ni el coste del endpoint bajo carga.',
        fraseClave: 'El endpoint es el modelo en contacto con la realidad.',
      },
      {
        n: 3,
        termino: 'Monitoreo de deriva de datos (data drift)',
        definicionTextual: 'Vigilar que la distribución de los datos de entrada en producción no se aleje de la que había en entrenamiento; cuando lo hace, el rendimiento cae aunque el código no cambie.',
        fuente: F.huyen.titulo,
        idea: ['La deriva es la causa más común de que un modelo empeore "solo". El monitoreo la detecta antes de que el daño sea grande.'],
        ejemplo: 'El perfil de los clientes cambia tras una campaña y el modelo, entrenado con el perfil antiguo, empieza a fallar.',
        errorComun: 'Asumir que si nadie tocó el código, el modelo sigue igual de bien.',
        fraseClave: 'El modelo se degrada solo; hay que vigilar la entrada.',
      },
      {
        n: 4,
        termino: 'Despliegue automático desde el repositorio (CI/CD de modelos)',
        definicionTextual: 'Cada cambio validado del código o del modelo pasa a producción por un proceso repetible y auditable, con reversión rápida si algo falla.',
        fuente: F.madewithml.titulo,
        idea: ['Reduce el error manual y acelera tanto el despliegue como la vuelta atrás. Incluye las pruebas, no las elimina.'],
        ejemplo: 'Un merge a la rama principal dispara pruebas, empaqueta el modelo y lo despliega al endpoint de staging.',
        errorComun: 'Desplegar a mano copiando archivos al servidor.',
        fraseClave: 'Despliegue repetible o despliegue frágil.',
      },
    ],
    casoCompleto: {
      escenario: 'Diseñas la arquitectura para llevar a producción el modelo de detección de anomalías del programa.',
      pasos: [
        { titulo: 'Ingesta', texto: 'Cómo entran los datos y con qué frecuencia.' },
        { titulo: 'Entrenamiento gestionado', texto: 'Dónde se entrena y cómo se registran las corridas.' },
        { titulo: 'Registro de modelos', texto: 'Versionado con métricas y datos; capacidad de revertir.' },
        { titulo: 'Endpoint', texto: 'Con monitoreo de latencia, uso y coste.' },
        { titulo: 'Monitoreo de deriva', texto: 'Sobre las distribuciones de entrada y de predicción, con alerta.' },
      ],
    },
    preguntas: [
      {
        q: 'Un modelo en producción empieza a fallar semanas después sin que nadie toque el código. Causa más probable y pieza que lo habría detectado:',
        opts: [
          'Un bug nuevo; pruebas unitarias.',
          'Deriva de datos: los datos de entrada se alejaron de los de entrenamiento; un monitoreo de deriva sobre las distribuciones lo habría alertado.',
          'Falta de RAM; más memoria.',
          'El certificado SSL caducó.',
        ],
        a: 1,
        why: 'Si el código no cambió, la degradación progresiva suele ser deriva de datos, y el monitoreo de deriva es la pieza que la detecta.',
      },
      {
        q: 'Tu arquitectura omite el registro de modelos. ¿Qué problema aparece con el tiempo?',
        opts: [
          'Ninguno, es opcional.',
          'No se sabe qué versión está en producción, no se puede revertir a una anterior ni auditar qué datos y métricas tenía la desplegada.',
          'El modelo entrena más lento.',
          'Aumenta el coste de almacenamiento de datos.',
        ],
        a: 1,
        why: 'El registro aporta versionado, reversión y trazabilidad; sin él, el modelo en producción es una caja negra operativa.',
      },
    ],
    fuentes: [F.mlflow, F.huyen, F.madewithml],
  },

  'Principales servicios': {
    objetivo: 'Aprender a elegir entre APIs preentrenadas y plataformas de entrenamiento, y por qué estudiar por categorías y no por nombres de producto.',
    terminos: [
      {
        n: 1,
        termino: 'APIs preentrenadas frente a plataformas de ML gestionado',
        definicionTextual: 'API preentrenada: una capacidad ya construida (visión, voz, lenguaje) que consumes por llamada. Plataforma de ML gestionado: un entorno donde entrenas y despliegas tus propios modelos.',
        fuente: F.huyen.titulo,
        idea: ['La API preentrenada conviene para tareas estándar sin ventaja en hacerlo propio y sin equipo de ML; la plataforma, cuando el problema es específico o el dato no puede salir.'],
        ejemplo: 'Transcribir reuniones: API preentrenada. Predecir la demanda de tu producto: plataforma propia.',
        errorComun: 'Entrenar internamente una tarea estándar ya resuelta por APIs, o usar una API genérica para un problema muy específico del negocio.',
        fraseClave: 'Estándar y sin ventaja propia: API. Específico o dato sensible: plataforma.',
      },
      {
        n: 2,
        termino: 'Estudiar por categorías de servicio, no por nombres de producto',
        definicionTextual: 'Las categorías (cómputo, almacenamiento, ML gestionado, datos, MLOps, APIs preentrenadas) son estables entre proveedores; los nombres comerciales cambian y se renuevan.',
        fuente: F.madewithml.titulo,
        idea: ['Dominar las categorías hace el conocimiento transferible entre AWS, Azure y GCP; memorizar nombres de producto caduca en meses.'],
        ejemplo: 'Saber "necesito un servicio de ML gestionado con registro de modelos" es transferible; saber solo un nombre comercial, no.',
        errorComun: 'Preparar una comparativa a base de nombres de producto que quedará obsoleta antes de implementarla.',
        fraseClave: 'Las categorías perduran; los nombres caducan.',
      },
      {
        n: 3,
        termino: 'Elección de proveedor por un factor que no es el precio de lista',
        definicionTextual: 'La decisión de nube se apoya en integración con el ecosistema existente, cumplimiento, fortaleza específica en un servicio o coste total de operación, no en el precio por hora publicado.',
        fuente: F.huyen.titulo,
        idea: ['El precio de lista es fácil de comparar y casi nunca es el factor decisivo; el coste real incluye migración, formación del equipo y operación.'],
        ejemplo: 'Una organización con todo su directorio y correo en un ecosistema elige la nube de ese ecosistema por integración de identidad, aunque otra tenga un servicio puntual más barato.',
        errorComun: '"Elegimos X porque es el más grande / el más barato por hora."',
        fraseClave: 'El precio de lista no decide; el coste total y el encaje sí.',
      },
      {
        n: 4,
        termino: 'Coste total de operación (más allá del cómputo)',
        definicionTextual: 'Suma del cómputo, el almacenamiento, la transferencia de datos, el mantenimiento del sistema y el coste de formar y retener al equipo que lo opera.',
        fuente: F.madewithml.titulo,
        idea: ['Un servicio gestionado más caro por hora puede salir más barato en total si ahorra semanas de operación propia.'],
        ejemplo: 'Un endpoint gestionado cuesta más que una VM, pero no necesitas a alguien parcheando y escalando esa VM.',
        errorComun: 'Comparar solo el precio del cómputo y no la carga de operación que cada opción impone al equipo.',
        fraseClave: 'Lo barato por hora puede ser caro al año.',
      },
    ],
    casoCompleto: {
      escenario: 'Necesitas transcribir y resumir 500 audios de reuniones al mes, sin equipo de ML y con presupuesto ajustado.',
      pasos: [
        { titulo: 'Categoría', texto: 'Es una tarea estándar: API preentrenada de transcripción + LLM gestionado para el resumen.' },
        { titulo: 'Sin equipo', texto: 'Descarta entrenar desde cero o montar infraestructura propia.' },
        { titulo: 'Proveedor', texto: 'Elige por integración con lo que ya usas y por coste total, no por el precio por minuto.' },
        { titulo: 'Coste', texto: 'Estima el coste mensual real (llamadas + almacenamiento) y ponle una alerta.' },
      ],
    },
    preguntas: [
      {
        q: 'Necesitas transcribir 500 audios al mes, sin equipo de ML y con presupuesto ajustado. ¿Qué opción encaja?',
        opts: [
          'Entrenar un modelo de reconocimiento de voz desde cero.',
          'Usar una API preentrenada de transcripción + un LLM gestionado para el resumen: sin equipo de ML, coste por uso, puesta en marcha en días.',
          'Montar un clúster de GPUs propio.',
          'Contratar tres ingenieros de ML.',
        ],
        a: 1,
        why: 'Para una tarea estándar sin equipo propio, las APIs preentrenadas y los servicios gestionados son la opción proporcional.',
      },
      {
        q: '¿Por qué la asignatura recomienda estudiar la nube por categorías y no memorizando nombres de producto?',
        opts: [
          'Porque los nombres son difíciles de pronunciar.',
          'Porque los nombres comerciales cambian y se renuevan con frecuencia, mientras que las categorías (cómputo, almacenamiento, ML gestionado, datos, MLOps) son estables y transferibles entre proveedores.',
          'Porque los proveedores no publican sus nombres.',
          'Porque son secretos comerciales.',
        ],
        a: 1,
        why: 'Las categorías perduran y hacen el conocimiento transferible; los nombres de producto caducan rápido.',
      },
    ],
    fuentes: [F.huyen, F.madewithml, F.mlflow],
  },
};
