// Lectura guiada — Asignatura VI: Machine Learning. Las 6 lecciones.
const F = {
  geron: { titulo: 'Hands-On Machine Learning 3e — Aurélien Géron', url: 'https://github.com/ageron/handson-ml3' },
  islp: { titulo: 'An Introduction to Statistical Learning (Python)', url: 'https://www.statlearning.com/' },
  ngml: { titulo: 'Machine Learning Specialization — Andrew Ng (DeepLearning.AI & Stanford)', url: 'https://www.coursera.org/specializations/machine-learning-introduction' },
  molnar: { titulo: 'Interpretable Machine Learning — Christoph Molnar', url: 'https://christophm.github.io/interpretable-ml-book/' },
  shap: { titulo: 'SHAP — documentación', url: 'https://shap.readthedocs.io/' },
  suttonbarto: { titulo: 'Reinforcement Learning: An Introduction (2ª ed.) — Sutton & Barto', url: 'http://incompleteideas.net/book/the-book-2nd.html' },
};

module.exports = {
  'Introducción a Machine Learning': {
    objetivo: 'Formular un problema de negocio como un problema de aprendizaje bien definido y justificar la métrica de evaluación antes de entrenar nada.',
    terminos: [
      {
        n: 1,
        termino: 'Aprendizaje supervisado, no supervisado y por refuerzo',
        definicionTextual: 'Supervisado: se aprende de ejemplos con la respuesta correcta (etiqueta). No supervisado: se busca estructura en datos sin etiqueta. Por refuerzo: se aprende de la recompensa de las propias acciones.',
        fuente: F.ngml.titulo,
        idea: ['La mayoría de los problemas de negocio con valor claro son supervisados; identificar mal el tipo lleva a elegir algoritmos y a recoger datos equivocados.'],
        ejemplo: 'Predecir si un cliente renovará (supervisado); segmentar la base de clientes sin criterio previo (no supervisado).',
        errorComun: 'Plantear como no supervisado (clustering) un problema para el que sí hay etiqueta histórica disponible.',
        fraseClave: 'Primero decide de qué señal aprende el modelo.',
      },
      {
        n: 2,
        termino: 'Generalización y el compromiso sesgo–varianza',
        definicionTextual: 'Generalizar es rendir bien en datos nuevos, no en los de entrenamiento. Sesgo alto (modelo demasiado simple) subajusta; varianza alta (modelo demasiado flexible) sobreajusta.',
        fuente: F.islp.titulo,
        idea: ['La meta no es el error de entrenamiento sino el error esperado en datos no vistos; por eso siempre se reserva un conjunto de prueba que no se toca hasta el final.'],
        ejemplo: 'Un polinomio de grado 15 con error 0 en entrenamiento y error enorme en prueba: pura varianza.',
        errorComun: 'Ajustar hiperparámetros mirando el conjunto de prueba y "contaminarlo".',
        fraseClave: 'El modelo se juzga por lo que aún no ha visto.',
      },
      {
        n: 3,
        termino: 'Justificar la métrica antes de entrenar',
        definicionTextual: 'Elegir y fijar la métrica de evaluación (exactitud, F1, MAE, coste esperado…) a partir del coste real de cada tipo de error, antes de ver ningún resultado.',
        fuente: F.ngml.titulo,
        idea: ['Si la métrica se elige después de ver los resultados, se acaba escogiendo la que hace lucir mejor al modelo; el "apartado que casi todo el mundo se salta".'],
        ejemplo: 'En detección de fraude, priorizar exhaustividad (no dejar pasar fraude) sobre exactitud global, que un modelo trivial ya alcanza.',
        errorComun: 'Reportar "95% de exactitud" en un problema con 95% de una sola clase.',
        fraseClave: 'La métrica se decide con el coste del error, no con el resultado.',
      },
      {
        n: 4,
        termino: 'Fuga de datos (data leakage)',
        definicionTextual: 'Que información no disponible en el momento real de predecir (o que codifica la respuesta) entre en el entrenamiento, produciendo una métrica excelente que se desploma en producción.',
        fuente: F.geron.titulo,
        idea: ['Las fuentes típicas: normalizar antes de partir train/test, usar agregados con ventana que incluye el futuro, o incluir una variable que solo se rellena tras conocer el resultado.'],
        ejemplo: 'Un modelo de impago que usa "fecha de la primera gestión de cobro": esa variable solo existe si ya hubo impago.',
        errorComun: 'Aplicar el escalado o la imputación sobre todo el dataset antes de separar entrenamiento y prueba.',
        fraseClave: 'Si el modelo es "demasiado bueno", busca la fuga antes de celebrar.',
      },
    ],
    casoCompleto: {
      escenario: 'Dirección pide "un modelo de IA para reducir la rotación de clientes" y espera ver "el porcentaje de acierto".',
      pasos: [
        { titulo: 'Tipo de problema', texto: 'Supervisado de clasificación: hay histórico de quién se fue y quién no.' },
        { titulo: 'Métrica', texto: 'Fijar antes de entrenar: exhaustividad sobre la clase "se va" (el coste de no detectarla es alto) y precisión suficiente para que la acción comercial sea rentable.' },
        { titulo: 'Partición honesta', texto: 'Separar por cliente y por tiempo; escalar e imputar solo con datos de entrenamiento.' },
        { titulo: 'Fuga', texto: 'Revisar cada variable: ¿estaría disponible el día que quiero predecir?' },
      ],
    },
    preguntas: [
      {
        q: 'Tu modelo de impago da 0,97 de AUC en validación. Antes de presentarlo, ¿qué es lo primero que revisas?',
        opts: [
          'Nada, es un resultado excelente.',
          'Fuga de datos: ¿alguna variable codifica el resultado o no estaría disponible al predecir? ¿Se escaló/imputó antes de partir?',
          'Añadir más capas.',
          'Cambiar la métrica a exactitud.',
        ],
        a: 1,
        why: 'Un resultado sorprendentemente bueno es, con más frecuencia, síntoma de fuga que de un modelo excepcional.',
      },
      {
        q: '¿Por qué se fija la métrica de evaluación antes de entrenar?',
        opts: [
          'Para poder documentar el proyecto.',
          'Porque si se elige después de ver los resultados, se acaba escogiendo la métrica que favorece al modelo en vez de la que refleja el coste real del error.',
          'Porque el código lo exige.',
          'Para acelerar el entrenamiento.',
        ],
        a: 1,
        why: 'La métrica debe derivarse del coste de negocio de cada tipo de error, no de conveniencia posterior.',
      },
    ],
    fuentes: [F.ngml, F.islp, F.geron],
  },

  'Aprendizaje Supervisado': {
    objetivo: 'Entender que cada clasificador es una forma distinta de frontera de decisión y elegir entre precisión y exhaustividad según el coste real de cada error.',
    terminos: [
      {
        n: 1,
        termino: 'Frontera de decisión',
        definicionTextual: 'La superficie en el espacio de las variables donde el clasificador cambia de una clase predicha a otra. Cada algoritmo puede representar formas de frontera distintas.',
        fuente: F.islp.titulo,
        idea: ['Regresión logística: frontera lineal. k-NN: frontera irregular que sigue los ejemplos. SVM con kernel: frontera no lineal suave. La elección del algoritmo es, en el fondo, la elección de qué fronteras son posibles.'],
        ejemplo: 'Dos clases en forma de espiral: la logística falla, k-NN y SVM con kernel las separan.',
        errorComun: 'Insistir con un modelo lineal en un problema cuya frontera real es claramente curva.',
        fraseClave: 'Elegir algoritmo es elegir qué formas de frontera puedes trazar.',
      },
      {
        n: 2,
        termino: 'k vecinos más cercanos (k-NN)',
        definicionTextual: 'Clasifica un caso nuevo por la clase mayoritaria entre sus k ejemplos de entrenamiento más cercanos. No "aprende" un modelo: guarda los datos y decide en tiempo de predicción.',
        fuente: F.geron.titulo,
        idea: ['Simple y sin entrenamiento, pero sensible a la escala de las variables y costoso en predicción con muchos datos; k pequeño sobreajusta, k grande difumina.'],
        ejemplo: 'k=5: los 5 clientes históricos más parecidos deciden la etiqueta del nuevo.',
        errorComun: 'Usar k-NN sin estandarizar las variables: la de mayor rango domina la distancia.',
        fraseClave: 'k-NN no entrena; recuerda y vota.',
      },
      {
        n: 3,
        termino: 'Máquina de vector soporte (SVM) y margen máximo',
        definicionTextual: 'Un clasificador que busca la frontera que deja el mayor margen (distancia) posible respecto a los ejemplos más cercanos de cada clase; con un "kernel" puede representar fronteras no lineales.',
        fuente: F.islp.titulo,
        idea: ['El margen máximo tiende a generalizar bien; el kernel permite no linealidad sin transformar explícitamente las variables.'],
        ejemplo: 'Separar dos clases con la banda más ancha posible entre ellas.',
        errorComun: 'Aplicar un kernel muy flexible (RBF con gamma alto) y sobreajustar; o no escalar antes.',
        fraseClave: 'SVM busca la separación con más aire a cada lado.',
      },
      {
        n: 4,
        termino: 'Precisión, exhaustividad y F1',
        definicionTextual: 'Precisión: de lo que predije como positivo, cuánto lo era. Exhaustividad (recall): de todos los positivos reales, cuántos detecté. F1: media armónica de ambas.',
        fuente: F.geron.titulo,
        idea: ['Suben en direcciones opuestas al mover el umbral; cuál priorizar depende de si duele más un falso positivo o un falso negativo en tu caso.'],
        ejemplo: 'Cribado de cáncer: prioriza exhaustividad. Filtro de spam agresivo: cuida la precisión para no perder correo legítimo.',
        errorComun: 'Reportar solo exactitud en un problema con clases desbalanceadas.',
        fraseClave: 'El umbral se elige con el coste del error, no por defecto en 0,5.',
      },
    ],
    casoCompleto: {
      escenario: 'Un clasificador de "transacción fraudulenta" tiene 99,3% de exactitud, pero solo el 0,7% de las transacciones son fraude.',
      pasos: [
        { titulo: 'Descartar la exactitud', texto: 'Un modelo que diga "nunca fraude" ya tiene 99,3%: la métrica no informa.' },
        { titulo: 'Mirar exhaustividad', texto: '¿Qué porcentaje del fraude real detecta? Esa es la métrica que importa aquí.' },
        { titulo: 'Ajustar el umbral', texto: 'Bajar el umbral sube la exhaustividad a costa de precisión; el punto óptimo lo fija el coste de revisar un falso positivo frente al de dejar pasar fraude.' },
        { titulo: 'Elegir modelo', texto: 'Si la frontera es no lineal, SVM con kernel o un modelo de árboles antes que regresión logística.' },
      ],
    },
    preguntas: [
      {
        q: 'Un modelo de detección de fraude tiene 99% de exactitud, con 1% de casos de fraude. ¿Qué métrica reportas y por qué?',
        opts: [
          'La exactitud: 99% es excelente.',
          'La exhaustividad (y la precisión): con 1% de positivos, un modelo trivial ya alcanza 99% de exactitud; lo que importa es cuánto fraude real detecta y a qué coste de falsos positivos.',
          'El tiempo de entrenamiento.',
          'El número de variables.',
        ],
        a: 1,
        why: 'Con clases muy desbalanceadas la exactitud es engañosa; precisión y exhaustividad describen el error de forma útil.',
      },
      {
        q: 'Usas k-NN y una variable está en euros (rango 0–100.000) y otra en años (rango 0–40). ¿Qué falta?',
        opts: [
          'Nada, k-NN lo maneja solo.',
          'Estandarizar las variables: sin ello, la de mayor rango (euros) domina la distancia y la de años casi no cuenta.',
          'Quitar la variable de años.',
          'Aumentar k a 100.',
        ],
        a: 1,
        why: 'k-NN se basa en distancias; sin escalar, las variables de mayor magnitud dominan artificialmente el cálculo de vecindad.',
      },
    ],
    fuentes: [F.islp, F.geron],
  },

  'Aprendizaje supervisado de regresión': {
    objetivo: 'Controlar el sobreajuste con regularización y evaluar el error con la métrica correcta, sin fiarse de un R² sin validación.',
    terminos: [
      {
        n: 1,
        termino: 'Regularización L2 (Ridge) y L1 (Lasso)',
        definicionTextual: 'Añadir a la función de error una penalización por el tamaño de los coeficientes. L2 los encoge de forma suave; L1 puede llevar algunos exactamente a cero, seleccionando variables.',
        fuente: F.islp.titulo,
        idea: ['La regularización cambia sesgo por varianza: acepta algo más de error sistemático a cambio de un modelo mucho más estable en datos nuevos.'],
        ejemplo: 'Con 40 variables muy correlacionadas, Lasso deja 8 con coeficiente no nulo y descarta el resto.',
        errorComun: 'Elegir la fuerza de la penalización (alfa) a ojo en vez de por validación cruzada.',
        fraseClave: 'La regularización paga estabilidad con un poco de sesgo.',
      },
      {
        n: 2,
        termino: 'Regresión polinómica y grado del polinomio',
        definicionTextual: 'Ampliar la regresión lineal añadiendo potencias de las variables para capturar relaciones curvas. El grado controla la flexibilidad y el riesgo de sobreajuste.',
        fuente: F.geron.titulo,
        idea: ['Un grado alto ajusta cada zigzag del entrenamiento y falla fuera; la curva de validación en función del grado muestra el punto donde empieza a empeorar.'],
        ejemplo: 'Grado 2 capta una relación en U; grado 12 capta el ruido.',
        errorComun: 'Subir el grado mientras baje el error de entrenamiento.',
        fraseClave: 'Más grado ajusta el ruido, no la señal.',
      },
      {
        n: 3,
        termino: 'MAE frente a RMSE',
        definicionTextual: 'MAE: error absoluto medio, en las unidades de la variable, penaliza todos los errores por igual. RMSE: raíz del error cuadrático medio, penaliza más los errores grandes.',
        fuente: F.islp.titulo,
        idea: ['Si un error de 100 es diez veces peor que diez errores de 10, usa RMSE; si todos los errores cuestan proporcionalmente, MAE es más honesto y robusto a atípicos.'],
        ejemplo: 'Previsión de demanda donde un desabasto grande es catastrófico: RMSE.',
        errorComun: 'Reportar RMSE sin explicar que un solo caso muy atípico puede dominarlo.',
        fraseClave: 'Elige la métrica según cuánto duele un error grande.',
      },
      {
        n: 4,
        termino: 'R² y sus límites',
        definicionTextual: 'La proporción de la variabilidad de la salida que el modelo explica. Va de 0 a 1 (puede ser negativo fuera de entrenamiento).',
        fuente: F.islp.titulo,
        idea: ['Un R² alto en entrenamiento no dice nada sobre datos nuevos; siempre se reporta el de un conjunto de validación separado, junto a MAE/RMSE en unidades reales.'],
        ejemplo: 'R² 0,95 en entrenamiento y 0,40 en validación: el modelo no generaliza.',
        errorComun: 'Presentar el R² de entrenamiento como medida de calidad del modelo.',
        fraseClave: 'Un R² sin validación no es una medida de calidad.',
      },
    ],
    casoCompleto: {
      escenario: 'Un modelo de precio con regresión polinómica de grado 10 tiene R² 0,98 en entrenamiento y error grande en casos nuevos.',
      pasos: [
        { titulo: 'Diagnóstico', texto: 'Sobreajuste por grado excesivo: el modelo memoriza el ruido del entrenamiento.' },
        { titulo: 'Curva de validación', texto: 'Prueba grados de 1 a 10 y quédate con el grado donde el error de validación es mínimo.' },
        { titulo: 'Regularizar', texto: 'Aplica Ridge o Lasso y ajusta alfa por validación cruzada.' },
        { titulo: 'Reportar', texto: 'MAE/RMSE en euros y R² de validación, no de entrenamiento.' },
      ],
    },
    preguntas: [
      {
        q: 'Al subir el grado del polinomio de 3 a 10, el error de entrenamiento baja pero el de validación sube. ¿Qué grado eliges?',
        opts: [
          'Grado 10: el menor error de entrenamiento.',
          'El grado donde el error de validación es mínimo (probablemente 3–4); a partir de ahí solo estás ajustando ruido.',
          'Grado 1 siempre.',
          'El promedio de los dos.',
        ],
        a: 1,
        why: 'El objetivo es el error en datos nuevos; el mínimo de la curva de validación marca el punto antes del sobreajuste.',
      },
      {
        q: '¿Qué hace la regularización L1 (Lasso) que no hace L2 (Ridge)?',
        opts: [
          'Acelera el entrenamiento.',
          'Puede llevar coeficientes exactamente a cero, seleccionando automáticamente un subconjunto de variables.',
          'Aumenta el R² de entrenamiento.',
          'Elimina la necesidad de validar.',
        ],
        a: 1,
        why: 'L1 penaliza el valor absoluto de los coeficientes, lo que produce soluciones dispersas; L2 solo los encoge.',
      },
    ],
    fuentes: [F.islp, F.geron],
  },

  'Aprendizaje no supervisado': {
    objetivo: 'Elegir entre K-means y agrupamiento jerárquico según lo que se sabe de antemano, y evaluar un resultado sin etiquetas verdaderas con criterio de negocio.',
    terminos: [
      {
        n: 1,
        termino: 'K-means y la elección de k',
        definicionTextual: 'Agrupa los datos en k grupos minimizando la distancia de cada punto al centro de su grupo. Exige fijar k antes de ejecutar.',
        fuente: F.geron.titulo,
        idea: ['El "codo" de la curva de inercia y el coeficiente de silueta ayudan a elegir k, pero la decisión final debe tener sentido de negocio: 7 segmentos que nadie puede accionar no valen más que 3 que sí.'],
        ejemplo: 'Segmentar clientes en k=4 grupos por gasto y frecuencia.',
        errorComun: 'Fijar k por el número de campañas que ya existen en vez de por la estructura de los datos.',
        fraseClave: 'k se elige con los datos y se valida con el negocio.',
      },
      {
        n: 2,
        termino: 'Agrupamiento jerárquico',
        definicionTextual: 'Construye un árbol (dendrograma) uniendo iterativamente los grupos más cercanos; el número de grupos se decide cortando el árbol a la altura deseada, después de ver la estructura.',
        fuente: F.islp.titulo,
        idea: ['Útil cuando no se sabe cuántos grupos hay; más costoso que K-means y sensible a la medida de distancia y al criterio de enlace.'],
        ejemplo: 'Ver en el dendrograma que hay 2 grandes grupos que se subdividen en 5.',
        errorComun: 'Usarlo sobre cientos de miles de puntos, donde su coste lo hace inviable.',
        fraseClave: 'El jerárquico deja decidir el número de grupos al final.',
      },
      {
        n: 3,
        termino: 'Maldición de la dimensionalidad',
        definicionTextual: 'En espacios con muchas variables, todos los puntos tienden a estar casi a la misma distancia entre sí, y la noción de "cercano" pierde sentido; los métodos basados en distancia se degradan.',
        fuente: F.geron.titulo,
        idea: ['Por eso se reduce la dimensionalidad (PCA, selección de variables) antes de agrupar o de aplicar k-NN sobre datos con decenas o cientos de columnas.'],
        ejemplo: 'Un clustering sobre 300 variables que produce grupos sin sentido; con PCA a 15 componentes, grupos claros.',
        errorComun: 'Aplicar K-means directamente sobre cientos de variables sin reducir dimensionalidad.',
        fraseClave: 'Con muchas dimensiones, "cerca" deja de significar algo.',
      },
      {
        n: 4,
        termino: 'Evaluación sin etiquetas verdaderas',
        definicionTextual: 'Sin una respuesta correcta, la calidad de un agrupamiento se juzga con métricas internas (silueta, cohesión/separación) y, sobre todo, con la utilidad de los grupos para una decisión concreta.',
        fuente: F.islp.titulo,
        idea: ['Un buen resultado de clustering es el que un experto del dominio reconoce y puede accionar, no el que optimiza una métrica interna.'],
        ejemplo: 'Los 4 segmentos coinciden con perfiles que el equipo comercial ya intuía y permiten una oferta distinta para cada uno.',
        errorComun: 'Presentar el clustering con la silueta más alta sin comprobar si los grupos significan algo.',
        fraseClave: 'El clustering es bueno si sirve para decidir.',
      },
    ],
    casoCompleto: {
      escenario: 'Marketing pide "segmentar los clientes con IA" sobre una tabla de 250 variables por cliente.',
      pasos: [
        { titulo: 'Reducir dimensión', texto: 'PCA o selección de variables antes de agrupar: con 250 columnas la distancia no discrimina.' },
        { titulo: 'Elegir método', texto: 'K-means si se busca un número concreto de segmentos accionables; jerárquico si no se sabe cuántos hay.' },
        { titulo: 'Elegir k', texto: 'Codo + silueta como guía; decisión final por si los grupos son accionables.' },
        { titulo: 'Validar con negocio', texto: 'Presentar los perfiles a marketing: si no los reconoce ni puede actuar distinto en cada uno, el resultado no vale.' },
      ],
    },
    preguntas: [
      {
        q: 'Aplicas K-means directamente sobre 200 variables y los grupos no tienen sentido. ¿Qué causa probable y qué haces?',
        opts: [
          'K-means está roto; usa otra librería.',
          'Maldición de la dimensionalidad: con tantas variables las distancias no discriminan. Reduce dimensionalidad (PCA / selección) antes de agrupar.',
          'Faltan más variables.',
          'Sube k a 50.',
        ],
        a: 1,
        why: 'En alta dimensión todos los puntos quedan casi equidistantes; reducir dimensión restaura la utilidad de la distancia.',
      },
      {
        q: 'Tienes dos soluciones de clustering: A con silueta 0,55 y B con 0,42. El equipo de negocio reconoce y sabe accionar los grupos de B, no los de A. ¿Cuál eliges?',
        opts: [
          'A: mejor métrica interna.',
          'B: sin etiquetas verdaderas, la utilidad para decidir pesa más que la métrica interna.',
          'Ninguna, repetir todo.',
          'La media de A y B.',
        ],
        a: 1,
        why: 'La métrica interna es una guía; el criterio último de un clustering es que sea interpretable y accionable por el dominio.',
      },
    ],
    fuentes: [F.geron, F.islp],
  },

  'Aprendizaje semi-supervisado y por Refuerzo': {
    objetivo: 'Aprovechar datos sin etiquetar sin reforzar errores, y entender el compromiso exploración–explotación como el problema central del aprendizaje por refuerzo.',
    terminos: [
      {
        n: 1,
        termino: 'Auto-entrenamiento (self-training) y umbral de confianza',
        definicionTextual: 'Entrenar un modelo con los pocos datos etiquetados, usarlo para etiquetar los datos sin etiqueta (pseudo-etiquetas), quedarse solo con las predicciones de alta confianza y reentrenar.',
        fuente: F.geron.titulo,
        idea: ['Si el umbral de confianza es demasiado permisivo, el modelo etiqueta mal, aprende de sus propios errores y se degrada iteración a iteración.'],
        ejemplo: 'Con 500 correos etiquetados y 40.000 sin etiquetar: pseudo-etiquetar solo los que el modelo clasifica con >0,95 de probabilidad.',
        errorComun: 'Aceptar todas las pseudo-etiquetas y reforzar el sesgo inicial del modelo.',
        fraseClave: 'Pseudo-etiqueta solo lo que el modelo casi no duda.',
      },
      {
        n: 2,
        termino: 'Proceso de decisión de Markov (MDP)',
        definicionTextual: 'El marco formal del aprendizaje por refuerzo: estados, acciones, una recompensa por cada transición y una probabilidad de pasar de un estado a otro al actuar. La propiedad de Markov: el futuro depende solo del estado actual, no de toda la historia.',
        fuente: F.suttonbarto.titulo,
        idea: ['Antes de aplicar RL a un problema real hay que poder definir con honestidad estos elementos; si el "estado" no resume lo necesario para decidir, el planteamiento falla.'],
        ejemplo: 'Un robot de almacén: estado = posición y carga; acciones = mover/recoger/soltar; recompensa = pedidos completados menos tiempo.',
        errorComun: 'Forzar como RL un problema que es en realidad de optimización o de predicción supervisada.',
        fraseClave: 'Si no puedes definir estado, acción y recompensa, todavía no es RL.',
      },
      {
        n: 3,
        termino: 'Política, recompensa y valor',
        definicionTextual: 'Política: la regla que dice qué acción tomar en cada estado. Recompensa: la señal inmediata tras una acción. Valor: la recompensa total esperada a largo plazo desde un estado siguiendo una política.',
        fuente: F.suttonbarto.titulo,
        idea: ['El agente optimiza valor (largo plazo), no recompensa inmediata; una acción con recompensa baja hoy puede tener valor alto si abre buenas opciones mañana.'],
        ejemplo: 'Sacrificar una pieza en ajedrez (recompensa negativa inmediata) porque conduce a mate (valor alto).',
        errorComun: 'Diseñar la recompensa premiando solo el resultado inmediato y obtener un agente miope.',
        fraseClave: 'El agente juega el largo plazo, no el punto siguiente.',
      },
      {
        n: 4,
        termino: 'Exploración frente a explotación',
        definicionTextual: 'Explotar: elegir la acción que hoy parece mejor. Explorar: probar acciones inciertas para descubrir si alguna es mejor de lo que se cree. El agente debe equilibrar ambas.',
        fuente: F.suttonbarto.titulo,
        idea: ['Explotar siempre bloquea al agente en un óptimo local; explorar siempre desperdicia recompensa. Estrategias como ε-greedy o UCB gestionan ese compromiso.'],
        ejemplo: 'Un sistema de recomendación que el 90% del tiempo muestra lo que sabe que funciona y el 10% prueba contenido nuevo.',
        errorComun: 'Evaluar un agente de RL solo por su comportamiento durante el entrenamiento, cuando aún está explorando.',
        fraseClave: 'Sin explorar no aprendes; sin explotar no ganas.',
      },
    ],
    casoCompleto: {
      escenario: 'Tienes 300 casos etiquetados de una tarea de clasificación y 40.000 sin etiquetar; etiquetar más es caro. Un compañero propone auto-entrenamiento aceptando todas las pseudo-etiquetas.',
      pasos: [
        { titulo: 'Riesgo', texto: 'Aceptar todo refuerza los errores del modelo inicial: se degrada en cada iteración.' },
        { titulo: 'Umbral', texto: 'Pseudo-etiquetar solo las predicciones con probabilidad muy alta (p. ej. >0,95) y en pocas iteraciones.' },
        { titulo: 'Control', texto: 'Reservar un conjunto de validación etiquetado y detener si la métrica empeora.' },
        { titulo: 'Alternativa', texto: 'Si hay presupuesto, etiquetar activamente los casos donde el modelo más duda (aprendizaje activo) rinde más por etiqueta.' },
      ],
    },
    preguntas: [
      {
        q: 'En auto-entrenamiento, ¿qué pasa si el umbral de confianza para aceptar pseudo-etiquetas es demasiado bajo?',
        opts: [
          'El modelo entrena más rápido.',
          'El modelo etiqueta mal muchos casos, reentrena sobre sus propios errores y se degrada iteración a iteración.',
          'Se reduce el uso de memoria.',
          'Nada, el umbral no importa.',
        ],
        a: 1,
        why: 'Las pseudo-etiquetas de baja confianza suelen ser incorrectas; incorporarlas realimenta el sesgo del modelo.',
      },
      {
        q: 'Un agente de RL siempre elige la acción que hoy parece mejor y nunca prueba otras. ¿Qué problema tiene?',
        opts: [
          'Ninguno, es la estrategia óptima.',
          'Solo explota: puede quedar atrapado en un óptimo local sin descubrir acciones mejores que aún no ha probado.',
          'Explora demasiado.',
          'No puede recibir recompensa.',
        ],
        a: 1,
        why: 'Sin exploración el agente no obtiene información sobre acciones inciertas y no puede mejorar más allá de lo que ya conoce.',
      },
    ],
    fuentes: [F.suttonbarto, F.geron],
  },

  'Interpretabilidad de Modelos': {
    objetivo: 'Distinguir interpretabilidad por diseño de post-hoc y usar la explicación para detectar problemas, no solo para tranquilizar.',
    terminos: [
      {
        n: 1,
        termino: 'Interpretabilidad por diseño',
        definicionTextual: 'El modelo es inherentemente legible: una regresión lineal, un árbol poco profundo o un conjunto de reglas cuyo razonamiento se puede seguir directamente.',
        fuente: F.molnar.titulo,
        idea: ['Cuando la explicabilidad es un requisito duro (auditoría, apelación, sector regulado), se empieza por un modelo interpretable por diseño y solo se cambia si el rendimiento es claramente insuficiente.'],
        ejemplo: 'Un árbol de decisión de 4 niveles para aprobar o revisar una solicitud: cada decisión se lee como una regla.',
        errorComun: 'Elegir un modelo opaco por un 1% más de exactitud cuando el caso exige explicar cada decisión.',
        fraseClave: 'Si tienes que explicar cada decisión, empieza por un modelo legible.',
      },
      {
        n: 2,
        termino: 'Interpretabilidad post-hoc',
        definicionTextual: 'Técnicas externas (importancia de variables, LIME, SHAP) que aproximan una explicación de un modelo opaco después de entrenarlo.',
        fuente: F.shap.titulo,
        idea: ['Son aproximaciones, no la lógica real del modelo: útiles para diagnosticar, pero no equivalen a la transparencia de un modelo interpretable por diseño.'],
        ejemplo: 'Aplicar SHAP a un gradient boosting para ver qué variables empujaron una predicción concreta.',
        errorComun: 'Presentar una explicación SHAP como "así funciona el modelo" en vez de "así aproximamos por qué dio esta salida".',
        fraseClave: 'Post-hoc explica una salida, no la mente del modelo.',
      },
      {
        n: 3,
        termino: 'Importancia de variables y explicación local (SHAP)',
        definicionTextual: 'Importancia global: qué variables pesan más en el modelo en conjunto. Explicación local (SHAP): cuánto empujó cada variable la predicción de un caso concreto.',
        fuente: F.shap.titulo,
        idea: ['La explicación local es la que sirve para responder a una persona afectada ("tu solicitud se marcó sobre todo por X e Y").'],
        ejemplo: 'SHAP muestra que, para este cliente, "meses de antigüedad" bajó el score y "número de productos" lo subió.',
        errorComun: 'Usar solo la importancia global y no poder explicar decisiones individuales.',
        fraseClave: 'Global para entender el modelo; local para responder a una persona.',
      },
      {
        n: 4,
        termino: 'La interpretabilidad como herramienta de diagnóstico',
        definicionTextual: 'Usar la explicación no para justificar el modelo, sino para detectar que se apoya en algo que no debería: un proxy, una fuga de datos, una correlación espuria.',
        fuente: F.geron.titulo,
        idea: ['Si la variable más influyente es una que solo se rellena cuando ya existe el resultado que quieres predecir, tienes fuga de datos, y SHAP acaba de decírtelo.'],
        ejemplo: 'La variable "días desde el último contacto con reclamaciones" domina el modelo de riesgo de reclamación: señal de fuga temporal.',
        errorComun: 'Ver una variable con importancia altísima y celebrarlo en vez de sospechar.',
        fraseClave: 'Una importancia sospechosamente alta suele ser un problema, no un mérito.',
      },
    ],
    casoCompleto: {
      escenario: 'Aplicas SHAP a un modelo de scoring y descubres que la variable dominante es "número de reclamaciones en los últimos 12 meses", pero la etiqueta es "reclamará en los próximos 30 días".',
      pasos: [
        { titulo: 'Sospecha', texto: 'Una importancia tan alta de una variable tan cercana a la etiqueta es señal de alarma.' },
        { titulo: 'Revisar el tiempo', texto: 'Comprueba si los 12 meses terminan antes de la fecha de predicción; si incluyen información posterior, hay fuga.' },
        { titulo: 'Corregir', texto: 'Recalcula la variable con corte temporal correcto y reentrena.' },
        { titulo: 'Requisito', texto: 'Si el uso exige explicar cada decisión, valora un modelo interpretable por diseño en vez de post-hoc.' },
      ],
    },
    preguntas: [
      {
        q: 'SHAP muestra que la variable más influyente de tu modelo de riesgo es una que solo se rellena cuando el problema ya ocurrió. ¿Qué implica?',
        opts: [
          'Que el modelo es excelente: encontró la variable clave.',
          'Probablemente hay fuga de datos: esa variable codifica información del resultado; revisa cuándo se rellena respecto al momento de predecir.',
          'Que hay que eliminar SHAP.',
          'Que la variable debe multiplicarse por dos.',
        ],
        a: 1,
        why: 'La interpretabilidad sirve para detectar que el modelo se apoya en algo que no estará disponible al predecir, o que filtra la respuesta.',
      },
      {
        q: 'El caso exige explicar por escrito cada decisión a un auditor. Entre un árbol poco profundo y un gradient boosting con SHAP, ¿qué priorizas de partida?',
        opts: [
          'El gradient boosting siempre.',
          'El modelo interpretable por diseño (árbol poco profundo): la explicación es la lógica real, no una aproximación; se cambia solo si el rendimiento es claramente insuficiente.',
          'El que tenga más variables.',
          'Da igual, son equivalentes.',
        ],
        a: 1,
        why: 'Con explicabilidad como requisito duro se empieza por transparencia intrínseca, no por explicación post-hoc aproximada.',
      },
    ],
    fuentes: [F.molnar, F.shap, F.geron],
  },
};
